#region License
/* 
 * Copyright (C) 1999-2026 John Källén.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#endregion

using NUnit.Framework;
using Reko.Arch.IA64;
using Reko.Core;

namespace Reko.UnitTests.Arch.IA64;

[TestFixture]
public class IA64RewriterTests : RewriterTestBase
{
    private readonly IA64Architecture arch;
    private readonly Address addr;

    public IA64RewriterTests()
    {
        this.arch = new IA64Architecture(CreateServiceContainer(), "ia64", []);
        this.addr = Address.Ptr64(0x00100000);
    }

    public override IProcessorArchitecture Architecture => arch;

    public override Address LoadAddress => addr;

    // This file contains unit tests automatically generated by Reko decompiler.
    // Please copy the contents of this file and report it on GitHub, using the 
    // following URL: https://github.com/uxmal/reko/issues

    [Test]
    public void Ia64Rw_alloc()
    {
        Given_HexString("04101C008045024C80090060F0131A60");
        AssertCode(     // alloc	r2,ar.pfs,0x7,0x0,0x0
            "0|L--|0000000000100000(6): 1 instructions",
            "1|L--|r2 = ar.pfs",
            "2|L--|000000000010000C(4): 1 instructions",
            "3|L--|r3 = 0x9804C0270033F<64>");
    }

    [Test]
    public void Ia64Rw_br_ret()
    {
        Given_HexString("11000000010080F8F3FF4F8008008400");
        AssertCode(     // nop.m	0x0
            "0|L--|0000000000100000(6): 1 instructions",
            "1|L--|nop",
            "2|L--|0000000000100006(6): 1 instructions",
            "3|L--|r8 = 0<64> + -1<i64>",
            "4|L--|000000000010000C(4): 1 instructions",
            "5|R--|return (0,0)");
    }

    [Test]
    public void Ia64Rw_cmp_eq()
    {
        Given_HexString("003000400739200004650020C2EEE79F");
        AssertCode(     // cmp.eq	p06,p07,0x0,r32
            "0|L--|0000000000100000(6): 2 instructions",
            "1|L--|p06 = 0<64> == r32",
            "2|L--|p07 = 0<64> != r32",
            "3|L--|0000000000100006(6): 1 instructions",
            "4|L--|r2 = LC",
            "5|L--|000000000010000C(4): 1 instructions",
            "6|L--|r17 = r1 + -788<i64>");
    }

    [Test]
    public void Ia64Rw_cmp4_lt()
    {
        Given_HexString("0938FC418631E0080000480011000090");
        AssertCode(     // cmp4.lt	p07,p06,0x7F,r32
            "0|L--|0000000000100000(6): 4 instructions",
            "1|L--|v4 = SLICE(0x7F<64>, word32, 0)",
            "2|L--|v5 = SLICE(r32, word32, 0)",
            "3|L--|p07 = v4 < v5",
            "4|L--|p06 = v4 >= v5",
            "5|L--|0000000000100006(6): 1 instructions",
            "6|L--|r14 = 0<64> + 1<i64>",
            "7|L--|000000000010000C(4): 1 instructions",
            "8|L--|r8 = 0<64> + 1<i64>");
    }

    [Test]
    public void Ia64Rw_ld8()
    {
        Given_HexString("09700040181080000000420084000184");
        AssertCode(     // ld8	r14,[r32]
            "0|L--|0000000000100000(6): 1 instructions",
            "1|L--|r14 = Mem0[r32:word64]",
            "2|L--|0000000000100006(6): 1 instructions",
            "3|L--|r8 = 0<64> + 0<64>",
            "4|L--|000000000010000C(4): 1 instructions",
            "5|L--|r32 = r32 + 8<64>");
    }

    [Test]
    public void Ia64Rw_adds()
    {
        Given_HexString("0B7030420021F0003820200000000400");
        AssertCode(     // adds	r14,0xC,r33
            "0|L--|0000000000100000(6): 1 instructions",
            "1|L--|r14 = r33 + 0xC<64>",
            "2|L--|0000000000100006(6): 2 instructions",
            "3|L--|v5 = Mem0[r14:word32]",
            "4|L--|r15 = CONVERT(v5, word32, word64)",
            "5|L--|000000000010000C(4): 1 instructions",
            "6|L--|nop");
    }

    [Test]
    public void Ia64Rw_ld4()
    {
        Given_HexString("097800421010E00084004200F2E7F79F");
        AssertCode(     // ld4	r15,[r33]
            "0|L--|0000000000100000(6): 2 instructions",
            "1|L--|v4 = Mem0[r33:word32]",
            "2|L--|r15 = CONVERT(v4, word32, word64)",
            "3|L--|0000000000100006(6): 1 instructions",
            "4|L--|r14 = r33 + 0<64>",
            "5|L--|000000000010000C(4): 1 instructions",
            "6|L--|r16 = 0<64> + -257<i64>");
    }

    [Test]
    public void Ia64Rw_cmp4_eq()
    {
        Given_HexString("093804408639E06007884800010025E6");
        AssertCode(     // cmp4.eq	p07,p06,0x1,r32
            "0|L--|0000000000100000(6): 4 instructions",
            "1|L--|v4 = SLICE(1<64>, word32, 0)",
            "2|L--|v5 = SLICE(r32, word32, 0)",
            "3|L--|p07 = v4 == v5",
            "4|L--|p06 = v4 != v5",
            "5|L--|0000000000100006(6): 1 instructions",
            "6|L--|r14 = r1 + 8812<i64>",
            "7|L--|000000000010000C(4): 4 instructions",
            "8|L--|v10 = SLICE(0<64>, word32, 0)",
            "9|L--|v11 = SLICE(r32, word32, 0)",
            "10|L--|p08 = v10 == v11",
            "11|L--|p09 = v10 != v11");
    }

    [Test]
    public void Ia64Rw_addl()
    {
        Given_HexString("0B70900344240000383023C0C10D1091");
        AssertCode(     // addl	r14,8804,r1
            "0|L--|0000000000100000(6): 1 instructions",
            "1|L--|r14 = r1 + 8804<i64>",
            "2|L--|0000000000100006(6): 1 instructions",
            "3|L--|Mem0[r0:word64] = r14",
            "4|L--|000000000010000C(4): 1 instructions",
            "5|L--|r14 = r1 + 8796<i64>");
    }

    [Test]
    public void Ia64Rw_ld1()
    {
        Given_HexString("08700040001010A1F4A74FE011000184");
        AssertCode(     // ld1	r14,[r32]
            "0|L--|0000000000100000(6): 2 instructions",
            "1|L--|v4 = Mem0[r32:byte]",
            "2|L--|r14 = CONVERT(v4, byte, word64)",
            "3|L--|0000000000100006(6): 1 instructions",
            "4|L--|r17 = r1 + -5740<i64>",
            "5|L--|000000000010000C(4): 1 instructions",
            "6|L--|r15 = r32 + 1<64>");
    }

    [Test]
    public void Ia64Rw_addp4()
    {
        Given_HexString("1878840008207008010C610000000020");
        AssertCode(     // addp4	r15,r33,r0
            "0|L--|0000000000100000(6): 1 instructions",
            "1|L--|r15 = __addp4(0<64>, r33)",
            "2|L--|0000000000100006(6): 4 instructions",
            "3|L--|v5 = SLICE(r33, word32, 0)",
            "4|L--|v6 = SLICE(0<64>, word32, 0)",
            "5|L--|p07 = v5 < v6",
            "6|L--|p06 = v5 >= v6",
            "7|L--|000000000010000C(4): 1 instructions",
            "8|L--|nop");
    }


}
