// elf-Linux-ia64-bash_text_n.c
// Generated by decompiling elf-Linux-ia64-bash
// using Reko decompiler version 0.12.3.0.

#include "elf-Linux-ia64-bash.h"

// 400000000011CF40: define complete_builtin
define complete_builtin
{
	<anonymous> * b7;
	word64 r32;
	word64 r1;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r48 = ar.pfs;
	word64 r12 = r12 + ~0x1F;
	word64 r50 = pr;
	word64 r49 = r1 + 0x00;
	Eq_n p07 = 0x00 == r32;
	Eq_n p06 = 0x00 != r32;
	Eq_n r40 = r1 + 0x0000220C;
	Eq_n r34 = r12 + 0x10;
	Eq_n r41 = r1 + 0x00002214;
	<anonymous> * r47 = b7;
	Eq_n r39 = r1 + 0x0000221C;
	Eq_n r42 = r1 + 0x00002224;
	word32 * r51;
	word64 r33;
	<anonymous> * b0;
	word64 r8;
	if (p07)
	{
l400000000011D310:
		r51 = r1 + -3364;
		r33 = 0x00 + 0x00;
		r51 = (word32 *) *r51;
		b0();
		r8 = r33 + 0x00;
		r1 = r49 + 0x00;
		pr = r50;
		ar.pfs = r48;
		b0 = r47;
		r12 += 0x20;
		return;
	}
	Eq_n r43 = r1 + 0x0000222C;
	word64 r16;
	*r34.u1 = (word32) r16;
	r34.u0 = (word32) r34 + 16;
	Eq_n r44 = r1 + 0x00002234;
	Eq_n r45 = r1 + 0x0000223C;
	Eq_n r35 = r12 + 0x28;
	word32 * r36 = r12 + 0x18;
	word64 r38 = r12 + 0x14;
	word32 * r37 = r12 + 0x1C;
	r51 = r32 + 0x00;
	union Eq_n * r0;
	r0->u0 = (word32) (word32) r36;
	r0->u1 = (word32 *) r34;
	word64 r52 = r12 + 0x10;
	r0->u0 = (word32) (word32) r37;
	r0->u0 = (word32) (word32) r38;
	word64 r53 = r35.u1;
	word32 * r54 = r34.u1;
	r0->u1 = (word32 *) r35;
	r0->u1 = (word32 *) r40;
	r0->u1 = (word32 *) r41;
	r0->u1 = (word32 *) r39;
	r0->u1 = (word32 *) r42;
	r0->u1 = (word32 *) r43;
	r0->u1 = (word32 *) r44;
	r0->u1 = (word32 *) r45;
	b0();
	r1 = r49 + 0x00;
	word64 r14 = 0x00 + 258;
	r33 = r8 + 0x00;
	union Eq_n * r15 = r1 + 0x00002434;
	word32 v39 = (word32) r14;
	word32 v40 = (word32) r8;
	p06 = v39 == v40;
	p07 = v39 != v40;
	if (p06)
	{
l400000000011D100:
		r8 = r33 + 0x00;
		pr = r50;
		ar.pfs = r48;
		b0 = r47;
		r12 += 0x20;
		return;
	}
	word32 v41 = *r36;
	r14 = (word64) v41;
	word32 v42 = (word32) 0x00;
	word32 v43 = (word32) r14;
	p06 = v42 == v43;
	p07 = v42 != v43;
	Eq_n r46;
	r46.u0 = r15->u0;
	r15 = r12 + 0x10;
	if (p07)
	{
		r51 = r1 + -3484;
		r51 = (word32 *) *r51;
		b0();
		r1 = r49 + 0x00;
		r51 = r8 + 0x00;
		r52 = 0x00 + 0x00;
		b0();
		r1 = r49 + 0x00;
		r36 = r8 + 0x00;
	}
	else
	{
		word32 v45 = *r37;
		r14 = (word64) v45;
		word32 v46 = (word32) 0x00;
		word32 v47 = (word32) r14;
		p06 = v46 == v47;
		p07 = v46 != v47;
		if (!p07)
		{
			Eq_n v51;
			v51.u1 = r15->u1;
			r14 = (word64) v51;
			if (p06)
				r36 = 0x00 + 0x00;
			word32 v52 = (word32) 0x00;
			word32 v53 = (word32) r14;
			p07 = v52 == v53;
			p06 = v52 != v53;
			if (!p07)
			{
l400000000011D0B0:
				p06 = null == r36;
				p07 = null != r36;
				r51 = r36;
				if (p06)
				{
					p06 = 0x00 == r46;
					p07 = 0x00 != r46;
					r51 = r46.u0;
					if (!p06)
					{
						b0();
						r33 = r8 + 0x00;
						r1 = r49 + 0x00;
						r8 = r33 + 0x00;
						pr = r50;
						ar.pfs = r48;
						b0 = r47;
						r12 += 0x20;
						return;
					}
					goto l400000000011D310;
				}
				b0();
				r1 = r49 + 0x00;
				r33 = r8 + 0x00;
				r51 = r36;
				b0();
				r1 = r49 + 0x00;
				goto l400000000011D100;
			}
l400000000011D130:
			p06 = 0x00 == r46;
			p07 = 0x00 != r46;
			word32 v54 = (word32) 0x01;
			word32 v55 = (word32) r33;
			Eq_n p09 = v54 == v55;
			Eq_n p08 = v54 != v55;
			if (p06)
				r15 = 0x00 + 1;
			if (p08)
				r33 = 0x00 + 1;
			if (!p07)
				;
		}
		r51 = r1 + -0x0DA4;
		r51 = (word32 *) *r51;
		b0();
		r1 = r49 + 0x00;
		r51 = r8 + 0x00;
		r52 = 0x00 + 0x00;
		b0();
		r1 = r49 + 0x00;
		r36 = r8 + 0x00;
	}
	r15 = r12 + 0x10;
	Eq_n v48;
	v48.u1 = r15->u1;
	r14 = (word64) v48;
	word32 v49 = (word32) 0x00;
	word32 v50 = (word32) r14;
	p07 = v49 == v50;
	p06 = v49 != v50;
	if (p06)
		goto l400000000011D0B0;
	goto l400000000011D130;
}

// 400000000011D940: define compgen_builtin
define compgen_builtin
{
	word64 r1;
	word64 r32;
	<anonymous> * b3;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r44 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	<anonymous> * r43 = b3;
	Eq_n p07 = 0x00 == r32;
	Eq_n p06 = 0x00 != r32;
	union Eq_n * r36 = r1 + 0x0000220C;
	Eq_n r35;
	Eq_n r8;
	<anonymous> * b0;
	if (p07)
	{
l400000000011E0E0:
		r35 = 0x00 + 0x00;
		r8.u1 = &r35.u1->t0000.u0;
		ar.pfs = r44;
		b0 = r43;
		r12 += 0x10;
		return;
	}
	union Eq_n * r34 = r12 + 0x10;
	union Eq_n * r37 = r1 + 0x00002214;
	union Eq_n * r38 = r1 + 0x0000221C;
	union Eq_n * r39 = r1 + 0x00002224;
	union Eq_n * r40 = r1 + 0x0000222C;
	union Eq_n * r41 = r1 + 0x00002234;
	r34->u1 = (struct Eq_n *) r8;
	r34 = (union Eq_n *) ((char *) r34 + 8);
	union Eq_n * r42 = r1 + 0x0000223C;
	word64 r45 = r1 + 0x00;
	union Eq_n ** r0;
	*r0 = (union Eq_n **) r36;
	Eq_n r46 = r32 + 0x00;
	struct Eq_n * r47 = 0x00 + 0x00;
	*r0 = (union Eq_n **) r34;
	*r0 = (union Eq_n **) r37;
	word64 * r48 = (word64 *) &r34->u0;
	word64 r49 = r12 + 0x10;
	*r0 = (union Eq_n **) r38;
	*r0 = (union Eq_n **) r39;
	*r0 = (union Eq_n **) r40;
	*r0 = (union Eq_n **) r41;
	*r0 = (union Eq_n **) r42;
	b0();
	r1 = r45 + 0x00;
	Eq_n r14 = 0x00 + 258;
	r35.u1 = &r8.u1->t0000.u0;
	word32 v31 = (word32) r14;
	word32 v32 = (word32) r8;
	p06 = v31 == v32;
	p07 = v31 != v32;
	r14 = r1 + 0x00002434;
	if (p06)
	{
		r8.u1 = &r35.u1->t0000.u0;
		ar.pfs = r44;
		b0 = r43;
		r12 += 0x10;
		return;
	}
	word32 v33 = (word32) 0x01;
	word32 v34 = (word32) r8;
	p06 = v33 == v34;
	p07 = v33 != v34;
	if (p06)
		goto l400000000011E0E0;
	r14.u1 = r14.u1->t0000.u1;
	p06 = 0x00 == r14;
	p07 = 0x00 != r14;
	r14.u0 = (word32) r14 + 8;
	if (!p06)
	{
		r14.u1 = r14.u1->t0000.u1;
		p06 = 0x00 == r14;
		p07 = 0x00 != r14;
		if (!p06)
		{
			if (p07)
				r35.u1 = r14.u1->t0000.u1;
			__break();
l400000000011DA72:
			r47 = r1 + -3444;
			r48 = 0x00 + 5;
			r46 = 0x00 + 0x00;
			p06 = 0x00 == r14;
			p07 = 0x00 != r14;
			if (!p06)
			{
				r47 = r47->ptr0000;
				b0();
				r1 = r45 + 0x00;
				r46.u1 = &r8.u1->t0000.u0;
				b0();
				r1 = r45 + 0x00;
			}
			r14.u1 = r36->u1;
			r47 = r1 + -3436;
			r48 = 0x00 + 5;
			r46 = 0x00 + 0x00;
			p06 = 0x00 == r14;
			p07 = 0x00 != r14;
			if (!p06)
			{
				r47 = r47->ptr0000;
				b0();
				r1 = r45 + 0x00;
				r46.u1 = &r8.u1->t0000.u0;
				b0();
				r1 = r45 + 0x00;
			}
			b0();
			Eq_n r16;
			r16.u1 = r34->u1;
			r14.u0 = (word32) r8 + 8;
			Eq_n r15;
			r15.u0 = (word32) r8 + 16;
			word64 r33 = (word64) &r8.u1->t0000.u0;
			r46.u1 = r42->u1;
			r1 = r45 + 0x00;
			r16.u1->t0000.u1 = (struct Eq_n *) r14;
			r16 = r12 + 0x10;
			p06 = 0x00 == r46;
			p07 = 0x00 != r46;
			r14.u1 = r16.u1->t0000.u1;
			r14.u1->t0000.u1 = (struct Eq_n *) r15;
			r14 = 0x00 + 1;
			r14.u1->t0000.u0 = (word32) (word32) r8;
			if (p06)
				r8 = 0x00 + 0x00;
		}
	}
	r35 = r1 + -0x0D7C;
	r35.u1 = r35.u1->t0000.u1;
	r14.u1 = r37->u1;
	goto l400000000011DA72;
}

// 400000000011E280: define compopt_builtin
define compopt_builtin
{
	word32 * r8;
	word64 r32;
	<anonymous> * b2;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r43 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	Eq_n r34 = r1 + 9276;
	word64 r39 = r1 + 0x00002424;
	struct Eq_n * r40 = r1 + -3380;
	word64 r44 = r1 + 0x00;
	word32 * r33 = r12 + 0x10;
	<anonymous> * r42 = b2;
	union Eq_n * r38 = 0x00 + 0x00;
	word64 r37 = 0x00 + 0x00;
	word64 r4;
	*r33 = (word32) r4;
	++r33;
	r40 = r40->ptr0000;
	word32 * r0;
	*r0 = (word32) r33;
	<anonymous> * b0;
	b0();
	r1 = r44 + 0x00;
	Eq_n r46 = r1 + -0x0D5C;
	Eq_n r45 = r32 + 0x00;
	r46.u1 = *r46.u1;
	b0();
	r1 = r44 + 0x00;
	word32 v24 = (word32) ~0x00;
	word32 v25 = (word32) r8;
	Eq_n p07 = v24 == v25;
	Eq_n p06 = v24 != v25;
	Eq_n r14;
	if (!p07)
	{
		word32 v28 = *r34.u2;
		r14.u1 = (word64) v28;
		word32 v30 = (word32) 0x2D;
		word32 v31 = (word32) r14;
		p07 = v30 == v31;
		p06 = v30 != v31;
		if (p06)
			r14 = r12 + 0x10;
		word64 p18;
		if (!p18)
			;
	}
	else
	{
		r14 = r1 + 0x00002434;
		word32 v32 = (word32) 0x00;
		word32 v33 = (word32) r37;
		p06 = v32 == v33;
		p07 = v32 != v33;
		r34.u1 = *r14.u1;
		if (p07)
		{
			r45 = r1 + -3484;
			r45.u1 = *r45.u1;
		}
		else
		{
			word32 v36 = (word32) 0x00;
			word32 v37 = (word32) r38;
			p06 = v36 == v37;
			p07 = v36 != v37;
			if (!p07)
			{
				p06 = 0x00 == r34;
				p07 = 0x00 != r34;
				Eq_n r35;
				ptr64 r36;
				word64 r47;
				if (!p07)
				{
					r14 = r1 + -10404;
					r14.u1 = *r14.u1;
					Eq_n v40;
					v40.u0 = *r14.u2;
					r14 = r1 + 9220;
					if (!p06)
					{
						r35.u1 = *r14.u1;
						r14 = r12 + 0x10;
						p07 = 0x00 == r35;
						p06 = 0x00 != r35;
						if (!p07)
						{
							word32 v44 = *r33;
							r33 = (word64) v44;
							Eq_n v45;
							v45.u0 = *r14.u2;
							r36 = (word64) v45;
							word32 v46 = (word32) 0x00;
							word32 v47 = (word32) r33;
							p07 = v46 == v47;
							p06 = v46 != v47;
							if (!p06)
							{
								word32 v54 = (word32) 0x00;
								word32 v55 = (word32) r36;
								p07 = v54 == v55;
								p06 = v54 != v55;
								if (p07)
								{
									r14 = r1 + 9212;
									r46.u1 = r35.u1;
									r45.u1 = *r14.u1;
									b0();
									r1 = r44 + 0x00;
									r45 = 0x00 + 0x00;
									b0();
									r34.u1 = r8;
									r1 = r44 + 0x00;
									r8 = (word32 *) r34.u1;
									ar.pfs = r43;
									b0 = r42;
									r12 += 0x10;
									return;
								}
							}
							r45.u1 = r35.u1;
							r46.u1 = r33;
							r47 = 0x00 + 1;
							r34 = 0x00 + 0x00;
							b0();
							r47 = 0x00 + 0x00;
							r1 = r44 + 0x00;
							r45.u1 = r35.u1;
							r46 = r36 + 0x00;
							b0();
							r1 = r44 + 0x00;
							r45.u1 = r33;
							r46 = 0x00 + 1;
							b0();
							r1 = r44 + 0x00;
							r45 = r36 + 0x00;
							r46 = 0x00 + 0x00;
							b0();
							r8 = (word32 *) r34.u1;
							r1 = r44 + 0x00;
							ar.pfs = r43;
							b0 = r42;
							r12 += 0x10;
							return;
						}
					}
					r46 = r1 + -0x0D54;
					r47 = 0x00 + 5;
					r45 = 0x00 + 0x00;
					r34 = 0x00 + 1;
					r46.u1 = *r46.u1;
					b0();
					r1 = r44 + 0x00;
					r45.u1 = r8;
					b0();
					r8 = (word32 *) r34.u1;
					r1 = r44 + 0x00;
					ar.pfs = r43;
					b0 = r42;
					r12 += 0x10;
					return;
				}
				else
				{
					r35.u1 = r34.u1;
					r34 = 0x00 + 0x00;
					do
					{
						r38 = (union Eq_n *) ((word32) r35 + 8);
						r14.u1 = r38->u1;
						r45.u1 = *r14.u1;
						b0();
						r1 = r44 + 0x00;
						p07 = null == r8;
						p06 = null != r8;
						r36 = r8;
						r47 = 0x00 + 1;
						r45.u1 = r8;
						if (!p07)
						{
							word32 v48 = *r33;
							r14.u1 = (word64) v48;
							word32 v49 = (word32) 0x00;
							word32 v50 = (word32) r14;
							p07 = v49 == v50;
							p06 = v49 != v50;
							r46.u1 = r14.u1;
							r14 = r12 + 0x10;
							Eq_n v51;
							v51.u0 = *r14.u2;
							r37 = (word64) v51;
							if (!p06)
							{
								word32 v52 = (word32) 0x00;
								word32 v53 = (word32) r37;
								p07 = v52 == v53;
								p06 = v52 != v53;
								if (p07)
								{
									r14.u1 = r38->u1;
									r46.u1 = r8;
									r45.u1 = *r14.u1;
									b0();
									r35.u1 = *r35.u1;
									r1 = r44 + 0x00;
									p07 = 0x00 == r35;
									p06 = 0x00 != r35;
									if (p06)
										continue;
									break;
								}
							}
							b0();
							r1 = r44 + 0x00;
							r45 = r36 + 0x00;
							r46 = r37 + 0x00;
							r47 = 0x00 + 0x00;
							b0();
							r35.u1 = *r35.u1;
							r1 = r44 + 0x00;
							p07 = 0x00 == r35;
							p06 = 0x00 != r35;
							if (p06)
								continue;
							break;
						}
						r46 = r1 + -0x0D94;
						r45 = 0x00 + 0x00;
						r47 = 0x00 + 5;
						r34 = 0x00 + 1;
						r46.u1 = *r46.u1;
						b0();
						r14.u1 = r38->u1;
						r1 = r44 + 0x00;
						r45.u1 = r8;
						r46.u1 = *r14.u1;
						b0();
						r35.u1 = *r35.u1;
						r1 = r44 + 0x00;
						p07 = 0x00 == r35;
						p06 = 0x00 != r35;
					} while (p06);
					r8 = (word32 *) r34.u1;
					ar.pfs = r43;
					b0 = r42;
					r12 += 0x10;
					return;
				}
			}
			r45 = r1 + -0x0DA4;
			r45.u1 = *r45.u1;
		}
		b0();
		r1 = r44 + 0x00;
		r45.u1 = r8;
		r46 = 0x00 + 0x00;
		b0();
		Eq_n p08 = 0x00 == r34;
		Eq_n p09 = 0x00 != r34;
		p06 = null == r8;
		p07 = null != r8;
		r1 = r44 + 0x00;
		if (p08)
			r14 = 0x00 + 1;
	}
}

// 400000000011F840: define glob_pattern_p
define glob_pattern_p
{
	word64 r32;
	word64 r8;
	<anonymous> * b2;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r36 = r1 + 0x00;
	<anonymous> * r34 = b2;
	<anonymous> * b0;
	b0();
	Eq_n p07 = 0x01 == r8;
	Eq_n p06 = 0x01 != r8;
	r1 = r36 + 0x00;
	word32 * r37 = r12 + 0x10;
	word64 r38 = 0x00 + 0x00;
	word64 r39 = r32 + 0x00;
	word64 r33;
	if (!p07)
	{
		b0();
		Eq_n r14 = r12 + 0x10;
		r1 = r36 + 0x00;
		p07 = ~0x00 == r8;
		p06 = ~0x00 != r8;
		word64 r19 = 0x00 + 0x00;
		if (!p07)
		{
			r37 = *r14.u2;
			struct Eq_n * r18 = r1 + -6196;
			r18 = r18->ptr0000;
			word32 * r16 = r37;
			word32 v24 = *r37;
			r14.u2 = (word64) v24;
			while (true)
			{
				word32 v25 = (word32) 0x00;
				word32 v26 = (word32) r14;
				p07 = v25 == v26;
				p06 = v25 != v26;
				r14.u1 = (word32) r14 - 33;
				word32 * r15 = r16 + 1;
				if (p07)
					break;
				up32 v28 = (word32) 0x3C;
				up32 v29 = (word32) r14;
				p06 = v28 < v29;
				p07 = v28 >= v29;
				if (p07)
				{
					r14 = __addp4(0x00, r14);
					r14.u2 = r18 + r14;
					word32 * r17 = *r14.u2;
					r14.u2 = r17 + r14;
					Eq_n b6 = r14;
					b6();
					return;
				}
				word32 v30 = *r15;
				r14.u2 = (word64) v30;
				r16 = r15;
			}
			r33 = 0x00 + 0x00;
			b0();
			r1 = r36 + 0x00;
			r8 = r33 + 0x00;
			ar.pfs = r35;
			b0 = r34;
			r12 += 0x10;
			return;
		}
	}
	r37 = r32 + 0x00;
	b0();
	r33 = r8 + 0x00;
	r1 = r36 + 0x00;
	r8 = r33 + 0x00;
	ar.pfs = r35;
	b0 = r34;
	r12 += 0x10;
}

// 400000000011FA80: define glob_vector
define glob_vector
{
	byte * r32;
	<anonymous> * b3;
	word64 r1;
	word64 pr;
	word64 r12;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r60 = ar.pfs;
	word64 r61 = r12 + 0x00;
	r12 += ~0x9F;
	word64 r63 = pr;
	word64 r62 = r1 + 0x00;
	<anonymous> * r59 = b3;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	Eq_n r14;
	Eq_n r64;
	Eq_n r36;
	<anonymous> * b0;
	Eq_n r35;
	union Eq_n * r8;
	Eq_n r41;
	word64 r33;
	word64 * r37;
	union Eq_n * r0;
	if (!p06)
	{
		byte v17 = *r32;
		r14.u2 = (word64) v17;
		int8 v19 = (int8) r14;
		r14.u2 = (int64) v19;
		word32 v20 = (word32) 0x00;
		word32 v21 = (word32) r14;
		p07 = v20 == v21;
		p06 = v20 != v21;
		if (!p07)
		{
			r64.u2 = r32;
			ui64 r50 = 0x00 + 528;
			r36 = 0x00 + 0x00;
			word64 r54 = 0x00 + 0x00;
			b0();
			r1 = r62 + 0x00;
			r35.u2 = &r8->u0;
			r64.u2 = r32;
			ui64 r34;
			r50 = r34 & r50;
			r41 = 0x00 + 0x00;
			b0();
			word32 v35 = (word32) 0x00;
			word32 v36 = (word32) r8;
			p06 = v35 == v36;
			p07 = v35 != v36;
			r1 = r62 + 0x00;
			r64 = r33 + 0x00;
			word64 r46 = r61 + 0x08;
			word64 r56 = 0x00 + 99999;
			Eq_n r38;
			Eq_n p08;
			Eq_n p09;
			if (p06)
			{
				r64 = r33 + 0x00;
				b0();
				r1 = r62 + 0x00;
				int32 v41 = (word32) r8;
				int32 v42 = (word32) 0x00;
				p07 = v41 < v42;
				p06 = v41 >= v42;
				if (p06)
				{
					r64 = r33 + 0x00;
					b0();
					r64.u2 = r35 + r8;
					r1 = r62 + 0x00;
					r37 = &r8->u0;
					r64.u1 = (word32) r64 + 2;
					int32 v45 = (int32) r64;
					r64.u2 = (int64) v45;
					b0();
					r64.u2 = &r35.u3->ptr0001;
					r1 = r62 + 0x00;
					r36.u2 = &r8->u0;
					int32 v46 = (int32) r64;
					r64.u2 = (int64) v46;
					b0();
					p06 = 0x00 == r36;
					p07 = 0x00 != r36;
					r38.u2 = &r8->u0;
					r1 = r62 + 0x00;
					if (!p06)
					{
						Eq_n r65;
						r65.u1 = r32;
						r64.u2 = &r8->u0;
						r41 = 0x00 + 1;
						b0();
						r1 = r62 + 0x00;
						r64.u2 = r38.u2;
						b0();
						r1 = r62 + 0x00;
						r64.u2 = r36.u2;
						r65 = r33 + 0x00;
						b0();
						r64.u2 = (char *) r37 + 1;
						int32 v50 = (int32) r37;
						r14.u2 = (int64) v50;
						Eq_n r15 = 0x00 + 47;
						r1 = r62 + 0x00;
						r65.u1 = r38.u2;
						r14.u2 = r14 + r36;
						int32 v51 = (int32) r64;
						r64.u2 = (int64) v51;
						r37 = 0x00 + 0x00;
						r15.u3->t0000.u0 = (byte) r14;
						r64.u2 = r64 + r36;
						b0();
						r65.u1 = r36.u2;
						r1 = r62 + 0x00;
						word64 r66 = r61 + ~0x8F;
						r64 = 0x00 + 1;
						b0();
						int32 v53 = (word32) r8;
						int32 v54 = (word32) 0x00;
						p06 = v53 < v54;
						p07 = v53 >= v54;
						r1 = r62 + 0x00;
						r64.u2 = r36.u2;
						r36 = 0x00 + 0x00;
						if (p06)
						{
							r41 = 0x00 + 0x00;
							r35 = 0x00 + 0x00;
							r36 = 0x00 + 0x00;
							b0();
							r1 = r62 + 0x00;
							r64.u2 = r38.u2;
							b0();
							r1 = r62 + 0x00;
						}
						else
						{
							b0();
							r12 += ~0x1F;
							r1 = r62 + 0x00;
							r35 = r12 + 0x10;
							r14.u2 = r35.u2;
							*r14.u2 = r8;
							r14.u1 = (word32) r14 + 8;
							*r38.u2 = (word64) r14;
						}
l4000000000120280:
						word32 v43 = (word32) 0x00;
						word32 v44 = (word32) r37;
						p07 = v43 == v44;
						p06 = v43 != v44;
						if (!p06)
						{
							r64.u2 = &r41.u3->ptr0001;
							r64 = __addp4(0x00, r64);
							r64 = (r64 << 0x03) + 0x00;
							b0();
							Eq_n r17;
							r17.u1 = (word32) r41 - 1;
							p06 = null == r8;
							p07 = null != r8;
							r1 = r62 + 0x00;
							r14.u2 = &r8->u0;
							r15.u2 = r35.u2;
							if (!p06)
							{
								r17 = __addp4(0x00, r17);
								word32 v55 = (word32) 0x00;
								word32 v56 = (word32) r41;
								p07 = v55 == v56;
								p06 = v55 != v56;
								r38.u2 = &r8->u0;
								if (!p07)
								{
									if (p06)
										r17.u2 = &r8->u0 + r17;
								}
								r41 = __addp4(0x00, r41);
								p07 = 0x00 == r36;
								p06 = 0x00 != r36;
								p08 = 0x00 == r35;
								p09 = 0x00 != r35;
								r41.u2 = r38.u2 + r41;
								r0->u2 = (word64 *) r41;
								if (!p07)
									;
l40000000001201C0:
								r8 = (union Eq_n *) r38.u2;
								pr = r63;
								ar.pfs = r60;
								b0 = r59;
								r12 = r61 + 0x00;
								return;
							}
						}
						r38 = r1 + 7684;
						while (true)
						{
							p07 = 0x00 == r35;
							p06 = 0x00 != r35;
							if (p07)
								break;
							p06 = 0x00 == r36;
							p07 = 0x00 != r36;
							p08 = r36 == r35;
							p09 = r36 != r35;
							r14.u1 = (word32) r35 + 8;
							if (!p06)
							{
								if (p08)
									r36 = 0x00 + 0x00;
							}
							r14.u1 = (word32) r35 + 8;
							r64.u2 = *r14.u2;
							b0();
							r1 = r62 + 0x00;
							r35.u2 = *r35.u2;
						}
						r14 = r1 + 7676;
						r15 = __ld_acquire<word32>(r14);
						word32 v57 = (word32) 0x00;
						word32 v58 = (word32) r15;
						p07 = v57 == v58;
						p06 = v57 != v58;
						if (p06)
						{
							r64 = __ld_acquire<word32>(r14);
							b0();
							r14 = __ld_acquire<word32>(r38);
							r1 = r62 + 0x00;
							r38 = 0x00 + 0x00;
							word32 v61 = (word32) 0x00;
							word32 v62 = (word32) r14;
							p06 = v61 == v62;
							p07 = v61 != v62;
							if (p06)
								goto l40000000001201C0;
						}
						else
						{
							r14 = __ld_acquire<word32>(r38);
							r38 = 0x00 + 0x00;
							word32 v63 = (word32) 0x00;
							word32 v64 = (word32) r14;
							p06 = v63 == v64;
							p07 = v63 != v64;
							if (!p07)
								goto l40000000001201C0;
						}
						b0();
						r8 = (union Eq_n *) r38.u2;
						r1 = r62 + 0x00;
						pr = r63;
						ar.pfs = r60;
						b0 = r59;
						r12 = r61 + 0x00;
						return;
					}
					goto l4000000000120850;
				}
			}
			else
			{
				r35 = 0x00 + 0x00;
				b0();
				r1 = r62 + 0x00;
				p06 = null == r8;
				p07 = null != r8;
				ui64 r16 = r34 & 0x18;
				word64 r39 = &r8->u0;
				if (!p06)
				{
					r14 = r1 + 0x00002244;
					word32 * r49 = r1 + 6372;
					r38 = r1 + 7684;
					word64 r40 = r1 + 7676;
					word32 v69 = (word32) 0x00;
					word32 v70 = (word32) r16;
					Eq_n p20 = v69 == v70;
					Eq_n p21 = v69 != v70;
					word64 r57 = r1 + 21276;
					Eq_n v74;
					v74.u1 = r14.u3->t0000.u1;
					r14.u2 = (word64) v74;
					r16 = 0x00 + -513;
					word64 r58 = r1 + 0x00002444;
					word32 v76 = *r49;
					ui64 r48 = (word64) v76;
					word32 v78 = (word32) 0x00;
					word32 v79 = (word32) r14;
					p06 = v78 == v79;
					p07 = v78 != v79;
					r14 = r1 + 7664;
					word32 v80 = (word32) 0x00;
					word32 v81 = (word32) r48;
					p08 = v80 == v81;
					p09 = v80 != v81;
					ui64 r55 = r34 & r16;
					if (p08)
						r48 = 0x00 + 1;
					if (p09)
						r48 = 0x00 + 5;
					Eq_n v83;
					v83.u1 = r14.u3->t0000.u1;
					r14.u2 = (word64) v83;
					if (p07)
						r48 |= 0x10;
					word32 v84 = (word32) 0x00;
					word32 v85 = (word32) r14;
					p06 = v84 == v85;
					p07 = v84 != v85;
					r14 = r34 & 0x10;
					word32 v86 = (word32) 0x00;
					word32 v87 = (word32) r14;
					Eq_n p16 = v86 == v87;
					Eq_n p17 = v86 != v87;
					if (p07)
						r48 |= 0x20;
					__break();
				}
			}
l4000000000120420:
			r38 = r1 + 0x00002444;
			r8 = (union Eq_n *) r38.u2;
			pr = r63;
			ar.pfs = r60;
			b0 = r59;
			r12 = r61 + 0x00;
			return;
		}
	}
	r64 = r33 + 0x00;
	r37 = 0x00 + 0x00;
	r41 = 0x00 + 1;
	r36 = 0x00 + 0x00;
	b0();
	r1 = r62 + 0x00;
	int32 v29 = (word32) r8;
	int32 v30 = (word32) 0x00;
	p07 = v29 < v30;
	p06 = v29 >= v30;
	r64 = 0x00 + 1;
	if (p07)
		goto l4000000000120420;
	r12 += ~0x1F;
	r35 = r12 + 0x10;
	r0->u2 = (word64 *) r35;
	b0();
	r14.u1 = (word32) r35 + 8;
	r1 = r62 + 0x00;
	p06 = null == r8;
	p07 = null != r8;
	if (!p06)
	{
		r0->u0 = (byte) (byte) r8;
		r8->u0 = (word64) r14;
		goto l4000000000120280;
	}
l4000000000120850:
	r37 = 0x00 + 1;
	r41 = 0x00 + 0x00;
	r35 = 0x00 + 0x00;
	r36 = 0x00 + 0x00;
	goto l4000000000120280;
}

// 4000000000120D80: define glob_filename
define glob_filename
{
	Eq_n r8;
	<anonymous> * b2;
	word64 r1;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r51 = ar.pfs;
	word64 r53 = pr;
	word64 r52 = r1 + 0x00;
	<anonymous> * r50 = b2;
	Eq_n r54 = 0x00 + 8;
	word64 r45 = 0x00 + 1;
	<anonymous> * b0;
	b0();
	Eq_n p07 = 0x00 == r8;
	Eq_n p06 = 0x00 != r8;
	r1 = r52 + 0x00;
	word64 r35 = r8.u2;
	Eq_n r55 = 0x00 + 47;
	word64 r32;
	r54 = r32 + 0x00;
	if (p07)
	{
l40000000001216A0:
		r35 = 0x00 + 0x00;
		pr = r53;
		r8 = r35 + 0x00;
		ar.pfs = r51;
		b0 = r50;
		return;
	}
	union Eq_n * r0;
	r0->u2 = (word64 *) r8;
	b0();
	Eq_n r34 = r32 - r8;
	p06 = 0x00 == r8;
	p07 = 0x00 != r8;
	r1 = r52 + 0x00;
	byte * r38 = (byte *) r8.u2;
	Eq_n r42;
	Eq_n r14;
	Eq_n p16;
	ui64 r33;
	if (p06)
	{
		r42 = r1 + -6188;
		r38 = r32 + 0x00;
		r45 = 0x00 + 0x00;
		r34 = 0x00 + 0x00;
		r42.u2 = r42.u2->t0000.u2;
		r54.u2 = &r42.u2->t0000.u0;
		b0();
		r1 = r52 + 0x00;
		word32 v27 = (word32) 0x00;
		word32 v28 = (word32) r8;
		p06 = v27 == v28;
		p07 = v27 != v28;
		if (p06)
			goto l4000000000120E80;
	}
	else
	{
		r54.u1 = (word32) r34 + 2;
		r34.u2 = &r34.u3->ptr0001;
		++r38;
		r54 = __addp4(0x00, r54);
		Eq_n r36 = __addp4(0x00, r34);
		b0();
		r42.u2 = r8.u2;
		p06 = 0x00 == r8;
		p07 = 0x00 != r8;
		r1 = r52 + 0x00;
		Eq_n r56;
		r56.u1 = &r36.u1->u0;
		r54.u2 = r8.u2;
		if (p06)
			goto l40000000001216A0;
		r55 = r32 + 0x00;
		r36.u1 = r36 + r42;
		b0();
		r1 = r52 + 0x00;
		r0->u0 = (byte) (byte) r36;
		r54.u2 = &r42.u2->t0000.u0;
		b0();
		r1 = r52 + 0x00;
		word32 v29 = (word32) 0x00;
		word32 v30 = (word32) r8;
		p06 = v29 == v30;
		p07 = v29 != v30;
		if (!p07)
		{
l4000000000120E80:
			byte v31 = *r38;
			r14.u2 = (word64) v31;
			word32 v33 = (word32) 0x00;
			word32 v34 = (word32) r34;
			p16 = v33 == v34;
			Eq_n p17 = v33 != v34;
			r54 = r35 + 0x00;
			r36 = r33 & 0xFE;
			int8 v38 = (int8) r14;
			r14.u2 = (int64) v38;
			word32 v39 = (word32) 0x00;
			word32 v40 = (word32) r14;
			p07 = v39 == v40;
			p06 = v39 != v40;
			if (!p07)
				;
			r34.u2 = &r34.u3->ptr0001;
			r54 = r35 + 0x00;
			r55 = 0x00 + 16;
			b0();
			p06 = 0x00 == r8;
			p07 = 0x00 != r8;
			r34 = __addp4(0x00, r34);
			r35 = r8.u2;
			r1 = r52 + 0x00;
			if (!p06)
			{
				r54.u2 = r34.u2;
				b0();
				p06 = 0x00 == r8;
				p07 = 0x00 != r8;
				r1 = r52 + 0x00;
				r54.u2 = r8.u2;
				*r8.u2 = r35;
				r55.u1 = &r42.u2->t0000.u0;
				if (!p06)
				{
					r56.u1 = r34.u2;
					b0();
					r14 = r35 + 0x08;
					r1 = r52 + 0x00;
					word32 v60 = (word32) 0x00;
					word32 v61 = (word32) r45;
					p06 = v60 == v61;
					p07 = v60 != v61;
					if (p07)
					{
						r54.u2 = &r42.u2->t0000.u0;
						b0();
						r14 = r35 + 0x08;
						r1 = r52 + 0x00;
						r0->u2 = (word64 *) r14;
					}
					else
						r0->u2 = (word64 *) r14;
					r8 = r35 + 0x00;
					pr = r53;
					ar.pfs = r51;
					b0 = r50;
					return;
				}
				else
				{
					r54 = r35 + 0x00;
					b0();
					r1 = r52 + 0x00;
					p07 = 0x00 == r42;
					p06 = 0x00 != r42;
					if (p06)
						r14 = 0x00 + 1;
				}
			}
			goto l40000000001216A0;
		}
	}
	r14 = r33 & 0xFE;
	r55.u1 = r14.u2;
	Eq_n r15;
	if (!p16)
	{
		Eq_n v46;
		v46.u0 = r42.u2->t0000.u0;
		r15.u1 = (word64) v46;
		int8 v47 = (int8) r15;
		r15.u1 = (int64) v47;
		word32 v48 = (word32) 0x2A;
		word32 v49 = (word32) r15;
		p07 = v48 == v49;
		p06 = v48 != v49;
		if (p07)
		{
			r15.u0 = (word32) r42 + 1;
			Eq_n v51;
			v51.u0 = r15.u1->u0;
			r15.u1 = (word64) v51;
			int8 v52 = (int8) r15;
			r15.u1 = (int64) v52;
			word32 v53 = (word32) 0x2A;
			word32 v54 = (word32) r15;
			p07 = v53 == v54;
			p06 = v53 != v54;
			if (!p06)
			{
				r15.u0 = (word32) r42 + 2;
				r54.u2 = &r42.u2->t0000.u0;
				Eq_n v55;
				v55.u0 = r15.u1->u0;
				r15.u1 = (word64) v55;
				int8 v56 = (int8) r15;
				r15.u1 = (int64) v56;
				word32 v57 = (word32) 0x2F;
				word32 v58 = (word32) r15;
				p06 = v57 == v58;
				p07 = v57 != v58;
				if (p06)
					r55 = 0x00 + 528;
			}
		}
	}
	r14.u1 = (word32) r34 - 1;
	r54.u2 = &r42.u2->t0000.u0;
	r14 = __addp4(0x00, r14);
	r14.u2 = r14 + r42;
	Eq_n v41;
	v41.u0 = r14.u3->t0000.u0;
	r15.u1 = (word64) v41;
	int8 v43 = (int8) r15;
	r15.u1 = (int64) v43;
	word32 v44 = (word32) 0x2F;
	word32 v45 = (word32) r15;
	p07 = v44 == v45;
	p06 = v44 != v45;
	if (p07)
		r0->u0 = (byte) (byte) r14;
	__break();
	pr = 0x0A04200D;
}

// 4000000000121C40: define strmatch
define strmatch
{
	word64 r34;
	word64 r33;
	word64 r1;
	word64 r32;
	<anonymous> * b3;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	<anonymous> * r35 = b3;
	Eq_n p06 = 0x00 == r32;
	Eq_n p07 = 0x00 != r32;
	word64 r37 = r1 + 0x00;
	word64 r8 = 0x00 + 1;
	ar.pfs = r36;
	<anonymous> * b0;
	if (!p07)
		b0 = r35;
	else
	{
		word64 r38 = r32 + 0x00;
		word64 r39 = r33 + 0x00;
		word64 r40 = r34 + 0x00;
		b0();
		r1 = r37 + 0x00;
		ar.pfs = r36;
		b0 = r35;
	}
}

// 4000000000121D00: define wcsmatch
define wcsmatch
{
	word64 r34;
	word64 r33;
	word64 r1;
	word64 r32;
	<anonymous> * b3;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	<anonymous> * r35 = b3;
	Eq_n p06 = 0x00 == r32;
	Eq_n p07 = 0x00 != r32;
	word64 r37 = r1 + 0x00;
	word64 r8 = 0x00 + 1;
	ar.pfs = r36;
	<anonymous> * b0;
	if (!p07)
		b0 = r35;
	else
	{
		word64 r38 = r32 + 0x00;
		word64 r39 = r33 + 0x00;
		word64 r40 = r34 + 0x00;
		b0();
		r1 = r37 + 0x00;
		ar.pfs = r36;
		b0 = r35;
	}
}

// 4000000000127100: define internal_strmatch
define internal_strmatch
{
	<anonymous> * b3;
	word64 LC;
	word64 pr;
	byte * r33;
	up64 r34;
	word64 r1;
	word64 r32;
	<anonymous> * b6;
	byte * ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	byte * r39 = ar.pfs;
	<anonymous> * r38 = b6;
	Eq_n p06 = 0x00 == r32;
	Eq_n p07 = 0x00 != r32;
	word32 * r40 = r1 + 0x00;
	ui64 r36 = r34 + 0x00;
	word16 ** r8 = 0x00 + 1;
	ar.pfs = r39;
	<anonymous> * b0;
	if (!p07)
	{
		b0 = r38;
		return;
	}
	word64 r41 = r33;
	r34 = r32 + 0x00;
	b0();
	r1 = r40;
	word64 r37 = r8;
	r41 = r32 + 0x00;
	r32 = r33;
	b0();
	r1 = r40;
	r33 += r37;
	up64 r35 = (char *) r8 + r34;
	b0 = r38;
	ar.pfs = r39;
	byte * r2 = ar.pfs;
	byte * r60 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r62 = pr;
	p06 = 0x00 == r32;
	p07 = 0x00 != r32;
	ui64 r47 = r36 & 0x20;
	ui64 r46 = r36 & 0x02;
	struct Eq_n * r51 = r1 + -5820;
	word64 r63 = LC;
	word64 r61 = r1 + 0x00;
	r39 = r32 + 0x00;
	ui64 r42 = 0x00 + 0x0100;
	word64 r49 = 0x00 + 0x00FF;
	<anonymous> * r59 = b3;
	word32 v36 = (word32) 0x00;
	word32 v37 = (word32) r47;
	Eq_n p18 = v36 == v37;
	Eq_n p19 = v36 != v37;
	word32 v40 = (word32) 0x00;
	word32 v41 = (word32) r46;
	Eq_n p23 = v40 == v41;
	Eq_n p22 = v40 != v41;
	word64 r50 = r1 + 6380;
	if (!p06)
	{
		p07 = r34 < r35;
		p06 = r34 >= r35;
		word16 * r14;
		if (!p06)
		{
			r51 = r51->ptr0000;
			r38 = r34 + 0x00;
			byte v45 = (byte) *r38;
			r37 = (word64) v45;
			r38 = (<anonymous> *) ((char *) r38 + 1);
			r14 = r37 + 0x00;
			byte * r45 = r38;
			word64 p16;
			if (!p16)
			{
				byte v49 = (byte) r37;
				r40 = (word64) v49;
				b0();
				r14 = (word16 *) *r8;
				r1 = r61 + 0x00;
				r14 += r40;
				word16 v50 = *r14;
				r14 = (word64) v50;
				r14 &= r42;
				word32 v51 = (word32) 0x00;
				word32 v52 = (word32) r14;
				p06 = v51 == v52;
				p07 = v51 != v52;
				if (!p06)
				{
					b0();
					r14 = (word16 *) *r8;
					r1 = r61 + 0x00;
					r40 = (word32 *) (r14 + r40 *64 2);
					word32 v56 = *r40;
					r37 = (word64) v56;
				}
			}
			Eq_n p21 = r39 < r33;
			Eq_n p20 = r39 >= r33;
			if (p21)
			{
				byte v55 = *r39;
				r40 = (word64) v55;
			}
			pr = 0x08001000;
		}
		r39 = r32 + 0x00;
		p06 = r39 == r33;
		p07 = r39 != r33;
		if (!p06)
		{
			if (p06)
				goto l4000000000122F20;
			byte v59 = *r39;
			r14 = (word64) v59;
			p06 = (word16 *) 0x2F == r14;
			p07 = (word16 *) 0x2F != r14;
			if (!p06)
				goto l4000000000122F20;
		}
		r8 = 0x00 + 0x00;
		pr = r62;
		ar.pfs = r60;
		LC = r63;
		b0 = r59;
		r12 += 0x10;
	}
	else
	{
l4000000000122F20:
		r8 = 0x00 + 1;
		pr = r62;
		ar.pfs = r60;
		LC = r63;
		b0 = r59;
		r12 += 0x10;
	}
}

// 40000000001271C0: define internal_wstrmatch
define internal_wstrmatch
{
	<anonymous> * b6;
	word64 pr;
	uint64 r34;
	word32 * r33;
	word64 r1;
	word64 r32;
	<anonymous> * b7;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r40 = ar.pfs;
	<anonymous> * r39 = b7;
	Eq_n p06 = 0x00 == r32;
	Eq_n p07 = 0x00 != r32;
	word64 r41 = r1 + 0x00;
	ui64 r37 = r32 + 0x00;
	ui64 r8 = 0x00 + 1;
	ar.pfs = r40;
	<anonymous> * b0;
	if (!p07)
	{
		b0 = r39;
		return;
	}
	word32 * r42 = r33;
	ui64 r36 = r34 + 0x00;
	r34 = r37 + 0x00;
	b0();
	r1 = r41 + 0x00;
	r42 = r32 + 0x00;
	word32 * r38 = r33 + r8;
	r32 = r33;
	b0();
	r1 = r41 + 0x00;
	r33 = r38;
	uint64 r35 = (r8 << 0x02) + r37;
	b0 = r39;
	ar.pfs = r40;
	word64 r2 = ar.pfs;
	word64 r55 = ar.pfs;
	word64 r12 = r12 + ~0x1F;
	word64 r57 = pr;
	ui64 r47 = r36 & 0x20;
	p06 = 0x00 == r32;
	p07 = 0x00 != r32;
	ui64 r46 = r36 & 0x02;
	struct Eq_n * r49 = r1 + -5772;
	word64 r56 = r1 + 0x00;
	word64 r44 = r1 + 6400;
	r38 = r32 + 0x00;
	word64 r45 = r1 + 6408;
	r49 = r49->ptr0000;
	word32 v33 = (word32) 0x00;
	word32 v34 = (word32) r47;
	Eq_n p18 = v33 == v34;
	Eq_n p19 = v33 != v34;
	word32 v37 = (word32) 0x00;
	word32 v38 = (word32) r46;
	Eq_n p21 = v37 == v38;
	Eq_n p20 = v37 != v38;
	<anonymous> * r54 = b6;
	if (!p06)
	{
		p07 = r34 < r35;
		p06 = r34 >= r35;
		if (!p06)
		{
			r42 = r34 + 0x00;
			word32 v43 = *r42;
			r37 = (word64) v43;
			++r42;
			word64 p16;
			if (!p16)
			{
				word64 r58 = r37 + 0x00;
				b0();
				r1 = r56 + 0x00;
				word32 v46 = (word32) 0x00;
				word32 v47 = (word32) r8;
				p06 = v46 == v47;
				p07 = v46 != v47;
				if (!p06)
				{
					r58 = r37 + 0x00;
					b0();
					r1 = r56 + 0x00;
					r37 = r8 + 0x00;
				}
			}
			Eq_n p23 = r38 < r33;
			Eq_n p22 = r38 >= r33;
			if (p23)
			{
				word32 v50 = *r38;
				r39 = (word64) v50;
			}
		}
		r38 = r32 + 0x00;
		p06 = r38 == r33;
		p07 = r38 != r33;
		if (!p06)
		{
			if (p06)
				goto l4000000000125460;
			word32 v53 = *r38;
			word64 r14 = (word64) v53;
			r8 = 0x00 + 1;
			word32 v55 = (word32) 0x2F;
			word32 v56 = (word32) r14;
			p06 = v55 == v56;
			p07 = v55 != v56;
			if (!p06)
			{
				pr = r57;
				ar.pfs = r55;
				b0 = r54;
				r12 += 0x20;
				return;
			}
		}
		r8 = 0x00 + 0x00;
		pr = r57;
		ar.pfs = r55;
		b0 = r54;
		r12 += 0x20;
	}
	else
	{
l4000000000125460:
		r8 = 0x00 + 1;
		pr = r57;
		ar.pfs = r55;
		b0 = r54;
		r12 += 0x20;
	}
}

// 40000000001272C0: define xstrmatch
define xstrmatch
{
	up64 r8;
	word64 r33;
	<anonymous> * b5;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r38 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r39 = r1 + 0x00;
	<anonymous> * r37 = b5;
	word64 r40 = r33 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r39 + 0x00;
	Eq_n p07 = 0x00 == r8;
	Eq_n p06 = 0x00 != r8;
	word64 r32;
	word64 r41;
	word64 r42;
	word64 r34;
	up64 r36;
	if (p07)
	{
		r40 = r32 + 0x00;
		b0();
		r1 = r39 + 0x00;
		p07 = 0x00 == r8;
		p06 = 0x00 != r8;
		if (!p06)
		{
			r40 = r32 + 0x00;
			r41 = r33 + 0x00;
			r42 = r34 + 0x00;
			b0();
			r1 = r39 + 0x00;
			r36 = r8 + 0x00;
			goto l4000000000127480;
		}
	}
	word64 * r35 = r12 + 0x18;
	b0();
	p07 = 0x01 == r8;
	p06 = 0x01 != r8;
	r1 = r39 + 0x00;
	r42 = r32 + 0x00;
	r40 = r35;
	r41 = 0x00 + 0x00;
	if (!p07)
	{
		b0();
		r8 += 0x02;
		r1 = r39 + 0x00;
		r40 = r12 + 0x10;
		r42 = r33 + 0x00;
		r41 = 0x00 + 0x00;
		p06 = 0x01 < r8;
		p07 = 0x01 >= r8;
		if (!p07)
		{
			b0();
			r8 += 0x02;
			word64 * r14 = r12 + 0x10;
			r1 = r39 + 0x00;
			r40 = *r35;
			r42 = r34 + 0x00;
			p06 = 0x01 < r8;
			p07 = 0x01 >= r8;
			if (!p07)
			{
				r41 = *r14;
				b0();
				r1 = r39 + 0x00;
				r36 = r8 + 0x00;
				r40 = *r35;
				b0();
				r14 = r12 + 0x10;
				r1 = r39 + 0x00;
				r40 = *r14;
				b0();
				r8 = r36 + 0x00;
				r1 = r39 + 0x00;
				ar.pfs = r38;
				b0 = r37;
				r12 += 0x10;
				return;
			}
			b0();
			r1 = r39 + 0x00;
		}
	}
	r40 = r32 + 0x00;
	r41 = r33 + 0x00;
	r42 = r34 + 0x00;
	b0();
	r1 = r39 + 0x00;
	r36 = r8 + 0x00;
l4000000000127480:
	r8 = r36 + 0x00;
	ar.pfs = r38;
	b0 = r37;
	r12 += 0x10;
}

// 4000000000127500: define xmbsrtowcs
define xmbsrtowcs
{
	word64 r8;
	word64 ** r33;
	<anonymous> * b0;
	word32 * r35;
	word64 r1;
	word64 LC;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r41 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r43 = LC;
	word64 r42 = r1 + 0x00;
	Eq_n p07 = null == r35;
	Eq_n p06 = null != r35;
	<anonymous> * r40 = b0;
	word32 * r14;
	word32 * r15;
	if (!p07)
	{
		word64 * r36 = *r33;
		ui64 r44 = r36;
		b0();
		word64 r32;
		p06 = 0x00 == r32;
		p07 = 0x00 != r32;
		r1 = r42 + 0x00;
		word64 r37 = r8 + 0x00;
		word64 r38;
		if (!p06)
		{
			word64 r34;
			p07 = 0x00 == r34;
			p06 = 0x00 != r34;
			r34 += ~0x00;
			if (p07)
				r38 = 0x00 + 0x00;
			__break();
			word64 r96;
			r32 = r96 + 0x00;
			__break();
			__break();
		}
		else
		{
			r44 = r8 + 0x01;
			r44 = (r44 << 0x02) + 0x00;
			b0();
			r14 = r12 + 0x10;
			word32 v29 = *r35;
			++r35;
			word64 r45 = r12 + 0x18;
			word64 r39 = r8 + 0x00;
			r1 = r42 + 0x00;
			word64 r46 = r37 + 0x00;
			word32 * r47 = r14;
			word64 r4;
			*r14 = (word32) r4;
			++r14;
			word32 v35 = *r35;
			r15 = (word64) v35;
			*r36 = r45;
			r44 = r8 + 0x00;
			*r15 = (word32) r14;
			b0();
			p06 = 0x00 == r39;
			p07 = 0x00 != r39;
			r1 = r42 + 0x00;
			r38 = r8 + 0x00;
			r44 = r39 + 0x00;
			if (!p06)
			{
				b0();
				r8 = r38 + 0x00;
				r1 = r42 + 0x00;
				ar.pfs = r41;
				LC = r43;
				b0 = r40;
				r12 += 0x10;
			}
			else
			{
				r8 = r38 + 0x00;
				ar.pfs = r41;
				LC = r43;
				b0 = r40;
				r12 += 0x10;
			}
		}
	}
	else
	{
		r14 = r1 + 8776;
		r35 = r1 + 8780;
		word32 v23 = *r14;
		r15 = (word64) v23;
		word32 v25 = (word32) 0x00;
		word32 v26 = (word32) r15;
		p07 = v25 == v26;
		p06 = v25 != v26;
		if (p07)
			r15 = r35;
	}
}

// 40000000001278C0: define xdupmbstowcs
define xdupmbstowcs
{
	word64 r1;
	word64 b5;
	word64 r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r46 = ar.pfs;
	word64 r12 = r12 + ~0x2F;
	Eq_n p06 = 0x00 == r32;
	Eq_n p07 = 0x00 != r32;
	word64 r45 = b5;
	word64 r47 = r1 + 0x00;
}

// 4000000000128180: define match_pattern_wchar
define match_pattern_wchar
{
	word32 * r32;
	word32 * r33;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 v5 = *r33;
	word64 r14 = (word64) v5;
	word32 v7 = (word32) 0x00;
	word32 v8 = (word32) r14;
	Eq_n p06 = v7 == v8;
	Eq_n p07 = v7 != v8;
	word64 r8;
	if (p06)
	{
		r8 = 0x00 + 0x00;
		return;
	}
	word32 v12 = *r32;
	word64 r16 = (word64) v12;
	int64 r15 = r16 + ~0x20;
	up32 v15 = (word32) 0x3B;
	up32 v16 = (word32) r15;
	p06 = v15 < v16;
	p07 = v15 >= v16;
	word64 r64;
	if (p07)
	{
		ui64 r17 = 0x00 + 1;
		int32 v22 = (int32) r15;
		r15 = (int64) v22;
		r15 = r17 << r15;
		r17 = 0x80000401;
		r17 = r15 & r17;
		p07 = 0x00 == r17;
		p06 = 0x00 != r17;
		if (p06)
		{
			++r32;
			word32 v25 = *r32;
			r15 = (word64) v25;
			word32 v26 = (word32) 0x28;
			word32 v27 = (word32) r15;
			p06 = v26 == v27;
			p07 = v26 != v27;
			if (p07)
				goto l40000000001281C0;
l40000000001282F0:
			r8 = 0x00 + 1;
			return;
		}
		r17 = 0x40000200;
		r17 = r15 & r17;
		p07 = 0x00 == r17;
		p06 = 0x00 != r17;
		if (p06)
			goto l40000000001282F0;
		if (!p07)
		{
			++r32;
			word32 v28 = *r32;
			r15 = (word64) v28;
			word32 v29 = (word32) r15;
			word32 v30 = (word32) r14;
			p06 = v29 == v30;
			p07 = v29 != v30;
			if (p06)
				r14 = 0x00 + 1;
			byte v31 = (byte) r64;
		}
	}
l40000000001281C0:
	word32 v19 = (word32) r16;
	word32 v20 = (word32) r14;
	p06 = v19 == v20;
	p07 = v19 != v20;
	if (p06)
		r14 = 0x00 + 1;
	byte v24 = (byte) r64;
}

// 4000000000128300: define wmatchlen
define wmatchlen
{
	word64 r1;
	word32 * r32;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 v5 = *r32;
	Eq_n r14;
	r14.u2 = (word64) v5;
	struct Eq_n * r17 = r1 + -5748;
	word32 * r15 = r32 + 1;
	word64 r18 = 0x00 + 0x00;
	word64 r20 = 0x00 + 0x00;
	word64 r19 = 0x00 + 0x00;
	word32 v13 = (word32) 0x00;
	word32 v14 = (word32) r14;
	Eq_n p06 = v13 == v14;
	Eq_n p07 = v13 != v14;
	word64 r8 = 0x00 + 0x00;
	if (!p06)
	{
		r17 = r17->ptr0000;
		do
		{
			r14.u1 = (word32) r14 - 33;
			up32 v18 = (word32) 0x3B;
			up32 v19 = (word32) r14;
			p06 = v18 < v19;
			p07 = v18 >= v19;
			if (p07)
			{
				r14 = __addp4(0x00, r14);
				r14.u2 = r17 + r14;
				word64 r16 = *r14.u2;
				r14.u2 = (char *) r14.u2 + r16;
				Eq_n b6 = r14;
				b6();
				return;
			}
			word32 v21 = *r15;
			r14.u2 = (word64) v21;
			r32 = r15;
			++r8;
			r15 = r32 + 1;
			word32 v22 = (word32) 0x00;
			word32 v23 = (word32) r14;
			p07 = v22 == v23;
			p06 = v22 != v23;
		} while (p06);
	}
	else
		r8 = 0x00 + 0x00;
}

// 4000000000128800: define match_pattern_char
define match_pattern_char
{
	word64 r64;
	byte * r32;
	byte * r33;
	ptr64 fp;
	ptr64 r11 = fp;
	byte v5 = *r33;
	int64 r14 = (word64) v5;
	int8 v7 = (int8) r14;
	r14 = (int64) v7;
	word32 v8 = (word32) 0x00;
	word32 v9 = (word32) r14;
	Eq_n p06 = v8 == v9;
	Eq_n p07 = v8 != v9;
	word64 r8;
	if (p06)
	{
		r8 = 0x00 + 0x00;
		return;
	}
	byte v13 = *r32;
	int64 r16 = (word64) v13;
	int8 v15 = (int8) r16;
	r16 = (int64) v15;
	int64 r15 = r16 + ~0x20;
	byte v17 = (byte) r15;
	ui64 r17 = (word64) v17;
	up32 v19 = (word32) 0x3B;
	up32 v20 = (word32) r17;
	p06 = v19 < v20;
	p07 = v19 >= v20;
	if (p07)
	{
		r17 = 0x00 + 1;
		int8 v25 = (int8) r15;
		r15 = (int64) v25;
		r15 = r17 << r15;
		r17 = 0x80000401;
		r17 = r15 & r17;
		p07 = 0x00 == r17;
		p06 = 0x00 != r17;
		if (p06)
		{
			++r32;
			byte v28 = *r32;
			r15 = (word64) v28;
			int8 v29 = (int8) r15;
			r15 = (int64) v29;
			word32 v30 = (word32) 0x28;
			word32 v31 = (word32) r15;
			p06 = v30 == v31;
			p07 = v30 != v31;
			if (p07)
				goto l4000000000128850;
l4000000000128990:
			r8 = 0x00 + 1;
			return;
		}
		r17 = 0x40000200;
		r17 = r15 & r17;
		p07 = 0x00 == r17;
		p06 = 0x00 != r17;
		if (p06)
			goto l4000000000128990;
		if (!p07)
		{
			++r32;
			byte v32 = *r32;
			r15 = (word64) v32;
			int8 v33 = (int8) r15;
			r15 = (int64) v33;
			word32 v34 = (word32) r15;
			word32 v35 = (word32) r14;
			p06 = v34 == v35;
			p07 = v34 != v35;
			if (p06)
				r14 = 0x00 + 1;
		}
	}
l4000000000128850:
	word32 v23 = (word32) r16;
	word32 v24 = (word32) r14;
	p06 = v23 == v24;
	p07 = v23 != v24;
	if (p06)
		r14 = 0x00 + 1;
	byte v27 = (byte) r64;
}

// 40000000001289C0: define umatchlen
define umatchlen
{
	word64 r1;
	byte * r32;
	ptr64 fp;
	ptr64 r11 = fp;
	byte v5 = *r32;
	<anonymous> * r14 = (word64) v5;
	struct Eq_n * r17 = r1 + -0x0000166C;
	byte * r15 = r32 + 1;
	word64 r18 = 0x00 + 0x00;
	word64 r20 = 0x00 + 0x00;
	word64 r19 = 0x00 + 0x00;
	int8 v13 = (int8) r14;
	r14 = (int64) v13;
	word64 r8 = 0x00 + 0x00;
	word32 v15 = (word32) 0x00;
	word32 v16 = (word32) r14;
	Eq_n p06 = v15 == v16;
	Eq_n p07 = v15 != v16;
	if (!p06)
	{
		r17 = r17->ptr0000;
		do
		{
			r14 = (<anonymous> *) ((char *) r14 - 33);
			byte v19 = (byte) r14;
			r14 = (word64) v19;
			up32 v20 = (word32) 0x3B;
			up32 v21 = (word32) r14;
			p06 = v20 < v21;
			p07 = v20 >= v21;
			if (p07)
			{
				r14 = (<anonymous> *) (r17 + r14);
				word64 r16 = *r14;
				r14 = (<anonymous> *) ((char *) r14 + r16);
				<anonymous> * b6 = r14;
				b6();
				return;
			}
			byte v23 = *r15;
			r14 = (word64) v23;
			r32 = r15;
			++r8;
			int8 v24 = (int8) r14;
			r14 = (int64) v24;
			r15 = r32 + 1;
			word32 v25 = (word32) 0x00;
			word32 v26 = (word32) r14;
			p07 = v25 == v26;
			p06 = v25 != v26;
		} while (p06);
	}
	else
		r8 = 0x00 + 0x00;
}

// 4000000000129000: define getenv
// Called from:
//      _getenv
define getenv
{
	<anonymous> * b4;
	word64 r1;
	word64 pr;
	byte * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r37 = ar.pfs;
	byte v7 = *r32;
	Eq_n r14;
	r14.u2 = (word64) v7;
	word64 r39 = pr;
	word64 r38 = r1 + 0x00;
	Eq_n r40;
	r40.u2 = r32;
	<anonymous> * r36 = b4;
	int8 v16 = (int8) r14;
	r14.u2 = (int64) v16;
	word32 v17 = (word32) 0x00;
	word32 v18 = (word32) r14;
	Eq_n p07 = v17 == v18;
	Eq_n p06 = v17 != v18;
	<anonymous> * b0;
	struct Eq_n * r8;
	if (!p07)
	{
		b0();
		r1 = r38 + 0x00;
		p06 = null == r8;
		p07 = null != r8;
		Eq_n r33;
		r33.u2 = &r8->ptr0000;
		Eq_n r34;
		if (!p06)
		{
			r34 = r1 + 8788;
			r40.u2 = r34.u3->t0000.u2;
			p06 = 0x00 == r40;
			p07 = 0x00 != r40;
			if (!p06)
			{
				b0();
				r1 = r38 + 0x00;
			}
			r33.u1 = (word32) r33 + 8;
			r40.u2 = r33.u3->t0000.u2;
			p06 = 0x00 == r40;
			p07 = 0x00 != r40;
			if (p06)
				r8 = 0x00 + 0x00;
			__break();
			__break();
		}
		r14 = r1 + 7172;
		r40.u2 = r32;
		r14.u2 = r14.u3->t0000.u2;
		p06 = 0x00 == r14;
		p07 = 0x00 != r14;
		if (p06)
		{
			b0();
			r1 = r38 + 0x00;
			int32 v24 = (int32) r8;
			int64 r35 = (int64) v24;
			word32 v26 = (word32) 0x00;
			word32 v27 = (word32) r8;
			Eq_n p16 = v26 == v27;
			Eq_n p17 = v26 != v27;
			r14 = r1 + -10116;
			r14.u2 = r14.u3->t0000.u2;
			r34.u2 = r14.u3->t0000.u2;
			r33.u2 = r34.u3->t0000.u2;
			r34.u1 = (word32) r34 + 8;
			p06 = 0x00 == r33;
			p07 = 0x00 != r33;
			if (!p06)
			{
				do
				{
					if (p16)
					{
l4000000000129300:
						r14.u2 = r33.u2 + r35;
						Eq_n v31;
						v31.u0 = *r14.u2;
						r14.u2 = (word64) v31;
						int8 v32 = (int8) r14;
						r14.u2 = (int64) v32;
						word32 v33 = (word32) 0x3D;
						word32 v34 = (word32) r14;
						p07 = v33 == v34;
						p06 = v33 != v34;
						if (!p06)
						{
							r8 = (struct Eq_n *) (r33.u2 + r35);
							pr = r39;
							ar.pfs = r37;
							b0 = r36;
							return;
						}
						goto l40000000001291E0;
					}
					Eq_n v35;
					v35.u0 = *r33.u2;
					int64 r15 = (word64) v35;
					byte v37 = *r32;
					r14.u2 = (word64) v37;
					int8 v38 = (int8) r15;
					r15 = (int64) v38;
					int8 v39 = (int8) r14;
					r14.u2 = (int64) v39;
					word32 v40 = (word32) r15;
					word32 v41 = (word32) r14;
					p07 = v40 == v41;
					p06 = v40 != v41;
					if (p07)
					{
						r40.u2 = r33.u2;
						byte * r41 = r32;
						int64 r42 = r35 + 0x00;
						b0();
						r1 = r38 + 0x00;
						word32 v44 = (word32) 0x00;
						word32 v45 = (word32) r8;
						p07 = v44 == v45;
						p06 = v44 != v45;
						if (p06)
							goto l40000000001291E0;
						goto l4000000000129300;
					}
l40000000001291E0:
					r33.u2 = r34.u3->t0000.u2;
					r34.u1 = (word32) r34 + 8;
					p07 = 0x00 == r33;
					p06 = 0x00 != r33;
				} while (p06);
			}
		}
		else
		{
			b0();
			r14.u2 = (char *) &r8->ptr0000 + 40;
			r1 = r38 + 0x00;
			p06 = null == r8;
			p07 = null != r8;
			r8 = (struct Eq_n *) ((char *) &r8->ptr0000 + 8);
			if (!p06)
			{
				Eq_n v46;
				v46.u1 = r14.u3->t0000.u1;
				r14.u2 = (word64) v46;
				ar.pfs = r37;
				if (!p06)
				{
					b0 = r36;
					r8 = r8->ptr0000;
					pr = r39;
					return;
				}
			}
		}
	}
	r8 = 0x00 + 0x00;
	pr = r39;
	ar.pfs = r37;
	b0 = r36;
}

// 4000000000129380: define _getenv
define _getenv
{
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r2 = ar.pfs;
	getenv();
}

// 40000000001293C0: define putenv
define putenv
{
	word64 r1;
	<anonymous> * b2;
	byte * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	byte v7 = *r32;
	union Eq_n * r14 = (word64) v7;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	byte * r37 = r32;
	int8 v14 = (int8) r14;
	r14 = (int64) v14;
	byte * r38 = 0x00 + 0x00;
	word32 v16 = (word32) 0x00;
	word32 v17 = (word32) r14;
	Eq_n p07 = v16 == v17;
	Eq_n p06 = v16 != v17;
	<anonymous> * b0;
	int64 r8;
	word64 r16;
	if (!p07)
	{
		b0();
		int32 v22 = (int32) r8;
		int64 r33 = (int64) v22;
		r37 = r32;
		r1 = r36 + 0x00;
		r14 = (union Eq_n *) (r32 + r33);
		Eq_n v24;
		v24.u0 = r14->u0;
		r14 = (word64) v24;
		int8 v25 = (int8) r14;
		r14 = (int64) v25;
		word32 v26 = (word32) 0x3D;
		word32 v27 = (word32) r14;
		p06 = v26 == v27;
		p07 = v26 != v27;
		if (!p07)
		{
			b0();
			r37 = r8 + 0x01;
			r1 = r36 + 0x00;
			b0();
			r37 = r8 + 0x00;
			r1 = r36 + 0x00;
			r38 = r32;
			b0();
			r37 = r8 + 0x00;
			r8 = r33 + r8;
			r1 = r36 + 0x00;
			word64 r39 = 0x00 + 0x00;
			r38 = r37 + r33;
			byte * r0;
			*r0 = (byte) r8;
			b0();
			p07 = 0x00 == r8;
			p06 = 0x00 != r8;
			word32 * r15 = r8 + 0x28;
			r16 = 0x00 + 0x00;
			r1 = r36 + 0x00;
			if (!p07)
			{
				if (p06)
				{
					word32 v32 = *r15;
					r14 = (word64) v32;
				}
			}
		}
	}
	b0();
	r16 = 0x00 + -1;
	r14 = 0x00 + 22;
	r1 = r36 + 0x00;
	ar.pfs = r35;
	r14->u1 = (word32) (word32) r8;
	b0 = r34;
	r8 = r16 + 0x00;
}

// 4000000000129580: define setenv
define setenv
{
	word64 r34;
	byte * r32;
	<anonymous> * b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 r37 = r1 + 0x00;
	<anonymous> * r35 = b3;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	byte * r38 = r32;
	<anonymous> * b0;
	word64 r15;
	word32 * r14;
	word64 r8;
	if (p06)
	{
l40000000001296E0:
		b0();
		r15 = 0x00 + -1;
		r14 = 0x00 + 22;
		r1 = r37 + 0x00;
		ar.pfs = r36;
		*r14 = (word32) r8;
		b0 = r35;
		r8 = r15 + 0x00;
		return;
	}
	byte v14 = *r32;
	r14 = (word64) v14;
	word64 r39 = 0x00 + 61;
	int8 v17 = (int8) r14;
	r14 = (int64) v17;
	word32 v18 = (word32) 0x00;
	word32 v19 = (word32) r14;
	p06 = v18 == v19;
	p07 = v18 != v19;
	if (p06)
		goto l40000000001296E0;
	b0();
	p06 = 0x00 == r8;
	p07 = 0x00 != r8;
	r1 = r37 + 0x00;
	if (p07)
		goto l40000000001296E0;
	word32 v24 = (word32) 0x00;
	word32 v25 = (word32) r34;
	p06 = v24 == v25;
	p07 = v24 != v25;
	ui64 r17;
	word32 * r16;
	if (p06)
	{
		r38 = r32;
		b0();
		r14 = r8 + 0x28;
		r1 = r37 + 0x00;
		p06 = 0x00 == r8;
		p07 = 0x00 != r8;
		r17 = 0x00 + -0x00001001;
		r15 = 0x00 + 0x00;
		if (!p06)
		{
			word32 v31 = *r14;
			r16 = (word64) v31;
			r16 &= r17;
			r16 |= 0x01;
			*r16 = (word32) r14;
			goto l4000000000129660;
		}
	}
	r38 = r32;
	word64 r33;
	r39 = r33 + 0x00;
	word64 r40 = 0x00 + 0x00;
	b0();
	r14 = r8 + 0x28;
	r1 = r37 + 0x00;
	p06 = 0x00 == r8;
	p07 = 0x00 != r8;
	r17 = 0x00 + -0x00001001;
	r15 = 0x00 + 0x00;
	if (p06)
	{
		r15 = 0x00 + -1;
		ar.pfs = r36;
		r8 = r15 + 0x00;
		b0 = r35;
		return;
	}
	word32 v29 = *r14;
	r16 = (word64) v29;
	r16 &= r17;
	r16 |= 0x01;
	*r16 = (word32) r14;
l4000000000129660:
	r8 = r15 + 0x00;
	ar.pfs = r36;
	b0 = r35;
}

// 4000000000129780: define unsetenv
define unsetenv
{
	word64 r1;
	<anonymous> * b1;
	byte * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	byte v7 = *r32;
	int64 r14 = (word64) v7;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	byte * r36 = r32;
	int8 v14 = (int8) r14;
	r14 = (int64) v14;
	word64 r37 = 0x00 + 61;
	word32 v16 = (word32) 0x00;
	word32 v17 = (word32) r14;
	Eq_n p06 = v16 == v17;
	Eq_n p07 = v16 != v17;
	<anonymous> * b0;
	int64 r8;
	if (!p06)
	{
		b0();
		p06 = 0x00 == r8;
		p07 = 0x00 != r8;
		r1 = r35 + 0x00;
		r36 = r32;
		if (!p07)
		{
			b0();
			r14 = 0x00 + 0x00;
			r1 = r35 + 0x00;
			ar.pfs = r34;
			r8 = r14 + 0x00;
			b0 = r33;
			return;
		}
	}
	b0();
	r14 = 0x00 + -1;
	word32 * r15 = 0x00 + 22;
	r1 = r35 + 0x00;
	ar.pfs = r34;
	*r15 = (word32) r8;
	b0 = r33;
	r8 = r14 + 0x00;
}

// 4000000000129880: define getmaxgroups
define getmaxgroups
{
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word32 * r32 = r1 + 0x00001914;
	word64 r35 = r1 + 0x00;
	word32 v11 = *r32;
	word64 r8 = (word64) v11;
	ar.pfs = r34;
	int32 v13 = (word32) 0x00;
	int32 v14 = (word32) r8;
	Eq_n p06 = v13 < v14;
	Eq_n p07 = v13 >= v14;
	<anonymous> * b0 = r33;
	if (p07)
	{
		word64 r36 = 0x00 + 3;
		b0();
		word64 r14 = r8 + 0x00;
		int32 v20 = (word32) 0x00;
		int32 v21 = (word32) r8;
		p07 = v20 < v21;
		p06 = v20 >= v21;
		r1 = r35 + 0x00;
		ar.pfs = r34;
		if (p06)
			r14 = 0x00 + 64;
	}
}

// 4000000000129940: define getmaxchild
define getmaxchild
{
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	struct Eq_n * r32 = r1 + 0x0000191C;
	word64 r35 = r1 + 0x00;
	struct Eq_n * r8 = r32->ptr0000;
	ar.pfs = r34;
	Eq_n p06 = null < r8;
	Eq_n p07 = null >= r8;
	<anonymous> * b0 = r33;
	if (p07)
	{
		word64 r36 = 0x00 + 1;
		b0();
		r1 = r35 + 0x00;
		r8->ptr0000 = r32;
		ar.pfs = r34;
		b0 = r33;
	}
}

// 40000000001299C0: define sh_setlinebuf
define sh_setlinebuf
{
	word64 r32;
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = r32 + 0x00;
	word64 r37 = 0x00 + 0x00;
	word64 r38 = 0x00 + 1;
	word64 r39 = 0x00 + 0x00002000;
	<anonymous> * b0;
	b0();
	r1 = r35 + 0x00;
	ar.pfs = r34;
	b0 = r33;
}

// 4000000000129A40: define inttostr
define inttostr
{
	word64 r34;
	word64 r33;
	word64 r32;
	<anonymous> * b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 r37 = r1 + 0x00;
	<anonymous> * r35 = b3;
	word64 r38 = r32 + 0x00;
	word64 r40 = r33 + 0x00;
	word64 r41 = r34 + 0x00;
	word64 r39 = 0x00 + 0x0A;
	word64 r42 = 0x00 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r37 + 0x00;
	ar.pfs = r36;
	b0 = r35;
}

// 4000000000129AC0: define itos
define itos
{
	word64 r8;
	word64 r32;
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word64 r12 = r12 + ~0x1F;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r37 = r32 + 0x00;
	word64 r39 = r12 + 0x10;
	word64 r40 = 0x00 + 22;
	word64 r41 = 0x00 + 0x00;
	word64 r38 = 0x00 + 0x0A;
	<anonymous> * b0;
	b0();
	r1 = r36 + 0x00;
	word64 r33 = r8 + 0x00;
	r37 = r8 + 0x00;
	b0();
	r1 = r36 + 0x00;
	r37 = r8 + 0x01;
	b0();
	r1 = r36 + 0x00;
	r37 = r8 + 0x00;
	r38 = r33 + 0x00;
	b0();
	r1 = r36 + 0x00;
	ar.pfs = r35;
	b0 = r34;
	r12 += 0x20;
}

// 4000000000129B80: define uinttostr
define uinttostr
{
	word64 r34;
	word64 r33;
	word64 r32;
	<anonymous> * b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 r37 = r1 + 0x00;
	<anonymous> * r35 = b3;
	word64 r38 = r32 + 0x00;
	word64 r40 = r33 + 0x00;
	word64 r41 = r34 + 0x00;
	word64 r39 = 0x00 + 0x0A;
	word64 r42 = 0x00 + 8;
	<anonymous> * b0;
	b0();
	r1 = r37 + 0x00;
	ar.pfs = r36;
	b0 = r35;
}

// 4000000000129C00: define uitos
define uitos
{
	word64 r8;
	word64 r32;
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word64 r12 = r12 + ~0x1F;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r37 = r32 + 0x00;
	word64 r39 = r12 + 0x10;
	word64 r40 = 0x00 + 21;
	word64 r41 = 0x00 + 8;
	word64 r38 = 0x00 + 0x0A;
	<anonymous> * b0;
	b0();
	r1 = r36 + 0x00;
	word64 r33 = r8 + 0x00;
	r37 = r8 + 0x00;
	b0();
	r1 = r36 + 0x00;
	r37 = r8 + 0x01;
	b0();
	r1 = r36 + 0x00;
	r37 = r8 + 0x00;
	r38 = r33 + 0x00;
	b0();
	r1 = r36 + 0x00;
	ar.pfs = r35;
	b0 = r34;
	r12 += 0x20;
}

// 4000000000129CC0: define zread
define zread
{
	word64 r34;
	word64 r33;
	word64 r32;
	word64 r1;
	<anonymous> * b4;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r37 = ar.pfs;
	<anonymous> * r36 = b4;
	word64 r38 = r1 + 0x00;
	<anonymous> * b0;
	Eq_n p06;
	word32 * r8;
	word32 * r35;
	do
	{
		word64 r39 = r32 + 0x00;
		word64 r40 = r33 + 0x00;
		word64 r41 = r34 + 0x00;
		b0();
		p06 = r8 < null;
		Eq_n p07 = r8 >= null;
		r1 = r38 + 0x00;
		r35 = r8;
		if (p07)
			break;
		b0();
		word32 v21 = *r8;
		word64 r14 = (word64) v21;
		r1 = r38 + 0x00;
		word32 v23 = (word32) 0x04;
		word32 v24 = (word32) r14;
		p06 = v23 == v24;
		p07 = v23 != v24;
	} while (p06);
	r8 = r35;
	ar.pfs = r37;
	b0 = r36;
}

// 4000000000129D80: define zreadretry
define zreadretry
{
	word32 * r8;
	word64 r34;
	word64 r33;
	word64 r32;
	word64 r1;
	<anonymous> * b5;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r38 = ar.pfs;
	<anonymous> * r37 = b5;
	word64 r39 = r1 + 0x00;
	word64 r36 = 0x00 + 3;
	word64 r40 = r32 + 0x00;
	word64 r41 = r33 + 0x00;
	word64 r42 = r34 + 0x00;
	r36 += ~0x00;
	<anonymous> * b0;
	b0();
	Eq_n p07 = r8 < null;
	Eq_n p06 = r8 >= null;
	r1 = r39 + 0x00;
	int64 r35 = r8;
	if (!p06)
	{
		p07 = (word32 *) ~0x00 == r8;
		p06 = (word32 *) ~0x00 != r8;
		if (!p06)
		{
			b0();
			word32 v22 = *r8;
			word64 r14 = (word64) v22;
			r1 = r39 + 0x00;
			word32 v24 = (word32) 0x00;
			word32 v25 = (word32) r36;
			Eq_n p09 = v24 == v25;
			Eq_n p08 = v24 != v25;
			word32 v28 = (word32) 0x04;
			word32 v29 = (word32) r14;
			p07 = v28 == v29;
			p06 = v28 != v29;
			if (!p06)
			{
				word64 p48;
				if (p48)
					__break();
			}
		}
	}
	r8 = r35 + 0x00;
	ar.pfs = r38;
	b0 = r37;
}

// 4000000000129E40: define zreadintr
define zreadintr
{
	word64 r34;
	word64 r33;
	word64 r32;
	<anonymous> * b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 r37 = r1 + 0x00;
	<anonymous> * r35 = b3;
	word64 r38 = r32 + 0x00;
	word64 r39 = r33 + 0x00;
	word64 r40 = r34 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r37 + 0x00;
	ar.pfs = r36;
	b0 = r35;
}

// 4000000000129EC0: define zreadcn
// Called from:
//      zreadc
define zreadcn
{
	word64 r34;
	word64 r32;
	word64 b5;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r38 = ar.pfs;
	word64 * r35 = r1 + 0x0000225C;
	word64 * r36 = r1 + 8804;
	word64 r41 = r1 + 21292;
	word64 r37 = b5;
	word64 r42 = 0x00 + 0x0080;
	word64 r14 = *r36;
	word64 r39 = r1 + 0x00;
	word64 r40 = r32 + 0x00;
	word64 r15 = *r35;
	up32 v18 = (word32) r42;
	up32 v20 = (word32) r34;
	Eq_n p06 = v18 < v20;
	Eq_n p07 = v18 >= v20;
	if (p06)
		r42 = 0x00 + 0x01;
	word64 p05;
	if (p05)
	{
		int64 r64;
		0x00 < r64;
		Eq_n p16 = 0x00 >= r64;
	}
	word64 p24;
	if (p24)
		__break();
	word64 p08;
	if (p08)
		__break();
	if (p07)
		r42 = r34 + 0x00;
	if (p06)
		r42 = 0x00 + 0x0080;
	__break();
}

// 400000000012A040: define zreadc
define zreadc
{
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	word64 r34 = 0x00 + 0x0080;
	word64 r2 = ar.pfs;
	zreadcn();
}

// 400000000012A080: define zreadcintr
define zreadcintr
{
	word64 r32;
	word64 b4;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r37 = ar.pfs;
	word64 * r34 = r1 + 0x0000225C;
	word64 * r35 = r1 + 8804;
	word64 r40 = r1 + 21292;
	word64 r36 = b4;
	word64 r14 = *r35;
	word64 r38 = r1 + 0x00;
	word64 r41 = 0x00 + 0x0080;
	word64 r39 = r32 + 0x00;
	word64 r15 = *r34;
	Eq_n p06 = r14 == r15;
	Eq_n p07 = r14 != r15;
	if (!p06)
	{
		p07 = 0x00 == r14;
		p06 = 0x00 != r14;
		if (p06)
			goto l400000000012A142;
	}
	<anonymous> * b0;
	b0();
	int64 r8;
	p06 = 0x00 < r8;
	p07 = 0x00 >= r8;
	r1 = r38 + 0x00;
	word64 ** r0;
	*r0 = r34;
	if (p07)
		*r0 = r35;
	__break();
l400000000012A142:
	word64 r33;
	p06 = 0x00 == r33;
	p07 = 0x00 != r33;
	if (p07)
		r15 = r1 + 21292;
}

// 400000000012A1C0: define zreset
define zreset
{
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r14 = r1 + 8804;
	word64 * r0;
	*r0 = r14;
	r14 = r1 + 0x0000225C;
	*r0 = r14;
}

// 400000000012A200: define zsyncfd
define zsyncfd
{
	word64 r32;
	<anonymous> * b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	int64 * r34 = r1 + 8804;
	<anonymous> * r35 = b3;
	int64 * r33 = r1 + 0x0000225C;
	word64 r37 = r1 + 0x00;
	word64 r38 = r32 + 0x00;
	int64 r39 = *r34;
	word64 r40 = 0x00 + 1;
	int64 r14 = *r33;
	r39 = r14 - r39;
	Eq_n p06 = 0x00 < r39;
	Eq_n p07 = 0x00 >= r39;
	r39 -= 0x00;
	<anonymous> * b0;
	if (!p07)
	{
		b0();
		r1 = r37 + 0x00;
		word64 r8;
		p07 = ~0x00 == r8;
		p06 = ~0x00 != r8;
		if (p07)
			goto l400000000012A280;
	}
	int64 ** r0;
	*r0 = r33;
	*r0 = r34;
l400000000012A280:
	ar.pfs = r36;
	b0 = r35;
}

// 400000000012A2C0: define ttgetattr
define ttgetattr
{
	word64 r33;
	word64 r32;
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r37 = r32 + 0x00;
	word64 r38 = r33 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r36 + 0x00;
	ar.pfs = r35;
	b0 = r34;
}

// 400000000012A340: define ttsetattr
// Called from:
//      ttfd_onechar
//      ttfd_noecho
//      ttfd_eightbit
//      ttfd_nocanon
//      ttfd_cbreak
define ttsetattr
{
	word64 r33;
	word64 r32;
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r37 = r32 + 0x00;
	word64 r39 = r33 + 0x00;
	word64 r38 = 0x00 + 1;
	<anonymous> * b0;
	b0();
	r1 = r36 + 0x00;
	ar.pfs = r35;
	b0 = r34;
}

// 400000000012A3C0: define ttsave
define ttsave
{
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word32 * r32 = r1 + 8812;
	word64 r35 = r1 + 0x00;
	word32 v11 = *r32;
	word32 * r14 = (word64) v11;
	ar.pfs = r34;
	word32 v13 = (word32) 0x00;
	word32 v14 = (word32) r14;
	Eq_n p07 = v13 == v14;
	Eq_n p06 = v13 != v14;
	<anonymous> * b0 = r33;
	if (!p07)
	{
		word64 p21;
		if (p21)
			__break();
		word64 p32;
		if (p32)
			__break();
		__break();
		word64 p08;
		if (p08)
			__break();
		b0();
		r14 = 0x00 + 1;
		r1 = r35 + 0x00;
		ar.pfs = r34;
		*r14 = (word32) r32;
		b0 = r33;
	}
	else
	{
		word64 r37 = r1 + 21420;
		__break();
	}
}

// 400000000012A480: define ttrestore
define ttrestore
{
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word32 * r32 = r1 + 8812;
	word64 r35 = r1 + 0x00;
	word32 v11 = *r32;
	word64 r14 = (word64) v11;
	ar.pfs = r34;
	word32 v13 = (word32) 0x00;
	word32 v14 = (word32) r14;
	Eq_n p06 = v13 == v14;
	Eq_n p07 = v13 != v14;
	<anonymous> * b0 = r33;
	if (!p07)
	{
		word64 p21;
		if (p21)
			__break();
		word64 p32;
		if (p32)
			__break();
		__break();
		word64 p08;
		if (p08)
			__break();
		b0();
		r1 = r35 + 0x00;
		word32 * r0;
		*r0 = (word32) r32;
		ar.pfs = r34;
		b0 = r33;
	}
	else
	{
		word64 r37 = r1 + 21420;
		__break();
	}
}

// 400000000012A540: define ttattr
define ttattr
{
	word64 r1;
	word64 r32;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 v5 = (word32) 0x01;
	word32 v6 = (word32) r32;
	Eq_n p07 = v5 == v6;
	Eq_n p06 = v5 != v6;
	word64 r14 = r1 + 8812;
	word32 v11 = (word32) 0x00;
	word32 v12 = (word32) r32;
	Eq_n p08 = v11 == v12;
	Eq_n p09 = v11 != v12;
	if (p07)
	{
		word64 r8 = r1 + 0x000053E8;
	}
}

// 400000000012A5C0: define tt_setonechar
define tt_setonechar
{
	word32 * r32;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 v5 = *r32;
	word32 * r17 = (word64) v5;
	ptr64 r18 = (char *) r32 + 23;
	byte * r19 = 0x00 + 1;
	word32 * r15 = r32 + 3;
	word32 * r14 = r32;
	r32 = (word32 *) ((char *) r32 + 22);
	*r19 = (byte) r18;
	r17 &= 191;
	r18 = 0x00 + 0x0100;
	word32 v11 = *r15;
	word32 * r16 = (word64) v11;
	byte * r0;
	*r0 = (byte) r32;
	word64 r8 = 0x00 + 0x00;
	r16 &= 0xFD;
	word64 r4;
	*r14 = (word32) r4;
	++r14;
	r17 = 0x00 + 0x00008001;
	r17 = r16 | r17;
	word32 v16 = *r14;
	r16 = (word64) v16;
	r16 &= 199;
	*r17 = (word32) r15;
	r16 |= 0x05;
	*r16 = (word32) r14;
}

// 400000000012A680: define ttfd_onechar
define ttfd_onechar
{
	word64 r8;
	word64 r33;
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r37 = r33 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r36 + 0x00;
	int32 v14 = (word32) r8;
	int32 v15 = (word32) 0x00;
	Eq_n p06 = v14 < v15;
	Eq_n p07 = v14 >= v15;
	b0 = r34;
	if (!p06)
	{
		ar.pfs = r35;
		word64 r2 = ar.pfs;
		ttsetattr();
	}
	else
	{
		r8 = 0x00 + -1;
		ar.pfs = r35;
		b0 = r34;
	}
}

// 400000000012A740: define ttonechar
define ttonechar
{
	word64 r1;
	word64 b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	word64 r32 = b0;
	word32 * r14 = r1 + 8812;
	word64 r36 = r1 + 21420;
	word64 r34 = r1 + 0x00;
	word32 v13 = *r14;
	r14 = (word64) v13;
	word64 r35 = r12 + 0x10;
	word64 r37 = 0x00 + 60;
	word32 v16 = (word32) 0x00;
	word32 v17 = (word32) r14;
	Eq_n p06 = v16 == v17;
	Eq_n p07 = v16 != v17;
	if (p06)
	{
		word64 r8 = 0x00 + -1;
	}
	__break();
	__break();
	word64 p32;
	if (p32)
		__break();
	word64 p08;
	if (p08)
		__break();
}

// 400000000012A800: define tt_setnoecho
define tt_setnoecho
{
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r32 = r32 + 3;
	word64 r8 = 0x00 + 0x00;
	word32 v6 = *r32;
	word32 * r14 = (word64) v6;
	r14 &= 151;
	*r14 = (word32) r32;
}

// 400000000012A840: define ttfd_noecho
define ttfd_noecho
{
	word64 ar.pfs;
	word64 r33;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r14 = r33 + 0x0C;
	word32 v6 = *r14;
	word32 * r15 = (word64) v6;
	r15 &= 151;
	*r15 = (word32) r14;
	word64 r2 = ar.pfs;
	ttsetattr();
}

// 400000000012A880: define ttnoecho
define ttnoecho
{
	word64 r1;
	word64 b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	word64 r32 = b0;
	word32 * r14 = r1 + 8812;
	word64 r36 = r1 + 21420;
	word64 r34 = r1 + 0x00;
	word32 v13 = *r14;
	r14 = (word64) v13;
	word64 r35 = r12 + 0x10;
	word64 r37 = 0x00 + 60;
	word32 v16 = (word32) 0x00;
	word32 v17 = (word32) r14;
	Eq_n p06 = v16 == v17;
	Eq_n p07 = v16 != v17;
	if (p06)
	{
		word64 r8 = 0x00 + -1;
	}
	__break();
	__break();
	word64 p32;
	if (p32)
		__break();
	word64 p08;
	if (p08)
		__break();
}

// 400000000012A940: define tt_seteightbit
define tt_seteightbit
{
	word32 * r32;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 v5 = *r32;
	word32 * r14 = (word64) v5;
	ui64 r15 = 0x00 + -0x0101;
	word64 r8 = 0x00 + 0x00;
	*r32 = (word32) r8;
	r32 += 2;
	word32 v9 = *r32;
	r14 = (word64) v9;
	r14 &= r15;
	r14 |= 0x30;
	*r14 = (word32) r32;
}

// 400000000012A9C0: define ttfd_eightbit
define ttfd_eightbit
{
	word64 ar.pfs;
	word32 * r33;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 v5 = *r33;
	word32 * r15 = (word64) v5;
	word32 * r14 = r33;
	ui64 r16 = 0x00 + -0x0101;
	word64 r8;
	*r14 = (word32) r8;
	r14 += 2;
	word32 v10 = *r14;
	r15 = (word64) v10;
	r15 &= r16;
	r15 |= 0x30;
	*r15 = (word32) r14;
	word64 r2 = ar.pfs;
	ttsetattr();
}

// 400000000012AA40: define tteightbit
define tteightbit
{
	word64 r1;
	word64 b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	word64 r32 = b0;
	word32 * r14 = r1 + 8812;
	word64 r36 = r1 + 21420;
	word64 r34 = r1 + 0x00;
	word32 v13 = *r14;
	r14 = (word64) v13;
	word64 r35 = r12 + 0x10;
	word64 r37 = 0x00 + 60;
	word32 v16 = (word32) 0x00;
	word32 v17 = (word32) r14;
	Eq_n p06 = v16 == v17;
	Eq_n p07 = v16 != v17;
	if (p06)
	{
		word64 r8 = 0x00 + -1;
	}
	__break();
	__break();
	word64 p32;
	if (p32)
		__break();
	word64 p08;
	if (p08)
		__break();
}

// 400000000012AB00: define tt_setnocanon
define tt_setnocanon
{
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r32 = r32 + 3;
	word64 r8 = 0x00 + 0x00;
	word32 v6 = *r32;
	word32 * r14 = (word64) v6;
	r14 &= 0xFD;
	*r14 = (word32) r32;
}

// 400000000012AB40: define ttfd_nocanon
define ttfd_nocanon
{
	word64 ar.pfs;
	word64 r33;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r14 = r33 + 0x0C;
	word32 v6 = *r14;
	word32 * r15 = (word64) v6;
	r15 &= 0xFD;
	*r15 = (word32) r14;
	word64 r2 = ar.pfs;
	ttsetattr();
}

// 400000000012AB80: define ttnocanon
define ttnocanon
{
	word64 r1;
	word64 b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	word64 r32 = b0;
	word32 * r14 = r1 + 8812;
	word64 r36 = r1 + 21420;
	word64 r34 = r1 + 0x00;
	word32 v13 = *r14;
	r14 = (word64) v13;
	word64 r35 = r12 + 0x10;
	word64 r37 = 0x00 + 60;
	word32 v16 = (word32) 0x00;
	word32 v17 = (word32) r14;
	Eq_n p06 = v16 == v17;
	Eq_n p07 = v16 != v17;
	if (p06)
	{
		word64 r8 = 0x00 + -1;
	}
	__break();
	__break();
	word64 p32;
	if (p32)
		__break();
	word64 p08;
	if (p08)
		__break();
}

// 400000000012AC40: define tt_setcbreak
define tt_setcbreak
{
	word64 r8;
	word32 * r32;
	word64 r1;
	word64 b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = r32;
	r32 += 3;
	<anonymous> * b0;
	b0();
	int32 v14 = (word32) r8;
	int32 v15 = (word32) 0x00;
	Eq_n p06 = v14 < v15;
	Eq_n p07 = v14 >= v15;
	r1 = r35 + 0x00;
	ar.pfs = r34;
	if (p07)
	{
		word32 v18 = *r32;
		word64 r14 = (word64) v18;
	}
}

// 400000000012ACC0: define ttfd_cbreak
define ttfd_cbreak
{
	word64 r8;
	word64 r33;
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r37 = r33 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r36 + 0x00;
	int32 v14 = (word32) r8;
	int32 v15 = (word32) 0x00;
	Eq_n p06 = v14 < v15;
	Eq_n p07 = v14 >= v15;
	b0 = r34;
	if (!p06)
	{
		ar.pfs = r35;
		word64 r2 = ar.pfs;
		ttsetattr();
	}
	else
	{
		r8 = 0x00 + -1;
		ar.pfs = r35;
		b0 = r34;
	}
}

// 400000000012AD80: define ttcbreak
define ttcbreak
{
	word64 r1;
	word64 b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	word64 r32 = b0;
	word32 * r14 = r1 + 8812;
	word64 r36 = r1 + 21420;
	word64 r34 = r1 + 0x00;
	word32 v13 = *r14;
	r14 = (word64) v13;
	word64 r35 = r12 + 0x10;
	word64 r37 = 0x00 + 60;
	word32 v16 = (word32) 0x00;
	word32 v17 = (word32) r14;
	Eq_n p06 = v16 == v17;
	Eq_n p07 = v16 != v17;
	if (p06)
	{
		word64 r8 = 0x00 + -1;
	}
	__break();
	__break();
	word64 p32;
	if (p32)
		__break();
	word64 p08;
	if (p08)
		__break();
}

// 400000000012AE40: define sh_regmatch
define sh_regmatch
{
	word64 r33;
	<anonymous> * b4;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r45 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	word32 * r15 = r1 + 0x00002244;
	<anonymous> * r44 = b4;
	word64 r46 = r1 + 0x00;
	union Eq_n * r14 = r12 + 0x10;
	ui64 r49 = 0x00 + 3;
	Eq_n r8;
	r14->u0 = (word64) r8;
	r14 = (union Eq_n *) ((char *) r14 + 8);
	r14->u0 = (word64) r8;
	r14 = (union Eq_n *) ((char *) r14 + 8);
	word32 v15 = *r15;
	r15 = (word64) v15;
	r14->u0 = (word64) r8;
	r14 = (union Eq_n *) ((char *) r14 + 8);
	word32 v16 = (word32) 0x00;
	word32 v17 = (word32) r15;
	Eq_n p07 = v16 == v17;
	Eq_n p06 = v16 != v17;
	r14->u0 = (word64) r8;
	r14 = (union Eq_n *) ((char *) r14 + 8);
	r14->u0 = (word64) r8;
	r14 = (union Eq_n *) ((char *) r14 + 8);
	r14->u0 = (word64) r8;
	r14 = (union Eq_n *) ((char *) r14 + 8);
	r14->u0 = (word64) r8;
	r14 = (union Eq_n *) ((char *) r14 + 8);
	union Eq_n ** r0;
	*r0 = (union Eq_n **) r14;
	if (!p06)
	{
		r14 = r1 + 7036;
		Eq_n v21;
		v21.u1 = r14->u1;
		r49 = (word64) v21;
		word32 v22 = (word32) 0x00;
		word32 v23 = (word32) r49;
		p07 = v22 == v23;
		p06 = v22 != v23;
		if (p06)
			r49 = 0x00 + 3;
	}
	else
	{
		ui64 r35 = 0x00 + 2;
		ui64 r47 = r12 + 0x10;
		word64 r48 = r33 + 0x00;
		<anonymous> * b0;
		b0();
		r1 = r46 + 0x00;
		word32 v29 = (word32) 0x00;
		word32 v30 = (word32) r8;
		p07 = v29 == v30;
		p06 = v29 != v30;
		r8 = r35 + 0x00;
		if (!p07)
		{
			ar.pfs = r45;
			b0 = r44;
			r12 += 0x40;
		}
		else
		{
			ui64 * r40 = r12 + 0x40;
			r35 = *r40;
			++r35;
			r47 = (r35 << 0x03) + 0x00;
			b0();
			r49 = r35 + 0x00;
			word64 r32;
			r48 = r32 + 0x00;
			word64 r50 = r8.u0;
			word64 r51 = 0x00 + 0x00;
			r1 = r46 + 0x00;
			word64 r39 = r8.u0;
			r47 = r12 + 0x10;
			b0();
			word32 v36 = (word32) 0x00;
			word32 v37 = (word32) r8;
			p07 = v36 == v37;
			p06 = v36 != v37;
			r47 = r32 + 0x00;
			r1 = r46 + 0x00;
			if (p06)
				r8 = 0x00 + 1;
		}
	}
}

// 400000000012B200: define sh_stat
define sh_stat
{
	word64 r1;
	<anonymous> * b6;
	byte * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r39 = ar.pfs;
	byte v7 = *r32;
	byte * r34 = (word64) v7;
	<anonymous> * r38 = b6;
	word64 r40 = r1 + 0x00;
	word64 * r14 = (word64 *) (r32 + 1);
	int8 v14 = (int8) r34;
	r34 = (int64) v14;
	word32 v15 = (word32) 0x00;
	word32 v16 = (word32) r34;
	Eq_n p07 = v15 == v16;
	Eq_n p06 = v15 != v16;
	<anonymous> * b0;
	word64 * r8;
	word32 * r15;
	if (!p07)
	{
		word32 v19 = (word32) 0x2F;
		word32 v20 = (word32) r34;
		p07 = v19 == v20;
		p06 = v19 != v20;
		byte * r42;
		word64 r43;
		byte * r41;
		word64 r33;
		if (p07)
		{
			byte v28 = (byte) *r14;
			int64 r35 = (word64) v28;
			int8 v30 = (int8) r35;
			r35 = (int64) v30;
			word32 v31 = (word32) 100;
			word32 v32 = (word32) r35;
			p07 = v31 == v32;
			p06 = v31 != v32;
			if (!p06)
			{
				r42 = r1 + -0x0000212C;
				r43 = 0x00 + 8;
				r41 = r32;
				r42 = (byte *) *r42;
				b0();
				r1 = r40 + 0x00;
				word32 v33 = (word32) 0x00;
				word32 v34 = (word32) r8;
				p07 = v33 == v34;
				p06 = v33 != v34;
				if (!p06)
				{
					r32 += 8;
					byte ** r37 = r1 + 8820;
					r41 = r32;
					b0();
					r1 = r40 + 0x00;
					r41 = (byte *) *r37;
					r42 = (char *) r8 + 9;
					b0();
					r14 = r8;
					*r8 = r37;
					r1 = r40 + 0x00;
					word64 * r36 = r8;
					r42 = r32;
					*r14 = (word64) (byte) r1;
					r14 = (word64 *) ((char *) r14 + 1);
					r41 = (byte *) (r8 + 1);
					*r14 = (word64) (byte) r1;
					r14 = (word64 *) ((char *) r14 + 1);
					*r14 = (word64) (byte) r1;
					r14 = (word64 *) ((char *) r14 + 1);
					*r14 = (word64) (byte) r1;
					r14 = (word64 *) ((char *) r14 + 1);
					r15 = 0x00 + 0x0066;
					*r14 = (word64) (byte) r1;
					r14 = (word64 *) ((char *) r14 + 1);
					*r14 = (word64) (byte) r1;
					r14 = (word64 *) ((char *) r14 + 1);
					*r14 = (word64) (byte) r1;
					r14 = (word64 *) ((char *) r14 + 1);
					*r34 = (byte) r14;
					b0();
					r1 = r40 + 0x00;
					r41 = 0x00 + 1;
					r42 = (byte *) r36;
					r43 = r33 + 0x00;
					b0();
					r14 = r8;
					r1 = r40 + 0x00;
					ar.pfs = r39;
					r8 = r14;
					b0 = r38;
					return;
				}
			}
		}
		r41 = 0x00 + 1;
		r42 = r32;
		r43 = r33 + 0x00;
		b0();
		r14 = r8;
		r1 = r40 + 0x00;
		ar.pfs = r39;
		r8 = r14;
		b0 = r38;
	}
	else
	{
		b0();
		r14 = 0x00 + -1;
		r15 = 0x00 + 2;
		r1 = r40 + 0x00;
		ar.pfs = r39;
		*r15 = (word32) r8;
		b0 = r38;
		r8 = r14;
	}
}

// 400000000012B440: define sh_eaccess
define sh_eaccess
{
	word64 r1;
	<anonymous> * b3;
	byte * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 r12 = r12 + ~0x8F;
	byte v8 = *r32;
	union Eq_n * r14 = (word64) v8;
	<anonymous> * r35 = b3;
	word64 r37 = r1 + 0x00;
	int8 v14 = (int8) r14;
	r14 = (int64) v14;
	word32 v15 = (word32) 0x2F;
	word32 v16 = (word32) r14;
	Eq_n p07 = v15 == v16;
	Eq_n p06 = v15 != v16;
	Eq_n r39;
	byte * r38;
	word64 r40;
	<anonymous> * b0;
	union Eq_n * r8;
	word64 r33;
	word64 r41;
	if (p07)
	{
		r14 = (union Eq_n *) (r32 + 1);
		Eq_n v26;
		v26.u0 = r14->u0;
		r14 = (word64) v26;
		int8 v27 = (int8) r14;
		r14 = (int64) v27;
		word32 v28 = (word32) 100;
		word32 v29 = (word32) r14;
		p07 = v28 == v29;
		p06 = v28 != v29;
		if (p07)
		{
			r39 = r1 + -0x0000212C;
			r38 = r32;
			r40 = 0x00 + 8;
			r39 = *r39;
			b0();
			r1 = r37 + 0x00;
			word32 v32 = (word32) 0x00;
			word32 v33 = (word32) r8;
			p06 = v32 == v33;
			p07 = v32 != v33;
			if (!p07)
				goto l400000000012B5E0;
		}
		r39 = r1 + -8484;
		r38 = r32;
		r40 = 0x00 + 8;
		r39 = *r39;
		b0();
		r14 = (union Eq_n *) (r32 + 8);
		r1 = r37 + 0x00;
		word32 v30 = (word32) 0x00;
		word32 v31 = (word32) r8;
		p07 = v30 == v31;
		p06 = v30 != v31;
		if (p06)
			goto l400000000012B480;
		Eq_n v34;
		v34.u0 = r14->u0;
		r14 = (word64) v34;
		int8 v35 = (int8) r14;
		r14 = (int64) v35;
		word32 v36 = (word32) 0x69;
		word32 v37 = (word32) r14;
		p07 = v36 == v37;
		p06 = v36 != v37;
		if (p07)
		{
			r14 = (union Eq_n *) (r32 + 9);
			Eq_n v40;
			v40.u0 = r14->u0;
			r14 = (word64) v40;
			p07 = (union Eq_n *) 110 == r14;
			p06 = (union Eq_n *) 110 != r14;
			if (p06)
				goto l400000000012B480;
			r14 = (union Eq_n *) (r32 + 0x0A);
			Eq_n v44;
			v44.u0 = r14->u0;
			r14 = (word64) v44;
			p06 = null == r14;
			p07 = null != r14;
			if (!p06)
			{
				r38 = 0x00 + -100;
				r39.u1 = r32;
				r40 = r33 + 0x00;
				r41 = 0x00 + 0x0200;
				b0();
				r1 = r37 + 0x00;
				r14 = r8 + null;
l400000000012B4B0:
				r8 = r14 + null;
				ar.pfs = r36;
				b0 = r35;
				r12 += 0x90;
				return;
			}
l400000000012B5E0:
			r38 = r32;
			r39 = r12 + 0x10;
			b0();
			r1 = r37 + 0x00;
			int32 v41 = (word32) r8;
			int32 v42 = (word32) 0x00;
			p06 = v41 < v42;
			p07 = v41 >= v42;
			if (!p06)
			{
				r14 = r1 + -22276;
				r14 += (union Eq_n *) 0x04;
				Eq_n v45;
				v45.u1 = r14->u1;
				r14 = (word64) v45;
				word32 v46 = (word32) 0x00;
				word32 v47 = (word32) r14;
				p07 = v46 == v47;
				p06 = v46 != v47;
				if (p06)
				{
					word64 r34 = r12 + 0x28;
				}
			}
			else
			{
				r14 = 0x00 + -1;
				r8 = r14 + null;
				ar.pfs = r36;
				b0 = r35;
				r12 += 0x90;
				return;
			}
		}
		word32 v38 = (word32) 111;
		word32 v39 = (word32) r14;
		p07 = v38 == v39;
		p06 = v38 != v39;
		if (p07)
		{
			r14 = (union Eq_n *) (r32 + 9);
			Eq_n v43;
			v43.u0 = r14->u0;
			r14 = (word64) v43;
			p07 = (union Eq_n *) 117 == r14;
			p06 = (union Eq_n *) 117 != r14;
			if (!p06)
			{
				r14 = (union Eq_n *) (r32 + 0x0A);
				Eq_n v49;
				v49.u0 = r14->u0;
				r14 = (word64) v49;
				p07 = (union Eq_n *) 116 == r14;
				p06 = (union Eq_n *) 116 != r14;
				if (!p06)
				{
					r14 = (union Eq_n *) (r32 + 11);
					Eq_n v51;
					v51.u0 = r14->u0;
					r14 = (word64) v51;
					p06 = null == r14;
					p07 = null != r14;
					if (p06)
						goto l400000000012B5E0;
				}
			}
		}
		else
		{
			word32 v52 = (word32) 101;
			word32 v53 = (word32) r14;
			p07 = v52 == v53;
			p06 = v52 != v53;
			if (!p06)
			{
				r14 = (union Eq_n *) (r32 + 9);
				Eq_n v54;
				v54.u0 = r14->u0;
				r14 = (word64) v54;
				p07 = (union Eq_n *) 114 == r14;
				p06 = (union Eq_n *) 114 != r14;
				if (!p06)
				{
					r14 = (union Eq_n *) (r32 + 0x0A);
					Eq_n v55;
					v55.u0 = r14->u0;
					r14 = (word64) v55;
					p06 = (union Eq_n *) 114 == r14;
					p07 = (union Eq_n *) 114 != r14;
					if (!p07)
					{
						r14 = (union Eq_n *) (r32 + 11);
						Eq_n v56;
						v56.u0 = r14->u0;
						r14 = (word64) v56;
						p06 = null == r14;
						p07 = null != r14;
						if (!p07)
							goto l400000000012B5E0;
					}
				}
			}
		}
	}
l400000000012B480:
	r38 = 0x00 + -100;
	r39.u1 = r32;
	r40 = r33 + 0x00;
	r41 = 0x00 + 0x0200;
	b0();
	r1 = r37 + 0x00;
	r14 = (union Eq_n *) &r8->u0;
	goto l400000000012B4B0;
}

// 400000000012B8C0: define isnetconn
define isnetconn
{
	word32 * r8;
	word64 r32;
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 r12 = r12 + ~0x1F;
	word64 r35 = r1 + 0x00;
	<anonymous> * r33 = b1;
	word64 r36 = r32 + 0x00;
	word64 r14 = r12 + 0x20;
	word32 * r15 = 0x00 + 16;
	word64 r37 = r12 + 0x10;
	word64 r38 = r14 + 0x00;
	*r15 = (word32) r14;
	<anonymous> * b0;
	b0();
	r14 = 0x00 + 1;
	r1 = r35 + 0x00;
	int32 v19 = (word32) r8;
	int32 v20 = (word32) 0x00;
	Eq_n p07 = v19 < v20;
	Eq_n p06 = v19 >= v20;
	if (p07)
	{
		b0();
		word32 v23 = *r8;
		r15 = (word64) v23;
		r1 = r35 + 0x00;
		r14 = 0x00 + 0x00;
		word32 v24 = (word32) 88;
		word32 v25 = (word32) r15;
		p07 = v24 == v25;
		p06 = v24 != v25;
		word32 v26 = (word32) 22;
		word32 v27 = (word32) r15;
		Eq_n p08 = v26 == v27;
		Eq_n p09 = v26 != v27;
		if (!p07)
		{
			if (p09)
				r14 = 0x00 + 1;
		}
	}
	r8 = r14 + 0x00;
	ar.pfs = r34;
	b0 = r33;
	r12 += 0x20;
}

// 400000000012B9C0: define netopen
define netopen
{
	byte * r4;
	word64 r32;
	<anonymous> * b6;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r39 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	word64 r40 = r1 + 0x00;
	<anonymous> * r38 = b6;
	Eq_n r41 = r32 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r40 + 0x00;
	Eq_n r8;
	r41.u1 = (word32) r8 + 1;
	union Eq_n * r37 = r12 + 0x40;
	b0();
	word64 r36 = r8.u1;
	r1 = r40 + 0x00;
	r41.u2 = r8.u1;
	byte * r42 = r32 + 0x00;
	b0();
	union Eq_n * r35 = r36 + 0x09;
	r1 = r40 + 0x00;
	r42 = 0x00 + 47;
	r41.u2 = &r35->u0;
	b0();
	union Eq_n * r15 = r12 + 0x10;
	Eq_n r33;
	r33.u2 = r8.u1;
	r1 = r40 + 0x00;
	Eq_n p07 = 0x00 == r8;
	Eq_n p06 = 0x00 != r8;
	union Eq_n * r16 = r32 + 0x05;
	word64 r43;
	word64 r34;
	if (!p07)
	{
		r43 = &r15->u0;
		*r33 = (byte) r1;
		r33.u1 = (word32) r33 + 1;
		r15->u1 = (word32 *) r8;
		r15 = (union Eq_n *) ((char *) r15 + 8);
		word64 r44 = &r37->u0;
		r41.u2 = &r35->u0;
		Eq_n r14;
		r14.u2 = &r15->u0;
		Eq_n v27;
		v27.u0 = r16->u0;
		r16 = (word64) v27;
		r42 = (byte *) r33.u2;
		*r14.u2 = (word64) r8;
		r14.u1 = (word32) r14 + 8;
		int8 v28 = (int8) r16;
		r16 = (int64) v28;
		*r14.u2 = (word64) r8;
		r14.u1 = (word32) r14 + 8;
		word32 v29 = (word32) 116;
		word32 v30 = (word32) r16;
		p07 = v29 == v30;
		p06 = v29 != v30;
		*r14.u2 = (word64) r8;
		r14.u1 = (word32) r14 + 8;
		if (p06)
			r16 = 0x00 + 2;
		word64 p01;
		if (p01)
			__break();
		if (p07)
		{
			byte v35 = *r4;
			r43 = (word64) v35;
		}
		r33.u2 = r37->u2;
		p06 = 0x00 == r33;
		p07 = 0x00 != r33;
		if (p06)
		{
l400000000012BC10:
			r41 = r36 + 0x00;
			b0();
			r1 = r40 + 0x00;
		}
		else
		{
			do
			{
				r16 = (union Eq_n *) ((word32) r33 + 4);
				r15 = (union Eq_n *) ((word32) r33 + 8);
				r14.u1 = (word32) r33 + 0x0C;
				r35 = (union Eq_n *) ((word32) r33 + 40);
				Eq_n v38;
				v38.u1 = r16->u1;
				r41.u2 = (word64) v38;
				Eq_n v39;
				v39.u0 = r15->u0;
				r42 = (word64) v39;
				Eq_n v40 = *r14;
				r43 = (word64) v40;
				b0();
				r14.u1 = (word32) r33 + 24;
				int32 v41 = (word32) r8;
				int32 v42 = (word32) 0x00;
				p07 = v41 < v42;
				p06 = v41 >= v42;
				r33.u1 = (word32) r33 + 16;
				r34 = r8.u1;
				r1 = r40 + 0x00;
				if (!p07)
				{
					r41.u2 = r8.u1;
					r42 = *r14.u2;
					Eq_n v43 = *r33;
					r43 = (word64) v43;
					b0();
					r1 = r40 + 0x00;
					int32 v44 = (word32) r8;
					int32 v45 = (word32) 0x00;
					p07 = v44 < v45;
					p06 = v44 >= v45;
					r41 = r34 + 0x00;
					if (p06)
					{
						r41.u2 = r37->u2;
						b0();
						r1 = r40 + 0x00;
						r41 = r36 + 0x00;
						b0();
						r1 = r40 + 0x00;
						goto l400000000012BC30;
					}
					r14.u2 = r35->u2;
					p06 = 0x00 == r14;
					p07 = 0x00 != r14;
					if (!p06)
					{
						b0();
						r33.u2 = r35->u2;
						r1 = r40 + 0x00;
						p07 = 0x00 == r33;
						p06 = 0x00 != r33;
						if (p06)
							continue;
						goto l400000000012BC10;
					}
					else
					{
						b0();
						r1 = r40 + 0x00;
						r33.u2 = r8.u1;
						word32 v46 = *r8.u1;
						r35 = (word64) v46;
						r41 = r1 + -8452;
						r41.u2 = *r41.u2;
						b0();
						r1 = r40 + 0x00;
						r41 = r34 + 0x00;
						r34 = 0x00 + -1;
						b0();
						r1 = r40 + 0x00;
						r41.u2 = r37->u2;
						b0();
						r1 = r40 + 0x00;
						r35->u1 = (word32) (word32) r33;
						r41 = r36 + 0x00;
						b0();
						r1 = r40 + 0x00;
						goto l400000000012BC30;
					}
				}
				r33.u2 = r35->u2;
				p07 = 0x00 == r33;
				p06 = 0x00 != r33;
			} while (p06);
			r41 = r1 + -8460;
			r34 = 0x00 + -1;
			r41.u2 = *r41.u2;
			b0();
			r1 = r40 + 0x00;
			r41.u2 = r37->u2;
			b0();
			r1 = r40 + 0x00;
			r41 = r36 + 0x00;
			b0();
			r1 = r40 + 0x00;
		}
l400000000012BC30:
		r8 = r34 + 0x00;
		ar.pfs = r39;
		b0 = r38;
		r12 += 0x40;
	}
	else
	{
		r42 = r1 + -0x0000211C;
		r43 = 0x00 + 5;
		r41 = 0x00 + 0x00;
		r34 = 0x00 + -1;
		r42 = (byte *) *r42;
		b0();
		r1 = r40 + 0x00;
		r41.u2 = r8.u1;
		r42 = r32 + 0x00;
		b0();
		r8 = r34 + 0x00;
		r1 = r40 + 0x00;
		ar.pfs = r39;
		b0 = r38;
		r12 += 0x40;
	}
}

// 400000000012BF80: define difftimeval
define difftimeval
{
	word64 r60;
	struct Eq_n ** r33;
	struct Eq_n * r32;
	struct Eq_n ** r34;
	ptr64 fp;
	ptr64 r11 = fp;
	struct Eq_n * r17 = (struct Eq_n *) *r34;
	r34 = (struct Eq_n **) ((char *) r34 + 8);
	struct Eq_n * r14 = (struct Eq_n *) &r32->ptr0000;
	struct Eq_n * r8 = (struct Eq_n *) &r32->ptr0000;
	struct Eq_n * r15 = (struct Eq_n *) *r33;
	r33 = (struct Eq_n **) ((char *) r33 + 8);
	struct Eq_n * r2 = (struct Eq_n *) *r34;
	r15 -= r17;
	struct Eq_n * r16 = (struct Eq_n *) *r33;
	r14->ptr0000 = r8;
	r14 = (struct Eq_n *) ((char *) &r14->ptr0000 + 8);
	r2 = r16 - r2;
	r2->ptr0000 = r14;
	Eq_n p06 = r2 < null;
	Eq_n p07 = r2 >= null;
	if (p07)
		return;
	r15 = (struct Eq_n *) ((char *) r15 - 1);
	r2 = (struct Eq_n *) ((char *) &r2->ptr0000 + 1000000);
	p07 = r15 < null;
	p06 = r15 >= null;
	r2->ptr0000 = r14;
	r15->ptr0000 = r32;
	if (p07)
	{
		struct Eq_n ** r0;
		*r0 = (struct Eq_n **) r14;
	}
	word64 p32;
	if (p32)
	{
		int32 v22 = (word32) r60;
		int32 v23 = (word32) 0x00;
		Eq_n p02 = v22 < v23;
		Eq_n p08 = v22 >= v23;
	}
	word64 p01;
	if (p01)
		__break();
	r2 = (struct Eq_n *) *r33;
	r2 = r15 + r2;
	r16 = (struct Eq_n *) ((char *) &r14->ptr0000 + 1);
	r14->ptr0000 = r32;
	r14 = 0x00 + 999999;
	p06 = r14 < r2;
	p07 = r14 >= r2;
	r15 = (struct Eq_n *) ((char *) r2 - 1000000);
	if (!p07)
		fn400000000012C050();
	else
	{
		r14 = (struct Eq_n *) &r17->ptr0000;
		fn400000000012C050();
	}
}

// 400000000012C000: define addtimeval
define addtimeval
{
	word64 ** r34;
	word64 r32;
	word64 ** r33;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 * r16 = *r33;
	r33 = (word64 **) ((char *) r33 + 8);
	word64 r17 = r32 + 0x08;
	word64 r8 = r32 + 0x00;
	word64 * r14 = *r34;
	r34 = (word64 **) ((char *) r34 + 8);
	word64 * r15 = *r34;
	r14 += r16;
	word64 * r2 = *r33;
	r2 = r15 + r2;
	r16 = (word64 *) ((char *) r14 + 1);
	*r14 = r32;
	r14 = 0x00 + 999999;
	Eq_n p06 = r14 < r2;
	Eq_n p07 = r14 >= r2;
	r15 = r2 + -125000;
	if (!p07)
		fn400000000012C050();
	else
	{
		r14 = r17 + 0x00;
		fn400000000012C050();
	}
}

// 400000000012C050: define fn400000000012C050
// Called from:
//      difftimeval
//      addtimeval
define fn400000000012C050
{
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 p06;
	if (p06)
	{
		word64 * r15;
		word64 r17;
		*r15 = r17;
	}
	word32 v7 = (word32) 0x00;
	word32 v9 = (word32) r1;
	v7 == v9;
	v7 != v9;
	__break();
	__break();
	__break();
	fn400000000012C082();
}

// 400000000012C080: define timeval_to_cpu
define timeval_to_cpu
{
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	fn400000000012C082();
}

// 400000000012C082: define fn400000000012C082
// Called from:
//      addtimeval
//      timeval_to_cpu
define fn400000000012C082
{
	ptr64 fp;
	ptr64 r11 = fp;
}

