// elf-Linux-ia64-bash_text_n.c
// Generated by decompiling elf-Linux-ia64-bash
// using Reko decompiler version 0.12.3.0.

#include "elf-Linux-ia64-bash.h"

// 400000000004C700: define dispose_function_def_contents
define dispose_function_def_contents
{
	word64 r1;
	<anonymous> * b1;
	word64 * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 * r14 = r32 + 1;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = *r14;
	<anonymous> * b0;
	b0();
	r14 = r32 + 2;
	r1 = r35 + 0x00;
	r32 += 3;
	r36 = *r14;
	b0();
	r36 = *r32;
	r1 = r35 + 0x00;
	Eq_n p06 = 0x00 == r36;
	Eq_n p07 = 0x00 != r36;
	if (!p06)
	{
		b0();
		r1 = r35 + 0x00;
	}
	ar.pfs = r34;
	b0 = r33;
}

// 400000000004C7C0: define dispose_function_def
define dispose_function_def
{
	word64 r32;
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = r32 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r35 + 0x00;
	r36 = r32 + 0x00;
	b0();
	r1 = r35 + 0x00;
	ar.pfs = r34;
	b0 = r33;
}

// 400000000004CF00: define close_fd_bitmap
define close_fd_bitmap
{
	word64 r1;
	word32 * r32;
	<anonymous> * b3;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	<anonymous> * r35 = b3;
	Eq_n p07 = null == r32;
	Eq_n p06 = null != r32;
	word64 r37 = r1 + 0x00;
	byte ** r34 = (byte **) (r32 + 2);
	<anonymous> * b0;
	if (!p07)
	{
		word64 r33 = 0x00 + 0x00;
		word32 v15 = *r32;
		word64 r15 = (word64) v15;
		int32 v17 = (word32) 0x00;
		int32 v18 = (word32) r15;
		p07 = v17 < v18;
		p06 = v17 >= v18;
		if (!p06)
		{
			do
			{
				byte * r14 = (byte *) *r34;
				r14 += r33;
				byte v21 = *r14;
				r14 = (word64) v21;
				int8 v22 = (int8) r14;
				r14 = (int64) v22;
				word32 v23 = (word32) 0x00;
				word32 v24 = (word32) r14;
				p06 = v23 == v24;
				p07 = v23 != v24;
				r14 = r33 + 0x01;
				if (p07)
				{
					word64 r38 = r33 + 0x00;
					b0();
					r14 = (byte *) *r34;
					r1 = r37 + 0x00;
					word32 v28 = *r32;
					r15 = (word64) v28;
					r14 += r33;
					byte * r0;
					*r0 = (byte) r14;
					r14 = r33 + 0x01;
					++r33;
					int32 v30 = (word32) r14;
					int32 v31 = (word32) r15;
					p06 = v30 < v31;
					p07 = v30 >= v31;
					if (p06)
						continue;
					break;
				}
				++r33;
				int32 v25 = (word32) r14;
				int32 v26 = (word32) r15;
				p06 = v25 < v26;
				p07 = v25 >= v26;
			} while (p06);
		}
	}
	ar.pfs = r36;
	b0 = r35;
}

// 400000000004D0C0: define dispose_fd_bitmap
define dispose_fd_bitmap
{
	<anonymous> * b1;
	word64 r1;
	word64 r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 * r14 = r32 + 0x08;
	word64 r35 = r1 + 0x00;
	<anonymous> * r33 = b1;
	word64 r36 = *r14;
	Eq_n p06 = 0x00 == r36;
	Eq_n p07 = 0x00 != r36;
	<anonymous> * b0;
	if (!p06)
	{
		b0();
		r1 = r35 + 0x00;
	}
	r36 = r32 + 0x00;
	b0();
	r1 = r35 + 0x00;
	ar.pfs = r34;
	b0 = r33;
}

// 400000000004EE40: define new_fd_bitmap
define new_fd_bitmap
{
	word64 r8;
	word32 * r32;
	word64 r1;
	word64 b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word64 r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r37 = 0x00 + 16;
	<anonymous> * b0;
	b0();
	word32 v13 = (word32) 0x00;
	word32 v14 = (word32) r32;
	Eq_n p06 = v13 == v14;
	Eq_n p07 = v13 != v14;
	word64 r33 = r8 + 0x00;
	ar.pfs = r35;
	word64 r14 = r8 + 0x08;
	*r32 = (word32) r8;
	r1 = r36 + 0x00;
	if (p06)
	{
		word64 * r0;
		*r0 = r14;
	}
}

// 400000000004EF40: define executing_line_number
define executing_line_number
{
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	Eq_n r14 = r1 + 6488;
	Eq_n v6;
	v6.u0 = r14.u1->t0000.u0;
	r14.u1 = (word64) v6;
	word32 v7 = (word32) 0x00;
	word32 v8 = (word32) r14;
	Eq_n p06 = v7 == v8;
	Eq_n p07 = v7 != v8;
	word64 r8;
	if (!p06)
	{
		r14 = r1 + 7076;
		Eq_n v11;
		v11.u0 = r14.u1->t0000.u0;
		r14.u1 = (word64) v11;
		word32 v12 = (word32) 0x00;
		word32 v13 = (word32) r14;
		p07 = v12 == v13;
		p06 = v12 != v13;
		if (p06)
			goto l400000000004F020;
		r14 = r1 + 7148;
		Eq_n v17;
		v17.u0 = r14.u1->t0000.u0;
		r14.u1 = (word64) v17;
		word32 v18 = (word32) 0x00;
		word32 v19 = (word32) r14;
		p06 = v18 == v19;
		p07 = v18 != v19;
		if (p07)
		{
			r14 = r1 + 6512;
			Eq_n v20;
			v20.u0 = r14.u1->t0000.u0;
			r14.u1 = (word64) v20;
			word32 v21 = (word32) 0x00;
			word32 v22 = (word32) r14;
			p07 = v21 == v22;
			p06 = v21 != v22;
			if (!p07)
			{
				r14 = r1 + 6648;
				Eq_n v27;
				v27.u0 = r14.u1->t0000.u0;
				r8 = (word64) v27;
				return;
			}
		}
		r14 = r1 + 7084;
		r14.u1 = r14.u1->t0000.u1;
		p06 = 0x00 == r14;
		p07 = 0x00 != r14;
		if (!p06)
		{
			Eq_n v23;
			v23.u0 = r14.u1->t0000.u0;
			word64 r15 = (word64) v23;
			word32 v25 = (word32) 11;
			word32 v26 = (word32) r15;
			p07 = v25 == v26;
			p06 = v25 != v26;
			if (!p07)
			{
				word32 v28 = (word32) 0x0A;
				word32 v29 = (word32) r15;
				p07 = v28 == v29;
				p06 = v28 != v29;
				if (!p07)
				{
					word32 v31 = (word32) 0x0C;
					word32 v32 = (word32) r15;
					p07 = v31 == v32;
					p06 = v31 != v32;
					if (!p07)
						goto l400000000004F020;
				}
			}
			r14.u0 = (word32) r14 + 24;
			r14.u1 = r14.u1->t0000.u1;
			r14.u0 = (word32) r14 + 4;
			Eq_n v30;
			v30.u0 = r14.u1->t0000.u0;
			r8 = (word64) v30;
			return;
		}
	}
l400000000004F020:
	r14 = r1 + 6648;
	Eq_n v14;
	v14.u0 = r14.u1->t0000.u0;
	r8 = (word64) v14;
}

// 400000000004F0C0: define dispose_exec_redirects
define dispose_exec_redirects
{
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 * r32 = r1 + 7060;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r14 = *r32;
	Eq_n p06 = 0x00 == r14;
	Eq_n p07 = 0x00 != r14;
	word64 r36 = r14 + 0x00;
	<anonymous> * b0;
	if (!p06)
	{
		b0();
		r1 = r35 + 0x00;
		word64 ** r0;
		*r0 = r32;
	}
	ar.pfs = r34;
	b0 = r33;
}

// 400000000004F140: define getcoprocbypid
define getcoprocbypid
{
	word64 r32;
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r14 = r1 + -21372;
	r14 += 2;
	word32 v6 = *r14;
	word64 r8 = (word64) v6;
	word32 v9 = (word32) r32;
	word32 v10 = (word32) r8;
	Eq_n p07 = v9 == v10;
	Eq_n p06 = v9 != v10;
	if (p07)
		r8 = r1 + -21372;
	__break();
	__break();
}

// 400000000004F1C0: define getcoprocbyname
define getcoprocbyname
{
	byte * r32;
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	Eq_n r14 = r1 + -21372;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r37 = r32;
	r14.u1 = r14.u1->t0000.u1;
	word64 * r36 = (word64 *) &r14.u1->t0000.u0;
	Eq_n p06 = 0x00 == r14;
	Eq_n p07 = 0x00 != r14;
	word64 r8;
	if (!p06)
	{
		byte v16 = *r32;
		int64 r15 = (word64) v16;
		Eq_n v18;
		v18.u0 = r14.u1->t0000.u0;
		r14.u1 = (word64) v18;
		int8 v19 = (int8) r14;
		r14.u1 = (int64) v19;
		int8 v20 = (int8) r15;
		r15 = (int64) v20;
		word32 v21 = (word32) r14;
		word32 v22 = (word32) r15;
		p07 = v21 == v22;
		p06 = v21 != v22;
		if (!p06)
		{
			<anonymous> * b0;
			b0();
			r1 = r35 + 0x00;
			word32 v25 = (word32) 0x00;
			word32 v26 = (word32) r8;
			p07 = v25 == v26;
			p06 = v25 != v26;
			ar.pfs = r34;
			if (p07)
				r8 = r1 + -21372;
			__break();
l400000000004F272:
			ar.pfs = r34;
			b0 = r33;
			return;
		}
	}
	r8 = 0x00 + 0x00;
	goto l400000000004F272;
}

// 400000000004F2C0: define coproc_init
define coproc_init
{
	word64 r32;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 * r15 = r32 + 0x00;
	word32 * r14 = 0x00 + -1;
	word64 r20 = r32 + 0x10;
	word64 r19 = r32 + 0x0C;
	word64 r18 = r32 + 0x18;
	word64 r17 = r32 + 0x14;
	word64 r16 = r32 + 0x20;
	word64 r8;
	*r15 = r8;
	++r15;
	r32 += 0x1C;
	*r14 = (word32) r20;
	*r14 = (word32) r15;
	*r14 = (word32) r19;
	*r14 = (word32) r18;
	*r14 = (word32) r17;
	word32 * r0;
	*r0 = (word32) r16;
	*r0 = (word32) r32;
}

// 400000000004F340: define coproc_alloc
define coproc_alloc
{
	word64 r32;
	<anonymous> * b4;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r37 = ar.pfs;
	word64 r34 = r1 + -21372;
	<anonymous> * r36 = b4;
	word64 r38 = r1 + 0x00;
	word64 r39 = r32 + 0x00;
	word32 * r14 = 0x00 + -1;
	word64 ** r35 = r34 + 0x00;
	word64 r20 = r34 + 0x10;
	word64 r19 = r34 + 0x0C;
	word64 r18 = r34 + 0x18;
	word64 r17 = r34 + 0x14;
	word64 r16 = r34 + 0x20;
	word64 r15 = r34 + 0x1C;
	word64 * r8;
	*r35 = r8;
	r35 = (word64 **) ((char *) r35 + 8);
	*r14 = (word32) r20;
	*r14 = (word32) r35;
	*r14 = (word32) r19;
	*r14 = (word32) r18;
	*r14 = (word32) r17;
	word32 * r0;
	*r0 = (word32) r16;
	*r0 = (word32) r15;
	<anonymous> * b0;
	b0();
	r1 = r38 + 0x00;
	r39 = (char *) r8 + 1;
	b0();
	r1 = r38 + 0x00;
	r39 = r8;
	word64 r40 = r32 + 0x00;
	b0();
	r1 = r38 + 0x00;
	*r8 = r34;
	word32 * r33;
	*r33 = (word32) r35;
	r8 = r34 + 0x00;
	ar.pfs = r37;
	b0 = r36;
}

// 400000000004F440: define coproc_close
// Called from:
//      coproc_closeall
define coproc_close
{
	<anonymous> * b3;
	word64 r1;
	word64 r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word32 * r34 = r32 + 0x0C;
	word64 r37 = r1 + 0x00;
	<anonymous> * r35 = b3;
	word32 * r33 = r32 + 0x10;
	word32 v13 = *r34;
	word32 * r14 = (word64) v13;
	int32 v15 = (word32) r14;
	int32 v16 = (word32) 0x00;
	Eq_n p06 = v15 < v16;
	Eq_n p07 = v15 >= v16;
	word32 * r38 = r14;
	<anonymous> * b0;
	if (!p06)
	{
		b0();
		r14 = 0x00 + -1;
		r1 = r37 + 0x00;
		*r14 = (word32) r34;
	}
	word32 v21 = *r33;
	r14 = (word64) v21;
	int32 v22 = (word32) r14;
	int32 v23 = (word32) 0x00;
	p06 = v22 < v23;
	p07 = v22 >= v23;
	r38 = r14;
	if (!p06)
	{
		b0();
		r14 = 0x00 + -1;
		r1 = r37 + 0x00;
		*r14 = (word32) r33;
	}
	r14 = 0x00 + -1;
	word64 r15 = r32 + 0x18;
	r32 += 0x14;
	ar.pfs = r36;
	*r14 = (word32) r15;
	*r14 = (word32) r32;
	b0 = r35;
}

// 400000000004F540: define coproc_closeall
define coproc_closeall
{
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	word64 r32 = r1 + -21372;
	word64 r2 = ar.pfs;
	coproc_close();
}

// 400000000004F580: define coproc_rclose
define coproc_rclose
{
	word64 r33;
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word32 * r32 = r32 + 3;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word32 v11 = *r32;
	word64 r37 = (word64) v11;
	int32 v13 = (word32) r37;
	int32 v14 = (word32) 0x00;
	Eq_n p06 = v13 < v14;
	Eq_n p07 = v13 >= v14;
	<anonymous> * b0;
	if (!p06)
	{
		word32 v18 = (word32) r33;
		word32 v19 = (word32) r37;
		p07 = v18 == v19;
		p06 = v18 != v19;
		if (p07)
		{
			b0();
			word32 * r14 = 0x00 + -1;
			r1 = r36 + 0x00;
			ar.pfs = r35;
			*r14 = (word32) r32;
			b0 = r34;
			return;
		}
	}
	ar.pfs = r35;
	b0 = r34;
}

// 400000000004F640: define coproc_wclose
define coproc_wclose
{
	word64 r33;
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word32 * r32 = r32 + 4;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word32 v11 = *r32;
	word64 r37 = (word64) v11;
	int32 v13 = (word32) r37;
	int32 v14 = (word32) 0x00;
	Eq_n p06 = v13 < v14;
	Eq_n p07 = v13 >= v14;
	<anonymous> * b0;
	if (!p06)
	{
		word32 v18 = (word32) r33;
		word32 v19 = (word32) r37;
		p07 = v18 == v19;
		p06 = v18 != v19;
		if (p07)
		{
			b0();
			word32 * r14 = 0x00 + -1;
			r1 = r36 + 0x00;
			ar.pfs = r35;
			*r14 = (word32) r32;
			b0 = r34;
			return;
		}
	}
	ar.pfs = r35;
	b0 = r34;
}

// 400000000004F700: define coproc_fdsave
define coproc_fdsave
{
	word64 r32;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r15 = r32 + 0x0C;
	word32 * r14 = r32 + 0x10;
	word64 r16 = r32 + 0x14;
	r32 += 0x18;
	word32 v8 = *r15;
	r15 = (word64) v8;
	word32 v9 = *r14;
	r14 = (word64) v9;
	*r15 = (word32) r16;
	*r14 = (word32) r32;
}

// 400000000004F740: define coproc_fdrestore
define coproc_fdrestore
{
	word64 r32;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r15 = r32 + 0x14;
	word32 * r14 = r32 + 0x18;
	word64 r16 = r32 + 0x0C;
	r32 += 0x10;
	word32 v8 = *r15;
	r15 = (word64) v8;
	word32 v9 = *r14;
	r14 = (word64) v9;
	*r15 = (word32) r16;
	*r14 = (word32) r32;
}

// 400000000004F780: define coproc_pidchk
define coproc_pidchk
{
	word64 r32;
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r14 = r1 + -21372;
	word32 * r15 = r14 + 0x08;
	word32 v7 = *r15;
	r15 = (word64) v7;
	word32 v9 = (word32) r15;
	word32 v10 = (word32) r32;
	Eq_n p06 = v9 == v10;
	Eq_n p07 = v9 != v10;
	if (p06)
		r15 = r14 + 0x1C;
}

// 400000000004F800: define coproc_setvars
// Called from:
//      coproc_fdclose
//      coproc_checkfd
define coproc_setvars
{
	word64 r1;
	<anonymous> * b5;
	word64 ** r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r38 = ar.pfs;
	word64 * r14 = *r32;
	<anonymous> * r37 = b5;
	word64 r39 = r1 + 0x00;
	word64 * r34 = r32;
	word64 * r33 = r32;
	Eq_n p06 = null == r14;
	Eq_n p07 = null != r14;
	word64 * r40 = r14;
	<anonymous> * b0;
	if (p06)
	{
l400000000004FA30:
		ar.pfs = r38;
		b0 = r37;
		return;
	}
	b0();
	word64 r8;
	r40 = r8 + 0x10;
	r1 = r39 + 0x00;
	int32 v19 = (int32) r40;
	r40 = (int64) v19;
	b0();
	r1 = r39 + 0x00;
	word64 r35 = r8 + 0x00;
	r40 = *r32;
	b0();
	r14 = r8 + 0x28;
	r1 = r39 + 0x00;
	p07 = 0x00 == r8;
	p06 = 0x00 != r8;
	word64 r41;
	word64 r42;
	struct Eq_n * r43;
	word64 r36;
	word64 r44;
	if (p07)
	{
		r40 = *r32;
		b0();
		r14 = r8 + 0x28;
		r1 = r39 + 0x00;
		word32 v22 = (word32) *r14;
		r14 = (word64) v22;
		if (p06)
		{
l400000000004F8C0:
			r14 = (word64 *) ((char *) r32 + 0x0C);
			word32 v23 = (word32) *r14;
			r40 = (word64) v23;
			int32 v24 = (int32) r40;
			r40 = (int64) v24;
			b0();
			r41 = 0x00 + 0x00;
			r42 = r8 + 0x00;
			r43 = 0x00 + 0x00;
			r40 = *r34;
			r34 += 2;
			r1 = r39 + 0x00;
			r36 = r8 + 0x00;
			b0();
			r1 = r39 + 0x00;
			r40 = r36 + 0x00;
			b0();
			Eq_n v29;
			v29.u0 = *r34;
			r40 = (word64) v29;
			r1 = r39 + 0x00;
			int32 v30 = (int32) r40;
			r40 = (int64) v30;
			b0();
			r41 = 0x00 + 1;
			r42 = r8 + 0x00;
			r43 = 0x00 + 0x00;
			r1 = r39 + 0x00;
			r40 = *r32;
			r34 = r8 + 0x00;
			b0();
			r1 = r39 + 0x00;
			r40 = r34;
			b0();
			r1 = r39 + 0x00;
			r44 = *r33;
			++r33;
			r42 = 0x00 + -1;
			r41 = 0x00 + 1;
			r40 = r35 + 0x00;
			r43 = r1 + -0x0CC4;
			r43 = r43->ptr0000;
			b0();
			Eq_n v32;
			v32.u0 = *r33;
			r40 = (word64) v32;
			r1 = r39 + 0x00;
			int32 v33 = (int32) r40;
			r40 = (int64) v33;
			b0();
			r42 = 0x00 + 0x00;
			r41 = r8 + 0x00;
			r1 = r39 + 0x00;
			r33 = r8 + 0x00;
			r40 = r35 + 0x00;
			b0();
			r1 = r39 + 0x00;
			r40 = r33;
			b0();
			r1 = r39 + 0x00;
			r40 = r35 + 0x00;
			b0();
			r1 = r39 + 0x00;
			goto l400000000004FA30;
		}
	}
	else
	{
		word32 v21 = (word32) *r14;
		r14 = (word64) v21;
		if (!p07)
			goto l400000000004F8C0;
	}
	r40 = r8 + 0x00;
	b0();
	r14 = (word64 *) ((char *) r32 + 0x0C);
	r1 = r39 + 0x00;
	word32 v34 = (word32) *r14;
	r40 = (word64) v34;
	int32 v35 = (int32) r40;
	r40 = (int64) v35;
	b0();
	r41 = 0x00 + 0x00;
	r42 = r8 + 0x00;
	r43 = 0x00 + 0x00;
	r40 = *r34;
	r34 += 2;
	r1 = r39 + 0x00;
	r36 = r8 + 0x00;
	b0();
	r1 = r39 + 0x00;
	r40 = r36 + 0x00;
	b0();
	Eq_n v36;
	v36.u0 = *r34;
	r40 = (word64) v36;
	r1 = r39 + 0x00;
	int32 v37 = (int32) r40;
	r40 = (int64) v37;
	b0();
	r1 = r39 + 0x00;
	r34 = r8 + 0x00;
	r41 = 0x00 + 1;
	r42 = r8 + 0x00;
	r40 = *r32;
	r43 = 0x00 + 0x00;
	b0();
	r1 = r39 + 0x00;
	r40 = r34;
	b0();
	r1 = r39 + 0x00;
	r44 = *r33;
	++r33;
	r40 = r35 + 0x00;
	r42 = 0x00 + -1;
	r41 = 0x00 + 1;
	r43 = r1 + -0x0CC4;
	r43 = r43->ptr0000;
	b0();
	Eq_n v38;
	v38.u0 = *r33;
	r40 = (word64) v38;
	r1 = r39 + 0x00;
	int32 v39 = (int32) r40;
	r40 = (int64) v39;
	b0();
	r42 = 0x00 + 0x00;
	r41 = r8 + 0x00;
	r1 = r39 + 0x00;
	r33 = r8 + 0x00;
	r40 = r35 + 0x00;
	b0();
	r1 = r39 + 0x00;
	r40 = r33;
	b0();
	r1 = r39 + 0x00;
	r40 = r35 + 0x00;
	b0();
	r1 = r39 + 0x00;
	goto l400000000004FA30;
}

// 400000000004FC40: define coproc_fdclose
define coproc_fdclose
{
	word64 r33;
	word64 r32;
	word64 r1;
	<anonymous> * b3;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	<anonymous> * r35 = b3;
	word64 r37 = r1 + 0x00;
	word64 r38 = r32 + 0x00;
	word64 r39 = r33 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r37 + 0x00;
	r38 = r32 + 0x00;
	r39 = r33 + 0x00;
	b0();
	r1 = r37 + 0x00;
	b0 = r35;
	ar.pfs = r36;
	word64 r2 = ar.pfs;
	coproc_setvars();
}

// 400000000004FCC0: define coproc_checkfd
// Called from:
//      coproc_fdchk
define coproc_checkfd
{
	word64 ar.pfs;
	word64 r32;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r14 = r32 + 0x0C;
	word32 v6 = *r14;
	word32 * r15 = (word64) v6;
	int32 v8 = (word32) r15;
	int32 v9 = (word32) 0x00;
	Eq_n p06 = v8 < v9;
	Eq_n p07 = v8 >= v9;
	word64 r33;
	if (!p06)
	{
		word32 v13 = (word32) r33;
		word32 v14 = (word32) r15;
		p07 = v13 == v14;
		p06 = v13 != v14;
		if (p07)
			r15 = 0x00 + -1;
	}
	else
	{
		word64 r16 = 0x00 + 0x00;
		r15 = r32 + 0x10;
		word32 v16 = *r15;
		r14 = (word64) v16;
		int32 v17 = (word32) r14;
		int32 v18 = (word32) 0x00;
		p06 = v17 < v18;
		p07 = v17 >= v18;
		if (!p06)
		{
			word32 v19 = (word32) r14;
			word32 v20 = (word32) r33;
			p07 = v19 == v20;
			p06 = v19 != v20;
			if (p07)
				r14 = 0x00 + -1;
		}
		else
		{
			word32 v21 = (word32) 0x00;
			word32 v22 = (word32) r16;
			p06 = v21 == v22;
			p07 = v21 != v22;
			if (p06)
				return;
			word64 r2 = ar.pfs;
			coproc_setvars();
		}
	}
}

// 400000000004FD80: define coproc_fdchk
define coproc_fdchk
{
	word64 r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	word64 r33 = r32 + 0x00;
	word64 r1;
	r32 = r1 + -21372;
	word64 r2 = ar.pfs;
	coproc_checkfd();
}

// 400000000004FDC0: define coproc_unsetvars
define coproc_unsetvars
{
	word64 r1;
	<anonymous> * b2;
	int64 * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	int64 r14 = *r32;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	int64 r37 = r14 + 0x00;
	Eq_n p06 = 0x00 == r14;
	Eq_n p07 = 0x00 != r14;
	<anonymous> * b0;
	if (!p06)
	{
		b0();
		word64 r8;
		r37 = r8 + 0x10;
		r1 = r36 + 0x00;
		int32 v17 = (int32) r37;
		r37 = (int64) v17;
		b0();
		r1 = r36 + 0x00;
		word64 r38 = 0x00 + 1;
		word64 r39 = 0x00 + -1;
		int64 r41 = *r32;
		word64 r33 = r8 + 0x00;
		r37 = r8 + 0x00;
		struct Eq_n * r40 = r1 + -0x0CC4;
		r40 = r40->ptr0000;
		b0();
		r1 = r36 + 0x00;
		r37 = r33 + 0x00;
		b0();
		r1 = r36 + 0x00;
		r37 = *r32;
		b0();
		r1 = r36 + 0x00;
		r37 = r33 + 0x00;
		b0();
		r1 = r36 + 0x00;
	}
	ar.pfs = r35;
	b0 = r34;
}

// 400000000004FF00: define coproc_dispose
// Called from:
//      coproc_reap
//      coproc_flush
define coproc_dispose
{
	word64 r1;
	<anonymous> * b1;
	word64 ** r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 * r36 = r32;
	<anonymous> * b0;
	if (!p06)
	{
		b0();
		r36 = *r32;
		r1 = r35 + 0x00;
		p06 = null == r36;
		p07 = null != r36;
		if (!p06)
		{
			b0();
			r1 = r35 + 0x00;
		}
		r36 = r32;
		b0();
		word64 * r15 = r32;
		word32 * r14 = 0x00 + -1;
		ptr64 r20 = (char *) r32 + 16;
		ptr64 r19 = (char *) r32 + 0x0C;
		ptr64 r18 = (char *) r32 + 24;
		ptr64 r17 = (char *) r32 + 20;
		ptr64 r16 = (char *) r32 + 32;
		word64 r8;
		*r15 = r8;
		++r15;
		r32 = (word64 **) ((char *) r32 + 28);
		r1 = r35 + 0x00;
		*r14 = (word32) r20;
		*r14 = (word32) r15;
		*r14 = (word32) r19;
		*r14 = (word32) r18;
		*r14 = (word32) r17;
		word32 * r0;
		*r0 = (word32) r16;
		*r0 = (word32) r32;
	}
	ar.pfs = r34;
	b0 = r33;
}

// 4000000000050040: define coproc_reap
define coproc_reap
{
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	word64 r32 = r1 + -21372;
	word32 * r14 = r32 + 0x1C;
	word32 v9 = *r14;
	r14 = (word64) v9;
	word64 p06;
	if (p06)
		return;
	word64 r2 = ar.pfs;
	coproc_dispose();
}

// 40000000000500C0: define coproc_flush
define coproc_flush
{
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	word64 r32 = r1 + -21372;
	word64 r2 = ar.pfs;
	coproc_dispose();
}

// 4000000000050100: define setup_async_signals
define setup_async_signals
{
	<anonymous> * b0;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	word32 * r14 = r1 + 5868;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	ar.pfs = r33;
	b0 = r32;
	word32 v11 = *r14;
	r14 = (word64) v11;
	word32 v12 = (word32) 0x00;
	word32 v13 = (word32) r14;
	Eq_n p07 = v12 == v13;
	Eq_n p06 = v12 != v13;
	if (p07)
	{
		word64 r36 = 0x00 + 1;
		word64 r35 = 0x00 + 2;
		b0();
		r1 = r34 + 0x00;
		r35 = 0x00 + 2;
		b0();
		r1 = r34 + 0x00;
		r36 = 0x00 + 1;
		r35 = 0x00 + 3;
		b0();
		r1 = r34 + 0x00;
		r35 = 0x00 + 3;
		b0();
		r1 = r34 + 0x00;
		ar.pfs = r33;
		b0 = r32;
	}
}

// 40000000000501C0: define shell_execve
define shell_execve
{
	word32 * r8;
	Eq_n LC;
	word64 r34;
	word64 r33;
	word64 r32;
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r42 = ar.pfs;
	word64 r12 = r12 + ~0x4F;
	word64 r43 = r1 + 0x00;
	<anonymous> * r41 = b1;
	Eq_n r45 = r32 + 0x00;
	Eq_n r46 = r33 + 0x00;
	union Eq_n * r47 = r34 + 0x00;
	Eq_n r44 = LC;
	<anonymous> * b0;
	b0();
	r1 = r43 + 0x00;
	b0();
	r1 = r43 + 0x00;
	word32 v21 = *r8;
	word32 * r35 = (word64) v21;
	word32 * r36 = r8;
	r45 = r32 + 0x00;
	Eq_n r14 = r1 + 7676;
	Eq_n r15 = __ld_acquire<word32>(r14);
	word32 v26 = (word32) 0x00;
	word32 v27 = (word32) r15;
	Eq_n p06 = v26 == v27;
	Eq_n p07 = v26 != v27;
	word64 pr;
	union Eq_n * r0;
	Eq_n r16;
	if (p07)
	{
		r45 = __ld_acquire<word32>(r14);
		b0();
		r1 = r43 + 0x00;
		r45 = r32 + 0x00;
		word32 v32 = (word32) 0x08;
		word32 v33 = (word32) r35;
		p06 = v32 == v33;
		p07 = v32 != v33;
		if (p07)
		{
l4000000000050260:
			b0();
			r1 = r43 + 0x00;
			word32 v34 = (word32) 0x00;
			word32 v35 = (word32) r8;
			p06 = v34 == v35;
			p07 = v34 != v35;
			word64 p32;
			if (p07)
			{
				r46 = r1 + -0x0CBC;
				r47 = 0x00 + 5;
				r45 = 0x00 + 0x00;
				r46 = *r46;
				b0();
				r1 = r43 + 0x00;
				r36 = r8;
				r45 = 0x00 + 21;
				b0();
				r1 = r43 + 0x00;
				r47 = (union Eq_n *) r8;
				r45.u2 = r36;
				r46 = r32 + 0x00;
				b0();
				word32 v40 = (word32) 0x02;
				word32 v41 = (word32) r35;
				p06 = v40 == v41;
				p07 = v40 != v41;
				r1 = r43 + 0x00;
				if (p06)
					r8 = 0x00 + 0x007F;
				if (p07)
					r8 = 0x00 + 0x007E;
				if (p32)
					__break();
			}
			r45 = r32 + 0x00;
			b0();
			word32 v38 = (word32) 0x00;
			word32 v39 = (word32) r8;
			p07 = v38 == v39;
			p06 = v38 != v39;
			r1 = r43 + 0x00;
			word64 p05;
			if (p07)
			{
l4000000000050360:
				*r35 = (word32) r36;
				r45 = r32 + 0x00;
				b0();
				word32 v47 = (word32) 0x02;
				word32 v48 = (word32) r35;
				p06 = v47 == v48;
				p07 = v47 != v48;
				r1 = r43 + 0x00;
				if (p06)
					r8 = 0x00 + 0x007F;
				word64 p04;
				if (p04)
					pr = 0x00;
				Eq_n v58;
				v58.u0 = r0->u0;
				r32 = (word64) v58;
				if (p05)
					__break();
				__break();
				word64 p56;
				if (p56)
					__break();
			}
			word32 v45 = (word32) 0x0C;
			word32 v46 = (word32) r35;
			p07 = v45 == v46;
			p06 = v45 != v46;
			if (p07)
				goto l4000000000050360;
			r45 = r32 + 0x00;
			r46 = 0x00 + 0x00;
			b0();
			int32 v49 = (word32) r8;
			int32 v50 = (word32) 0x00;
			p06 = v49 < v50;
			p07 = v49 >= v50;
			r1 = r43 + 0x00;
			word32 * r37 = r8;
			r46 = r12 + 0x10;
			r47 = 0x00 + 80;
			if (p06)
				goto l4000000000050360;
			r45.u2 = r8;
			b0();
			r1 = r43 + 0x00;
			word32 * r38 = r8;
			r45.u2 = r37;
			b0();
			r15 = r12 + 0x10;
			r1 = r43 + 0x00;
			int32 v56 = (word32) 0x02;
			int32 v57 = (word32) r38;
			p07 = v56 < v57;
			p06 = v56 >= v57;
			if (p06)
				goto l4000000000050360;
			Eq_n v61;
			v61.u0 = r15.u3->t0000.u0;
			r14.u2 = (word64) v61;
			int8 v62 = (int8) r14;
			r14.u2 = (int64) v62;
			word32 v63 = (word32) 0x23;
			word32 v64 = (word32) r14;
			p07 = v63 == v64;
			p06 = v63 != v64;
			if (!p07)
				goto l4000000000050360;
			r14 = r12 + 0x11;
			Eq_n v67;
			v67.u0 = r14.u3->t0000.u0;
			r14.u2 = (word64) v67;
			int8 v68 = (int8) r14;
			r14.u2 = (int64) v68;
			word32 v69 = (word32) 33;
			word32 v70 = (word32) r14;
			p07 = v69 == v70;
			p06 = v69 != v70;
			if (p06)
				goto l4000000000050360;
			if (p07)
				r14.u2 = (char *) r38 - 3;
			word64 p01;
			if (p01)
				__break();
			if (p05)
				__break();
			__break();
			__break();
			while (true)
			{
				__break();
				if (p32)
					__break();
				int8 v76 = (int8) r14;
				r14.u2 = (int64) v76;
				word32 v77 = (word32) 0x20;
				word32 v78 = (word32) r14;
				p06 = v77 == v78;
				p07 = v77 != v78;
				if (p07)
					break;
				r46.u0 = (word32) r46 + 1;
				if (LC == 0x00)
					goto l4000000000050AA0;
				--LC;
			}
			int32 v79 = (word32) r46;
			int32 v80 = (word32) r38;
			p07 = v79 < v80;
			p06 = v79 >= v80;
			r16 = r12 + 0x10;
			int32 v81 = (int32) r46;
			r15.u2 = (int64) v81;
			r47 = (union Eq_n *) r46.u1;
			if (!p06)
			{
				word32 v87 = (word32) 0x0A;
				word32 v88 = (word32) r14;
				p06 = v87 == v88;
				p07 = v87 != v88;
				r14 = r46 - r38;
				r15.u2 = r15 + r16;
				r47 = (union Eq_n *) ((char *) r47 + 1);
				if (!p06)
				{
					r14 = __addp4(0x00, r14);
					LC = r14;
					if (LC != 0x00)
					{
						--LC;
						Eq_n v90;
						v90.u0 = r15.u3->t0000.u0;
						r14.u2 = (word64) v90;
						r15.u2 = &r15.u3->ptr0001;
						int8 v91 = (int8) r14;
						r14.u2 = (int64) v91;
						word32 v92 = (word32) 0x09;
						word32 v93 = (word32) r14;
						p07 = v92 == v93;
						p06 = v92 != v93;
						word32 v94 = (word32) 0x20;
						word32 v95 = (word32) r14;
						Eq_n p09 = v94 == v95;
						Eq_n p08 = v94 != v95;
						if (p06)
						{
							word64 r17 = 0x00 + 1;
						}
					}
					r45 = r12 + 0x10;
					b0();
					r1 = r43 + 0x00;
					r37 = r8;
					r45.u2 = r8;
					b0();
					int32 v99 = (int32) r8;
					r38 = (int64) v99;
					*r35 = (word32) r36;
					r1 = r43 + 0x00;
					r35 = (word32 *) ((char *) r38 - 1);
					r14.u2 = r35 + r37;
					byte v100 = r14.u3->t0000.u0;
					r14.u2 = (word64) v100;
					int8 v101 = (int8) r14;
					r14.u2 = (int64) v101;
					word32 v102 = (word32) 0x0D;
					word32 v103 = (word32) r14;
					p07 = v102 == v103;
					p06 = v102 != v103;
					if (p06)
					{
l4000000000050B30:
						r46 = r1 + -3252;
						r45 = 0x00 + 0x00;
						r47 = 0x00 + 5;
						r46 = *r46;
						b0();
						p07 = null == r37;
						p06 = null != r37;
						r45.u2 = r8;
						r1 = r43 + 0x00;
						r46 = r32 + 0x00;
						r47 = (union Eq_n *) r37;
						if (!p07)
						{
							b0();
							r1 = r43 + 0x00;
							r45.u2 = r37;
							b0();
							r8 = 0x00 + 0x007E;
							r1 = r43 + 0x00;
							ar.pfs = r42;
							LC = r44;
							b0 = r41;
							r12 += 0x50;
							return;
						}
						else
						{
							r47 = r1 + -3348;
							r46 = r32 + 0x00;
							r47 = r47->u0;
							b0();
							r8 = 0x00 + 0x007E;
							r1 = r43 + 0x00;
							ar.pfs = r42;
							LC = r44;
							b0 = r41;
							r12 += 0x50;
							return;
						}
					}
l4000000000050BC0:
					r46.u1 = (char *) r8 + 2;
					r45.u2 = r37;
					int32 v89 = (int32) r46;
					r46.u1 = (int64) v89;
					b0();
					r14 = 0x00 + 94;
					r35 += r8;
					r38 += r8;
					r1 = r43 + 0x00;
					r37 = r8;
					r14.u3->t0000.u0 = (byte) (byte) r35;
					r14 = 0x00 + 77;
					*r38 = (word32) (byte) r1;
					r38 = (word32 *) ((char *) r38 + 1);
					r0->u0 = (byte) (byte) r38;
					goto l4000000000050B30;
				}
			}
l4000000000050AA0:
			r47 = (union Eq_n *) r46.u1;
			r45 = r12 + 0x10;
			b0();
			r1 = r43 + 0x00;
			r37 = r8;
			r45.u2 = r8;
			b0();
			int32 v82 = (int32) r8;
			r38 = (int64) v82;
			*r35 = (word32) r36;
			r1 = r43 + 0x00;
			r35 = (word32 *) ((char *) r38 - 1);
			r14.u2 = r35 + r37;
			Eq_n v83;
			v83.u0 = r14.u3->t0000.u0;
			r14.u2 = (word64) v83;
			int8 v84 = (int8) r14;
			r14.u2 = (int64) v84;
			word32 v85 = (word32) 0x0D;
			word32 v86 = (word32) r14;
			p07 = v85 == v86;
			p06 = v85 != v86;
			if (!p07)
				goto l4000000000050B30;
			goto l4000000000050BC0;
		}
	}
	else
	{
		word32 v30 = (word32) 0x08;
		word32 v31 = (word32) r35;
		p06 = v30 == v31;
		p07 = v30 != v31;
		if (!p06)
			goto l4000000000050260;
	}
	r46 = 0x00 + 0x00;
	b0();
	int32 v36 = (word32) r8;
	int32 v37 = (word32) 0x00;
	p06 = v36 < v37;
	p07 = v36 >= v37;
	r1 = r43 + 0x00;
	r35 = r8;
	r45.u2 = r8;
	r46 = r12 + 0x10;
	if (!p06)
	{
		r47 = 0x00 + 80;
		b0();
		r1 = r43 + 0x00;
		r36 = r8;
		r45.u2 = r35;
		b0();
		word32 v72 = (word32) 0x00;
		word32 v73 = (word32) r36;
		p06 = v72 == v73;
		p07 = v72 != v73;
		r1 = r43 + 0x00;
		if (p06)
			r8 = 0x00 + 0x00;
		__break();
		pr = 0x00;
	}
	else
	{
		b0();
		r1 = r43 + 0x00;
		r14 = r1 + 9148;
		r0->u1 = (word32) (word32) r14;
		b0();
		r1 = r43 + 0x00;
		b0();
		r1 = r43 + 0x00;
		b0();
		r1 = r43 + 0x00;
		b0();
		r1 = r43 + 0x00;
		b0();
		r1 = r43 + 0x00;
		b0();
		r1 = r43 + 0x00;
		r45 = 0x00 + 0x00;
		r14 = r1 + 7172;
		r15.u2 = *r14.u2;
		r16.u0 = (word32) r15 + 0x0C;
		Eq_n v44;
		v44.u1 = r16.u1->u1;
		r16.u1 = (word64) v44;
		if (p07)
			r15.u1 = (word32) r15 + 24;
		if (p07)
			r15.u2 = *r15.u2;
	}
}

// 4000000000053C40: define execute_command_internal
define execute_command_internal
{
	word32 * r65;
	<anonymous> * b4;
	word64 LC;
	word64 pr;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r85 = ar.pfs;
	word64 r12 = r12 + ~0x2F;
	word32 * r41 = r1 + 8360;
	word32 * r45 = r1 + 8356;
	word64 r87 = pr;
	word64 r88 = LC;
	Eq_n r47 = r1 + 7676;
	Eq_n r48 = r1 + 7684;
	word64 r86 = r1 + 0x00;
	<anonymous> * r84 = b4;
	word32 v19 = *r41;
	Eq_n r14;
	r14.u2 = (word64) v19;
	word32 v21 = (word32) 0x00;
	word32 v22 = (word32) r14;
	Eq_n p07 = v21 == v22;
	Eq_n p06 = v21 != v22;
	Eq_n r8;
	<anonymous> * b0;
	if (p06)
	{
l40000000000542E0:
		r14 = r1 + 9044;
		Eq_n v28;
		v28.u1 = r14.u3->t0000.u1;
		r8.u1 = (word64) v28;
		pr = r87;
		ar.pfs = r85;
		LC = r88;
		b0 = r84;
		r12 += 0x30;
		return;
	}
	word32 v25 = *r45;
	r14.u2 = (word64) v25;
	word32 v26 = (word32) 0x00;
	word32 v27 = (word32) r14;
	p06 = v26 == v27;
	p07 = v26 != v27;
	r14 = r1 + 7392;
	if (p07)
		goto l40000000000542E0;
	union Eq_n * r32;
	p06 = null == r32;
	p07 = null != r32;
	if (p06)
	{
l4000000000054430:
		r8 = 0x00 + 0x00;
		pr = r87;
		ar.pfs = r85;
		LC = r88;
		b0 = r84;
		r12 += 0x30;
		return;
	}
	Eq_n v32;
	v32.u1 = r14.u3->t0000.u1;
	r14.u2 = (word64) v32;
	word32 v33 = (word32) 0x00;
	word32 v34 = (word32) r14;
	p07 = v33 == v34;
	p06 = v33 != v34;
	if (p06)
		goto l4000000000054430;
	r14 = __ld_acquire<word32>(r47);
	word32 v35 = (word32) 0x00;
	word32 v36 = (word32) r14;
	p06 = v35 == v36;
	p07 = v35 != v36;
	Eq_n r89;
	word32 * r38;
	Eq_n r37;
	Eq_n r15;
	Eq_n r51;
	Eq_n r16;
	Eq_n r39;
	Eq_n r53;
	if (p07)
	{
		r89 = __ld_acquire<word32>(r47);
		b0();
		r1 = r86 + 0x00;
		r48 = r1 + 7684;
		r14 = __ld_acquire<word32>(r48);
		word32 v40 = (word32) 0x00;
		word32 v41 = (word32) r14;
		p06 = v40 == v41;
		p07 = v40 != v41;
		if (p06)
		{
l4000000000053D40:
			r38 = r1 + 7404;
			r37.u2 = (char *) r32 + 4;
			b0();
			r1 = r86 + 0x00;
			Eq_n v44;
			v44.u1 = r37.u3->t0000.u1;
			r15.u2 = (word64) v44;
			r51 = r1 + 7084;
			bool v47 = SLICE(r15, bool, 2);
			r14.u2 = (word64) v47;
			word32 v48 = *r38;
			r16.u2 = (word64) v48;
			r32->u2 = (word64 *) r51;
			word32 v50 = (word32) 0x00;
			word32 v51 = (word32) r16;
			p06 = v50 == v51;
			p07 = v50 != v51;
			r39.u1 = r14.u2;
			r53.u1 = r14.u2;
			if (p06)
				goto l4000000000053DC0;
			goto l4000000000053DA0;
		}
	}
	else
	{
		r14 = __ld_acquire<word32>(r48);
		word32 v37 = (word32) 0x00;
		word32 v38 = (word32) r14;
		p06 = v37 == v38;
		p07 = v37 != v38;
		if (!p07)
			goto l4000000000053D40;
	}
	r37.u2 = (char *) r32 + 4;
	b0();
	r1 = r86 + 0x00;
	r38 = r1 + 7404;
	b0();
	r1 = r86 + 0x00;
	Eq_n v54;
	v54.u1 = r37.u3->t0000.u1;
	r15.u2 = (word64) v54;
	r51 = r1 + 7084;
	bool v55 = SLICE(r15, bool, 2);
	r14.u2 = (word64) v55;
	word32 v56 = *r38;
	r16.u2 = (word64) v56;
	r32->u2 = (word64 *) r51;
	word32 v57 = (word32) 0x00;
	word32 v58 = (word32) r16;
	p06 = v57 == v58;
	p07 = v57 != v58;
	r39.u1 = r14.u2;
	r53.u1 = r14.u2;
	if (p06)
	{
l4000000000053DC0:
		goto l4000000000053DC2;
	}
l4000000000053DA0:
	word32 v59 = (word32) 0x00;
	word32 v60 = (word32) r14;
	p06 = v59 == v60;
	p07 = v59 != v60;
	if (p07)
		r15 |= 0x08;
	if (p07)
		r15.u3->t0000.u1 = (word32) r37;
	__break();
	__break();
l4000000000053DC2:
	r16.u0 = 0x40FFFFFFFF;
	r15.u2 = r32->u2;
	r15 &= r16;
	r16.u0 = 0x400000000D;
	p07 = r16 == r15;
	p06 = r16 != r15;
	Eq_n r90;
	word64 r33;
	Eq_n r91;
	word64 r34;
	word64 r92;
	word64 r35;
	word64 r93;
	word64 r36;
	if (p07)
	{
		r89.u2 = &r32->u0;
		r90 = r33 + 0x00;
		r91 = r34 + 0x00;
		r92 = r35 + 0x00;
		r93 = r36 + 0x00;
		b0();
		r1 = r86 + 0x00;
		pr = r87;
		ar.pfs = r85;
		LC = r88;
		b0 = r84;
		r12 += 0x30;
		return;
	}
	Eq_n v69;
	v69.u1 = r32->u1;
	r14.u2 = (word64) v69;
	word32 v70 = (word32) 0x0E;
	word32 v71 = (word32) r14;
	p07 = v70 == v71;
	p06 = v70 != v71;
	Eq_n r17;
	union Eq_n * r40;
	union Eq_n * r0;
	word32 * r42;
	word32 * r52;
	if (p07)
	{
		r37 = r1 + -21372;
		r89 = r1 + -0x0C44;
		r14.u1 = (word32) r37 + 8;
		Eq_n v74;
		v74.u1 = r14.u3->t0000.u1;
		r90.u1 = (word64) v74;
		word32 v75 = (word32) ~0x00;
		word32 v76 = (word32) r90;
		p06 = v75 == v76;
		p07 = v75 != v76;
		if (!p06)
		{
			r89.u2 = *r89.u2;
			r91.u2 = *r37.u2;
			b0();
			r1 = r86 + 0x00;
		}
		r15.u2 = r37.u2;
		ptr64 r20 = (ptr64) ((word32) r37 + 16);
		ptr64 r19 = (ptr64) ((word32) r37 + 0x0C);
		ptr64 r18 = (ptr64) ((word32) r37 + 24);
		r17 = (word32) r37 + 20;
		r14 = 0x00 + -1;
		*r15.u2 = (word64) r8;
		r15.u1 = (word32) r15 + 8;
		r14.u3->t0000.u1 = (word32) (word32) r20;
		r16.u1 = (word32) r37 + 32;
		r37.u1 = (word32) r37 + 28;
		r40 = r12 + 0x18;
		r89.u2 = &r32->u0;
		r14.u3->t0000.u1 = (word32) (word32) r19;
		r14.u3->t0000.u1 = (word32) (word32) r18;
		r38 = r12 + 0x10;
		r14.u3->t0000.u1 = (word32) (word32) r17;
		r14.u3->t0000.u1 = (word32) (word32) r15;
		r14 = r1 + 0x00001B1C;
		r0->u1 = (word32) (word32) r16;
		r0->u1 = (word32) (word32) r37;
		r0->u1 = (word32) (word32) r14;
		b0();
		r89.u2 = &r40->u0;
		r37.u2 = r8.u1;
		r1 = r86 + 0x00;
		b0();
		r1 = r86 + 0x00;
		r89 = r12 + 0x10;
		b0();
		r89.u2 = r37.u2;
		r1 = r86 + 0x00;
		b0();
		r1 = r86 + 0x00;
		r89.u1 = (word32) r8 + 1;
		b0();
		r90.u1 = r37.u2;
		r1 = r86 + 0x00;
		r89.u2 = r8.u1;
		b0();
		r90 = 0x00 + 1;
		r1 = r86 + 0x00;
		r89.u2 = r8.u1;
		b0();
		r14 = r12 + 0x1C;
		word32 v88 = (word32) 0x00;
		word32 v89 = (word32) r8;
		p07 = v88 == v89;
		p06 = v88 != v89;
		r1 = r86 + 0x00;
		r39.u1 = r8.u1;
		if (p07)
		{
			Eq_n v93;
			v93.u1 = r40->u1;
			r89.u2 = (word64) v93;
			b0();
			r14 = r12 + 0x14;
			r1 = r86 + 0x00;
			Eq_n v94;
			v94.u1 = r14.u3->t0000.u1;
			r89.u2 = (word64) v94;
			b0();
			r14 = r12 + 0x10;
			r90 = 0x00 + 1;
			r93 = r36 + 0x00;
			r1 = r86 + 0x00;
			r89.u2 = &r32->u0;
			Eq_n v95;
			v95.u1 = r14.u3->t0000.u1;
			r91.u2 = (word64) v95;
			r14 = r12 + 0x1C;
			Eq_n v96;
			v96.u1 = r14.u3->t0000.u1;
			r92 = (word64) v96;
			b0();
			r1 = r86 + 0x00;
			r37.u2 = r8.u1;
			r14 = r1 + -10260;
			r14.u2 = *r14.u2;
			r89.u2 = *r14.u2;
			b0();
			r1 = r86 + 0x00;
			r14 = r1 + -0x0000299C;
			r14.u2 = *r14.u2;
			r89.u2 = *r14.u2;
			b0();
			r1 = r86 + 0x00;
			r89.u2 = r37.u2;
			b0();
			do
			{
				r14 = r1 + 9044;
				r15 = 0x00 + 1;
				r89 = 0x00 + 1;
				r15.u3->t0000.u1 = (word32) r14;
				b0();
				word32 v97 = *r8.u1;
				r14 = r1 + 6512;
				if (p06)
					break;
				Eq_n v138;
				v138.u1 = r14.u3->t0000.u1;
				r14.u2 = (word64) v138;
				word32 v139 = (word32) 0x00;
				word32 v140 = (word32) r14;
				p07 = v139 == v140;
				p06 = v139 != v140;
				r14 = r1 + 6456;
				if (p06)
					break;
				Eq_n v147;
				v147.u1 = r14.u3->t0000.u1;
				r14.u2 = (word64) v147;
				word32 v148 = (word32) 0x00;
				word32 v149 = (word32) r14;
				p06 = v148 == v149;
				p07 = v148 != v149;
			} while (p07);
			r41 = r1 + 9044;
			word64 r54;
			r89 = r54 + 0x00;
			r42 = 0x00 + 1;
			b0();
			r1 = r86 + 0x00;
			r89 = r1 + -0x0C2C;
			r89.u2 = *r89.u2;
			b0();
			word32 v112 = *r65;
			r14.u2 = (word64) v112;
			r1 = r86 + 0x00;
			word32 * r68;
			*r68 = (word32) r52;
			r14.u1 = (word32) r14 - 1;
			r14.u3->t0000.u1 = (word32) (word32) r65;
			goto l40000000000541A0;
		}
		Eq_n v98;
		v98.u1 = r14.u3->t0000.u1;
		r89.u2 = (word64) v98;
		r32 = (union Eq_n *) ((char *) r32 + 24);
		b0();
		word32 v99 = *r38;
		r89.u2 = (word64) v99;
		++r38;
		r1 = r86 + 0x00;
		b0();
		r14.u2 = r32->u2;
		r1 = r86 + 0x00;
		r90.u1 = r39.u1;
		r14.u1 = (word32) r14 + 8;
		r89.u2 = *r14.u2;
		b0();
		Eq_n v100;
		v100.u1 = r40->u1;
		r14.u2 = (word64) v100;
		r16.u1 = (word32) r8 + 0x0C;
		r40 = (union Eq_n *) ((word32) r8 + 16);
		r1 = r86 + 0x00;
		r37.u2 = r8.u1;
		r90 = 0x00 + 2;
		word32 v101 = *r38;
		r15.u2 = (word64) v101;
		r89.u2 = r14.u2;
		r14.u3->t0000.u1 = (word32) (word32) r16;
		r91 = 0x00 + 1;
		r15.u3->t0000.u1 = (word32) r40;
		b0();
		r91 = 0x00 + 1;
		r90 = 0x00 + 2;
		r1 = r86 + 0x00;
		Eq_n v102;
		v102.u1 = r40->u1;
		r89.u2 = (word64) v102;
		b0();
		r1 = r86 + 0x00;
		r89.u2 = r37.u2;
		b0();
		r89 = r34 + 0x00;
		r90 = r35 + 0x00;
		r1 = r86 + 0x00;
		b0();
		r1 = r86 + 0x00;
		b0();
		r1 = r86 + 0x00;
		r89 = 0x00 + 1;
		r90 = 0x00 + 0x00;
		b0();
		r1 = r86 + 0x00;
		r14 = r1 + 6516;
		Eq_n v103;
		v103.u1 = r14.u3->t0000.u1;
		r14.u2 = (word64) v103;
		word32 v104 = (word32) 0x00;
		word32 v105 = (word32) r14;
		p06 = v104 == v105;
		p07 = v104 != v105;
		if (p06)
			goto l4000000000054600;
		goto l40000000000546A0;
	}
	word32 v72 = (word32) 0x0D;
	word32 v73 = (word32) r14;
	p06 = v72 == v73;
	p07 = v72 != v73;
	if (p06)
	{
		r42 = 0x00 + 1;
		goto l4000000000054330;
	}
	Eq_n v141;
	v141.u1 = r37.u3->t0000.u1;
	r15.u2 = (word64) v141;
	r16 = r15 & 0x03;
	r42 = r15 & 0x01;
	word32 v142 = (word32) 0x00;
	word32 v143 = (word32) r16;
	p07 = v142 == v143;
	p06 = v142 != v143;
	if (p06)
		goto l4000000000054330;
	up32 v150 = (word32) 0x0C;
	up32 v151 = (word32) r14;
	p06 = v150 < v151;
	p07 = v150 >= v151;
	Eq_n p08;
	if (!p06)
	{
		r17 = 0x00 + 1;
		int32 v158 = (int32) r14;
		r16.u2 = (int64) v158;
		r17 <<= r16;
		r16 = 0x00 + 8111;
		r16 = r17 & r16;
		Eq_n p09 = 0x00 == r16;
		p08 = 0x00 != r16;
		if (!p09)
		{
			word32 v161 = (word32) ~0x00;
			word32 v162 = (word32) r34;
			p09 = v161 == v162;
			p08 = v161 != v162;
			word64 r61;
			if (!p08)
			{
				word32 v163 = (word32) 0x00;
				word32 v164 = (word32) r33;
				p08 = v163 == v164;
				p09 = v163 != v164;
				if (!p09)
				{
					if (!p08)
					{
l4000000000053EE0:
						if (!p06)
						{
							r15 = 0x00 + 1;
							int32 v165 = (int32) r14;
							r14.u2 = (int64) v165;
							r15 <<= r14;
							r14 = 0x00 + 8111;
							r14 = r15 & r14;
							p07 = 0x00 == r14;
							p06 = 0x00 != r14;
							if (!p07)
							{
								r40 = (union Eq_n *) ((char *) r32 + 16);
								r89.u2 = r40->u2;
								p07 = 0x00 == r89;
								p06 = 0x00 != r89;
								if (!p07)
								{
									b0();
									r1 = r86 + 0x00;
									r89.u2 = r40->u2;
									r14 = r1 + 9048;
									*r8.u1 = (word32) r14;
								}
l4000000000053F80:
								r90 = 0x00 + 3;
								b0();
								r1 = r86 + 0x00;
								word32 v166 = (word32) 0x00;
								word32 v167 = (word32) r8;
								p06 = v166 == v167;
								p07 = v166 != v167;
								if (!p07)
								{
									r40 = r1 + 7068;
									r89.u2 = r40->u2;
									p06 = 0x00 == r89;
									p07 = 0x00 != r89;
									if (p06)
										r61 = 0x00 + 0x00;
								}
								else
								{
									r37 = r1 + 7068;
									r89.u2 = *r37.u2;
									b0();
									r1 = r86 + 0x00;
									r0->u2 = (word64 *) r37;
									b0();
									r1 = r86 + 0x00;
									r15 = 0x00 + 1;
									r8 = 0x00 + 1;
									r14 = r1 + 9044;
									r15.u3->t0000.u1 = (word32) r14;
									pr = r87;
									ar.pfs = r85;
									LC = r88;
									b0 = r84;
									r12 += 0x30;
									return;
								}
							}
						}
						r14.u2 = (char *) r32 + 16;
						r89.u2 = *r14.u2;
						goto l4000000000053F80;
					}
					goto l4000000000054D70;
				}
			}
l4000000000054330:
			r52 = r1 + 6648;
			r40 = r1 + 0x00001BB4;
			r89.u2 = &r32->u0;
			word32 v80 = *r52;
			r14.u2 = (word64) v80;
			r14.u3->t0000.u1 = (word32) (word32) r40;
			b0();
			r1 = r86 + 0x00;
			r89.u2 = r8.u1;
			b0();
			r1 = r86 + 0x00;
			r89.u1 = (word32) r8 + 1;
			b0();
			r1 = r86 + 0x00;
			r39.u1 = r8.u1;
			r89.u2 = &r32->u0;
			b0();
			r89.u2 = r39.u1;
			r1 = r86 + 0x00;
			r90.u1 = r8.u1;
			b0();
			r1 = r86 + 0x00;
			r89.u2 = r8.u1;
			r90 = r33 + 0x00;
			b0();
			word32 v81 = (word32) 0x00;
			word32 v82 = (word32) r8;
			p07 = v81 == v82;
			p06 = v81 != v82;
			r1 = r86 + 0x00;
			r39.u1 = r8.u1;
			r89 = r34 + 0x00;
			r90 = r35 + 0x00;
			ui64 r44;
			if (p07)
			{
				r90 = r33 + 0x00;
				r91 = r34 + 0x00;
				r92 = r35 + 0x00;
				r93 = r36 + 0x00;
				r89.u2 = &r32->u0;
				b0();
				r1 = r86 + 0x00;
				r89.u2 = r8.u1;
				b0();
				Eq_n v90;
				v90.u1 = r37.u3->t0000.u1;
				r89.u2 = (word64) v90;
				b0();
				r1 = r86 + 0x00;
				r42 = r8.u1;
				word32 v106 = (word32) 0x00;
				word32 v107 = (word32) r45;
				p06 = v106 == v107;
				p07 = v106 != v107;
				if (p07)
				{
					word32 v114 = (word32) ~0x00;
					word32 v115 = (word32) r34;
					p06 = v114 == v115;
					p07 = v114 != v115;
					byte v116 = (byte) r39;
					r39.u1 = (word64) v116;
					if (p06)
						r15 = 0x00 + 1;
				}
				r41 = r1 + 9044;
				byte v132 = (byte) r39;
				r39.u1 = (word64) v132;
				r39 = r44 | r39;
				word32 v133 = (word32) 0x00;
				word32 v134 = (word32) r39;
				p07 = v133 == v134;
				p06 = v133 != v134;
				if (!p06)
				{
					r14 = r1 + 6456;
					Eq_n v135;
					v135.u1 = r14.u3->t0000.u1;
					r14.u2 = (word64) v135;
					word32 v136 = (word32) 0x00;
					word32 v137 = (word32) r14;
					p06 = v136 == v137;
					p07 = v136 != v137;
					if (!p06)
					{
						r14 = r1 + 6516;
						Eq_n v168;
						v168.u1 = r14.u3->t0000.u1;
						r14.u2 = (word64) v168;
						word32 v169 = (word32) 0x00;
						word32 v170 = (word32) r14;
						p07 = v169 == v170;
						p06 = v169 != v170;
						if (!p06)
						{
							r14 = r1 + 0x00001BB8;
							Eq_n v171;
							v171.u1 = r14.u3->t0000.u1;
							r14.u2 = (word64) v171;
							word32 v172 = (word32) 0x00;
							word32 v173 = (word32) r14;
							p07 = v172 == v173;
							p06 = v172 != v173;
							if (p06)
							{
								*r42 = (word32) r41;
								b0();
								r1 = r86 + 0x00;
								r89 = 0x00 + 4;
								b0();
								r89 = 0x00 + 66;
								b0();
								word32 v174 = (word32) 0x00;
								word32 v175 = (word32) r8;
								p06 = v174 == v175;
								p07 = v174 != v175;
								r1 = r86 + 0x00;
								if (!p07)
								{
									if (p06)
										r48 = 0x00 + 0x00;
									Eq_n p42 = r16 < 0x00;
									p08 = r16 >= 0x00;
								}
								else
								{
									r89 = 0x00 + 66;
									byte v176 = (byte) r42;
									r44 = (word64) v176;
									b0();
									word32 v177 = (word32) 0x00;
									word32 v178 = (word32) r8;
									p06 = v177 == v178;
									p07 = v177 != v178;
									r1 = r86 + 0x00;
									if (p06)
										r8 = 0x00 + 1;
								}
							}
						}
					}
					word32 v144 = *r38;
					r14.u2 = (word64) v144;
					word32 v145 = (word32) 0x00;
					word32 v146 = (word32) r14;
					p06 = v145 == v146;
					p07 = v145 != v146;
					if (!p06)
					{
						word32 v152 = (word32) ~0x00;
						word32 v153 = (word32) r34;
						p08 = v152 == v153;
						p09 = v152 != v153;
						word32 v156 = (word32) ~0x00;
						word32 v157 = (word32) r35;
						p06 = v156 == v157;
						p07 = v156 != v157;
						if (p06)
							r35 = 0x00 + 1;
					}
				}
l40000000000541A0:
				word32 v123 = (word32) 0x00;
				word32 v124 = (word32) r61;
				p06 = v123 == v124;
				p07 = v123 != v124;
				if (!p06)
				{
					r90 = 0x00 + 1;
					word64 r60;
					r89 = r60 + 0x00;
					b0();
					r1 = r86 + 0x00;
					r89 = r60 + 0x00;
					b0();
					r1 = r86 + 0x00;
				}
				word64 p17;
				if (p17)
				{
					word64 r63;
					r89 = r63 + 0x00;
				}
			}
			b0();
			r1 = r86 + 0x00;
			b0();
			r1 = r86 + 0x00;
			word32 v91 = (word32) ~0x00;
			word32 v92 = (word32) r35;
			p07 = v91 == v92;
			p06 = v91 != v92;
			if (!p07)
				goto l4000000000054430;
			r89 = r33 + 0x00;
			r90 = 0x00 + 0x00;
			b0();
			r1 = r86 + 0x00;
			word32 v108 = (word32) 0x00;
			word32 v109 = (word32) r33;
			p07 = v108 == v109;
			p06 = v108 != v109;
			if (p07)
			{
				r89 = 0x00 + 66;
				b0();
				word32 v120 = (word32) 0x00;
				word32 v121 = (word32) r8;
				p06 = v120 == v121;
				p07 = v120 != v121;
				r1 = r86 + 0x00;
				if (!p07)
				{
					if (p06)
						r44 = 0x00 + 0x00;
					__break();
				}
				else
				{
					r89 = 0x00 + 66;
					b0();
					word32 v126 = (word32) 0x00;
					word32 v127 = (word32) r8;
					p06 = v126 == v127;
					p07 = v126 != v127;
					r1 = r86 + 0x00;
					if (p06)
						r8 = 0x00 + 1;
					if (p07)
						r8 = 0x00 + 0x00;
				}
			}
			r14 = r1 + 6516;
			Eq_n v117;
			v117.u1 = r14.u3->t0000.u1;
			r14.u2 = (word64) v117;
			word32 v118 = (word32) 0x00;
			word32 v119 = (word32) r14;
			p06 = v118 == v119;
			p07 = v118 != v119;
			if (!p07)
			{
l4000000000054600:
				b0();
				r1 = r86 + 0x00;
				r8 = 0x00 + 0x00;
				goto l4000000000054620;
			}
l40000000000546A0:
			r89.u2 = r39.u1;
			b0();
			r1 = r86 + 0x00;
			b0();
			r1 = r86 + 0x00;
			r8 = 0x00 + 0x00;
l4000000000054620:
			pr = r87;
			ar.pfs = r85;
			LC = r88;
			b0 = r84;
			r12 += 0x30;
			return;
		}
	}
	if (p08)
		goto l4000000000053EE0;
	word32 v159 = (word32) 0x00;
	word32 v160 = (word32) r33;
	p06 = v159 == v160;
	p07 = v159 != v160;
	if (!p06)
	{
		r15 |= 0x02;
		r89.u2 = &r32->u0;
		r90 = 0x00 + 1;
		r91 = r34 + 0x00;
		r92 = r35 + 0x00;
		r93 = r36 + 0x00;
		r15.u3->t0000.u1 = (word32) r37;
		b0();
		r1 = r86 + 0x00;
		pr = r87;
		ar.pfs = r85;
		LC = r88;
		b0 = r84;
		r12 += 0x30;
		return;
	}
l4000000000054D70:
	r89.u2 = &r32->u0;
	r90 = 0x00 + 0x00;
	r91 = r34 + 0x00;
	r92 = r35 + 0x00;
	r93 = r36 + 0x00;
	b0();
	r1 = r86 + 0x00;
	r0->u2 = (word64 *) r51;
	pr = r87;
	ar.pfs = r85;
	LC = r88;
	b0 = r84;
	r12 += 0x30;
}

// 400000000005B380: define execute_shell_function
define execute_shell_function
{
	word64 r8;
	<anonymous> * b5;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r38 = ar.pfs;
	struct Eq_n * r35 = r1 + -2988;
	<anonymous> * r37 = b5;
	word64 r39 = r1 + 0x00;
	r35 = r35->ptr0000;
	word64 * r40 = 0x00 + 32;
	<anonymous> * b0;
	b0();
	r1 = r39 + 0x00;
	word64 r34 = r8 + 0x00;
	r40 = &r35->ptr0000;
	b0();
	r1 = r39 + 0x00;
	word64 r41 = r34 + 0x00;
	r40 = r1 + -0x00002624;
	r40 = *r40;
	b0();
	word64 r33;
	r41 = r33 + 0x00;
	word64 r42 = 0x00 + 0x00;
	word64 r43 = r34 + 0x00;
	word64 r44 = 0x00 + 0x00;
	word64 r45 = 0x00 + 0x00;
	r1 = r39 + 0x00;
	word64 r32;
	r40 = r32 + 0x00;
	b0();
	r1 = r39 + 0x00;
	word64 r36 = r8 + 0x00;
	r40 = r34 + 0x00;
	b0();
	r1 = r39 + 0x00;
	r40 = &r35->ptr0000;
	b0();
	r8 = r36 + 0x00;
	r1 = r39 + 0x00;
	ar.pfs = r38;
	b0 = r37;
}

