// elf-Linux-ia64-bash_text_n.c
// Generated by decompiling elf-Linux-ia64-bash
// using Reko decompiler version 0.12.3.0.

#include "elf-Linux-ia64-bash.h"

// 400000000008CE00: define char_is_quoted
define char_is_quoted
{
	word64 r33;
	up64 r8;
	<anonymous> * b3;
	word64 r32;
	word64 r1;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r44 = ar.pfs;
	word64 r12 = r12 + ~0x2F;
	word64 r46 = pr;
	word64 r39 = r1 + 7548;
	word64 r45 = r1 + 0x00;
	word64 r47 = r32 + 0x00;
	Eq_n r40 = r12 + 0x30;
	word64 r37 = 0x00 + 0x00;
	<anonymous> * r43 = b3;
	word64 r34 = 0x00 + 0x00;
	Eq_n p16 = 0x00 == 0x00;
	Eq_n p17 = 0x00 != 0x00;
	word64 r41 = r12 + 0x18;
	union Eq_n * r0;
	r0->u1 = (struct Eq_n *) r40;
	<anonymous> * b0;
	b0();
	r1 = r45 + 0x00;
	struct Eq_n * r14 = 0x00 + 1;
	int64 r42 = r8 + 0x00;
	int32 v28 = (word32) r33;
	int32 v29 = (word32) 0x00;
	Eq_n p07 = v28 < v29;
	Eq_n p06 = v28 >= v29;
	struct Eq_n * r38 = r1 + -9996;
	r14->t0000.u0 = (word32) (word32) r39;
	if (!p07)
	{
		r38 = r38->ptr0000;
		int32 v33 = (int32) r34;
		int64 r36 = (int64) v33;
		byte * r35 = r36 + r32;
		byte v36 = *r35;
		r14 = (word64) v36;
		int8 v37 = (int8) r14;
		r14 = (int64) v37;
		byte * r48;
		if (!p16)
		{
			do
			{
				int32 v38 = (word32) r34;
				int32 v39 = (word32) r33;
				p06 = v38 < v39;
				p07 = v38 >= v39;
				r8 = 0x00 + 1;
				if (!p06)
				{
					r0->u0 = (word32) (word32) r39;
					pr = r46;
					ar.pfs = r44;
					b0 = r43;
					r12 += 0x30;
					return;
				}
				b0();
				r1 = r45 + 0x00;
				p07 = 0x01 < r8;
				p06 = 0x01 >= r8;
				if (p06)
				{
					++r34;
					goto l400000000008D2A2;
				}
				byte v48 = *r35;
				r14 = (word64) v48;
				int8 v49 = (int8) r14;
				r14 = (int64) v49;
				word3 v50 = SLICE(r14, word3, 5);
				ui64 r16 = (word64) v50;
				Eq_n r15 = r14 & 0x1F;
				r14 = (struct Eq_n *) ((char *) &r38->ptr0000 + (r16 << 0x02));
				Eq_n v53;
				v53.u0 = r14->t0000.u0;
				r14 = (word64) v53;
				r14 >>= r15;
				if (!p07)
				{
					if (p06)
						r14 = 0x00 + 1;
					__break();
					__break();
				}
				r15 = r12 + 0x28;
				r14 = r40.u1->ptr0000;
				r47 = 0x00 + 0x00;
				r48 = r35;
				int64 r49 = r36 - r42;
				word64 * r50 = &r40.u1->ptr0000;
				r14->t0000.u1 = (struct Eq_n *) r15;
				r37 = 0x00 + 0x00;
				b0();
				r14 = r8 + 0x02;
				r1 = r45 + 0x00;
				p06 = (struct Eq_n *) 0x01 < r14;
				p07 = (struct Eq_n *) 0x01 >= r14;
				if (p06)
				{
					p06 = 0x00 == r8;
					p07 = 0x00 != r8;
					if (p07)
						r14 = r8 + 0x00;
					__break();
					__break();
l400000000008D2A2:
					r37 = 0x00 + 0x00;
				}
				else
				{
					r15 = r12 + 0x28;
					++r34;
					r14 = r15.u1->ptr0000;
					r14->t0000.u1 = (struct Eq_n *) r40;
				}
				int32 v57 = (int32) r34;
				r36 = (int64) v57;
				int32 v58 = (word32) r33;
				int32 v59 = (word32) r34;
				p07 = v58 < v59;
				p06 = v58 >= v59;
				word32 v60 = (word32) 0x00;
				word32 v61 = (word32) r37;
				p16 = v60 == v61;
				p17 = v60 != v61;
				if (p07)
					goto l400000000008D440;
				r35 = r36 + r32;
			} while (p17);
			byte v64 = *r35;
			r14 = (word64) v64;
			int8 v65 = (int8) r14;
			r14 = (int64) v65;
		}
		word32 v40 = (word32) 0x5C;
		word32 v41 = (word32) r14;
		p07 = v40 == v41;
		p06 = v40 != v41;
		word32 v42 = (word32) 0x27;
		word32 v43 = (word32) r14;
		Eq_n p08 = v42 == v43;
		Eq_n p09 = v42 != v43;
		r47 = r32 + 0x00;
		r48 = r42 + 0x00;
		if (p07)
			++r34;
		word64 p48;
		if (p48)
			__break();
	}
	else
	{
l400000000008D440:
		r8 = 0x00 + 0x00;
		r0->u0 = (word32) (word32) r39;
		pr = r46;
		ar.pfs = r44;
		b0 = r43;
		r12 += 0x30;
	}
}

// 400000000008D500: define unclosed_pair
define unclosed_pair
{
	int64 r33;
	up64 r8;
	<anonymous> * b6;
	word64 r32;
	int64 r1;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r47 = ar.pfs;
	word64 r12 = r12 + ~0x2F;
	word64 r49 = pr;
	struct Eq_n * r43 = r1 + -9996;
	word64 r48 = r1 + 0x00;
	byte * r50 = r32 + 0x00;
	Eq_n r42 = r12 + 0x30;
	r43 = r43->ptr0000;
	<anonymous> * r46 = b6;
	word64 r38 = 0x00 + 0x00;
	word64 r39 = 0x00 + 0x00;
	word64 r35 = 0x00 + 0x00;
	union Eq_n * r0;
	r0->u1 = (struct Eq_n *) r42;
	<anonymous> * b0;
	b0();
	r1 = r48 + 0x00;
	int64 r44 = r8 + 0x00;
	byte * r34;
	r50 = r34;
	b0();
	int32 v26 = (word32) r33;
	int32 v27 = (word32) 0x00;
	Eq_n p07 = v26 < v27;
	Eq_n p06 = v26 >= v27;
	r1 = r48 + 0x00;
	word64 r40 = r8 + 0x00;
	word32 v31 = (word32) 0x00;
	word32 v32 = (word32) r8;
	Eq_n p16 = v31 == v32;
	Eq_n p17 = v31 != v32;
	int32 v35 = (int32) r8;
	int64 r45 = (int64) v35;
	if (p07)
	{
l400000000008D5B0:
		r39 = 0x00 + 0x00;
		goto l400000000008D5C0;
	}
	word32 v37 = (word32) 0x00;
	word32 v38 = (word32) r38;
	p06 = v37 == v38;
	p07 = v37 != v38;
	struct Eq_n * r14;
	int64 r52;
	byte * r51;
	if (p06)
	{
		do
		{
			int32 v41 = (int32) r35;
			int64 r37 = (int64) v41;
			byte * r41 = r37 + r32;
			byte v44 = *r41;
			int64 r36 = (word64) v44;
			int8 v46 = (int8) r36;
			r36 = (int64) v46;
			word32 v47 = (word32) 0x5C;
			word32 v48 = (word32) r36;
			p07 = v47 == v48;
			p06 = v47 != v48;
			if (p07)
			{
				++r35;
				r38 = 0x00 + 1;
				int32 v51 = (word32) r33;
				int32 v52 = (word32) r35;
				p07 = v51 < v52;
				p06 = v51 >= v52;
				if (!p06)
					goto l400000000008D5C0;
				goto l400000000008D6B0;
			}
			if (!p16)
			{
				byte v53 = *r34;
				r14 = (word64) v53;
				int8 v55 = (int8) r14;
				r14 = (int64) v55;
				word32 v56 = (word32) r14;
				word32 v57 = (word32) r36;
				p07 = v56 == v57;
				p06 = v56 != v57;
				if (!p07)
				{
l400000000008D720:
					word32 v67 = (word32) 0x27;
					word32 v68 = (word32) r36;
					Eq_n p08 = v67 == v68;
					Eq_n p09 = v67 != v68;
					word32 v71 = (word32) 0x22;
					word32 v72 = (word32) r36;
					p06 = v71 == v72;
					p07 = v71 != v72;
					r52 = r35 + 0x00;
					r50 = r32 + 0x00;
					r51 = r44 + 0x00;
					if (p08)
						r14 = 0x00 + 1;
					if (p09)
						r14 = 0x00 + 0x00;
					r1 < 0x00;
					p17 = r1 >= 0x00;
					pr = r32;
					word64 p28;
					if (p28)
					{
						int64 r64;
						r64 < r33;
						Eq_n p11 = r64 >= r33;
					}
				}
				r50 = r41;
				r51 = r34;
				r52 = r45 + 0x00;
				b0();
				r1 = r48 + 0x00;
				word32 v65 = (word32) 0x00;
				word32 v66 = (word32) r8;
				p07 = v65 == v66;
				p06 = v65 != v66;
				if (p06)
					goto l400000000008D720;
			}
			r35 = r40 + r35;
			--r39;
			int32 v58 = (word32) r33;
			int32 v59 = (word32) r35;
			p07 = v58 < v59;
			p06 = v58 >= v59;
			if (!p06)
				goto l400000000008D5C0;
l400000000008D6B0:
			word32 v60 = (word32) 0x00;
			word32 v61 = (word32) r38;
			p06 = v60 == v61;
			p07 = v60 != v61;
		} while (!p07);
	}
	int32 v39 = (word32) r35;
	int32 v40 = (word32) r33;
	p07 = v39 < v40;
	p06 = v39 >= v40;
	if (!p07)
		goto l400000000008D5B0;
	b0();
	int32 v49 = (int32) r35;
	r52 = (int64) v49;
	r1 = r48 + 0x00;
	p07 = 0x01 < r8;
	p06 = 0x01 >= r8;
	if (p06)
	{
		++r35;
		r38 = 0x00 + 0x00;
	}
	else
	{
		r51 = r52 + r32;
		byte v73 = *r51;
		r14 = (word64) v73;
		int8 v74 = (int8) r14;
		r14 = (int64) v74;
		word3 v75 = SLICE(r14, word3, 5);
		ui64 r16 = (word64) v75;
		Eq_n r15 = r14 & 0x1F;
		r14 = (struct Eq_n *) ((char *) &r43->ptr0000 + (r16 << 0x02));
		Eq_n v78;
		v78.u0 = r14->t0000.u0;
		r14 = (word64) v78;
		r14 >>= r15;
		if (!p07)
		{
			if (p06)
				r14 = 0x00 + 1;
			__break();
			__break();
		}
		r14 = r42.u1->ptr0000;
		r15 = r12 + 0x28;
		r50 = 0x00 + 0x00;
		r52 -= r44;
		word64 * r53 = &r42.u1->ptr0000;
		r38 = 0x00 + 0x00;
		r14->t0000.u1 = (struct Eq_n *) r15;
		b0();
		r14 = r8 + 0x02;
		r15 = r12 + 0x28;
		r1 = r48 + 0x00;
		p06 = (struct Eq_n *) 0x01 < r14;
		p07 = (struct Eq_n *) 0x01 >= r14;
		if (p06)
		{
			p06 = 0x00 == r8;
			p07 = 0x00 != r8;
			if (p07)
				r14 = r8 + 0x00;
		}
		r14 = r15.u1->ptr0000;
		++r35;
		r14->t0000.u1 = (struct Eq_n *) r42;
	}
	int32 v62 = (word32) r33;
	int32 v63 = (word32) r35;
	p07 = v62 < v63;
	p06 = v62 >= v63;
	if (p07)
	{
l400000000008D5C0:
		r8 = r39 + 0x00;
		pr = r49;
		ar.pfs = r47;
		b0 = r46;
		r12 += 0x30;
		return;
	}
	goto l400000000008D6B0;
}

// 400000000008DCC0: define split_at_delims
define split_at_delims
{
	ui64 r36;
	<anonymous> * b4;
	Eq_n r34;
	word64 r1;
	byte * r32;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r53 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r55 = pr;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	word64 r54 = r1 + 0x00;
	int64 r56 = (int64) r34;
	<anonymous> * r52 = b4;
	Eq_n r45 = r12 + 0x18;
	Eq_n p09 = 0x00 == r34;
	Eq_n p08 = 0x00 != r34;
	word64 r40 = 0x00 + 0x00;
	union Eq_n * r0;
	if (p06)
	{
l400000000008DFF0:
		word64 r37;
		p06 = 0x00 == r37;
		p07 = 0x00 != r37;
		if (p07)
			r0->u1 = (word32) (word32) r37;
		word64 p32;
		if (p32)
			__break();
		word64 p05;
		if (p05)
			__break();
		word64 p14;
		if (p14)
			__break();
		r12 += 0x10;
		return;
	}
	byte v22 = *r32;
	byte * r57 = (word64) v22;
	word64 r43 = 0x00 + 0x00;
	int8 v25 = (int8) r57;
	r57 = (int64) v25;
	word32 v26 = (word32) 0x00;
	word32 v27 = (word32) r57;
	p07 = v26 == v27;
	p06 = v26 != v27;
	if (p07)
		goto l400000000008DFF0;
	union Eq_n * r14;
	word64 r42;
	int64 r46;
	byte * r39;
	byte * r41;
	<anonymous> * b0;
	up64 r8;
	up64 r44;
	if (p09)
	{
		r14 = r1 + 9092;
		r42 = 0x00 + 1;
		r46 = 0x00 + 0x00;
		r39 = r32 + 1;
		r41 = r32;
		r40 = 0x00 + 0x00;
		r34.u0 = r14->u0;
	}
	else
	{
		r0->u2 = (union Eq_n **) r45;
		b0();
		r1 = r54 + 0x00;
		r41 = r8 + 0x00;
		r56 = r8 + 0x01;
		b0();
		r1 = r54 + 0x00;
		r46 = r8 + 0x00;
		int32 v35 = (int32) r40;
		r39 = (int64) v35;
		r39 += r34;
		byte v37 = *r39;
		r14 = (word64) v37;
		int8 v39 = (int8) r14;
		r14 = (int64) v39;
		word32 v40 = (word32) 0x00;
		word32 v41 = (word32) r14;
		p07 = v40 == v41;
		p06 = v40 != v41;
		if (!p07)
		{
			Eq_n r15 = r12 + 0x10;
			r14 = (union Eq_n *) *r45.u2;
			r14->u0 = (int64) r15;
			b0();
			p07 = 0x01 < r8;
			p06 = 0x01 >= r8;
			r1 = r54 + 0x00;
			ptr64 r58 = r41;
			r57 = r39;
			r56 = 0x00 + 0x00;
			if (!p06)
			{
				word64 * r59 = r45.u2;
				b0();
				r14 = r8 + 0x02;
				r44 = r8 + 0x00;
				int32 v73 = (int32) r43;
				r56 = (int64) v73;
				r57 = r39;
				r58 = r8 + 0x00;
				p09 = 0x01 < r8;
				p08 = 0x01 >= r8;
				p06 = (union Eq_n *) 0x01 < r14;
				p07 = (union Eq_n *) 0x01 >= r14;
				r56 += r46;
				r1 = r54 + 0x00;
				if (p07)
					r15 = r12 + 0x10;
			}
			else
			{
				byte v74 = *r39;
				r14 = (word64) v74;
				int32 v75 = (int32) r43;
				r15.u0 = (int64) v75;
				++r40;
				r41 += -1;
				int8 v76 = (int8) r14;
				r14 = (int64) v76;
				r15 = (word64) r15.u0 + r46;
				word32 v77 = (word32) 0x20;
				word32 v78 = (word32) r14;
				p06 = v77 == v78;
				p07 = v77 != v78;
				if (p07)
					r14->u1 = (byte) (byte) r15;
			}
		}
		r39 = r32 + 1;
		int32 v44 = (int32) r43;
		r14 = (int64) v44;
		r41 = r32;
		r40 = 0x00 + 0x00;
		r42 = 0x00 + 0x00;
		r14 = (union Eq_n *) ((char *) &r14->u0 + r46);
		r0->u0 = (byte) (byte) r14;
		byte v45 = *r32;
		r14 = (word64) v45;
		int8 v46 = (int8) r14;
		r57 = (int64) v46;
		word32 v47 = (word32) 0x00;
		word32 v48 = (word32) r57;
		p07 = v47 == v48;
		p06 = v47 != v48;
		if (p07)
		{
l400000000008DFB0:
			r44 = 0x00 + 0x00;
			r8 = r44 + 0x00;
			pr = r55;
			ar.pfs = r53;
			b0 = r52;
			r12 += 0x10;
			return;
		}
	}
	do
	{
		r56 = (int64) r34;
		b0();
		byte v49 = *r41;
		r14 = (word64) v49;
		r1 = r54 + 0x00;
		p07 = 0x00 == r8;
		p06 = 0x00 != r8;
		r41 = r39;
		if (p07)
		{
			int8 v52 = (int8) r14;
			r14 = (int64) v52;
l400000000008E0B0:
			word64 r38;
			p07 = 0x00 == r38;
			p06 = 0x00 != r38;
			p09 = 0x00 == r46;
			p08 = 0x00 != r46;
			ui64 r49 = r36 | 0x01;
			r44 = 0x00 + 0x00;
			r43 = 0x00 + -1;
			word64 r47 = 0x00 + 0x00;
			if (p06)
			{
				word64 r51 = 0x00 + 1;
			}
		}
		int8 v59 = (int8) r14;
		r14 = (int64) v59;
		word32 v60 = (word32) 0x20;
		word32 v61 = (word32) r14;
		p06 = v60 == v61;
		p07 = v60 != v61;
		word32 v62 = (word32) 0x0A;
		word32 v63 = (word32) r14;
		p08 = v62 == v63;
		p09 = v62 != v63;
		if (!p06 && p09)
			goto l400000000008E0B0;
		byte v65 = *r39;
		r57 = (word64) v65;
		++r39;
		++r40;
		int8 v66 = (int8) r57;
		r57 = (int64) v66;
		word32 v67 = (word32) 0x00;
		word32 v68 = (word32) r57;
		p06 = v67 == v68;
		p07 = v67 != v68;
	} while (p07);
	goto l400000000008DFB0;
}

// 400000000008E7C0: define string_list_internal
// Called from:
//      string_list
define string_list_internal
{
	<anonymous> * b0;
	word64 r1;
	word64 * r32;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r41 = ar.pfs;
	word64 r43 = pr;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	word64 r42 = r1 + 0x00;
	<anonymous> * r40 = b0;
	word64 r39;
	word64 r8;
	if (p06)
	{
		r39 = 0x00 + 0x00;
		pr = r43;
		r8 = r39 + 0x00;
		ar.pfs = r41;
		b0 = r40;
		return;
	}
	word64 * r34 = *r32;
	p07 = null == r34;
	p06 = null != r34;
	word64 * r14;
	int64 r44;
	if (p07)
	{
		++r32;
		r14 = *r32;
		r44 = *r14;
		b0();
		r1 = r42 + 0x00;
		r44 = r8 + 0x01;
		b0();
		r14 = *r32;
		r1 = r42 + 0x00;
		r44 = r8 + 0x00;
		int64 r45 = *r14;
		b0();
		r39 = r8 + 0x00;
		r1 = r42 + 0x00;
		pr = r43;
		r8 = r39 + 0x00;
		ar.pfs = r41;
		b0 = r40;
		return;
	}
	byte * r33;
	p06 = null == r33;
	p07 = null != r33;
	word64 r36;
	if (!p06)
	{
		byte v35 = *r33;
		r14 = (word64) v35;
		int8 v36 = (int8) r14;
		r14 = (int64) v36;
		word32 v37 = (word32) 0x00;
		word32 v38 = (word32) r14;
		p06 = v37 == v38;
		p07 = v37 != v38;
		if (!p06)
		{
			r14 = (word64 *) (r33 + 1);
			Eq_n v39;
			v39.u1 = *r14;
			r14 = (word64) v39;
			int8 v40 = (int8) r14;
			r14 = (int64) v40;
			word32 v41 = (word32) 0x00;
			word32 v42 = (word32) r14;
			p06 = v41 == v42;
			p07 = v41 != v42;
			if (p06)
				r36 = 0x00 + 1;
			word64 p03;
			if (p03)
			{
				null < r33;
				Eq_n p11 = null >= r33;
			}
		}
	}
	r36 = 0x00 + 0x00;
	r14 = r32;
	word64 r35 = 0x00 + 0x00;
	word64 ** r37 = r32 + 1;
	word64 ** r15 = r14 + 1;
	p06 = r32 == r14;
	p07 = r32 != r14;
	if (p06)
	{
		do
		{
			r14 = *r37;
			r44 = *r14;
			b0();
			r14 = r34;
			r1 = r42 + 0x00;
			r35 = r8 + r35;
			r34 = *r34;
l400000000008E930:
			r15 = r14 + 1;
			p06 = r32 == r14;
			p07 = r32 != r14;
		} while (!p07);
	}
	r14 = *r15;
	r35 = r36 + r35;
	r44 = *r14;
	b0();
	p07 = null == r34;
	p06 = null != r34;
	r1 = r42 + 0x00;
	r35 = r8 + r35;
	r14 = r34;
	if (p07)
	{
		r44 = r35 + 0x01;
		r34 = r32;
		int32 v26 = (word32) 0x01;
		int32 v27 = (word32) r36;
		Eq_n p17 = v26 < v27;
		Eq_n p16 = v26 >= v27;
		int32 v30 = (int32) r36;
		int64 r38 = (int64) v30;
		int32 v32 = (int32) r44;
		r44 = (int64) v32;
		b0();
		word32 v33 = (word32) 0x00;
		word32 v34 = (word32) r36;
		p07 = v33 == v34;
		p06 = v33 != v34;
		r1 = r42 + 0x00;
		r39 = r8 + 0x00;
		r35 = r8 + 0x00;
		if (p06)
			r37 = 0x00 + 1;
	}
	r34 = *r34;
	goto l400000000008E930;
}

// 400000000008EC40: define string_list
// Called from:
//      string_list_pos_params
define string_list
{
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	struct Eq_n * r33 = r1 + -6732;
	r33 = r33->ptr0000;
	word64 r2 = ar.pfs;
	string_list_internal();
}

// 400000000008EC80: define ifs_firstchar
define ifs_firstchar
{
	word64 r8;
	<anonymous> * b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	union Eq_n * r34 = r1 + 9108;
	<anonymous> * r35 = b3;
	word64 r37 = r1 + 0x00;
	word64 r38 = 0x00 + 0x0011;
	<anonymous> * b0;
	b0();
	r1 = r37 + 0x00;
	byte * r15 = r8 + 0x00;
	word64 r33 = r8 + 0x00;
	r38 = r8 + 0x00;
	Eq_n r14;
	r14.u1 = r34->u1;
	byte * r39 = r1 + 23524;
	Eq_n p07 = 0x01 == r14;
	Eq_n p06 = 0x01 != r14;
	word64 r40 = r14.u1;
	int64 r16;
	byte * r0;
	if (p07)
	{
		byte v25 = *r39;
		r16 = (word64) v25;
	}
	else
	{
		b0();
		Eq_n v21;
		v21.u0 = r34->u0;
		r14.u1 = (word64) v21;
		word64 r32;
		p06 = 0x00 == r32;
		p07 = 0x00 != r32;
		r8 = r33 + 0x00;
		r1 = r37 + 0x00;
		ar.pfs = r36;
		b0 = r35;
		int32 v23 = (int32) r14;
		r15 = (int64) v23;
		r15 += r33;
		*r0 = (byte) r15;
		if (p07)
			r14->u0 = (word32) r32;
	}
	r14.u1 = r39;
	r8 = r33 + 0x00;
	ar.pfs = r36;
	b0 = r35;
	int8 v27 = (int8) r16;
	r16 = (int64) v27;
	word32 v28 = (word32) 0x00;
	word32 v29 = (word32) r16;
	p07 = v28 == v29;
	p06 = v28 != v29;
	*r15 = (byte) r1;
	++r15;
	if (p07)
		r14 = 0x00 + 0x00;
	*r0 = (byte) r15;
	if (p06)
		r14 = 0x00 + 1;
}

// 400000000008EDC0: define string_list_dollar_star
// Called from:
//      string_list_pos_params
define string_list_dollar_star
{
	word64 r1;
	<anonymous> * b3;
	ui64 r12;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 r37 = r12 + 0x00;
	<anonymous> * r35 = b3;
	word64 r38 = r1 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r38 + 0x00;
	ui64 r8 = r8 + 0x10;
	union Eq_n * r14 = r1 + 9108;
	r8 &= 0xF0;
	byte * r40 = r1 + 23524;
	r12 = r8 - r12;
	ui64 r34 = r12 + 0x10;
	Eq_n r33;
	r33.u1 = r14->u1;
	ui64 r39 = r34 + 0x00;
	Eq_n p07 = 0x01 == r33;
	Eq_n p06 = 0x01 != r33;
	word64 r41 = r33.u1;
	r33.u1 = (word64) r33.u1 + r34;
	byte * r0;
	word64 r32;
	if (!p07)
	{
		b0();
		r1 = r38 + 0x00;
		*r0 = (byte) r33;
		r39 = r32 + 0x00;
		r40 = r34 + 0x00;
		b0();
		r1 = r38 + 0x00;
		ar.pfs = r36;
		b0 = r35;
		r12 = r37 + 0x00;
	}
	else
	{
		byte v22 = *r40;
		r14 = (word64) v22;
		ui64 r15 = r12 + 0x11;
		r39 = r32 + 0x00;
		r40 = r34 + 0x00;
		r14->u0 = (byte) (byte) r34;
		*r0 = (byte) r15;
		b0();
		r1 = r38 + 0x00;
		ar.pfs = r36;
		b0 = r35;
		r12 = r37 + 0x00;
	}
}

// 400000000008EF00: define get_word_from_string
define get_word_from_string
{
	word64 b0;
	word64 r1;
	byte ** r32;
	word64 LC;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r41 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r43 = LC;
	Eq_n p07 = null == r32;
	Eq_n p06 = null != r32;
	word64 r42 = r1 + 0x00;
	word64 r40 = b0;
	if (!p07)
	{
		byte * r35 = (byte *) *r32;
		p06 = null == r35;
		p07 = null != r35;
		if (!p06)
		{
			byte v19 = *r35;
			int64 r14 = (word64) v19;
			int8 v21 = (int8) r14;
			r14 = (int64) v21;
			word32 v22 = (word32) 0x00;
			word32 v23 = (word32) r14;
			p06 = v22 == v23;
			p07 = v22 != v23;
			if (!p06)
			{
				byte * r33;
				p06 = null == r33;
				p07 = null != r33;
				word64 r17;
				if (!p06)
				{
					byte v25 = *r33;
					byte * r15 = (word64) v25;
					int8 v27 = (int8) r15;
					r15 = (int64) v27;
					word32 v28 = (word32) 0x20;
					word32 v29 = (word32) r15;
					Eq_n p09 = v28 == v29;
					Eq_n p08 = v28 != v29;
					if (p09)
					{
						r15 = r33 + 1;
						byte v33 = *r15;
						r15 = (word64) v33;
						int8 v34 = (int8) r15;
						r15 = (int64) v34;
						word32 v35 = (word32) 0x09;
						word32 v36 = (word32) r15;
						p09 = v35 == v36;
						p08 = v35 != v36;
						if (!p08)
						{
							r15 = r33 + 2;
							byte v37 = *r15;
							r15 = (word64) v37;
							int8 v38 = (int8) r15;
							r15 = (int64) v38;
							word32 v39 = (word32) 0x0A;
							word32 v40 = (word32) r15;
							p09 = v39 == v40;
							p08 = v39 != v40;
							if (!p08)
							{
								r15 = r33 + 3;
								byte v41 = *r15;
								r15 = (word64) v41;
								int8 v42 = (int8) r15;
								r15 = (int64) v42;
								word32 v43 = (word32) 0x00;
								word32 v44 = (word32) r15;
								p08 = v43 == v44;
								p09 = v43 != v44;
								if (p08)
									r17 = 0x00 + 1;
								__break();
							}
						}
					}
				}
				if (p06)
					r17 = 0x00 + 1;
			}
		}
	}
	word64 r36 = 0x00 + 0x00;
	word64 r8 = r36 + 0x00;
	ar.pfs = r41;
	LC = r43;
	b0 = r40;
	r12 += 0x10;
}

// 400000000008F800: define strip_trailing_ifs_whitespace
define strip_trailing_ifs_whitespace
{
	word64 r34;
	word64 b3;
	word64 r1;
	byte * r32;
	byte * LC;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	byte * r38 = LC;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	word64 r37 = r1 + 0x00;
	word64 r35 = b3;
	byte * r15;
	byte * r14;
	byte * r17;
	Eq_n p01;
	int64 r33;
	if (p06)
		r15 = 0x00 + -1;
	else
	{
		byte v15 = *r32;
		r14 = (word64) v15;
		int8 v17 = (int8) r14;
		r14 = (int64) v17;
		word32 v18 = (word32) 0x00;
		word32 v19 = (word32) r14;
		p06 = v18 == v19;
		p07 = v18 != v19;
		byte * r8;
		if (!p06)
		{
			r17 = r32 + 1;
			byte v22 = *r17;
			r14 = (word64) v22;
			int8 v23 = (int8) r14;
			r14 = (int64) v23;
			word32 v24 = (word32) 0x00;
			word32 v25 = (word32) r14;
			p06 = v24 == v25;
			p07 = v24 != v25;
			if (!p06)
			{
				r14 = r32 + 2;
				byte v49 = *r14;
				r14 = (word64) v49;
				int8 v50 = (int8) r14;
				r14 = (int64) v50;
				word32 v51 = (word32) 0x00;
				word32 v52 = (word32) r14;
				p06 = v51 == v52;
				p07 = v51 != v52;
				if (p06)
					r8 = 0x00 + 1;
				if (p01)
				{
					0x00 == r33;
					Eq_n p17 = 0x00 != r33;
				}
				__break();
			}
			goto l400000000008FA00;
		}
		r8 = 0x00 + -1;
		r15 = r8 + r32;
		p06 = r32 < r15;
		p07 = r32 >= r15;
		if (!p06)
		{
l400000000008F9F0:
			r17 = r15 + 1;
l400000000008FA00:
			r8 = r32;
			byte * r0;
			*r0 = (byte) r17;
			ar.pfs = r36;
			LC = r38;
			word64 b0 = r35;
			return;
		}
	}
	r14 = r15 + -1;
	byte * r16 = r32 - r15;
	int64 r18 = r1 + 0x00005BF4;
	word32 v30 = (word32) 0x00;
	word32 v31 = (word32) r34;
	Eq_n p12 = v30 == v31;
	Eq_n p13 = v30 != v31;
	p06 = r14 < r32;
	p07 = r14 >= r32;
	LC = r16;
	if (!p06)
	{
		p06 = (byte *) ~0x00 == r32;
		p07 = (byte *) ~0x00 != r32;
		if (!p06)
			goto l400000000008F940;
	}
	LC = null;
l400000000008F940:
	Eq_n p11;
	while (true)
	{
		byte v36 = *r15;
		r14 = (word64) v36;
		r17 = r15 + 1;
		int8 v37 = (int8) r14;
		r14 = (int64) v37;
		byte v38 = (byte) r14;
		r16 = (word64) v38;
		word32 v39 = (word32) 0x20;
		word32 v40 = (word32) r14;
		p06 = v39 == v40;
		p07 = v39 != v40;
		word32 v41 = (word32) 0x0A;
		word32 v42 = (word32) r14;
		p11 = v41 == v42;
		Eq_n p10 = v41 != v42;
		word32 v45 = (word32) 0x01;
		word32 v46 = (word32) r14;
		Eq_n p09 = v45 == v46;
		Eq_n p08 = v45 != v46;
		r16 += r18;
		if (!p06 && !p11)
			break;
		byte v53 = *r16;
		r14 = (word64) v53;
		p07 = null == r14;
		p06 = null != r14;
		if (p07)
			break;
		r15 += -1;
		if (LC == null)
			goto l400000000008F9F0;
		--LC;
	}
	if (!p12)
	{
		word64 p03;
		if (p03)
		{
			int64 r64;
			r64 < r33;
			p11 = r64 >= r33;
		}
		word64 p16;
		if (p16)
			__break();
		if (p16)
		{
			int64 r96;
			0x00 < r96;
			p01 = 0x00 >= r96;
		}
	}
	goto l400000000008F9F0;
}

// 400000000008FAC0: define list_rest_of_args
define list_rest_of_args
{
	word64 LC;
	<anonymous> * b2;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	struct Eq_n * r14 = r1 + 5924;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	struct Eq_n ** r33 = 0x00 + 0x00;
	struct Eq_n * r32 = r14->ptr0000;
	word64 r37 = LC;
	LC = 0x08;
	struct Eq_n * r38;
	Eq_n p07;
	Eq_n p06;
	<anonymous> * b0;
	word64 r39;
	word64 * r8;
	while (true)
	{
		r38 = r32->ptr0000;
		r32 = (struct Eq_n *) ((char *) &r32->ptr0000 + 8);
		p07 = null == r38;
		p06 = null != r38;
		if (p07)
			break;
		b0();
		r1 = r36 + 0x00;
		r39 = r33;
		r38 = (struct Eq_n *) r8;
		b0();
		r1 = r36 + 0x00;
		r33 = r8;
		if (LC == 0x00)
			break;
		--LC;
	}
	r14 = r1 + 7132;
	r32 = r14->ptr0000;
	p06 = null == r32;
	p07 = null != r32;
	if (!p06)
	{
		do
		{
			r14 = (struct Eq_n *) ((char *) &r32->ptr0000 + 8);
			r14 = r14->ptr0000;
			r38 = r14->ptr0000;
			b0();
			r1 = r36 + 0x00;
			r39 = r33;
			r38 = (struct Eq_n *) r8;
			b0();
			r32 = r32->ptr0000;
			r1 = r36 + 0x00;
			r33 = r8;
			p07 = null == r32;
			p06 = null != r32;
		} while (p06);
	}
	p06 = null == r33;
	p07 = null != r33;
	r38 = (struct Eq_n *) r33;
	if (!p06)
	{
		r14 = (struct Eq_n *) *r33;
		p06 = null == r14;
		p07 = null != r14;
		if (!p06)
		{
			b0();
			r1 = r36 + 0x00;
			r33 = r8;
		}
	}
	r8 = r33;
	ar.pfs = r35;
	LC = r37;
	b0 = r34;
}

// 400000000008FC80: define number_of_args
define number_of_args
{
	word64 LC;
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	struct Eq_n * r14 = r1 + 5932;
	word64 r8 = 0x00 + 0x00;
	word64 r2 = LC;
	r14 = r14->ptr0000;
	LC = 0x08;
	Eq_n p07;
	Eq_n p06;
	while (true)
	{
		struct Eq_n * r15 = r14->ptr0000;
		r14 = (struct Eq_n *) ((char *) &r14->ptr0000 + 8);
		word64 r16 = r8 + 0x01;
		p07 = null == r15;
		p06 = null != r15;
		if (p07)
			break;
		r8 = r16 + 0x00;
		if (LC == 0x00)
			break;
		--LC;
	}
	r14 = r1 + 7132;
	r14 = r14->ptr0000;
	p06 = null == r14;
	p07 = null != r14;
	if (!p06)
	{
		do
		{
			r14 = r14->ptr0000;
			++r8;
			p07 = null == r14;
			p06 = null != r14;
		} while (p06);
	}
	LC = r2;
}

// 400000000008FD40: define get_dollar_var_value
define get_dollar_var_value
{
	<anonymous> * b2;
	int64 r32;
	int64 LC;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	struct Eq_n * r14 = r1 + 23444;
	int64 r37 = LC;
	word64 r36 = r1 + 0x00;
	Eq_n p06 = 0x09 < r32;
	Eq_n p07 = 0x09 >= r32;
	<anonymous> * r34 = b2;
	<anonymous> * b0;
	word64 r8;
	if (p06)
	{
		r14 = r1 + 7132;
		int64 r15 = r32 + ~0x0A;
		Eq_n p08 = 0x0A == r32;
		Eq_n p09 = 0x0A != r32;
		LC = r15;
		r14 = r14->ptr0000;
		p06 = null == r14;
		p07 = null != r14;
		if (!p06)
		{
			__break();
			__break();
		}
	}
	else
	{
		struct Eq_n ** r33 = (struct Eq_n **) (r14 + r32);
		r14 = (struct Eq_n *) *r33;
		p06 = null == r14;
		p07 = null != r14;
		word64 r38 = &r14->ptr0000;
		if (!p06)
		{
			b0();
			r1 = r36 + 0x00;
			r38 = r8 + 0x01;
			b0();
			r1 = r36 + 0x00;
			r38 = r8 + 0x00;
			struct Eq_n * r39 = (struct Eq_n *) *r33;
			b0();
			r1 = r36 + 0x00;
			ar.pfs = r35;
			LC = r37;
			b0 = r34;
			return;
		}
	}
	r8 = 0x00 + 0x00;
	ar.pfs = r35;
	LC = r37;
	b0 = r34;
}

// 400000000008FF40: define string_rest_of_args
define string_rest_of_args
{
	word64 r8;
	word64 r32;
	word64 r1;
	<anonymous> * b3;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	<anonymous> * r35 = b3;
	word64 r37 = r1 + 0x00;
	<anonymous> * b0;
	b0();
	word32 v12 = (word32) 0x00;
	word32 v13 = (word32) r32;
	Eq_n p06 = v12 == v13;
	Eq_n p07 = v12 != v13;
	r1 = r37 + 0x00;
	word64 r33 = r8 + 0x00;
	word64 r38 = r8 + 0x00;
	word64 r34;
	if (!p07)
	{
		b0();
		r1 = r37 + 0x00;
		r34 = r8 + 0x00;
		r38 = r33 + 0x00;
		b0();
		r8 = r34 + 0x00;
		r1 = r37 + 0x00;
		ar.pfs = r36;
		b0 = r35;
	}
	else
	{
		b0();
		r1 = r37 + 0x00;
		r34 = r8 + 0x00;
		r38 = r33 + 0x00;
		b0();
		r8 = r34 + 0x00;
		r1 = r37 + 0x00;
		ar.pfs = r36;
		b0 = r35;
	}
}

// 4000000000090040: define remove_backslashes
define remove_backslashes
{
	int64 r114;
	int64 r9;
	byte * r32;
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = r32;
	<anonymous> * b0;
	b0();
	r1 = r35 + 0x00;
	word64 r8;
	r36 = r8 + 0x01;
	b0();
	r1 = r35 + 0x00;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	word64 r15 = r8 + 0x00;
	word64 r14 = r32;
	word64 r18;
	byte * r0;
	if (!p06)
	{
		byte v18 = *r32;
		int64 r17 = (word64) v18;
		int8 v20 = (int8) r17;
		r17 = (int64) v20;
		word32 v21 = (word32) 0x00;
		word32 v22 = (word32) r17;
		p06 = v21 == v22;
		p07 = v21 != v22;
		if (!p06)
		{
			word64 r16 = r14 + 0x00;
			word32 v26 = (word32) 0x5C;
			word32 v27 = (word32) r17;
			p07 = v26 == v27;
			p06 = v26 != v27;
			r18 = r15 + 0x00;
			if (p07)
				r16 = r14 + 0x01;
			__break();
			word64 p02;
			if (p02)
				__break();
			Eq_n p14 = r9 < r114;
			Eq_n p17 = r9 >= r114;
			byte * pr = r32;
			word64 p50;
			if (p50)
				__break();
			__break();
			__break();
			*r0 = (byte) r18;
			ar.pfs = r34;
			b0 = r33;
			return;
		}
	}
	r18 = r8 + 0x00;
	ar.pfs = r34;
	*r0 = (byte) r18;
	b0 = r33;
}

// 4000000000090180: define quote_escapes
define quote_escapes
{
	word64 r64;
	up64 r8;
	byte * LC;
	<anonymous> * b1;
	byte * r32;
	word64 r1;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r42 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r44 = pr;
	word64 r43 = r1 + 0x00;
	word64 r46 = r32;
	Eq_n r37 = r12 + 0x18;
	<anonymous> * r41 = b1;
	byte * r33 = 0x00 + 0x00;
	word64 r35 = 0x00 + 0x00;
	struct Eq_n * r36 = 0x00 + 1;
	union Eq_n * r0;
	r0->u2 = (byte *) r37;
	byte * r45 = LC;
	<anonymous> * b0;
	b0();
	r1 = r43 + 0x00;
	ui64 r40 = r32 + r8;
	Eq_n r14 = r1 + 9092;
	r14.u2 = r14.u3->t0000.u2;
	Eq_n r15;
	r15.u1 = (word32) r14 + 1;
	Eq_n p06 = 0x00 == r14;
	Eq_n p07 = 0x00 != r14;
	byte * r34;
	Eq_n p18;
	Eq_n p16;
	Eq_n p20;
	word64 r39;
	byte * r16;
	byte * r4;
	if (p06)
	{
		r46 = r8 + r8;
		r36 = 0x00 + 0x00;
		r33 = 0x00 + 0x00;
		r35 = 0x00 + 0x00;
		r34 = r32;
		b0();
		r1 = r43 + 0x00;
		byte v35 = *r32;
		r14.u2 = (word64) v35;
		word32 v36 = (word32) 0x00;
		word32 v37 = (word32) r36;
		p18 = v36 == v37;
		Eq_n p19 = v36 != v37;
		word32 v40 = (word32) 0x00;
		word32 v41 = (word32) r33;
		Eq_n p17 = v40 == v41;
		p16 = v40 != v41;
		word32 v44 = (word32) 0x00;
		word32 v45 = (word32) r35;
		Eq_n p21 = v44 == v45;
		p20 = v44 != v45;
		word64 r38 = 0x00 + 1;
		r36 = r1 + -9996;
		r39 = r8 + 0x00;
		r33 = r8 + 0x00;
		int8 v50 = (int8) r14;
		r14.u2 = (int64) v50;
		r36 = r36->ptr0000;
l40000000000902A0:
	}
	else
	{
		Eq_n v29;
		v29.u0 = *r14.u2;
		r14.u2 = (word64) v29;
		r16 = r15 - 0x00;
		int8 v31 = (int8) r14;
		r14.u2 = (int64) v31;
		word32 v32 = (word32) 0x00;
		word32 v33 = (word32) r14;
		p06 = v32 == v33;
		p07 = v32 != v33;
		LC = r16;
		Eq_n p08;
		struct Eq_n * r66;
		if (p07)
		{
			word32 v51 = (word32) 0x01;
			word32 v52 = (word32) r14;
			p06 = v51 == v52;
			p07 = v51 != v52;
			word32 v53 = (word32) 0x7F;
			word32 v54 = (word32) r14;
			p08 = v53 == v54;
			Eq_n p09 = v53 != v54;
			if (p06)
				r16 = 0x00 + 1;
			if (p08)
				r14 = 0x00 + 1;
			Eq_n f0;
			f0.u0 = r66->t0000.u0;
			f0.u0 = r66->t0004.u0;
		}
		if (p06)
			r33 = 0x00 + 0x00;
		null < r66;
		p08 = null >= r66;
		byte v65 = *r4;
		word64 r10 = (word64) v65;
		r4 += -0x00FE;
		__break();
		__break();
		__break();
	}
	word32 v57 = (word32) 0x00;
	word32 v58 = (word32) r14;
	p07 = v57 == v58;
	p06 = v57 != v58;
	if (p07)
	{
		r8 = r39 + 0x00;
		r0->u0 = (byte) (byte) r33;
		pr = r44;
		ar.pfs = r42;
		LC = r45;
		b0 = r41;
		r12 += 0x10;
		return;
	}
	if (!p20)
	{
		word32 v93 = (word32) 0x01;
		word32 v94 = (word32) r14;
		p06 = v93 == v94;
		p07 = v93 != v94;
		if (p06)
			goto l4000000000090620;
	}
	if (!p16)
	{
		word32 v69 = (word32) 0x7F;
		word32 v70 = (word32) r14;
		p06 = v69 == v70;
		p07 = v69 != v70;
		if (p06)
			goto l4000000000090620;
	}
	if (p18)
	{
l4000000000090310:
		b0();
		r1 = r43 + 0x00;
		p07 = 0x01 < r8;
		p06 = 0x01 >= r8;
		if (p06)
			goto l4000000000090640;
l4000000000090330:
		byte v75 = *r34;
		r14.u2 = (word64) v75;
		r8 = 0x00 + 1;
		int8 v76 = (int8) r14;
		r14.u2 = (int64) v76;
		word3 v77 = SLICE(r14, word3, 5);
		r15.u2 = (word64) v77;
		r16 = r14 & 0x1F;
		r15.u2 = (char *) &r36->ptr0000 + (r15 << 0x02);
		Eq_n v78;
		v78.u1 = r15.u3->t0000.u1;
		r15.u2 = (word64) v78;
		r15 >>= r16;
		Eq_n r19;
		ptr64 r17;
		byte * r18;
		if (!p07)
		{
			r19 = r34 - r34;
			p06 = 0x00 == r8;
			p07 = 0x00 != r8;
			r15.u2 = r34;
			r16 = r33;
			r17 = r34 + 1;
			r18 = (byte *) ((word32) r19 + r8);
			LC = r18;
			if (p07)
				LC = r18;
			byte v89 = (byte) r64;
		}
		r14.u2 = r37.u3->t0000.u2;
		r15 = r12 + 0x10;
		r46 = 0x00 + 0x00;
		byte * r47 = r34;
		ptr64 r48 = r34 - r40;
		word64 * r49 = (word64 *) r37.u2;
		r14.u3->t0000.u2 = (byte *) r15;
		b0();
		r14 = r8 + 0x02;
		r18 = r12 + 0x10;
		r1 = r43 + 0x00;
		p06 = 0x01 < r14;
		p07 = 0x01 >= r14;
		if (p06)
		{
			p06 = 0x00 == r8;
			p07 = 0x00 != r8;
			if (p07)
			{
				byte v92 = *r34;
				r14.u2 = (word64) v92;
			}
		}
		r14.u0 = *r18;
		r8 = 0x00 + 1;
		r14.u3->t0000.u2 = (byte *) r37;
		byte v90 = *r34;
		r14.u2 = (word64) v90;
		int8 v91 = (int8) r14;
		r14.u2 = (int64) v91;
		r19 = r34 - r34;
		p06 = 0x00 == r8;
		p07 = 0x00 != r8;
		r15.u2 = r34;
		r16 = r33;
		r17 = r34 + 1;
		r18 = (byte *) ((word32) r19 + r8);
		LC = r18;
		if (p07)
			LC = r18;
		if (p06)
			LC = null;
		if (p20)
			__break();
		if (p07)
		{
			byte v96 = *r4;
			r11 = (word64) v96;
			r4 += -252;
		}
l4000000000090640:
		byte v79 = *r34;
		++r34;
		*r33 = (byte) r1;
		++r33;
		byte v80 = *r34;
		r14.u2 = (word64) v80;
		int8 v81 = (int8) r14;
		r14.u2 = (int64) v81;
		goto l40000000000902A0;
	}
	word32 v73 = (word32) 0x20;
	word32 v74 = (word32) r14;
	p07 = v73 == v74;
	p06 = v73 != v74;
	if (!p07)
		goto l4000000000090310;
l4000000000090620:
	*r33 = (byte) r1;
	++r33;
	b0();
	r1 = r43 + 0x00;
	p07 = 0x01 < r8;
	p06 = 0x01 >= r8;
	if (!p07)
		goto l4000000000090640;
	goto l4000000000090330;
}

// 4000000000090740: define dequote_escapes
define dequote_escapes
{
	word64 LC;
	<anonymous> * b0;
	word64 r1;
	word64 r32;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r41 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r43 = pr;
	Eq_n p06 = 0x00 == r32;
	Eq_n p07 = 0x00 != r32;
	word64 r42 = r1 + 0x00;
	word64 r45 = r32 + 0x00;
	word64 r37 = r12 + 0x18;
	<anonymous> * r40 = b0;
	word64 r44 = LC;
	word64 * r0;
	*r0 = r37;
	word64 r8;
	if (!p06)
	{
		b0();
		r1 = r42 + 0x00;
		word64 r38 = r8 + r32;
		r45 = r8 + 0x01;
		b0();
		r1 = r42 + 0x00;
		word64 r39 = r8 + 0x00;
		r45 = r32 + 0x00;
		word64 r46 = 0x00 + 1;
		b0();
		r1 = r42 + 0x00;
		p07 = 0x00 == r8;
		p06 = 0x00 != r8;
		if (!p07)
		{
			struct Eq_n * r14 = r1 + 9092;
			r14 = r14->ptr0000;
			p06 = null == r14;
			p07 = null != r14;
			if (p06)
			{
				word64 r15 = 0x00 + 0x00;
			}
			__break();
		}
		else
		{
			r46 = r32 + 0x00;
			r45 = r39 + 0x00;
			b0();
			r32 = r8 + 0x00;
			r1 = r42 + 0x00;
			r8 = r32 + 0x00;
			pr = r43;
			ar.pfs = r41;
			LC = r44;
			b0 = r40;
			r12 += 0x10;
		}
	}
	else
	{
		r8 = r32 + 0x00;
		pr = r43;
		ar.pfs = r41;
		LC = r44;
		b0 = r40;
		r12 += 0x10;
	}
}

// 4000000000090C40: define quote_string
define quote_string
{
	word64 LC;
	<anonymous> * b7;
	byte * r32;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r40 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	struct Eq_n * r36 = r1 + -9996;
	byte v10 = *r32;
	byte * r14 = (word64) v10;
	<anonymous> * r39 = b7;
	word64 r41 = r1 + 0x00;
	Eq_n r37 = r12 + 0x18;
	int8 v16 = (int8) r14;
	r14 = (int64) v16;
	byte * r43 = r32;
	r36 = r36->ptr0000;
	word64 r35 = 0x00 + 1;
	word32 v19 = (word32) 0x00;
	word32 v20 = (word32) r14;
	Eq_n p07 = v19 == v20;
	Eq_n p06 = v19 != v20;
	word64 r42 = LC;
	union Eq_n * r0;
	<anonymous> * b0;
	word64 r8;
	word64 r38;
	if (!p07)
	{
		r0->u1 = (word64) r37;
		b0();
		r1 = r41 + 0x00;
		byte * r34 = r32 + r8;
		r43 = r8 + r8;
		b0();
		p07 = r32 < r34;
		p06 = r32 >= r34;
		word64 r33 = r8 + 0x00;
		r1 = r41 + 0x00;
		r38 = r8 + 0x00;
		if (p06)
			r33 = r8 + 0x00;
		__break();
		__break();
	}
	else
	{
		r43 = 0x00 + 2;
		b0();
		word64 r15 = 0x00 + 0x007F;
		r14 = r8 + 0x00;
		r38 = r8 + 0x00;
		r1 = r41 + 0x00;
		*r14 = (byte) r1;
		++r14;
		r8 = r38 + 0x00;
		r0->u0 = (byte) (byte) r14;
		ar.pfs = r40;
		LC = r42;
		b0 = r39;
		r12 += 0x10;
	}
}

// 4000000000091100: define string_list_dollar_at
// Called from:
//      string_list_pos_params
define string_list_dollar_at
{
	<anonymous> * b6;
	word64 r1;
	ui64 r12;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r39 = ar.pfs;
	word64 r40 = r12 + 0x00;
	word64 r41 = r1 + 0x00;
	<anonymous> * r38 = b6;
	<anonymous> * b0;
	b0();
	r1 = r41 + 0x00;
	ui64 r8 = r8 + 0x10;
	Eq_n r14 = r1 + 9076;
	ui64 r15 = r8 & 0xF0;
	r12 = r15 - r12;
	ui64 r37 = r12 + 0x10;
	r14.u1 = r14.u1->t0000.u1;
	Eq_n p06 = 0x00 == r14;
	Eq_n p07 = 0x00 != r14;
	r14.u1 = (word32) r14 + 8;
	byte * r0;
	ui64 r33;
	if (!p06)
	{
		r14.u1 = r14.u1->t0000.u1;
		p06 = 0x00 == r14;
		p07 = 0x00 != r14;
		if (!p06)
		{
			Eq_n v29;
			v29.u0 = r14.u1->t0000.u0;
			r14.u1 = (word64) v29;
			int8 v30 = (int8) r14;
			r14.u1 = (int64) v30;
			word32 v31 = (word32) 0x00;
			word32 v32 = (word32) r14;
			p06 = v31 == v32;
			p07 = v31 != v32;
			if (!p06)
			{
				r14 = r1 + 9108;
				Eq_n r34;
				r34.u1 = r14.u1->t0000.u1;
				p07 = 0x01 == r34;
				p06 = 0x01 != r34;
				ui64 r43;
				ui64 r42;
				if (p06)
				{
					r43 = r1 + 23524;
					word64 r44 = (word64) &r34.u1->t0000.u0;
					r42 = r37 + 0x00;
					r34.u1 = &r34.u1->t0000.u0 + r37;
					b0();
					r1 = r41 + 0x00;
					*r0 = (byte) r34;
				}
				else
				{
					r14 = r1 + 23524;
					r15 = r12 + 0x11;
					Eq_n v36;
					v36.u0 = r14.u1->t0000.u0;
					r14.u1 = (word64) v36;
					r14.u1->t0000.u0 = (byte) (byte) r37;
					*r0 = (byte) r15;
				}
				r33 &= 11;
				word32 v34 = (word32) 0x00;
				word32 v35 = (word32) r33;
				p07 = v34 == v35;
				p06 = v34 != v35;
				word64 r32;
				if (!p06)
				{
l4000000000091230:
					p07 = 0x00 == r32;
					p06 = 0x00 != r32;
					if (!p07)
					{
						if (p06)
							r34 = r32 + 0x00;
						__break();
						__break();
						__break();
					}
					else
					{
						r42 = r32 + 0x00;
						r43 = r37 + 0x00;
						b0();
						r1 = r41 + 0x00;
						ar.pfs = r39;
						b0 = r38;
						r12 = r40 + 0x00;
						return;
					}
				}
l4000000000091330:
				r42 = r32 + 0x00;
				b0();
				r1 = r41 + 0x00;
				r42 = r8 + 0x00;
				r43 = r37 + 0x00;
				b0();
				r1 = r41 + 0x00;
				ar.pfs = r39;
				b0 = r38;
				r12 = r40 + 0x00;
				return;
			}
		}
	}
	r14 = r37 + 0x00;
	r15 = 0x00 + 32;
	r33 &= 11;
	r14.u1->t0000.u0 = (byte) (byte) r1;
	r14.u1 = (word32) r14 + 1;
	word32 v20 = (word32) 0x00;
	word32 v21 = (word32) r33;
	p07 = v20 == v21;
	p06 = v20 != v21;
	*r0 = (byte) r14;
	if (p07)
		goto l4000000000091230;
	goto l4000000000091330;
}

// 4000000000091400: define dequote_string
define dequote_string
{
	word64 r64;
	union Eq_n ** LC;
	byte * r32;
	<anonymous> * b0;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r41 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	struct Eq_n * r36 = r1 + -9996;
	word64 r42 = r1 + 0x00;
	<anonymous> * r40 = b0;
	Eq_n r37 = r12 + 0x18;
	r36 = r36->ptr0000;
	byte * r44 = r32;
	union Eq_n ** r43 = LC;
	byte * r34 = r32;
	union Eq_n * r0;
	r0->u1 = (byte *) r37;
	b0();
	r1 = r42 + 0x00;
	up64 r8;
	r44 = r8 + 0x01;
	ui64 r39 = r32 + r8;
	b0();
	byte v21 = *r32;
	union Eq_n * r14 = (word64) v21;
	r1 = r42 + 0x00;
	word64 r38 = r8 + 0x00;
	r44 = r32;
	byte * r45 = 0x00 + 1;
	byte * r33 = r8 + 0x00;
	int8 v26 = (int8) r14;
	int64 r35 = (int64) v26;
	word32 v28 = (word32) 0x7F;
	word32 v29 = (word32) r35;
	Eq_n p07 = v28 == v29;
	Eq_n p06 = v28 != v29;
	if (!p07)
	{
		b0();
		r1 = r42 + 0x00;
		p07 = 0x00 == r8;
		p06 = 0x00 != r8;
		if (!p07)
		{
			while (true)
			{
				r14 = (union Eq_n *) (r34 + 1);
				word32 v36 = (word32) 0x00;
				word32 v37 = (word32) r35;
				p07 = v36 == v37;
				p06 = v36 != v37;
				if (p07)
					break;
				word32 v39 = (word32) 0x01;
				word32 v40 = (word32) r35;
				p07 = v39 == v40;
				p06 = v39 != v40;
				Eq_n r15;
				if (!p06)
				{
					Eq_n v41;
					v41.u0 = r14->u0;
					r15.u1 = (word64) v41;
					r34 = &r14->u0;
					int8 v43 = (int8) r15;
					r14 = (int64) v43;
					word32 v44 = (word32) 0x00;
					word32 v45 = (word32) r14;
					p06 = v44 == v45;
					p07 = v44 != v45;
					if (p06)
						break;
				}
				b0();
				r1 = r42 + 0x00;
				p07 = 0x01 < r8;
				p06 = 0x01 >= r8;
				r8 = 0x00 + 1;
				if (!p06)
				{
					byte v46 = *r34;
					r14 = (word64) v46;
					int8 v47 = (int8) r14;
					r14 = (int64) v47;
					word3 v48 = SLICE(r14, word3, 5);
					r15.u1 = (word64) v48;
					byte * r16 = r14 & 0x1F;
					r15.u1 = (char *) &r36->ptr0000 + (r15 << 0x02);
					word32 v50 = (word32) *r15;
					r15.u1 = (word64) v50;
					r15 >>= r16;
					Eq_n r19;
					ptr64 r17;
					union Eq_n ** r18;
					if (!p07)
					{
						r19 = r34 - r34;
						p06 = 0x00 == r8;
						p07 = 0x00 != r8;
						r15.u1 = r34;
						r16 = r33;
						r17 = r34 + 1;
						r18 = (union Eq_n **) ((word32) r19 + r8);
						LC = r18;
						if (p07)
							LC = r18;
						byte v60 = (byte) r64;
					}
					r14 = (union Eq_n *) *r37;
					r15 = r12 + 0x10;
					r44 = 0x00 + 0x00;
					r45 = r34;
					ptr64 r46 = r34 - r39;
					word64 * r47 = (word64 *) r37.u1;
					r14->u1 = (byte *) r15;
					b0();
					r14 = r8 + 0x02;
					r18 = r12 + 0x10;
					r1 = r42 + 0x00;
					p06 = (union Eq_n *) 0x01 < r14;
					p07 = (union Eq_n *) 0x01 >= r14;
					if (!p06)
					{
						r14 = (union Eq_n *) *r18;
						r8 = 0x00 + 1;
						r14->u1 = (byte *) r37;
						byte v62 = *r34;
						r14 = (word64) v62;
						int8 v63 = (int8) r14;
						r14 = (int64) v63;
						r19 = r34 - r34;
						p06 = 0x00 == r8;
						p07 = 0x00 != r8;
						r15.u1 = r34;
						r16 = r33;
						r17 = r34 + 1;
						r18 = (union Eq_n **) ((word32) r19 + r8);
						LC = r18;
						if (p07)
							LC = r18;
						if (p06)
							LC = null;
						word64 p04;
						if (p04)
							__break();
						__break();
					}
					else
					{
						p06 = 0x00 == r8;
						p07 = 0x00 != r8;
						if (p07)
						{
							byte v61 = *r34;
							r14 = (word64) v61;
						}
					}
				}
				byte v51 = *r34;
				r14 = (word64) v51;
				++r34;
				byte v52 = *r34;
				r35 = (word64) v52;
				*r33 = (byte) r1;
				++r33;
				int8 v53 = (int8) r35;
				r35 = (int64) v53;
			}
			r0->u0 = (byte) (byte) r33;
			r8 = r38 + 0x00;
			ar.pfs = r41;
			LC = r43;
			b0 = r40;
			r12 += 0x10;
		}
		else
		{
			r44 = r38 + 0x00;
			r45 = r32;
			b0();
			r38 = r8 + 0x00;
			r1 = r42 + 0x00;
			r8 = r38 + 0x00;
			ar.pfs = r41;
			LC = r43;
			b0 = r40;
			r12 += 0x10;
		}
	}
	else
	{
		r14 = (union Eq_n *) (r32 + 1);
		Eq_n v32;
		v32.u0 = r14->u0;
		r14 = (word64) v32;
		int8 v33 = (int8) r14;
		r14 = (int64) v33;
		word32 v34 = (word32) 0x00;
		word32 v35 = (word32) r14;
		p07 = v34 == v35;
		p06 = v34 != v35;
		if (p07)
			r0->u0 = (byte) (byte) r8;
	}
}

// 4000000000091E80: define dequote_list
// Called from:
//      expand_string
//      expand_word
define dequote_list
{
	word64 r3;
	<anonymous> * b5;
	word64 r32;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r38 = ar.pfs;
	word64 r39 = r1 + 0x00;
	struct Eq_n * r33 = r32 + 0x00;
	<anonymous> * r37 = b5;
	Eq_n p07 = 0x00 == r32;
	Eq_n p06 = 0x00 != r32;
	word64 r36 = 0x00 + -0x00040001;
	<anonymous> * b0;
	word64 r8;
	if (!p07)
	{
		do
		{
			union Eq_n * r34 = (union Eq_n *) ((char *) &r33->ptr0000 + 8);
			Eq_n r14;
			r14.u2 = r34->u2;
			Eq_n r40;
			r40.u2 = *r14.u2;
			b0();
			Eq_n r15;
			r15.u2 = r34->u2;
			r1 = r39 + 0x00;
			union Eq_n * r35 = r8 + 0x00;
			r14.u2 = *r15.u2;
			r40.u2 = r14.u2;
			Eq_n v22 = *r14;
			int64 r16 = (word64) v22;
			int8 v24 = (int8) r16;
			r16 = (int64) v24;
			word32 v25 = (word32) 0x7F;
			word32 v26 = (word32) r16;
			p07 = v25 == v26;
			p06 = v25 != v26;
			if (p07)
			{
				r14.u1 = (word32) r14 + 1;
				r15.u1 = (word32) r15 + 8;
				Eq_n v27 = *r14;
				r14.u2 = (word64) v27;
				int8 v28 = (int8) r14;
				r14.u2 = (int64) v28;
				word32 v29 = (word32) 0x00;
				word32 v30 = (word32) r14;
				p07 = v29 == v30;
				p06 = v29 != v30;
				if (p07)
				{
					Eq_n v31 = *r15;
					r14.u2 = (word64) v31;
				}
				byte v33 = (byte) r3;
				word64 r73 = (word64) v33;
			}
			b0();
			r14.u2 = r34->u2;
			r1 = r39 + 0x00;
			r33 = r33->ptr0000;
			p07 = null == r33;
			p06 = null != r33;
			r35->u2 = (word64 *) r14;
		} while (p06);
	}
	r8 = r32 + 0x00;
	ar.pfs = r38;
	b0 = r37;
}

// 4000000000092040: define remove_quoted_escapes
define remove_quoted_escapes
{
	word64 r1;
	<anonymous> * b2;
	word64 r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	Eq_n p06 = 0x00 == r32;
	Eq_n p07 = 0x00 != r32;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r37 = r32 + 0x00;
	<anonymous> * b0;
	word64 r8;
	if (!p06)
	{
		b0();
		r1 = r36 + 0x00;
		word64 r33 = r8 + 0x00;
		r37 = r32 + 0x00;
		word64 r38 = r8 + 0x00;
		b0();
		r1 = r36 + 0x00;
		r37 = r33 + 0x00;
		b0();
		r1 = r36 + 0x00;
	}
	r8 = r32 + 0x00;
	ar.pfs = r35;
	b0 = r34;
}

// 4000000000092100: define remove_quoted_nulls
define remove_quoted_nulls
{
	up64 r8;
	word64 LC;
	union Eq_n * r32;
	word64 r1;
	<anonymous> * b7;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r40 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	<anonymous> * r39 = b7;
	word64 r41 = r1 + 0x00;
	word64 r43 = &r32->u0;
	Eq_n r38 = r12 + 0x18;
	union Eq_n * r44 = 0x00 + 0x007F;
	word64 r33 = 0x00 + 0x00;
	word64 r42 = LC;
	int64 r35 = 0x00 + 0x00;
	union Eq_n * r0;
	r0->u2 = (struct Eq_n *) r38;
	int32 v20 = (int32) r33;
	union Eq_n * r34 = (int64) v20;
	<anonymous> * b0;
	b0();
	r1 = r41 + 0x00;
	Eq_n p06 = 0x00 == r8;
	Eq_n p07 = 0x00 != r8;
	r43 = &r32->u0;
	if (p06)
	{
l40000000000923D0:
		r8 = &r32->u0;
		ar.pfs = r40;
		LC = r42;
		b0 = r39;
		r12 += 0x10;
		return;
	}
	struct Eq_n * r37 = r1 + -9996;
	r37 = r37->ptr0000;
	b0();
	union Eq_n * r36 = r8 + 0x00;
	r1 = r41 + 0x00;
	p06 = r34 < r36;
	p07 = r34 >= r36;
	if (p07)
	{
		int32 v33 = (int32) r35;
		r35 = (int64) v33;
		r35 = &r32->u0 + r35;
		r0->u0 = (byte) (byte) r35;
		goto l40000000000923D0;
	}
	struct Eq_n * r14 = r34 + r32;
	Eq_n v29;
	v29.u0 = r14->t0000.u0;
	r14 = (word64) v29;
	int8 v30 = (int8) r14;
	r14 = (int64) v30;
	word32 v31 = (word32) 0x01;
	word32 v32 = (word32) r14;
	p07 = v31 == v32;
	p06 = v31 != v32;
	up64 r18;
	if (!p07)
	{
		word32 v34 = (word32) 0x7F;
		word32 v35 = (word32) r14;
		p07 = v34 == v35;
		p06 = v34 != v35;
		if (p07)
			r18 = r33 + 0x01;
	}
	int32 v37 = (int32) r35;
	Eq_n r15;
	r15.u2 = (int64) v37;
	++r33;
	++r35;
	int32 v39 = (int32) r33;
	r34 = (int64) v39;
	r15.u2 = r15 + r32;
	r14->t0000.u0 = (byte) (byte) r15;
	p06 = r36 == r34;
	p07 = r36 != r34;
	if (!p07)
	{
		int32 v40 = (int32) r35;
		r35 = (int64) v40;
		r35 = &r32->u0 + r35;
		r0->u0 = (byte) (byte) r35;
		goto l40000000000923D0;
	}
	b0();
	r44 = r34 + r32;
	r1 = r41 + 0x00;
	p07 = 0x01 < r8;
	p06 = 0x01 >= r8;
	if (p06)
		r18 = r33 + 0x01;
	else
	{
		Eq_n v41;
		v41.u0 = r44->u0;
		r14 = (word64) v41;
		int8 v42 = (int8) r14;
		r14 = (int64) v42;
		word3 v43 = SLICE(r14, word3, 5);
		ui64 r16 = (word64) v43;
		r15 = r14 & 0x1F;
		r14 = (struct Eq_n *) ((char *) &r37->ptr0000 + (r16 << 0x02));
		Eq_n v45;
		v45.u1 = r14->t0000.u1;
		r14 = (word64) v45;
		r14 >>= r15;
		if (!p07)
		{
			if (p06)
				r18 = 0x00 + 1;
			__break();
			__break();
l40000000000922B2:
			int32 v48 = (word32) r35;
			int32 v49 = (word32) r33;
			p07 = v48 < v49;
			p06 = v48 >= v49;
			if (p06)
				r35 = r18 + 0x00;
		}
		r14 = r38.u2->ptr0000;
		r15 = r12 + 0x10;
		r43 = 0x00 + 0x00;
		union Eq_n * r45 = r34 - r36;
		word64 * r46 = &r38.u2->ptr0000;
		r14->t0000.u2 = (struct Eq_n *) r15;
		b0();
		r14 = r8 + 0x02;
		r15 = r12 + 0x10;
		r1 = r41 + 0x00;
		r18 = r33 + 0x01;
		p06 = (struct Eq_n *) 0x01 < r14;
		p07 = (struct Eq_n *) 0x01 >= r14;
		if (p06)
		{
			p06 = 0x00 == r8;
			p07 = 0x00 != r8;
			if (p07)
				r18 = r8 + 0x00;
		}
		r14 = r15.u2->ptr0000;
		r14->t0000.u2 = (struct Eq_n *) r38;
	}
	goto l40000000000922B2;
}

// 4000000000092540: define list_string
// Called from:
//      word_split
define list_string
{
	word64 b0;
	word64 LC;
	word64 r33;
	word64 r1;
	byte * r32;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r49 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r51 = pr;
	Eq_n p07 = null == r32;
	Eq_n p06 = null != r32;
	word64 r50 = r1 + 0x00;
	Eq_n p08 = 0x00 == r33;
	Eq_n p09 = 0x00 != r33;
	word64 r52 = LC;
	word64 r48 = b0;
	if (!p07)
	{
		byte v21 = *r32;
		int64 r14 = (word64) v21;
		int8 v23 = (int8) r14;
		r14 = (int64) v23;
		word32 v24 = (word32) 0x00;
		word32 v25 = (word32) r14;
		p06 = v24 == v25;
		p07 = v24 != v25;
		if (!p06)
		{
			Eq_n p01;
			if (p01)
			{
				word64 r64;
				r64 == r33;
				Eq_n p11 = r64 != r33;
			}
			word64 p16;
			if (p16)
				__break();
			if (p16)
			{
				word64 r112;
				0x00 == r112;
				p01 = 0x00 != r112;
			}
			word64 p02;
			if (p02)
				__break();
		}
	}
	word64 r41 = 0x00 + 0x00;
	word64 r8 = r41 + 0x00;
	pr = r51;
	ar.pfs = r49;
	LC = r52;
	b0 = r48;
	r12 += 0x10;
}

// 4000000000093340: define word_list_remove_quoted_nulls
define word_list_remove_quoted_nulls
{
	<anonymous> * b4;
	word64 r32;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r37 = ar.pfs;
	word64 r38 = r1 + 0x00;
	struct Eq_n * r33 = r32 + 0x00;
	<anonymous> * r36 = b4;
	Eq_n p07 = 0x00 == r32;
	Eq_n p06 = 0x00 != r32;
	ui64 r35 = 0x00 + -0x00040001;
	<anonymous> * b0;
	if (!p07)
	{
		do
		{
			union Eq_n ** r34 = (union Eq_n **) ((char *) &r33->ptr0000 + 8);
			union Eq_n * r14 = (union Eq_n *) *r34;
			Eq_n r39;
			r39.u0 = r14->u0;
			b0();
			r14 = (union Eq_n *) *r34;
			r1 = r38 + 0x00;
			r33 = r33->ptr0000;
			r14 = (union Eq_n *) ((char *) r14 + 8);
			p07 = null == r33;
			p06 = null != r33;
			Eq_n v19;
			v19.u1 = r14->u1;
			word32 * r15 = (word64) v19;
			r15 &= r35;
			*r15 = (word32) r14;
		} while (p06);
	}
	ar.pfs = r37;
	b0 = r36;
}

// 4000000000093400: define string_list_pos_params
define string_list_pos_params
{
	word64 r1;
	word64 r32;
	<anonymous> * b3;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	<anonymous> * r35 = b3;
	word32 v9 = (word32) 0x2A;
	word32 v10 = (word32) r32;
	Eq_n p07 = v9 == v10;
	Eq_n p06 = v9 != v10;
	word64 r37 = r1 + 0x00;
	ui64 r33;
	<anonymous> * b0;
	word64 r2;
	ui64 r38;
	word64 r8;
	if (!p07)
	{
		word32 v15 = (word32) 0x40;
		word32 v16 = (word32) r32;
		p07 = v15 == v16;
		p06 = v15 != v16;
		r32 = r33 + 0x00;
		ar.pfs = r36;
		ui64 r34;
		if (!p07)
		{
			r34 &= 0x03;
			b0 = r35;
			word32 v20 = (word32) 0x00;
			word32 v21 = (word32) r34;
			p06 = v20 == v21;
			p07 = v20 != v21;
			if (!p07)
			{
				r2 = ar.pfs;
				string_list();
			}
			else
			{
				r38 = r33 + 0x00;
				b0();
				r33 = r8 + 0x00;
				r1 = r37 + 0x00;
				b0 = r35;
				r32 = r33 + 0x00;
				ar.pfs = r36;
				r2 = ar.pfs;
				string_list();
			}
		}
		else
		{
			ui64 r14 = r34 & 0x03;
			r32 = r33 + 0x00;
			b0 = r35;
			word32 v23 = (word32) 0x00;
			word32 v24 = (word32) r14;
			p06 = v23 == v24;
			p07 = v23 != v24;
			ar.pfs = r36;
			if (!p07)
			{
				r2 = ar.pfs;
				string_list_dollar_star();
			}
			else
			{
				r33 = r34 + 0x00;
				b0 = r35;
				ar.pfs = r36;
				r2 = ar.pfs;
				string_list_dollar_at();
			}
		}
	}
	else
	{
		r32 = r33 + 0x00;
		if (!p07)
		{
			if (!p07)
			{
				b0 = r35;
				ar.pfs = r36;
				r2 = ar.pfs;
				string_list_dollar_star();
			}
			else
			{
				r38 = r33 + 0x00;
				b0();
				r1 = r37 + 0x00;
				r32 = r8 + 0x00;
				r38 = r8 + 0x00;
				b0();
				r1 = r37 + 0x00;
				b0 = r35;
				ar.pfs = r36;
				r2 = ar.pfs;
				string_list();
			}
		}
		else
		{
			r38 = r33 + 0x00;
			b0();
			r1 = r37 + 0x00;
			r32 = r8 + 0x00;
			r38 = r8 + 0x00;
			b0();
			r1 = r37 + 0x00;
			b0 = r35;
			ar.pfs = r36;
			r2 = ar.pfs;
			string_list_dollar_star();
		}
	}
}

// 4000000000093880: define copy_fifo_list
define copy_fifo_list
{
	word64 r32;
	word64 b2;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word32 * r14 = r1 + 7576;
	word64 r34 = b2;
	word64 r36 = r1 + 0x00;
	word32 * r33 = r1 + 7572;
	Eq_n p08 = 0x00 == r32;
	Eq_n p09 = 0x00 != r32;
	word32 v15 = *r14;
	r14 = (word64) v15;
	word64 r8 = 0x00 + 0x00;
	word32 v17 = (word32) 0x00;
	word32 v18 = (word32) r14;
	Eq_n p06 = v17 == v18;
	Eq_n p07 = v17 != v18;
	if (!p06)
	{
		word32 v21 = *r33;
		r14 = (word64) v21;
		__break();
		word64 p04;
		if (p04)
			__break();
		r1 == 0x00;
		Eq_n p24 = r1 != 0x00;
		word64 pr = r32;
	}
	else if (p09)
	{
		word32 * r0;
		*r0 = (word32) r32;
	}
}

// 40000000000939C0: define fifos_pending
define fifos_pending
{
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r8 = 0x00 + 0x00;
}

// 4000000000093A00: define num_fifos
define num_fifos
{
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r14 = r1 + 7576;
	word32 v6 = *r14;
	word64 r8 = (word64) v6;
}

// 4000000000093A40: define unlink_fifo
define unlink_fifo
{
	word64 r64;
	word64 r32;
	word64 b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	byte ** r34 = r1 + 7564;
	word64 r35 = b3;
	word64 r37 = r1 + 0x00;
	int32 v12 = (int32) r32;
	int64 r33 = (int64) v12;
	byte * r14 = (byte *) *r34;
	ar.pfs = r36;
	r14 += r33;
	word64 b0 = r35;
	byte v16 = *r14;
	r14 = (word64) v16;
	int8 v17 = (int8) r14;
	r14 = (int64) v17;
	word32 v18 = (word32) 0x00;
	word32 v19 = (word32) r14;
	Eq_n p06 = v18 == v19;
	Eq_n p07 = v18 != v19;
	if (!p07)
	{
		r33 < 0x00;
		Eq_n p17 = r33 >= 0x00;
		__break();
		Eq_n p08;
		if (p08)
		{
			int32 v28 = (word32) r64;
			int32 v29 = (word32) 0x00;
			Eq_n p04 = v28 < v29;
			p08 = v28 >= v29;
		}
	}
	else
	{
		word64 r38 = r32 + 0x00;
		__break();
	}
}

// 4000000000093B00: define unlink_fifo_list
// Called from:
//      close_new_fifos
define unlink_fifo_list
{
	<anonymous> * b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word32 * r33 = r1 + 7576;
	word32 * r34 = r1 + 7572;
	<anonymous> * r35 = b3;
	word64 r37 = r1 + 0x00;
	word32 v12 = *r33;
	word64 r14 = (word64) v12;
	word64 r32 = 0x00 + 0x00;
	word32 v15 = (word32) 0x00;
	word32 v16 = (word32) r14;
	Eq_n p06 = v15 == v16;
	Eq_n p07 = v15 != v16;
	<anonymous> * b0;
	if (!p06)
	{
		word32 v20 = *r34;
		r14 = (word64) v20;
		int32 v21 = (word32) 0x00;
		int32 v22 = (word32) r14;
		p07 = v21 < v22;
		p06 = v21 >= v22;
		if (!p06)
		{
			do
			{
				word64 r38 = r32 + 0x00;
				++r32;
				b0();
				word32 v25 = *r33;
				r14 = (word64) v25;
				r1 = r37 + 0x00;
				word32 v26 = (word32) 0x00;
				word32 v27 = (word32) r14;
				p06 = v26 == v27;
				p07 = v26 != v27;
				if (p06)
					break;
				word32 v28 = *r34;
				r14 = (word64) v28;
				int32 v29 = (word32) r32;
				int32 v30 = (word32) r14;
				p06 = v29 < v30;
				p07 = v29 >= v30;
			} while (p06);
		}
		word32 * r0;
		*r0 = (word32) r33;
	}
	ar.pfs = r36;
	b0 = r35;
}

// 4000000000093C00: define close_new_fifos
define close_new_fifos
{
	int64 r96;
	int64 r24;
	<anonymous> * b6;
	int64 r1;
	Eq_n LC;
	word64 r33;
	word64 r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r39 = ar.pfs;
	Eq_n p06 = 0x00 == r32;
	Eq_n p07 = 0x00 != r32;
	Eq_n r14 = r33 + ~0x00;
	Eq_n r41 = LC;
	word32 * r36 = r1 + 7572;
	word64 r34 = 0x00 + 0x00;
	r14 = __addp4(0x00, r14);
	<anonymous> * r38 = b6;
	word64 r35 = r32 + 0x00;
	union Eq_n * r37 = r1 + 7564;
	<anonymous> * b0;
	if (p06)
	{
		b0 = r38;
		ar.pfs = r39;
		LC = r41;
		word64 r2 = ar.pfs;
		unlink_fifo_list();
		return;
	}
	int32 v20 = (word32) 0x00;
	int32 v21 = (word32) r33;
	p06 = v20 < v21;
	p07 = v20 >= v21;
	word64 r40 = r1 + 0x00;
	word32 v23 = *r36;
	word64 r16 = (word64) v23;
	word64 r42;
	if (p07)
	{
l4000000000093CF0:
		r34 = r33 + 0x00;
		int32 v27 = (word32) r33;
		int32 v28 = (word32) r16;
		p06 = v27 < v28;
		p07 = v27 >= v28;
		if (!p07)
		{
			do
			{
				r42 = r34 + 0x00;
				++r34;
				b0();
				word32 v51 = *r36;
				r14.u2 = (word64) v51;
				r1 = r40 + 0x00;
				int32 v52 = (word32) r34;
				int32 v53 = (word32) r14;
				p06 = v52 < v53;
				p07 = v52 >= v53;
			} while (p06);
		}
		ar.pfs = r39;
		LC = r41;
		b0 = r38;
		return;
	}
	if (p06)
		LC = r14;
	__break();
	__break();
	r1 < 0x00;
	Eq_n p03 = r1 >= 0x00;
	while (true)
	{
l4000000000093C80:
		word64 p02;
		if (p02)
		{
			Eq_n p34 = r24 < r96;
			Eq_n p01 = r24 >= r96;
		}
		if (p02)
			__break();
		word64 p12;
		if (p12)
			__break();
		word64 p08;
		if (p08)
			break;
		r14.u2 = r37->u2;
		r14.u2 = (char *) r14.u2 + r34;
		byte v56 = r14.u3->t0000.u0;
		r14.u2 = (word64) v56;
		int8 v57 = (int8) r14;
		r14.u2 = (int64) v57;
		word32 v58 = (word32) 0x00;
		word32 v59 = (word32) r14;
		p06 = v58 == v59;
		p07 = v58 != v59;
		if (!p07)
			break;
		r42 = r34 + 0x00;
		++r34;
		b0();
		r1 = r40 + 0x00;
		word32 v60 = *r36;
		r16 = (word64) v60;
		if (LC == 0x00)
			goto l4000000000093CF0;
		--LC;
	}
	++r34;
	if (LC == 0x00)
		goto l4000000000093CF0;
	--LC;
	goto l4000000000093C80;
}

// 4000000000093E00: define command_substitute
define command_substitute
{
	int64 r70;
	int64 r63;
	word64 r43;
	<anonymous> * b2;
	union Eq_n * r32;
	word64 pr;
	Eq_n LC;
	word64 r12;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r51 = ar.pfs;
	Eq_n r16 = r12 + 0x00;
	r12 += ~0xBF;
	Eq_n r17 = LC;
	Eq_n r14 = r12 + 0xA0;
	word64 r52 = pr;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	r32->u2 = (word32 *) r14;
	<anonymous> * r50 = b2;
	Eq_n r8;
	r16.u3->t0000.u2 = (word32 *) r8;
	r16.u1 = (word32) r16 + 8;
	Eq_n r1;
	r1.u3->t0000.u2 = (word32 *) r16;
	Eq_n r18;
	Eq_n r19;
	<anonymous> * b0;
	if (p06)
	{
l40000000000944E0:
		r8 = 0x00 + 0x00;
		r18 = r12 + 0xC0;
		pr = r52;
		r19.u2 = r18.u1->u2;
		ar.pfs = r51;
		LC = r19;
		b0 = r50;
		r12 += 0xC0;
		return;
	}
	Eq_n v20;
	v20.u0 = r32->u0;
	r14.u2 = (word64) v20;
	int8 v21 = (int8) r14;
	r14.u2 = (int64) v21;
	word32 v22 = (word32) 0x00;
	word32 v23 = (word32) r14;
	p06 = v22 == v23;
	p07 = v22 != v23;
	if (p06)
		goto l40000000000944E0;
	word32 v27 = (word32) 0x0A;
	word32 v28 = (word32) r14;
	p07 = v27 == v28;
	p06 = v27 != v28;
	if (p07)
	{
l40000000000944A0:
		r14.u2 = (char *) r32 + 1;
		Eq_n v32;
		v32.u0 = r14.u3->t0000.u0;
		r14.u2 = (word64) v32;
		int8 v33 = (int8) r14;
		r14.u2 = (int64) v33;
		word32 v34 = (word32) 0x00;
		word32 v35 = (word32) r14;
		p06 = v34 == v35;
		p07 = v34 != v35;
		if (!p07)
			goto l40000000000944E0;
	}
	r14.u1 = (word32) r1 + 6464;
	Eq_n v29;
	v29.u1 = *r14.u2;
	r14.u2 = (word64) v29;
	word32 v30 = (word32) 0x00;
	word32 v31 = (word32) r14;
	p06 = v30 == v31;
	p07 = v30 != v31;
	word32 * r15;
	union Eq_n * r0;
	if (!p07)
	{
l4000000000093EC0:
		r14.u1 = (word32) r1 + 7540;
		r14.u2 = r14.u3->t0000.u2;
		p06 = 0x00 == r14;
		p07 = 0x00 != r14;
		r14.u1 = (word32) r1 + 7588;
		if (p06)
		{
l4000000000095050:
			b0();
			r1 = r12 + 200;
			r1.u2 = r1.u3->t0000.u2;
			r14.u1 = (word32) r1 + 6516;
			Eq_n v39;
			v39.u1 = *r14.u2;
			r14.u2 = (word64) v39;
			word32 v40 = (word32) 0x00;
			word32 v41 = (word32) r14;
			p06 = v40 == v41;
			p07 = v40 != v41;
			if (p06)
				r14 = r12 + 0xB0;
		}
		r14.u2 = r14.u3->t0000.u2;
		p07 = 0x00 == r14;
		p06 = 0x00 != r14;
		r14.u1 = (word32) r1 + 6516;
		if (p07)
			goto l4000000000095050;
		Eq_n v59;
		v59.u1 = *r14.u2;
		r14.u2 = (word64) v59;
		word32 v60 = (word32) 0x00;
		word32 v61 = (word32) r14;
		p06 = v60 == v61;
		p07 = v60 != v61;
		if (!p07)
		{
			if (p06)
				r14 = r12 + 0xB0;
		}
		r14.u1 = (word32) r1 + 8412;
		r15 = 0x00 + 16;
		Eq_n v69;
		v69.u1 = *r14.u2;
		r14.u2 = (word64) v69;
		word32 v70 = (word32) 0x00;
		word32 v71 = (word32) r14;
		p07 = v70 == v71;
		p06 = v70 != v71;
		r14 = r12 + 0xB0;
		if (p06)
			r0->u1 = (word32) (word32) r14;
		goto l40000000000943E2;
	}
	r14.u1 = (word32) r1 + 7392;
l40000000000943E2:
	Eq_n v36;
	v36.u1 = *r14.u2;
	r14.u2 = (word64) v36;
	word32 v37 = (word32) 0x00;
	word32 v38 = (word32) r14;
	p06 = v37 == v38;
	p07 = v37 != v38;
	if (p06)
		goto l4000000000093EC0;
	r14.u1 = (word32) r1 + 9044;
	r15 = 0x00 + 0x007D;
	Eq_n r53 = 0x00 + 3;
	*r15 = (word32) r14;
	b0();
	Eq_n v44;
	v44.u0 = r17.u3->t0000.u0;
	r14.u2 = (word64) v44;
	r17.u1 = (word32) r17 + 1;
	int8 v45 = (int8) r14;
	r14.u2 = (int64) v45;
	word32 v46 = (word32) 0x00;
	word32 v47 = (word32) r14;
	p07 = v46 == v47;
	p06 = v46 != v47;
	word32 v48 = (word32) 0x7F;
	word32 v49 = (word32) r14;
	Eq_n p08 = v48 == v49;
	Eq_n p09 = v48 != v49;
	Eq_n p17;
	if (p07)
	{
		ui64 r33;
		r14 = r33 & 0x03;
		union Eq_n * r48 = (union Eq_n *) ((word32) r1 + 9092);
		int32 v55 = (word32) r43;
		int32 v56 = (word32) 0x00;
		p06 = v55 < v56;
		p07 = v55 >= v56;
		word32 * r44 = 0x00 + 0x00;
		Eq_n r38 = 0x00 + 0x00;
		word32 * r41;
		word32 * r47;
		if (p06)
		{
			r14 = r12 + 0x90;
			r44 = 0x00 + 0x00;
			r38 = 0x00 + 0x00;
			Eq_n v64;
			v64.u1 = *r14.u2;
			r53.u0 = (word64) v64;
			b0();
			r1 = r12 + 200;
			r53.u0 = r41;
			r1.u2 = r1.u3->t0000.u2;
			r14.u1 = (word32) r1 + 5956;
			*r41 = (word32) r14;
			b0();
			r1 = r12 + 200;
			r1.u2 = r1.u3->t0000.u2;
			r14.u1 = (word32) r1 + 9044;
			*r8.u2 = (word32) (word32) r14;
			r14.u1 = (word32) r1 + 5960;
			*r41 = (word32) r14;
			r14 = 0x00 + 0x0082;
			word32 v66 = (word32) r14;
			word32 v67 = (word32) r8;
			p07 = v66 == v67;
			p06 = v66 != v67;
			r14.u1 = (word32) r1 + 5876;
			*r47 = (word32) r14;
			if (p06)
				goto l4000000000094740;
			goto l40000000000950C0;
		}
		Eq_n r39 = 0x00 + 0x00;
		word64 r34 = 0x00 + 0x00;
		word32 * r35 = 0x00 + 0x00;
		word32 v92 = (word32) 0x00;
		word32 v93 = (word32) r14;
		Eq_n p16 = v92 == v93;
		p17 = v92 != v93;
		byte * r40 = 0x00 + 1;
		word64 r45 = 0x00200000;
		int64 r54;
		Eq_n r36;
		Eq_n r49;
		do
		{
			r35 = (word32 *) ((char *) r35 - 1);
			p06 = null < r35;
			p07 = null >= r35;
			byte * r37;
			if (p07)
			{
				do
				{
					r53 = r43 + 0x00;
					r54 = r12 + 0x10;
					word64 r55 = 0x00 + 0x0080;
					r37 = r12 + 0x10;
					b0();
					r1 = r12 + 200;
					p07 = 0x00 < r8;
					p06 = 0x00 >= r8;
					r35 = r8.u2;
					r1.u2 = r1.u3->t0000.u2;
					if (p06)
					{
						int32 v107 = (int32) r34;
						r14.u2 = (int64) v107;
						p06 = 0x00 == r38;
						p07 = null != r38;
						if (p06)
						{
							word32 v112 = (word32) 0x00;
							word32 v113 = (word32) r34;
							p06 = v112 == v113;
							p07 = v112 != v113;
							if (p06)
								goto l4000000000094690;
						}
						else
						{
							r14.u2 = r14 + r38;
							word32 v110 = (word32) 0x00;
							word32 v111 = (word32) r34;
							p07 = v110 == v111;
							p06 = v110 != v111;
							r0->u0 = (byte) (byte) r14;
							if (!p06)
							{
								r53.u0 = r38 + 0x00;
								r38 = 0x00 + 0x00;
								b0();
								r1 = r12 + 200;
								r1.u2 = r1.u3->t0000.u2;
l4000000000094690:
								r14 = r12 + 0x90;
								Eq_n v120;
								v120.u1 = *r14.u2;
								r53.u0 = (word64) v120;
								b0();
								r1 = r12 + 200;
								r53.u0 = r41;
								r1.u2 = r1.u3->t0000.u2;
								r14.u1 = (word32) r1 + 5956;
								*r41 = (word32) r14;
								b0();
								r1 = r12 + 200;
								r1.u2 = r1.u3->t0000.u2;
								r14.u1 = (word32) r1 + 9044;
								*r8.u2 = (word32) (word32) r14;
								r14.u1 = (word32) r1 + 5960;
								*r41 = (word32) r14;
								r14 = 0x00 + 0x0082;
								word32 v121 = (word32) r14;
								word32 v122 = (word32) r8;
								p07 = v121 == v122;
								p06 = v121 != v122;
								r14.u1 = (word32) r1 + 5876;
								*r47 = (word32) r14;
								if (p07)
									goto l40000000000950C0;
								goto l4000000000094740;
							}
						}
						r33 &= 0x03;
						word32 v118 = (word32) 0x00;
						word32 v119 = (word32) r33;
						p07 = v118 == v119;
						p06 = v118 != v119;
						if (!p07)
						{
							if (p06)
								r18 = r38 - 0x01;
							__break();
							pr = 0x4000;
							__break();
							if (!p08)
							{
								word64 p63;
								if (p63)
								{
									Eq_n p34 = r63 < r70;
									Eq_n p03 = r63 >= r70;
								}
								word64 p20;
								if (p20)
									__break();
								__break();
							}
						}
						r54 = r34 + ~0x00;
						r55 = 0x00 + 1;
						r53.u0 = r38 + 0x00;
						b0();
						r14 = r12 + 0x90;
						r1 = r12 + 200;
						Eq_n v124;
						v124.u1 = *r14.u2;
						r53.u0 = (word64) v124;
						r1.u2 = r1.u3->t0000.u2;
						b0();
						r1 = r12 + 200;
						r53.u0 = r41;
						r1.u2 = r1.u3->t0000.u2;
						r14.u1 = (word32) r1 + 5956;
						*r41 = (word32) r14;
						b0();
						r1 = r12 + 200;
						r1.u2 = r1.u3->t0000.u2;
						r14.u1 = (word32) r1 + 9044;
						*r8.u2 = (word32) (word32) r14;
						r14.u1 = (word32) r1 + 5960;
						*r41 = (word32) r14;
						r14 = 0x00 + 0x0082;
						word32 v125 = (word32) r14;
						word32 v126 = (word32) r8;
						p07 = v125 == v126;
						p06 = v125 != v126;
						r14.u1 = (word32) r1 + 5876;
						*r47 = (word32) r14;
						if (!p06)
						{
l40000000000950C0:
							r14.u1 = (word32) r1 + 0x00002338;
							Eq_n v85;
							v85.u1 = *r14.u2;
							r14.u2 = (word64) v85;
							word32 v86 = (word32) 0x02;
							word32 v87 = (word32) r14;
							p07 = v86 == v87;
							p06 = v86 != v87;
							if (!p06)
							{
								b0();
								r1 = r12 + 200;
								r53.u0 = r8.u2;
								r54 = 0x00 + 2;
								r1.u2 = r1.u3->t0000.u2;
								b0();
								r1 = r12 + 200;
								r1.u2 = r1.u3->t0000.u2;
							}
							goto l4000000000094740;
						}
l4000000000094740:
						r14.u1 = (word32) r1 + 6516;
						Eq_n v76;
						v76.u1 = *r14.u2;
						r14.u2 = (word64) v76;
						word32 v77 = (word32) 0x00;
						word32 v78 = (word32) r14;
						p06 = v77 == v78;
						p07 = v77 != v78;
						if (!p06)
						{
							r14.u1 = (word32) r1 + 7436;
							Eq_n v80;
							v80.u1 = *r14.u2;
							r53.u0 = (word64) v80;
							word32 v81 = (word32) 0x00;
							word32 v82 = (word32) r53;
							p06 = v81 == v82;
							p07 = v81 != v82;
							if (!p06)
							{
								r14.u1 = (word32) r1 + 0x00002344;
								Eq_n v84;
								v84.u1 = *r14.u2;
								r14.u2 = (word64) v84;
								if (p07)
								{
									r54 = 0x00 + 0x00;
									b0();
									r1 = r12 + 200;
									r1.u2 = r1.u3->t0000.u2;
									b0();
									r1 = r12 + 200;
									r14.u2 = r8.u2;
									r1.u2 = r1.u3->t0000.u2;
									r14.u3->t0000.u2 = (word32 *) r8;
									r14.u2 = r14 + 8;
									*r44 = (word32) r14;
l4000000000094820:
									r18 = r12 + 0xC0;
									pr = r52;
									r19.u2 = r18.u1->u2;
									ar.pfs = r51;
									LC = r19;
									b0 = r50;
									r12 += 0xC0;
									return;
								}
							}
						}
						b0();
						r1 = r12 + 200;
						r14.u2 = r8.u2;
						r1.u2 = r1.u3->t0000.u2;
						r14.u3->t0000.u2 = (word32 *) r8;
						r14.u2 = r14 + 8;
						*r44 = (word32) r14;
						goto l4000000000094820;
					}
					word64 p31;
					if (p31)
						__break();
					__break();
					if (p16)
						__break();
					r14.u2 = r48->u2;
					p06 = 0x00 == r14;
					p07 = 0x00 != r14;
					if (!p06)
					{
						Eq_n v142;
						v142.u0 = r14.u3->t0000.u0;
						r14.u2 = (word64) v142;
						int8 v143 = (int8) r14;
						r14.u2 = (int64) v143;
						word32 v144 = (word32) 0x00;
						word32 v145 = (word32) r14;
						p07 = v144 == v145;
						p06 = v144 != v145;
						if (!p06)
							goto l40000000000945E0;
					}
					int32 v146 = (int32) r34;
					r14.u2 = (int64) v146;
					++r34;
					r14.u2 = r14 + r38;
					r36.u1->u0 = (byte) (byte) r14;
l4000000000094370:
					r35 = (word32 *) ((char *) r35 - 1);
					p06 = null < r35;
					p07 = null >= r35;
				} while (!p06);
			}
			byte v98 = *r37;
			r14.u2 = (word64) v98;
			++r37;
			int8 v99 = (int8) r14;
			r14.u2 = (int64) v99;
			r36.u0 = r14 + 0x00;
			r49.u0 = r14 + 0x00;
			word32 v102 = (word32) 0x00;
			word32 v103 = (word32) r14;
			p06 = v102 == v103;
			p07 = v102 != v103;
		} while (p06);
		r15 = r34 + 0x02;
		int32 v105 = (word32) r15;
		int32 v106 = (word32) r39;
		p06 = v105 < v106;
		p07 = v105 >= v106;
		if (!p06)
		{
			r17 = r39 - r15;
			r39 = (word32) r39 + 0x0080;
			r53.u0 = r38.u0;
			int25 v108 = SLICE(r17, int25, 7);
			r17.u2 = (int64) v108;
			r39 = r17 + r39;
			int32 v109 = (int32) r39;
			r54 = (int64) v109;
			b0();
			r1 = r12 + 200;
			r38.u0 = r8.u2;
			r1.u2 = r1.u3->t0000.u2;
		}
		if (!p17)
		{
			word32 v114 = (word32) 0x01;
			word32 v115 = (word32) r49;
			p06 = v114 == v115;
			p07 = v114 != v115;
			if (p06)
				r17 = 0x00 + 1;
			word64 p02;
			if (p02)
				__break();
			__break();
			if (p16)
				__break();
			__break();
			bool v136 = (bool) r44;
			word64 r24 = (word64) v136;
		}
l40000000000945E0:
		int32 v116 = (int32) r34;
		r14.u2 = (int64) v116;
		++r34;
		r14.u2 = r14 + r38;
		*r40 = (byte) r14;
		int32 v117 = (int32) r34;
		r14.u2 = (int64) v117;
		++r34;
		r14.u2 = r14 + r38;
		r36.u1->u0 = (byte) (byte) r14;
		goto l4000000000094370;
	}
	word32 v62 = (word32) 0x01;
	word32 v63 = (word32) r14;
	p06 = v62 == v63;
	p07 = v62 != v63;
	if (p08)
		r14 = 0x00 + 1;
	int64 r72;
	0x00 < r72;
	Eq_n p43 = 0x00 >= r72;
	word64 p01;
	if (p01)
	{
		fn4000000000CB446C();
		return;
	}
	word64 p33;
	if (p33)
		__break();
	if (p17)
		__break();
	__break();
	goto l40000000000944A0;
}

// 4000000000095600: define pat_subst
define pat_subst
{
	<anonymous> * b0;
	<anonymous> * r33;
	word64 LC;
	ui64 r35;
	byte * r32;
	word64 r1;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r65 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	word64 r67 = pr;
	word64 r66 = r1 + 0x00;
	Eq_n p07 = null == r32;
	Eq_n p06 = null != r32;
	ui64 r47 = r35 & 0x03;
	word64 r68 = LC;
	Eq_n p24 = null == r33;
	Eq_n p25 = null != r33;
	<anonymous> * r64 = b0;
	byte * r69;
	byte * r0;
	byte * r8;
	byte * r39;
	if (!p07)
	{
		Eq_n p26;
		Eq_n p11;
		if (p26)
		{
			r64 < r33;
			p11 = r64 >= r33;
		}
		Eq_n p16;
		if (p16)
			__break();
		Eq_n p01;
		if (p16)
		{
			int64 r96;
			0x00 < r96;
			p01 = 0x00 >= r96;
		}
		word64 p02;
		if (p02)
			__break();
		r69 = 0x00 + 64;
		b0();
		r1 = r66 + 0x00;
		*r0 = (byte) r8;
		r39 = r8;
		byte * r34;
		p06 = null == r34;
		p07 = null != r34;
		byte * r14;
		word64 r41;
		Eq_n p03;
		if (!p06)
		{
			byte v35 = *r34;
			r14 = (word64) v35;
			int8 v37 = (int8) r14;
			r14 = (int64) v37;
			word32 v38 = (word32) 0x00;
			word32 v39 = (word32) r14;
			p06 = v38 == v39;
			p07 = v38 != v39;
			if (!p06)
			{
				r14 = r34 + 1;
				byte v70 = *r14;
				r14 = (word64) v70;
				int8 v71 = (int8) r14;
				r14 = (int64) v71;
				word32 v72 = (word32) 0x00;
				word32 v73 = (word32) r14;
				p06 = v72 == v73;
				p07 = v72 != v73;
				if (p06)
					r41 = 0x00 + 1;
				if (p03)
				{
					null < r33;
					p11 = null >= r33;
				}
			}
		}
		r41 = 0x00 + 0x00;
		word64 r45 = r1 + 7664;
		byte * r37 = 0x00 + 64;
		ptr64 r38 = 0x00 + 0x00;
		word64 r53 = r12 + 0x18;
		word64 r56 = r12 + 0x20;
		word32 v46 = (word32) 0x01;
		word32 v47 = (word32) r47;
		p26 = v46 == v47;
		Eq_n p27 = v46 != v47;
		word64 r40 = r12 + 0x30;
		word64 r42 = r12 + 0x28;
		word32 v51 = (word32) 0x02;
		word32 v52 = (word32) r47;
		Eq_n p28 = v51 == v52;
		Eq_n p29 = v51 != v52;
		word32 v55 = (word32) 0x00;
		word32 v56 = (word32) r47;
		Eq_n p30 = v55 == v56;
		Eq_n p31 = v55 != v56;
		word64 r60 = 0x00 + 42;
		word32 v60 = (word32) 0x00;
		word32 v61 = (word32) r41;
		Eq_n p18 = v60 == v61;
		Eq_n p19 = v60 != v61;
		word32 v64 = (word32) 0x00;
		word32 v65 = (word32) r47;
		Eq_n p21 = v64 == v65;
		Eq_n p20 = v64 != v65;
		int32 v68 = (int32) r41;
		int64 r54 = (int64) v68;
		byte v74 = *r32;
		r14 = (word64) v74;
		int8 v75 = (int8) r14;
		r14 = (int64) v75;
		word32 v76 = (word32) 0x00;
		word32 v77 = (word32) r14;
		p06 = v76 == v77;
		p07 = v76 != v77;
		if (!p06)
		{
			word64 p60;
			if (p60)
			{
				p01 = r64 < r33;
				p03 = r64 >= r33;
			}
		}
		else
		{
			p06 = null == r32;
			p07 = null != r32;
			if (p07)
			{
				byte v80 = *r32;
				r14 = (word64) v80;
				byte * r15 = r32 + 1;
				int32 v82 = (int32) r38;
				int64 r36 = (int64) v82;
				int8 v84 = (int8) r14;
				r14 = (int64) v84;
				word32 v85 = (word32) 0x00;
				word32 v86 = (word32) r14;
				p06 = v85 == v86;
				p07 = v85 != v86;
				if (!p06)
				{
					byte v87 = *r15;
					r14 = (word64) v87;
					byte * r16 = r32 + 2;
					r8 = 0x00 + 2;
					int8 v89 = (int8) r14;
					r14 = (int64) v89;
					word32 v90 = (word32) 0x00;
					word32 v91 = (word32) r14;
					p16 = v90 == v91;
					Eq_n p17 = v90 != v91;
					if (!p16)
					{
						byte v94 = *r16;
						r14 = (word64) v94;
						r69 = r32;
						r8 = 0x00 + 3;
						int8 v95 = (int8) r14;
						r14 = (int64) v95;
						word32 v96 = (word32) 0x00;
						word32 v97 = (word32) r14;
						p06 = v96 == v97;
						p07 = v96 != v97;
						if (!p06)
						{
							b0();
							r1 = r66 + 0x00;
							++r8;
						}
					}
					int32 v98 = (int32) r37;
					r37 = (int64) v98;
					r8 += r36;
					p06 = r8 < r37;
					p07 = r8 >= r37;
					if (!p06)
					{
						r38 = r32 + 2;
						if (p16)
							r8 = 0x00 + 2;
						if (p03)
						{
							null == r33;
							Eq_n p09 = null != r33;
						}
						__break();
						pr = 0x01;
					}
					else
					{
						r69 = r39 + r36;
						byte * r70 = r32;
						b0();
						r8 = r39 + null;
						r1 = r66 + 0x00;
						pr = r67;
						ar.pfs = r65;
						LC = r68;
						b0 = r64;
						r12 += 0x40;
						return;
					}
				}
			}
			int32 v93 = (int32) r38;
			r14 = (int64) v93;
			r8 = r39;
			r14 += r39;
			*r0 = (byte) r14;
			pr = r67;
			ar.pfs = r65;
			LC = r68;
			b0 = r64;
			r12 += 0x40;
		}
	}
	else
	{
		r69 = 0x00 + 1;
		b0();
		r39 = r8;
		*r0 = (byte) r8;
		r1 = r66 + 0x00;
		r8 = r39;
		pr = r67;
		ar.pfs = r65;
		LC = r68;
		b0 = r64;
		r12 += 0x40;
	}
}

// 4000000000096E00: define string_quote_removal
define string_quote_removal
{
	up64 r8;
	byte * r32;
	word64 r1;
	<anonymous> * b7;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r48 = ar.pfs;
	byte * r12 = r12 + -32;
	<anonymous> * r47 = b7;
	word64 r49 = r1 + 0x00;
	byte * r50 = r32;
	ui64 r33 = r33 & 0x03;
	Eq_n r40;
	r40.u1 = r12 + 40;
	ui64 r37 = 0x00 + 0x00;
	word64 r35 = 0x00 + 0x00;
	Eq_n r39;
	r39.u1 = r12 + 24;
	Eq_n r43;
	r43.u1 = r12 + 32;
	union Eq_n * r0;
	r0->u1 = (struct Eq_n *) r40;
	<anonymous> * b0;
	b0();
	r1 = r49 + 0x00;
	ui64 r45 = r32 + r8;
	r50 = r8 + 0x01;
	struct Eq_n * r38 = r1 + -9996;
	r38 = r38->ptr0000;
	b0();
	r1 = r49 + 0x00;
	word64 r41 = r8 + 0x00;
	byte * r36 = r8 + 0x00;
	byte * r15 = 0x00 + 0x00;
	word64 r46 = r1 + -18556;
l4000000000096EC0:
	byte * r34 = r15 + r32;
	byte v29 = *r34;
	r15 = (word64) v29;
	int8 v30 = (int8) r15;
	r15 = (int64) v30;
	byte v31 = (byte) r15;
	struct Eq_n * r14 = (word64) v31;
	word32 v33 = (word32) 0x00;
	word32 v34 = (word32) r14;
	Eq_n p07 = v33 == v34;
	Eq_n p06 = v33 != v34;
	if (!p07)
	{
		do
		{
			word32 v37 = (word32) 0x27;
			word32 v38 = (word32) r14;
			p06 = v37 == v38;
			p07 = v37 != v38;
			if (p06)
			{
				r14 = r33 | r37;
				word32 v41 = (word32) 0x00;
				word32 v42 = (word32) r14;
				p06 = v41 == v42;
				p07 = v41 != v42;
				if (!p06)
				{
					++r35;
					*r36 = (byte) r1;
					++r36;
					int32 v61 = (int32) r35;
					r15 = (int64) v61;
					goto l4000000000096EC0;
				}
				else
				{
					word64 r42 = r35 + 0x01;
					r0->u1 = (struct Eq_n *) r39;
					b0();
					int32 v51 = (int32) r42;
					int64 r44 = (int64) v51;
					p07 = 0x01 < r8;
					p06 = 0x01 >= r8;
					r1 = r49 + 0x00;
					if (p06)
						r44 = 0x00 + 0x00;
					__break();
					word64 p16;
					word64 pr;
					if (p16)
					{
						word64 r64;
						pr = r64;
					}
					byte v67 = *r12;
					r48 = (word64) v67;
					r12 += 0x0082;
					word64 p01;
					if (p01)
						__break();
					word64 p12;
					if (p12)
						pr = 0x00;
					word64 p18;
					if (p18)
						__break();
				}
			}
			word32 v39 = (word32) 0x5C;
			word32 v40 = (word32) r14;
			p06 = v39 == v40;
			p07 = v39 != v40;
			struct Eq_n * r16;
			if (p06)
			{
				++r35;
				int32 v45 = (int32) r35;
				r15 = (int64) v45;
				r34 = r15 + r32;
				byte v46 = *r34;
				r16 = (word64) v46;
				word32 v48 = (word32) 0x00;
				word32 v49 = (word32) r16;
				p07 = v48 == v49;
				p06 = v48 != v49;
				if (p07)
				{
					*r36 = (byte) r1;
					++r36;
				}
				__break();
			}
			word32 v43 = (word32) 0x22;
			word32 v44 = (word32) r14;
			p06 = v43 == v44;
			p07 = v43 != v44;
			if (p06)
			{
				++r35;
				--r37;
				int32 v54 = (int32) r35;
				r15 = (int64) v54;
				goto l4000000000096EC0;
			}
			b0();
			r1 = r49 + 0x00;
			byte v53 = *r34;
			r14 = (word64) v53;
			p07 = 0x01 < r8;
			p06 = 0x01 >= r8;
			if (p06)
			{
				++r35;
				*r36 = (byte) r1;
				++r36;
				int32 v56 = (int32) r35;
				r15 = (int64) v56;
				goto l4000000000096EC0;
			}
			int8 v57 = (int8) r14;
			r14 = (int64) v57;
			r50 = r36;
			byte * r51 = r34;
			word3 v59 = SLICE(r14, word3, 5);
			r16 = (word64) v59;
			r15 = r14 & 0x1F;
			r14 = (struct Eq_n *) ((char *) &r38->ptr0000 + (r16 << 0x02));
			Eq_n v60;
			v60.u0 = r14->t0000.u0;
			r14 = (word64) v60;
			r14 >>= r15;
			if (!p07)
			{
				if (p06)
					r15 = 0x00 + 1;
			}
			r14 = r40.u1->ptr0000;
			r51 = r34;
			ptr64 r52 = r34 - r45;
			word64 * r53 = &r40.u1->ptr0000;
			r50 = 0x00 + 0x00;
			r14->t0000.u1 = (struct Eq_n *) r43;
			b0();
			r15 = r8 + 0x02;
			r1 = r49 + 0x00;
			r50 = r36;
			r51 = r34;
			p06 = (byte *) 0x01 < r15;
			p07 = (byte *) 0x01 >= r15;
			if (p06)
			{
				p06 = 0x00 == r8;
				p07 = 0x00 != r8;
				r50 = r36;
				r51 = r34;
				if (p06)
					r15 = 0x00 + 1;
			}
			r16 = r43.u1->ptr0000;
			r15 = 0x00 + 1;
			r8 = 0x00 + 1;
			r35 = r15 + r35;
			r16->t0000.u1 = (struct Eq_n *) r40;
			r52 = r8 + 0x00;
			r36 += r8;
			b0();
			r1 = r49 + 0x00;
			int32 v71 = (int32) r35;
			r15 = (int64) v71;
			r34 = r15 + r32;
			byte v73 = *r34;
			r15 = (word64) v73;
			int8 v74 = (int8) r15;
			r15 = (int64) v74;
			byte v75 = (byte) r15;
			r14 = (word64) v75;
			word32 v76 = (word32) 0x00;
			word32 v77 = (word32) r14;
			p07 = v76 == v77;
			p06 = v76 != v77;
		} while (p06);
	}
	r8 = r41 + 0x00;
	r0->u0 = (byte) (byte) r36;
	ar.pfs = r48;
	b0 = r47;
	r12 += 32;
}

// 4000000000097980: define expand_arith_string
define expand_arith_string
{
	word64 r32;
	up64 r8;
	word64 b2;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	struct Eq_n * r34 = r1 + -9900;
	r34 = r34->ptr0000;
	word64 r2 = ar.pfs;
	word64 r43 = ar.pfs;
	word64 r12 = r12 + ~0x1F;
	word64 r44 = r1 + 0x00;
	word64 r42 = b2;
	word64 r39 = r12 + 0x18;
	word64 * r0;
	*r0 = r39;
	<anonymous> * b0;
	b0();
	Eq_n p07 = 0x01 < r8;
	Eq_n p06 = 0x01 >= r8;
	r1 = r44 + 0x00;
	word64 r45 = r32 + 0x00;
	if (p06)
	{
		word64 r41 = 0x00 + 0x00;
	}
}

// 40000000000999C0: define do_assignment_no_expand
define do_assignment_no_expand
{
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r14 = r12 + 0x10;
	word32 * r15 = 0x00 + 4;
	word64 r37 = 0x00 + 0x00;
	word64 * r32;
	*r32 = r14;
	word64 r36 = r14 + 0x00;
	r14 = r12 + 0x18;
	*r15 = (word32) r14;
	<anonymous> * b0;
	b0();
	r1 = r35 + 0x00;
	ar.pfs = r34;
	b0 = r33;
	r12 += 0x10;
}

// 4000000000099A40: define do_word_assignment
define do_word_assignment
{
	<anonymous> * b0;
	word64 r1;
	word64 * r32;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = 0x00 + 1;
	word64 r2 = ar.pfs;
	word64 r41 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r43 = pr;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	word64 r42 = r1 + 0x00;
	<anonymous> * r40 = b0;
	word64 r45 = 0x00 + 0x00;
	int64 r35;
	word64 r8;
	if (!p06)
	{
		word64 r34 = *r32;
		p06 = 0x00 == r34;
		p07 = 0x00 != r34;
		word64 r44 = r34 + 0x00;
		if (!p06)
		{
			b0();
			r44 = r34 + 0x00;
			r1 = r42 + 0x00;
			r35 = r8 + 0x00;
			b0();
			r1 = r42 + 0x00;
			int32 v23 = (int32) r35;
			r35 = (int64) v23;
			r44 = r8 + 0x01;
			b0();
			r1 = r42 + 0x00;
			r45 = r34 + 0x00;
			r44 = r8 + 0x00;
			b0();
			byte * r14 = r35 + r8;
			r1 = r42 + 0x00;
			r34 = r8 + 0x00;
			byte v25 = *r14;
			byte * r15 = (word64) v25;
			int8 v27 = (int8) r15;
			r15 = (int64) v27;
			word32 v28 = (word32) 0x3D;
			word32 v29 = (word32) r15;
			p07 = v28 == v29;
			p06 = v28 != v29;
			if (!p07)
			{
				if (p06)
				{
					word64 r37 = 0x00 + 0x00;
				}
			}
			else
			{
				r15 = r35 + ~0x00;
				int64 r36 = r35 + r8;
				r15 += r8;
				byte v32 = *r15;
				int64 r16 = (word64) v32;
				int8 v34 = (int8) r16;
				r16 = (int64) v34;
				word32 v35 = (word32) 0x2B;
				word32 v36 = (word32) r16;
				p07 = v35 == v36;
				p06 = v35 != v36;
				if (p07)
				{
					byte * r0;
					*r0 = (byte) r15;
				}
				word64 p20;
				if (p20)
				{
					0x00 < 0x00;
					Eq_n p18 = 0x00 >= 0x00;
				}
			}
		}
	}
	r35 = 0x00 + 0x00;
	r8 = r35 + 0x00;
	pr = r43;
	ar.pfs = r41;
	b0 = r40;
	r12 += 0x10;
}

// 4000000000099A80: define do_assignment
define do_assignment
{
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r14 = r12 + 0x10;
	word32 * r15 = 0x00 + 4;
	word64 r37 = 0x00 + 1;
	word64 * r32;
	*r32 = r14;
	word64 r36 = r14 + 0x00;
	r14 = r12 + 0x18;
	*r15 = (word32) r14;
	<anonymous> * b0;
	b0();
	r1 = r35 + 0x00;
	ar.pfs = r34;
	b0 = r33;
	r12 += 0x10;
}

// 4000000000099B00: define setifs
define setifs
{
	<anonymous> * b3;
	word64 ** LC;
	word64 *** r32;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 ** r14 = r1 + 9076;
	word64 * r15 = (word64 *) ((char *) r32 + 8);
	word64 r37 = r1 + 0x00;
	word64 ** r38 = LC;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	<anonymous> * r35 = b3;
	Eq_n r34 = r1 + 9092;
	Eq_n r39 = r1 + 0x00005BF4;
	word64 * r40 = 0x00 + 0x00;
	word64 *** r41 = 0x00 + 0x0100;
	*r32 = r14;
	Eq_n r33;
	if (!p06)
	{
		r33.u1 = *r15;
		p07 = 0x00 == r33;
		p06 = 0x00 != r33;
		if (p07)
			r33 = r1 + -6668;
	}
	else
	{
		r34 = r1 + 9092;
		r33 = r1 + -6668;
		r39 = r1 + 0x00005BF4;
		r40 = 0x00 + 0x00;
		r41 = 0x00 + 0x0100;
		r33.u1 = *r33.u1;
		*r33.u1 = (word64) r34;
		<anonymous> * b0;
		b0();
		r1 = r37 + 0x00;
		r15 = r33.u1;
		byte * r18 = 0x00 + 1;
		word64 *** r17 = r1 + 0x00005BF4;
		LC = r14;
		Eq_n r16;
		while (true)
		{
			Eq_n v26;
			v26.u1 = *r15;
			r14 = (word64) v26;
			r15 = (word64 *) ((char *) r15 + 1);
			int8 v27 = (int8) r14;
			r14 = (int64) v27;
			byte v28 = (byte) r14;
			r16.u1 = (word64) v28;
			word32 v30 = (word32) 0x00;
			word32 v31 = (word32) r14;
			p07 = v30 == v31;
			p06 = v30 != v31;
			if (p07)
				break;
			r16.u1 = r16 + r17;
			*r18 = (byte) r16;
			if (LC == null)
				break;
			--LC;
		}
		b0();
		r39.u1 = r33.u1;
		r1 = r37 + 0x00;
		up64 r8;
		r40 = r8 + 0x00;
		b0();
		r1 = r37 + 0x00;
		r33 = r8 + 0x00;
		b0();
		p06 = 0x01 < r8;
		p07 = 0x01 >= r8;
		r1 = r37 + 0x00;
		r40 = r33.u1;
		if (p07)
		{
			r14 = r1 + 9108;
			r15 = 0x00 + 1;
			*r15 = r14;
		}
		else
		{
			r39.u1 = *r34.u1;
			b0();
			r1 = r37 + 0x00;
			int32 v33 = (int32) r8;
			r41 = (int64) v33;
			word64 r42 = 0x00 + 16;
			r14 = r1 + 9108;
			r15 = (word64 *) ((char *) r41 - 2);
			r39 = r1 + 23524;
			p07 = (word64 *) ~0x04 < r15;
			p06 = (word64 *) ~0x04 >= r15;
			*r41 = r14;
			if (!p07)
			{
				r14 = r1 + 9092;
				r40 = *r14;
				b0();
				r1 = r37 + 0x00;
				ar.pfs = r36;
				LC = r38;
				b0 = r35;
				return;
			}
		}
		r16.u1 = *r34.u1;
		r15 = r1 + 23524;
		r17 = 0x00 + 1;
		ar.pfs = r36;
		LC = r38;
		Eq_n v35 = *r16;
		r16.u1 = (word64) v35;
		b0 = r35;
		*r17 = r14;
		*r15 = (word64) (byte) r1;
		r15 = (word64 *) ((char *) r15 + 1);
		byte * r0;
		*r0 = (byte) r15;
	}
}

// 4000000000099E40: define getifs
define getifs
{
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 * r14 = r1 + 9092;
	word64 r8 = *r14;
}

// 4000000000099E80: define word_split
define word_split
{
	word64 * r33;
	word64 r1;
	struct Eq_n * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	word32 * r15 = (word32 *) ((char *) &r32->ptr0000 + 8);
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	struct Eq_n * r14 = r1 + -6740;
	Eq_n p09 = null == r33;
	Eq_n p08 = null != r33;
	if (!p06)
	{
		word32 v15 = *r15;
		ui64 r34 = (word64) v15;
		r14 = r14->ptr0000;
		r34 &= 0x02;
		word32 v17 = (word32) 0x00;
		word32 v18 = (word32) r34;
		p07 = v17 == v18;
		p06 = v17 != v18;
		if (p06)
			r32 = r32->ptr0000;
		else
		{
			if (p08)
				r14 = (struct Eq_n *) r33;
			__break();
		}
		r33 = &r14->ptr0000;
		word64 r2 = ar.pfs;
		list_string();
	}
	else
	{
		word64 r8 = 0x00 + 0x00;
	}
}

// 400000000009A080: define expand_string
define expand_string
{
	word64 r33;
	word64 r1;
	<anonymous> * b3;
	byte * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	Eq_n p07 = null == r32;
	Eq_n p06 = null != r32;
	<anonymous> * r35 = b3;
	word64 r37 = r1 + 0x00;
	word64 r39 = r33 + 0x00;
	<anonymous> * b0;
	word64 r8;
	if (!p07)
	{
		byte v15 = *r32;
		int64 r14 = (word64) v15;
		byte * r38 = r32;
		int8 v18 = (int8) r14;
		r14 = (int64) v18;
		word32 v19 = (word32) 0x00;
		word32 v20 = (word32) r14;
		p06 = v19 == v20;
		p07 = v19 != v20;
		if (!p06)
		{
			b0();
			p06 = 0x00 == r8;
			p07 = 0x00 != r8;
			r1 = r37 + 0x00;
			word64 r34 = r8 + 0x00;
			r38 = r8 + 0x00;
			if (!p06)
			{
				b0();
				r1 = r37 + 0x00;
				r32 = r8 + 0x00;
				r38 = r34 + 0x00;
				b0();
				r1 = r37 + 0x00;
				p06 = null == r32;
				p07 = null != r32;
				b0 = r35;
				if (!p06)
				{
					ar.pfs = r36;
					word64 r2 = ar.pfs;
					dequote_list();
					return;
				}
			}
		}
	}
	r8 = 0x00 + 0x00;
	ar.pfs = r36;
	b0 = r35;
}

