// elf-Linux-ia64-bash_text_n.c
// Generated by decompiling elf-Linux-ia64-bash
// using Reko decompiler version 0.12.3.0.

#include "elf-Linux-ia64-bash.h"

// 400000000007C580: define describe_pid
define describe_pid
{
	word64 r8;
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 r12 = r12 + ~0xFF;
	word64 r35 = r1 + 0x00;
	<anonymous> * r33 = b1;
	struct Eq_n * r36 = r12 + 0x90;
	<anonymous> * b0;
	b0();
	r1 = r35 + 0x00;
	r36 = r12 + 0x90;
	struct Eq_n * r37 = 0x00 + 0x0011;
	b0();
	r1 = r35 + 0x00;
	r36 = r12 + 0x10;
	b0();
	r1 = r35 + 0x00;
	r37 = r12 + 0x90;
	struct Eq_n * r38 = r12 + 0x10;
	r36 = 0x00 + 0x00;
	b0();
	r1 = r35 + 0x00;
	word64 r32;
	r36 = r32 + 0x00;
	r37 = 0x00 + 0x00;
	r38 = 0x00 + 0x00;
	b0();
	r1 = r35 + 0x00;
	word32 v17 = (word32) ~0x00;
	word32 v18 = (word32) r8;
	Eq_n p06 = v17 == v18;
	Eq_n p07 = v17 != v18;
	int32 v21 = (int32) r32;
	int64 r40 = (int64) v21;
	word64 r39 = r8 + 0x01;
	r37 = 0x00 + 1;
	if (!p06)
	{
		struct Eq_n * r14 = r1 + -0x0000299C;
		r38 = r1 + -8012;
		r14 = r14->ptr0000;
		r38 = r38->ptr0000;
		r36 = r14->ptr0000;
		b0();
		r1 = r35 + 0x00;
		r36 = 0x00 + 2;
		r37 = r12 + 0x10;
		r38 = 0x00 + 0x00;
		b0();
		r1 = r35 + 0x00;
		ar.pfs = r34;
		b0 = r33;
		r12 += 0x0100;
	}
	else
	{
		r37 = r1 + -8004;
		r38 = 0x00 + 5;
		r36 = 0x00 + 0x00;
		r37 = r37->ptr0000;
		b0();
		r1 = r35 + 0x00;
		r36 = r8 + 0x00;
		int32 v25 = (int32) r32;
		r37 = (int64) v25;
		b0();
		r1 = r35 + 0x00;
		r36 = 0x00 + 2;
		r37 = r12 + 0x10;
		r38 = 0x00 + 0x00;
		b0();
		r1 = r35 + 0x00;
		ar.pfs = r34;
		b0 = r33;
		r12 += 0x0100;
	}
}

// 400000000007C740: define list_one_job
define list_one_job
{
	word64 ar.pfs;
	word64 r35;
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	struct Eq_n * r14 = r1 + -10260;
	word64 r32 = r35 + 0x00;
	r14 = r14->ptr0000;
	struct Eq_n * r34 = r14->ptr0000;
	word64 r2 = ar.pfs;
	fn40000000000780C0();
}

// 400000000007C780: define ignore_tty_job_signals
define ignore_tty_job_signals
{
	word64 r1;
	<anonymous> * b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	word64 r35 = 0x00 + 20;
	word64 r36 = 0x00 + 1;
	b0();
	r1 = r34 + 0x00;
	r35 = 0x00 + 21;
	r36 = 0x00 + 1;
	b0();
	r1 = r34 + 0x00;
	r35 = 0x00 + 22;
	r36 = 0x00 + 1;
	b0();
	r1 = r34 + 0x00;
	ar.pfs = r33;
	b0 = r32;
}

// 400000000007C800: define default_tty_job_signals
define default_tty_job_signals
{
	word64 r1;
	<anonymous> * b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	word64 r35 = 0x00 + 20;
	word64 r36 = 0x00 + 0x00;
	b0();
	r1 = r34 + 0x00;
	r35 = 0x00 + 21;
	r36 = 0x00 + 0x00;
	b0();
	r1 = r34 + 0x00;
	r35 = 0x00 + 22;
	r36 = 0x00 + 0x00;
	b0();
	r1 = r34 + 0x00;
	ar.pfs = r33;
	b0 = r32;
}

// 400000000007C880: define get_tty_state
define get_tty_state
{
	<anonymous> * b0;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	Eq_n r14 = r1 + 5900;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	Eq_n v11;
	v11.u0 = r14.u1->t0000.u0;
	Eq_n r35;
	r35.u1 = (word64) v11;
	word32 v13 = (word32) ~0x00;
	word32 v14 = (word32) r35;
	Eq_n p07 = v13 == v14;
	Eq_n p06 = v13 != v14;
	word64 r8;
	if (p07)
	{
		r14 = r1 + -0x0000299C;
		r14.u1 = r14.u1->t0000.u1;
		r35.u1 = r14.u1->t0000.u1;
		b0();
		r1 = r34 + 0x00;
		r35 = r8 + 0x00;
		word32 v21 = (word32) ~0x00;
		word32 v22 = (word32) r8;
		p07 = v21 == v22;
		p06 = v21 != v22;
		r8 = 0x00 + 0x00;
		if (!p06)
			goto l400000000007C920;
	}
	word64 r36 = r1 + 0x00004A8C;
	b0();
	r1 = r34 + 0x00;
	int32 v19 = (word32) r8;
	int32 v20 = (word32) 0x00;
	p06 = v19 < v20;
	p07 = v19 >= v20;
	r8 = 0x00 + 0x00;
	if (p06)
	{
		r8 = 0x00 + -1;
		ar.pfs = r33;
		b0 = r32;
		return;
	}
	r14 = r1 + 9072;
	Eq_n v23;
	v23.u0 = r14.u1->t0000.u0;
	r14.u1 = (word64) v23;
	word32 v24 = (word32) 0x00;
	word32 v25 = (word32) r14;
	p06 = v24 == v25;
	p07 = v24 != v25;
	if (p07)
	{
		r35 = 0x00 + 0x00;
		r36 = 0x00 + 0x00;
		word64 r37 = 0x00 + 0x00;
		b0();
		r1 = r34 + 0x00;
		r8 = 0x00 + 0x00;
	}
l400000000007C920:
	ar.pfs = r33;
	b0 = r32;
}

// 400000000007CA00: define set_tty_state
define set_tty_state
{
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	Eq_n r14 = r1 + 5900;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	Eq_n v11;
	v11.u0 = r14.u1->t0000.u0;
	word64 r32 = (word64) v11;
	word32 v13 = (word32) ~0x00;
	word32 v14 = (word32) r32;
	Eq_n p07 = v13 == v14;
	Eq_n p06 = v13 != v14;
	Eq_n r36;
	<anonymous> * b0;
	word64 r8;
	if (p07)
	{
		r14 = r1 + -0x0000299C;
		r14.u1 = r14.u1->t0000.u1;
		r36.u1 = r14.u1->t0000.u1;
		b0();
		r1 = r35 + 0x00;
		r32 = r8 + 0x00;
		word32 v24 = (word32) ~0x00;
		word32 v25 = (word32) r8;
		p07 = v24 == v25;
		p06 = v24 != v25;
		r8 = 0x00 + 0x00;
		if (!p06)
		{
l400000000007CA70:
			ar.pfs = r34;
			b0 = r33;
			return;
		}
	}
	word64 r38 = r1 + 0x00004A8C;
	r36 = r32 + 0x00;
	int64 r37 = 0x00 + 1;
	b0();
	int32 v22 = (word32) r8;
	int32 v23 = (word32) 0x00;
	p07 = v22 < v23;
	p06 = v22 >= v23;
	r8 = 0x00 + 0x00;
	r1 = r35 + 0x00;
	if (p07)
	{
		r14 = r1 + 6516;
		r8 = 0x00 + -1;
		Eq_n v26;
		v26.u0 = r14.u1->t0000.u0;
		r14.u1 = (word64) v26;
		word32 v27 = (word32) 0x00;
		word32 v28 = (word32) r14;
		p06 = v27 == v28;
		p07 = v27 != v28;
		if (!p06)
		{
			b0();
			r1 = r35 + 0x00;
			int32 v29 = (int32) r8;
			r37 = (int64) v29;
			word64 r39 = r32 + 0x00;
			r14 = r1 + 7124;
			r36 = r1 + -7996;
			r36.u1 = r36.u1->t0000.u1;
			Eq_n v31;
			v31.u0 = r14.u1->t0000.u0;
			r38 = (word64) v31;
			b0();
			r8 = 0x00 + -1;
			r1 = r35 + 0x00;
			ar.pfs = r34;
			b0 = r33;
			return;
		}
	}
	goto l400000000007CA70;
}

// 400000000007CB80: define job_exit_status
define job_exit_status
{
	word64 r96;
	word64 r3;
	ui64 r32;
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = r32 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r35 + 0x00;
	ui64 r8;
	r32 = r8 + 0x00;
	b0 = r33;
	ar.pfs = r34;
	word64 r2 = ar.pfs;
	r8 = r32 & 0x7F;
	ui64 r14 = r8 + 0x01;
	r8 += 0x80;
	word7 v16 = SLICE(r14, word7, 1);
	r14 = (word64) v16;
	int32 v17 = (word32) 0x00;
	int32 v18 = (word32) r14;
	Eq_n p07 = v17 < v18;
	Eq_n p06 = v17 >= v18;
	if (p07)
		return;
	byte v21 = SLICE(r32, byte, 8);
	r8 = (word64) v21;
	byte v22 = (byte) r32;
	r32 = (word64) v22;
	word32 v23 = (word32) 0x7F;
	word32 v24 = (word32) r32;
	p06 = v23 == v24;
	p07 = v23 != v24;
	if (p06)
		r8 = 0x00 + 0x00;
	__break();
	__break();
	__break();
	__break();
	word64 p37;
	if (p37)
	{
		Eq_n p03 = r3 == r96;
		Eq_n p02 = r3 != r96;
	}
	word64 p08;
	if (p08)
		__break();
}

// 400000000007CC00: define job_exit_signal
define job_exit_signal
{
	ui64 r8;
	word64 r32;
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = r32 + 0x00;
	<anonymous> * b0;
	b0();
	ui64 r14 = r8 & 0x7F;
	r1 = r35 + 0x00;
	ar.pfs = r34;
	r8 = r14 + 0x01;
	b0 = r33;
	word7 v15 = SLICE(r8, word7, 1);
	r8 = (word64) v15;
	int32 v16 = (word32) 0x00;
	int32 v17 = (word32) r8;
	Eq_n p06 = v16 < v17;
	Eq_n p07 = v16 >= v17;
	if (p06)
		r8 = r14 + 0x00;
}

// 400000000007CC80: define kill_pid
define kill_pid
{
	word64 r33;
	word64 r1;
	word64 r32;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r42 = ar.pfs;
	word64 r12 = r12 + ~0x010F;
	word64 r44 = pr;
	int32 v10 = (word32) ~0x01;
	int32 v11 = (word32) r32;
	Eq_n p06 = v10 < v11;
	Eq_n p07 = v10 >= v11;
	word64 r43 = r1 + 0x00;
	word64 r46 = r33 + 0x00;
	if (p07)
		r32 -= 0x00;
}

// 400000000007D280: define run_sigchld_trap
define run_sigchld_trap
{
	word64 r32;
	Eq_n LC;
	word64 b7;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r40 = ar.pfs;
	word64 ** r33 = r1 + 0x00005EFC;
	word64 r38 = r1 + 7540;
	word64 r34 = r1 + 7672;
	word64 r41 = r1 + 0x00;
	word64 r36 = r1 + 7464;
	word64 r39 = b7;
	word64 r37 = r1 + 7428;
	word64 r35 = 0x00 + 1;
	r33 = (word64 **) ((char *) r33 + 0x0088);
	Eq_n r42 = LC;
	word64 * r43 = *r33;
	<anonymous> * b0;
	b0();
	r1 = r41 + 0x00;
	word64 r8;
	r43 = r8 + 0x01;
	b0();
	word64 * r44 = *r33;
	r1 = r41 + 0x00;
	r43 = r8 + 0x00;
	b0();
	r1 = r41 + 0x00;
	r33 = r8 + 0x00;
	r43 = r1 + -7988;
	r43 = *r43;
	b0();
	r1 = r41 + 0x00;
	r44 = 0x00 + 4;
	r43 = r1 + 9044;
	b0();
	r1 = r41 + 0x00;
	r44 = 0x00 + 4;
	r43 = r1 + 0x00002338;
	b0();
	r1 = r41 + 0x00;
	r44 = 0x00 + 4;
	r43 = r1 + 5876;
	b0();
	r1 = r41 + 0x00;
	r43 = r34 + 0x00;
	r44 = 0x00 + 4;
	b0();
	r1 = r41 + 0x00;
	r43 = r36 + 0x00;
	r44 = 0x00 + 4;
	b0();
	r1 = r41 + 0x00;
	r43 = r37 + 0x00;
	r44 = 0x00 + 8;
	b0();
	r1 = r41 + 0x00;
	r43 = r38 + 0x00;
	r44 = 0x00 + 8;
	b0();
	r1 = r41 + 0x00;
	r44 = r33;
	r43 = r1 + -9884;
	r43 = *r43;
	b0();
	r1 = r41 + 0x00;
	r44 = r33;
	r43 = r1 + -9932;
	r43 = *r43;
	b0();
	r1 = r41 + 0x00;
	word64 * r0;
	*r0 = r38;
	*r0 = r37;
	b0();
	Eq_n r14 = r32 + ~0x00;
	int32 v25 = (word32) 0x00;
	int32 v26 = (word32) r32;
	Eq_n p06 = v25 < v26;
	Eq_n p07 = v25 >= v26;
	r1 = r41 + 0x00;
	Eq_n r15 = __addp4(0x00, r14);
	r14 = 0x00 + 1;
	r14.u3->t0000.u1 = (word32) r36;
	if (p06)
		LC = r15;
}

// 400000000007E8C0: define fn400000000007E8C0
// Called from:
//      reap_dead_jobs
//      notify_and_cleanup
define fn400000000007E8C0
{
fn400000000007E8C0_entry:
	r11 = fp
	r41 = ar.pfs
	r36 = r1 + -20676
	r15 = r1 + 7464
	r40 = b0
	r37 = r1 + 7472
	r38 = r1 + 7468
	r34 = 0x00 + 0x00
	r33 = 0x00 + 0x00
	r35 = r1 + 7444
	r42 = r1 + 0x00
	r36 = r36 + 7
	v17 = *r36
	r14.u2 = (word64) v17
	v19 = (word32) 0x00
	v20 = (word32) r14
	p07 = v19 == v20
	p06 = v19 != v20
	branch !p07 l400000000007E920
	goto l400000000007EA60
l400000000007D580:
l400000000007D6E0:
	v99 = *r48
	r14.u2 = (word64) v99
	v100 = (word32) 0x00
	v101 = (word32) r14
	p09 = v100 == v101
	p08 = v100 != v101
	branch !p08 l400000000007D700
	goto l400000000007DC00
l400000000007D700:
	branch !p09 l400000000007D706
l400000000007D700_n:
	v102 = (word32) *r40
	r33 = (word64) v102
l400000000007D706:
l400000000007D710:
l400000000007D720:
	branch !p20 l400000000007D730
	goto l400000000007D740
l400000000007D730:
	r33 = r33 | 0x01
l400000000007D740:
	r14 = __ld_acquire<word32>(r38)
	v86 = (word32) 0x00
	v87 = (word32) r14
	p06 = v86 == v87
	p07 = v86 != v87
	branch !p07 l400000000007D75C
l400000000007D756_n:
	r73 = __ld_acquire<word32>(r47)
	b0()
	r1 = r71 + 0x00
	branch !p18 l400000000007DAF0
	goto l400000000007D760
l400000000007D75C:
	branch !p29 l400000000007D762
l400000000007D75C_n:
	goto l400000000007D762
l400000000007D760:
	r73 = 0x00 + -1
l400000000007D762:
l400000000007D766:
	__break()
	branch !p16 l400000000007D778
	goto l400000000007D772_n
l400000000007D772:
l400000000007D772_n:
	__break()
l400000000007D778:
	branch !p07 l400000000007D784
	goto l400000000007D77E_n
l400000000007D77E:
l400000000007D77E_n:
	v91 = *r56
	r11 = (word64) v91
l400000000007D784:
	__break()
l400000000007DAD0:
l400000000007DAF0:
	v92 = *r54
	r14.u2 = (word64) v92
	v93 = (word32) 0x00
	v94 = (word32) r14
	p07 = v93 == v94
	p06 = v93 != v94
	branch !p06 && !p06 l400000000007DB10
	goto l400000000007D760
l400000000007DB10:
l400000000007DB20:
	r74 = r1 + -7972
	r75 = 0x00 + 5
	r73 = 0x00 + 0x00
	r33 = r33 | 0x01
	r74 = r74->ptr0000
	b0()
	r1 = r71 + 0x00
	r73 = r8 + 0x00
	b0()
	r1 = r71 + 0x00
	goto l400000000007D760
l400000000007DC00:
	r33 = 0x00 + 0x00
	branch !p06 l400000000007D720
	goto l400000000007D730
l400000000007E8C0:
l400000000007E920:
	v23.u1 = r15.u1->u1
	r15.u1 = (word64) v23
	v24 = (word32) 0x00
	v25 = (word32) r15
	p07 = v24 == v25
	p06 = v24 != v25
	branch !p06 l400000000007E940
	goto l400000000007EA60
l400000000007E940:
	v26 = *r37
	r15.u1 = (word64) v26
	v27 = (word32) 0x00
	v28 = (word32) r14
	p06 = v27 < v28
	p07 = v27 >= v28
	v29 = r38.u3->t0000.u1
	r39 = (word64) v29
	r15.u0 = (word32) r15 + 1
	r15.u1->u1 = (word32) (word32) r37
	branch !p07 l400000000007E970
	goto l400000000007E9F0
l400000000007E980:
	r14.u2 = r35->u2
	r14.u2 = (char *) r14.u2 + r34
	r34 = r34 + 0x08
	r14.u2 = *r14.u2
	r15.u0 = (word32) r14 + 20
	p06 = 0x00 == r14
	p07 = 0x00 != r14
	branch !p06 l400000000007E9B0
	goto l400000000007E9D0
l400000000007E9B0:
	v106.u1 = r15.u1->u1
	r15.u1 = (word64) v106
	v107 = (word32) 0x04
	v108 = (word32) r15
	p07 = v107 == v108
	p06 = v107 != v108
	branch !p07 l400000000007E9D0
l400000000007E9CC_n:
	r14.u1 = (word32) r14 + 24
	v109.u1 = r14.u3->t0000.u1
	r14.u2 = (word64) v109
	branch !p06 l400000000007EAA0
l400000000007E9D0:
	r33 = r33 + 0x01
	v103 = *r36
	r14.u2 = (word64) v103
	v104 = (word32) r33
	v105 = (word32) r14
	p06 = v104 < v105
	p07 = v104 >= v105
	branch !p06 l400000000007E9F0
	goto l400000000007E980
l400000000007E9F0:
	r32 = 0x00 + 0x00
	b0()
	v32 = *r37
	r14.u2 = (word64) v32
	r1 = r42 + 0x00
	b0 = r40
	r14.u1 = (word32) r14 - 1
	ar.pfs = r41
	r14.u3->t0000.u1 = (word32) (word32) r37
	v33 = (word32) 0x00
	v34 = (word32) r14
	p06 = v33 == v34
	p07 = v33 != v34
	branch !p07 l400000000007EA30
	goto l400000000007EA60
l400000000007EA30:
	v35 = r38.u3->t0000.u1
	r14.u2 = (word64) v35
	v36 = (word32) r14
	v37 = (word32) r39
	p06 = v36 == v37
	p07 = v36 != v37
	branch !p06 l400000000007EA50
	goto l400000000007EA60
l400000000007EA50:
	r2 = ar.pfs
	r70 = ar.pfs
	r12 = r12 + ~0x0F
	r36 = r1 + 7468
	r43 = r1 + -20676
	r38 = r1 + 7676
	r40 = r1 + 0x00001718
	r48 = r1 + 0x00002344
	r53 = r1 + 6516
	r62 = r1 + 6512
	r65 = r1 + -9940
	r64 = r1 + -9628
	v47 = *r36
	r14.u2 = (word64) v47
	r63 = r1 + 9044
	r58 = r1 + 8364
	r67 = r1 + 8360
	r69 = b5
	r45 = r43 + 0x0C
	r72 = pr
	r56 = r43 + 44
	r44 = r43 + 0x18
	r71 = r1 + 0x00
	r41 = 0x00 + 0x00
	r51 = 0x00 + -1
	r46 = 0x00 + 0x00
	r39 = r1 + 5868
	v61 = (word32) 0x00
	v62 = (word32) r14
	p07 = v61 == v62
	p06 = v61 != v62
	v63 = (word32) 0x01
	v64 = (word32) r32
	p19 = v63 == v64
	p18 = v63 != v64
	r35 = r12 + 0x14
	v67 = (word32) 0x00
	v68 = (word32) r32
	p21 = v67 == v68
	p20 = v67 != v68
	r47.u2 = r38.u2
	r54 = r1 + 7472
	r61 = r40
	r52 = r36
	r42 = 0x00 + 0x0000FFFF
	r50 = r1 + 7444
	r37 = 0x00 + 0x00FF
	r55 = 0x00 + 0x0000FF00
	r60 = 0x00 + 4
	r57 = r1 + 7476
	r59 = r1 + 7464
	r66 = r1 + 0x0000171C
	r43 = r43 + 0x08
	r65 = r65->ptr0000
	r64 = r64->ptr0000
	v81 = *r39
	r14.u2 = (word64) v81
	v82 = (word32) 0x00
	v83 = (word32) r14
	p08 = v82 == v83
	p09 = v82 != v83
	branch !p08 l400000000007D6E0
	goto l400000000007DC00
l400000000007EA60:
	ar.pfs = r41
	b0 = r40
	return
l400000000007EA80:
l400000000007EAA0:
	r43 = r33 + 0x00
	r44 = 0x00 + 0x00
	r33 = r33 + 0x01
	b0()
	v110 = *r36
	r14.u2 = (word64) v110
	r1 = r42 + 0x00
	v111 = (word32) r33
	v112 = (word32) r14
	p06 = v111 < v112
	p07 = v111 >= v112
	branch !p06 l400000000007EAE0
	goto l400000000007E980
fn400000000007E8C0_exit:
}

// 400000000007EB00: define reap_dead_jobs
define reap_dead_jobs
{
	word64 r1;
	<anonymous> * b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	word64 r35 = 0x00 + 0x00;
	b0();
	r1 = r34 + 0x00;
	ar.pfs = r33;
	b0 = r32;
	fn400000000007E8C0();
}

// 400000000007EB80: define notify_and_cleanup
define notify_and_cleanup
{
	<anonymous> * b0;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	word32 * r14 = r1 + 7464;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	word32 v11 = *r14;
	r14 = (word64) v11;
	word32 v12 = (word32) 0x00;
	word32 v13 = (word32) r14;
	Eq_n p07 = v12 == v13;
	Eq_n p06 = v12 != v13;
	r14 = r1 + 6516;
	if (p06)
	{
		ar.pfs = r33;
		b0 = r32;
		return;
	}
	word32 v16 = *r14;
	r14 = (word64) v16;
	word32 v17 = (word32) 0x00;
	word32 v18 = (word32) r14;
	p07 = v17 == v18;
	p06 = v17 != v18;
	r14 = r1 + 6512;
	if (!p06)
	{
		word32 v19 = *r14;
		r14 = (word64) v19;
		word32 v20 = (word32) 0x00;
		word32 v21 = (word32) r14;
		p06 = v20 == v21;
		p07 = v20 != v21;
		if (!p06)
		{
			r14 = r1 + 8412;
			word32 v22 = *r14;
			r14 = (word64) v22;
			word32 v23 = (word32) 0x00;
			word32 v24 = (word32) r14;
			p06 = v23 == v24;
			p07 = v23 != v24;
			if (p06)
			{
l400000000007EC40:
				ar.pfs = r33;
				b0 = r32;
				fn400000000007E8C0();
				return;
			}
		}
	}
	b0();
	r1 = r34 + 0x00;
	goto l400000000007EC40;
}

// 400000000007EC80: define list_all_jobs
define list_all_jobs
{
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r33 = 0x00 + -1;
	<anonymous> * b0;
	b0();
	r1 = r36 + 0x00;
	b0 = r34;
	ar.pfs = r35;
	word64 r2 = ar.pfs;
	fn400000000007A100();
}

// 400000000007ED00: define list_running_jobs
define list_running_jobs
{
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r33 = 0x00 + 1;
	<anonymous> * b0;
	b0();
	r1 = r36 + 0x00;
	b0 = r34;
	ar.pfs = r35;
	word64 r2 = ar.pfs;
	fn400000000007A100();
}

// 400000000007ED80: define list_stopped_jobs
define list_stopped_jobs
{
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r33 = 0x00 + 2;
	<anonymous> * b0;
	b0();
	r1 = r36 + 0x00;
	b0 = r34;
	ar.pfs = r35;
	word64 r2 = ar.pfs;
	fn400000000007A100();
}

// 400000000007EE00: define initialize_job_signals
define initialize_job_signals
{
	<anonymous> * b0;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	word32 * r14 = r1 + 6516;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	ar.pfs = r33;
	b0 = r32;
	word32 v11 = *r14;
	r14 = (word64) v11;
	word32 v12 = (word32) 0x00;
	word32 v13 = (word32) r14;
	Eq_n p06 = v12 == v13;
	Eq_n p07 = v12 != v13;
	r14 = r1 + 5868;
	struct Eq_n * r36;
	word64 r35;
	if (!p07)
	{
		word32 v16 = *r14;
		r14 = (word64) v16;
		word32 v17 = (word32) 0x00;
		word32 v18 = (word32) r14;
		p06 = v17 == v18;
		p07 = v17 != v18;
		if (p07)
		{
			r36 = r1 + -0x00001DCC;
			r35 = 0x00 + 20;
			r36 = r36->ptr0000;
			b0();
			r1 = r34 + 0x00;
			r35 = 0x00 + 21;
			r14 = r1 + 7516;
			r36 = r1 + -0x00001DCC;
			r36 = r36->ptr0000;
			word32 ** r8;
			*r8 = (word32 **) r14;
			b0();
			r1 = r34 + 0x00;
			r35 = 0x00 + 22;
			r14 = r1 + 7524;
			r36 = r1 + -0x00001DCC;
			r36 = r36->ptr0000;
			*r8 = (word32 **) r14;
			b0();
			r1 = r34 + 0x00;
			ar.pfs = r33;
			r14 = r1 + 7484;
			b0 = r32;
			*r8 = (word32 **) r14;
		}
	}
	else
	{
		r36 = r1 + -10004;
		r35 = 0x00 + 2;
		r36 = r36->ptr0000;
		b0();
		r1 = r34 + 0x00;
		r35 = 0x00 + 20;
		r36 = 0x00 + 1;
		b0();
		r1 = r34 + 0x00;
		r35 = 0x00 + 22;
		r36 = 0x00 + 1;
		b0();
		r1 = r34 + 0x00;
		r35 = 0x00 + 21;
		r36 = 0x00 + 1;
		b0();
		r1 = r34 + 0x00;
		ar.pfs = r33;
		b0 = r32;
	}
}

// 400000000007F080: define give_terminal_to
define give_terminal_to
{
	<anonymous> * b4;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r37 = ar.pfs;
	word64 r12 = r12 + ~0xFF;
	word32 * r14 = r1 + 5868;
	<anonymous> * r36 = b4;
	word64 r38 = r1 + 0x00;
	word32 v12 = *r14;
	r14 = (word64) v12;
	word32 * r8 = 0x00 + 0x00;
	ui64 r33 = r33 | r14;
	word32 v15 = (word32) 0x00;
	word32 v16 = (word32) r33;
	Eq_n p06 = v15 == v16;
	Eq_n p07 = v15 != v16;
	<anonymous> * b0;
	if (!p07)
	{
		ar.pfs = r37;
		b0 = r36;
		r12 += 0x0100;
	}
	else
	{
		word64 r39 = r12 + 0x90;
		b0();
		r1 = r38 + 0x00;
		r39 = r12 + 0x90;
		word64 r40 = 0x00 + 22;
		b0();
		r1 = r38 + 0x00;
		r39 = r12 + 0x90;
		r40 = 0x00 + 21;
		b0();
		r1 = r38 + 0x00;
		r39 = r12 + 0x90;
		r40 = 0x00 + 20;
		b0();
		r1 = r38 + 0x00;
		r39 = r12 + 0x90;
		r40 = 0x00 + 0x0011;
		b0();
		r1 = r38 + 0x00;
		r39 = r12 + 0x10;
		b0();
		word64 r41 = r12 + 0x10;
		r1 = r38 + 0x00;
		r40 = r12 + 0x90;
		r39 = 0x00 + 0x00;
		b0();
		r1 = r38 + 0x00;
		word32 * r32;
		r40 = r32;
		r14 = r1 + 5900;
		word32 v24 = *r14;
		r39 = (word64) v24;
		b0();
		r1 = r38 + 0x00;
		int32 v25 = (word32) r8;
		int32 v26 = (word32) 0x00;
		p07 = v25 < v26;
		p06 = v25 >= v26;
		r39 = 0x00 + 2;
		r40 = r12 + 0x10;
		r41 = 0x00 + 0x00;
		if (!p07)
		{
			r14 = r1 + 5892;
			*r32 = (word32) r14;
			b0();
			r8 = 0x00 + 0x00;
			r1 = r38 + 0x00;
			ar.pfs = r37;
			b0 = r36;
			r12 += 0x0100;
		}
		else
		{
			b0();
			r1 = r38 + 0x00;
			word64 r34 = r8;
			r39 = 0x00 + 2;
			word32 v28 = *r8;
			word32 * r35 = (word64) v28;
			r40 = r12 + 0x10;
			r41 = 0x00 + 0x00;
			b0();
			r8 = 0x00 + -1;
			r1 = r38 + 0x00;
			*r35 = (word32) r34;
			ar.pfs = r37;
			b0 = r36;
			r12 += 0x0100;
		}
	}
}

// 400000000007F400: define initialize_job_control
// Called from:
//      restart_job_control
define initialize_job_control
{
	word64 r107;
	word64 b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r42 = ar.pfs;
	word64 r43 = r1 + 0x00;
	word64 r41 = b1;
	word32 * r32 = r1 + 5896;
	<anonymous> * b0;
	b0();
	r1 = r43 + 0x00;
	word32 * r8;
	*r8 = (word32) r32;
	word32 v13 = (word32) ~0x00;
	word32 v14 = (word32) r8;
	Eq_n p07 = v13 == v14;
	Eq_n p06 = v13 != v14;
	word32 * r15 = 0x00 + -1;
	Eq_n r45;
	word64 r46;
	word32 * r44;
	if (p07)
	{
		r45 = r1 + -0x00001F1C;
		r46 = 0x00 + 5;
		r44 = 0x00 + 0x00;
		r45 = *r45;
		b0();
		r1 = r43 + 0x00;
		r44 = r8;
		b0();
		r1 = r43 + 0x00;
		r44 = 0x00 + 1;
		b0();
		__break();
		wait_for();
		return;
	}
	word32 * r35 = r1 + 6516;
	word32 * r33 = r1 + 5900;
	word32 * r36 = r1 + -0x0000299C;
	word32 v24 = *r35;
	word32 * r14 = (word64) v24;
	word32 v26 = (word32) 0x00;
	word32 v27 = (word32) r14;
	p07 = v26 == v27;
	p06 = v26 != v27;
	r14 = r1 + 0x00001CC4;
	word32 * r34;
	word32 * r0;
	if (p07)
	{
		r36 = r1 + -0x0000299C;
		r34 = r1 + 5868;
		r14 = r1 + 5888;
		r15 = 0x00 + -1;
		r33 = r1 + 5900;
		r36 = (word32 *) *r36;
		*r0 = (word32) r34;
		*r15 = (word32) r14;
		r44 = (word32 *) *r36;
		b0();
		r1 = r43 + 0x00;
		*r8 = (word32) r33;
		goto l400000000007F760;
	}
	*r15 = (word32) r33;
	r36 = (word32 *) *r36;
	word32 v38 = *r14;
	r14 = (word64) v38;
	word32 v39 = (word32) 0x00;
	word32 v40 = (word32) r14;
	p07 = v39 == v40;
	p06 = v39 != v40;
	word32 * r38;
	word32 * r37;
	if (p06)
	{
		r44 = (word32 *) *r36;
		b0();
		r1 = r43 + 0x00;
		r44 = r8;
		b0();
		word32 v41 = (word32) 0x00;
		word32 v42 = (word32) r8;
		p06 = v41 == v42;
		p07 = v41 != v42;
		r1 = r43 + 0x00;
		if (!p06)
		{
			if (p07)
			{
				word32 v101 = *r33;
				r44 = (word64) v101;
			}
			r32 < null;
			r32 >= null;
			word64 p48;
			if (p48)
			{
				word64 pr = r107;
			}
		}
		r44 = r1 + -0x00001F14;
		r45 = 0x00 + 2050;
		r44 = (word32 *) *r44;
		b0();
		r44 = r8;
		r1 = r43 + 0x00;
		*r8 = (word32) r33;
		word32 v43 = (word32) ~0x00;
		word32 v44 = (word32) r44;
		p06 = v43 == v44;
		p07 = v43 != v44;
		if (p07)
		{
			r45 = 0x00 + 1;
			r46 = 0x00 + -1;
			b0();
			r1 = r43 + 0x00;
			word32 v45 = *r32;
			r14 = (word64) v45;
			r44 = r8;
			*r8 = (word32) r33;
			r34 = r1 + 5900;
			r38 = r1 + 5896;
			r37 = r1 + 5892;
			word32 v48 = (word32) 0x00;
			word32 v49 = (word32) r14;
			p07 = v48 == v49;
			p06 = v48 != v49;
			if (p06)
				goto l400000000007F530;
			goto l400000000007FA40;
		}
	}
	r44 = (word32 *) *r36;
	b0();
	r1 = r43 + 0x00;
	r44 = r8;
	b0();
	r1 = r43 + 0x00;
	r44 = r8;
	*r8 = (word32) r33;
	r45 = 0x00 + 1;
	r46 = 0x00 + -1;
	b0();
	r1 = r43 + 0x00;
	word32 v98 = *r32;
	r14 = (word64) v98;
	r44 = r8;
	*r8 = (word32) r33;
	r34 = r1 + 5900;
	r38 = r1 + 5896;
	r37 = r1 + 5892;
	word32 v99 = (word32) 0x00;
	word32 v100 = (word32) r14;
	p07 = v99 == v100;
	p06 = v99 != v100;
	if (!p07)
	{
l400000000007F530:
		word32 * r39;
		word32 * r40;
		while (true)
		{
			b0();
			r1 = r43 + 0x00;
			*r8 = (word32) r37;
			word32 v50 = (word32) ~0x00;
			word32 v51 = (word32) r8;
			p07 = v50 == v51;
			p06 = v50 != v51;
			r44 = 0x00 + 21;
			r45 = 0x00 + 0x00;
			if (p07)
				break;
			word32 v87 = *r32;
			r14 = (word64) v87;
			word32 v88 = (word32) r14;
			word32 v89 = (word32) r8;
			p06 = v88 == v89;
			p07 = v88 != v89;
			if (p06)
			{
				r38 = r1 + 5888;
				word32 v90 = *r32;
				r14 = (word64) v90;
				r39 = r1 + 5896;
				r40 = 0x00 + -1;
				*r14 = (word32) r38;
				b0();
				word32 v91 = *r38;
				r14 = (word64) v91;
				r1 = r43 + 0x00;
				*r8 = (word32) r32;
				word32 v92 = (word32) r14;
				word32 v93 = (word32) r8;
				p06 = v92 == v93;
				p07 = v92 != v93;
				if (p06)
					goto l400000000007F8C0;
				goto l400000000007F650;
			}
			b0();
			r1 = r43 + 0x00;
			r34 = r8;
			r44 = 0x00 + 0x00;
			r45 = 0x00 + 21;
			b0();
			r1 = r43 + 0x00;
			r44 = 0x00 + 21;
			r45.u1 = r34;
			b0();
			r1 = r43 + 0x00;
			word32 v94 = *r33;
			r44 = (word64) v94;
		}
		b0();
		r1 = r43 + 0x00;
		word32 v52 = *r32;
		r14 = (word64) v52;
		word32 v53 = *r8;
		r40 = (word64) v53;
		r38 = r1 + 5888;
		r39 = r1 + 5896;
		*r14 = (word32) r38;
		b0();
		word32 v56 = *r38;
		r14 = (word64) v56;
		r1 = r43 + 0x00;
		*r8 = (word32) r32;
		word32 v57 = (word32) r14;
		word32 v58 = (word32) r8;
		p06 = v57 == v58;
		p07 = v57 != v58;
		if (p07)
		{
l400000000007F650:
			r44 = 0x00 + 0x00;
			r45.u1 = r8;
			b0();
			r1 = r43 + 0x00;
			int32 v59 = (word32) r8;
			int32 v60 = (word32) 0x00;
			p06 = v59 < v60;
			p07 = v59 >= v60;
			r15 = 0x00 + 1;
			r45 = 0x00 + 0x00;
			if (!p06)
			{
				r34 = r1 + 5868;
				word32 v73 = *r39;
				r44 = (word64) v73;
				word32 v74 = *r38;
				r14 = (word64) v74;
				*r15 = (word32) r34;
				word32 v75 = (word32) r14;
				word32 v76 = (word32) r44;
				p07 = v75 == v76;
				p06 = v75 != v76;
				if (!p07)
				{
					word32 v77 = *r37;
					r14 = (word64) v77;
					word32 v78 = (word32) r44;
					word32 v79 = (word32) r14;
					p06 = v78 == v79;
					p07 = v78 != v79;
					if (!p06)
					{
						b0();
						r1 = r43 + 0x00;
						int32 v80 = (word32) r8;
						int32 v81 = (word32) 0x00;
						p07 = v80 < v81;
						p06 = v80 >= v81;
						r46 = 0x00 + 5;
						r44 = 0x00 + 0x00;
						if (p07)
						{
							word32 v82 = *r38;
							r45.u1 = (word64) v82;
							r44 = 0x00 + 0x00;
							b0();
							r1 = r43 + 0x00;
							word32 v83 = *r38;
							r14 = (word64) v83;
							r46 = 0x00 + 5;
							*r0 = (word32) r34;
							r44 = 0x00 + 0x00;
							r45 = r1 + -7932;
							*r14 = (word32) r39;
							r45 = *r45;
							b0();
							r1 = r43 + 0x00;
							r44 = r8;
							b0();
							r1 = r43 + 0x00;
							goto l400000000007F760;
						}
						word32 v84 = *r34;
						r14 = (word64) v84;
						r45 = r1 + -7932;
						word32 v85 = (word32) 0x00;
						word32 v86 = (word32) r14;
						p07 = v85 == v86;
						p06 = v85 != v86;
						if (!p06)
						{
							r45 = *r45;
							b0();
							r1 = r43 + 0x00;
							r44 = r8;
							b0();
							r1 = r43 + 0x00;
							goto l400000000007F760;
						}
					}
				}
l400000000007F8E0:
				word32 v62 = *r33;
				r44 = (word64) v62;
				b0();
				r1 = r43 + 0x00;
				word32 v63 = (word32) ~0x00;
				word32 v64 = (word32) r8;
				p06 = v63 == v64;
				p07 = v63 != v64;
				r37 = r8;
				if (!p06)
				{
					word32 v67 = *r32;
					r14 = (word64) v67;
					word32 v68 = (word32) r14;
					word32 v69 = (word32) r8;
					p06 = v68 == v69;
					p07 = v68 != v69;
					if (p06)
					{
						word32 v70 = *r34;
						r14 = (word64) v70;
						word32 v71 = (word32) 0x00;
						word32 v72 = (word32) r14;
						p07 = v71 == v72;
						p06 = v71 != v72;
						if (!p06)
						{
							r45 = r1 + -7932;
							r46 = 0x00 + 5;
							r44 = 0x00 + 0x00;
							r45 = *r45;
							b0();
							r1 = r43 + 0x00;
							r44 = r8;
							b0();
							r1 = r43 + 0x00;
						}
						goto l400000000007F760;
					}
				}
				word32 v65 = (word32) ~0x00;
				word32 v66 = (word32) r40;
				p06 = v65 == v66;
				p07 = v65 != v66;
				if (!p06)
				{
					b0();
					r1 = r43 + 0x00;
					*r40 = (word32) r8;
				}
				r45 = r1 + -7940;
				r46 = 0x00 + 5;
				r44 = 0x00 + 0x00;
				r45 = *r45;
				b0();
				r1 = r43 + 0x00;
				r44 = r8;
				r45.u1 = r37;
				b0();
				r1 = r43 + 0x00;
				r46 = 0x00 + 5;
				*r0 = (word32) r34;
				r44 = 0x00 + 0x00;
				r45 = r1 + -7932;
				r45 = *r45;
				b0();
				r1 = r43 + 0x00;
				r44 = r8;
				b0();
				r1 = r43 + 0x00;
l400000000007F760:
				r44 = (word32 *) *r36;
				b0();
				word32 v30 = *r33;
				r44 = (word64) v30;
				r1 = r43 + 0x00;
				r45 = 0x00 + 2;
				r46 = 0x00 + 1;
				word32 v31 = (word32) r44;
				word32 v32 = (word32) r8;
				p06 = v31 == v32;
				p07 = v31 != v32;
				if (!p06)
				{
					b0();
					r1 = r43 + 0x00;
				}
				r45 = r1 + -7644;
				r44 = 0x00 + 0x0011;
				r45 = *r45;
				b0();
				word32 v33 = *r34;
				r45.u1 = (word64) v33;
				r1 = r43 + 0x00;
				r44 = 0x00 + 0x006D;
				word32 v34 = (word32) 0x00;
				word32 v35 = (word32) r45;
				p06 = v34 == v35;
				p07 = v34 != v35;
				if (p06)
					r45 = 0x00 + 43;
				word32 v36 = (word32) 0x00;
				r11 = (word64) v36;
				__break();
			}
			r45 = r1 + -7948;
			r46 = 0x00 + 5;
			r44 = 0x00 + 0x00;
			r45 = *r45;
			b0();
			r1 = r43 + 0x00;
			r44 = r8;
			b0();
			word32 v61 = *r38;
			r14 = (word64) v61;
			r1 = r43 + 0x00;
			*r14 = (word32) r39;
		}
l400000000007F8C0:
		r34 = r1 + 5868;
		r14 = 0x00 + 1;
		*r14 = (word32) r34;
		goto l400000000007F8E0;
	}
l400000000007FA40:
	b0();
	r1 = r43 + 0x00;
	r44 = 0x00 + 0x00;
	r45.u1 = r8;
	*r8 = (word32) r38;
	b0();
	r1 = r43 + 0x00;
	word32 v95 = *r34;
	r44 = (word64) v95;
	word32 v96 = *r38;
	r45.u1 = (word64) v96;
	b0();
	r1 = r43 + 0x00;
	word32 v97 = *r34;
	r44 = (word64) v97;
	goto l400000000007F530;
}

// 400000000007FE40: define wait_for
// Called from:
//      restart_job_control
define wait_for
{
	word64 * r64;
	<anonymous> * b3;
	word64 r1;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r52 = ar.pfs;
	word64 r12 = r12 + ~0xFF;
	word64 r54 = pr;
	word64 r53 = r1 + 0x00;
	word32 * r40 = r1 + 5868;
	word64 r44 = r1 + 7476;
	<anonymous> * r51 = b3;
	Eq_n r55 = r12 + 0x90;
	<anonymous> * b0;
	b0();
	struct Eq_n * r56 = 0x00 + 0x0011;
	r1 = r53 + 0x00;
	r55 = r12 + 0x90;
	b0();
	r1 = r53 + 0x00;
	r55 = r12 + 0x10;
	b0();
	r1 = r53 + 0x00;
	r55 = 0x00 + 0x00;
	r56 = r12 + 0x90;
	word64 r57 = r12 + 0x10;
	b0();
	r1 = r53 + 0x00;
	word32 v19 = *r40;
	Eq_n r14;
	r14.u2 = (word64) v19;
	word32 * r0;
	*r0 = (word32) r44;
	word32 v22 = (word32) 0x00;
	word32 v23 = (word32) r14;
	Eq_n p06 = v22 == v23;
	Eq_n p07 = v22 != v23;
	r14 = r1 + 0x00002344;
	if (!p06)
	{
		word32 v26 = r14.u3->t0000.u1;
		r14.u2 = (word64) v26;
		if (!p06)
			goto l400000000007FF20;
	}
	r56 = r1 + -7788;
	r55 = 0x00 + 2;
	r56 = r56->ptr0000;
	b0();
	r1 = r53 + 0x00;
	union Eq_n * r8;
	p07 = (union Eq_n *) 0x01 == r8;
	p06 = (union Eq_n *) 0x01 != r8;
	r14 = r1 + 0x0000171C;
	r8->u2 = (word64 *) r14;
	word32 * r38;
	if (!p06)
	{
		r55 = 0x00 + 2;
		r56 = 0x00 + 1;
		b0();
		r1 = r53 + 0x00;
		r38 = r1 + 6516;
		word32 v32 = *r38;
		r14.u2 = (word64) v32;
		word32 v33 = (word32) 0x00;
		word32 v34 = (word32) r14;
		p07 = v33 == v34;
		p06 = v33 != v34;
		Eq_n r37;
		if (!p07)
		{
l40000000000805C0:
			word32 v38 = *r40;
			r14.u2 = (word64) v38;
			r37 = r1 + 7676;
			word32 v39 = (word32) 0x00;
			word32 v40 = (word32) r14;
			p07 = v39 == v40;
			p06 = v39 != v40;
			if (!p06)
			{
				r14 = __ld_acquire<word32>(r37);
				word32 v53 = (word32) 0x00;
				word32 v54 = (word32) r14;
				p06 = v53 == v54;
				p07 = v53 != v54;
				r14 = r1 + 7684;
				if (p07)
				{
					r55 = __ld_acquire<word32>(r37);
					b0();
					r1 = r53 + 0x00;
					r14 = r1 + 7684;
					r14 = __ld_acquire<word32>(r14);
					word32 v62 = (word32) 0x00;
					word32 v63 = (word32) r14;
					p06 = v62 == v63;
					p07 = v62 != v63;
					if (p06)
						goto l400000000007FF70;
				}
				else
				{
					r14 = __ld_acquire<word32>(r14);
					word32 v60 = (word32) 0x00;
					word32 v61 = (word32) r14;
					p06 = v60 == v61;
					p07 = v60 != v61;
					if (p06)
						goto l400000000007FF70;
				}
				b0();
				r14 = __ld_acquire<word32>(r37);
				r1 = r53 + 0x00;
				word32 v68 = (word32) 0x00;
				word32 v69 = (word32) r14;
				p06 = v68 == v69;
				p07 = v68 != v69;
				word64 * r33;
				word32 * r42;
				word32 * r50;
				union Eq_n * r49;
				Eq_n r47;
				Eq_n r41;
				Eq_n r43;
				word64 r39;
				union Eq_n * r36;
				ptr64 r48;
				word32 * r46;
				word32 * r45;
				if (!p06)
				{
l40000000000808A0:
					r14 = r1 + 7676;
					r33 = 0x00 + -1;
					r42 = 0x00 + 1;
					r50 = 0x00 + 4;
					r55 = __ld_acquire<word32>(r14);
					b0();
					r1 = r53 + 0x00;
					r14 = r1 + -20676;
					r49 = r1 + 8388;
					r47 = r1 + -9804;
					r41 = r1 + 7676;
					r43 = r1 + 7684;
					r39 = r1 + 7472;
					r36 = r1 + 7444;
					r48 = (ptr64) ((word32) r14 + 8);
					r47.u2 = *r47.u2;
					r46 = (word32 *) ((word32) r14 + 0x0C);
					r45 = (word32 *) ((word32) r14 + 44);
l4000000000080000:
					do
					{
						word64 r32;
						r55 = r32 + 0x00;
						r56 = 0x00 + 0x00;
						r57 = 0x00 + 0x00;
						b0();
						p07 = null == r8;
						p06 = null != r8;
						word32 * r35 = (word32 *) ((char *) r8 + 16);
						r1 = r53 + 0x00;
						word64 * r34 = (word64 *) &r8->u0;
						int32 v58 = (int32) r33;
						int64 r15 = (int64) v58;
						if (p07)
						{
							r14 = r1 + 5896;
							r56 = 0x00 + 0x00;
							r36 = 0x00 + 0x007F;
							word32 v66 = r14.u3->t0000.u1;
							r55.u2 = (word64) v66;
							b0();
							r1 = r53 + 0x00;
							r56 = r12 + 0x10;
							r55 = 0x00 + 2;
							r57 = 0x00 + 0x00;
							b0();
							r1 = r53 + 0x00;
							r57 = 0x00 + 5;
							r55 = 0x00 + 0x00;
							r56 = r1 + -7924;
							r56 = r56->ptr0000;
							b0();
							r1 = r53 + 0x00;
							r55.u2 = &r8->u0;
							int32 v67 = (int32) r32;
							r56 = (int64) v67;
							b0();
							r1 = r53 + 0x00;
							b0();
							r8 = (union Eq_n *) &r36->u0;
							r1 = r53 + 0x00;
							pr = r54;
							ar.pfs = r52;
							b0 = r51;
							r12 += 0x0100;
							return;
						}
						word32 v64 = (word32) ~0x00;
						word32 v65 = (word32) r33;
						p07 = v64 == v65;
						p06 = v64 != v65;
						if (p07)
						{
							r55 = r32 + 0x00;
							r56 = 0x00 + 0x00;
							r57 = 0x00 + 0x00;
							b0();
							word32 v70 = *r35;
							r14.u2 = (word64) v70;
							r33 = (word64 *) &r8->u0;
							r1 = r53 + 0x00;
							word32 v71 = (word32) 0x01;
							word32 v72 = (word32) r14;
							p06 = v71 == v72;
							p07 = v71 != v72;
							int32 v73 = (int32) r33;
							r15 = (int64) v73;
							if (p06)
								goto l4000000000080680;
							word32 v77 = (word32) ~0x00;
							word32 v78 = (word32) r8;
							p06 = v77 == v78;
							p07 = v77 != v78;
							if (p06)
								goto l40000000000800C0;
							r14.u2 = r36->u2;
							r14.u2 += r15;
							r14.u2 = *r14.u2;
							r14.u1 = (word32) r14 + 20;
							word32 v84 = r14.u3->t0000.u1;
							r14.u2 = (word64) v84;
							word32 v85 = (word32) 0x01;
							word32 v86 = (word32) r14;
							p07 = v85 == v86;
							p06 = v85 != v86;
							if (p06)
								goto l40000000000800C0;
							goto l4000000000080680;
						}
						word32 v74 = *r35;
						r14.u2 = (word64) v74;
						word32 v75 = (word32) 0x01;
						word32 v76 = (word32) r14;
						p06 = v75 == v76;
						p07 = v75 != v76;
						if (p06)
						{
l4000000000080680:
							*r42 = (word32) r39;
							r55 = 0x00 + 1;
							b0();
							r1 = r53 + 0x00;
							*r0 = (word32) r39;
							word32 v79 = (word32) ~0x00;
							word32 v80 = (word32) r8;
							p07 = v79 == v80;
							p06 = v79 != v80;
							if (!p06)
							{
								b0();
								Eq_n v90;
								v90.u1 = r8->u1;
								r15 = (word64) v90;
								r1 = r53 + 0x00;
								word32 v91 = (word32) 0x0A;
								word32 v92 = (word32) r15;
								p07 = v91 == v92;
								p06 = v91 != v92;
								if (!p06)
								{
									r14.u2 = r49->u2;
									int32 v95 = (int32) r33;
									int64 * r17 = (int64) v95;
									p06 = r47 == r14;
									p07 = r47 != r14;
									r14.u2 = (char *) r34 + 0x0C;
									if (p06)
									{
										r55 = 0x00 + 2;
										r56 = r12 + 0x10;
										r57 = 0x00 + 0x00;
										r36 = 0x00 + -1;
										b0();
										r1 = r53 + 0x00;
										b0();
										r1 = r53 + 0x00;
										r8 = (union Eq_n *) &r36->u0;
										pr = r54;
										ar.pfs = r52;
										b0 = r51;
										r12 += 0x0100;
										return;
									}
									*r0 = (word32) r14;
									*r0 = (word32) r35;
									word32 v113 = (word32) ~0x00;
									word32 v114 = (word32) r33;
									p07 = v113 == v114;
									p06 = v113 != v114;
									*r0 = (word32) r48;
									if (!p07)
									{
										r14.u2 = r36->u2;
										word32 v118 = *r46;
										r15 = (word64) v118;
										r17 = r14.u2 + r17;
										word32 * r16 = r15 + 0x01;
										word32 v120 = *r45;
										r14.u2 = (word64) v120;
										r15 = *r17;
										r14.u2 = &r14.u3->ptr0001;
										*r16 = (word32) r46;
										r15 += 0x14;
										*r50 = (word32) r15;
										r14.u3->t0000.u1 = (word32) r45;
									}
								}
							}
							goto l40000000000800C0;
						}
						r14.u2 = r36->u2;
						r14.u2 += r15;
						r14.u2 = *r14.u2;
						r14.u1 = (word32) r14 + 20;
						word32 v81 = r14.u3->t0000.u1;
						r14.u2 = (word64) v81;
						word32 v82 = (word32) 0x01;
						word32 v83 = (word32) r14;
						p07 = v82 == v83;
						p06 = v82 != v83;
						if (p07)
							goto l4000000000080680;
l40000000000800C0:
						word32 v87 = *r38;
						r14.u2 = (word64) v87;
						word32 v88 = (word32) 0x00;
						word32 v89 = (word32) r14;
						p07 = v88 == v89;
						p06 = v88 != v89;
						if (p07)
						{
l4000000000080140:
							r14 = __ld_acquire<word32>(r37);
							word32 v93 = (word32) 0x00;
							word32 v94 = (word32) r14;
							p06 = v93 == v94;
							p07 = v93 != v94;
							if (p07)
								goto l4000000000080660;
							goto l4000000000080160;
						}
						word32 v97 = *r40;
						r14.u2 = (word64) v97;
						word32 v98 = (word32) 0x00;
						word32 v99 = (word32) r14;
						p07 = v98 == v99;
						p06 = v98 != v99;
						if (p06)
							goto l4000000000080140;
						r14 = __ld_acquire<word32>(r37);
						word32 v108 = (word32) 0x00;
						word32 v109 = (word32) r14;
						p06 = v108 == v109;
						p07 = v108 != v109;
						if (p07)
						{
							r55 = __ld_acquire<word32>(r41);
							b0();
							r14 = __ld_acquire<word32>(r43);
							r1 = r53 + 0x00;
							word32 v115 = (word32) 0x00;
							word32 v116 = (word32) r14;
							p06 = v115 == v116;
							p07 = v115 != v116;
							if (p06)
								goto l4000000000080140;
							goto l4000000000080780;
						}
						r14 = __ld_acquire<word32>(r43);
						word32 v121 = (word32) 0x00;
						word32 v122 = (word32) r14;
						p06 = v121 == v122;
						p07 = v121 != v122;
						if (!p07)
							goto l4000000000080140;
l4000000000080780:
						b0();
						r14 = __ld_acquire<word32>(r37);
						r1 = r53 + 0x00;
						word32 v124 = (word32) 0x00;
						word32 v125 = (word32) r14;
						p06 = v124 == v125;
						p07 = v124 != v125;
						if (!p06)
						{
l4000000000080660:
							r55 = __ld_acquire<word32>(r41);
							b0();
							r1 = r53 + 0x00;
						}
l4000000000080160:
						word32 v100 = *r35;
						r14.u2 = (word64) v100;
						word32 v101 = (word32) ~0x00;
						word32 v102 = (word32) r33;
						Eq_n p16 = v101 == v102;
						Eq_n p17 = v101 != v102;
						int32 v105 = (int32) r33;
						r15 = (int64) v105;
						word32 v106 = (word32) 0x01;
						word32 v107 = (word32) r14;
						p06 = v106 == v107;
						p07 = v106 != v107;
					} while (p06);
					if (p07)
					{
						Eq_n p01 = r64 < r33;
						Eq_n p11 = r64 >= r33;
					}
					word64 p33;
					if (p33)
						__break();
					__break();
					__break();
				}
l400000000007FF90:
				r14 = r1 + -20676;
				r49 = r1 + 8388;
				r47 = r1 + -9804;
				r41 = r1 + 7676;
				r43 = r1 + 7684;
				r33 = 0x00 + -1;
				r39 = r1 + 7472;
				r42 = 0x00 + 1;
				r36 = r1 + 7444;
				r50 = 0x00 + 4;
				r48 = (ptr64) ((word32) r14 + 8);
				r47.u2 = *r47.u2;
				r46 = (word32 *) ((word32) r14 + 0x0C);
				r45 = (word32 *) ((word32) r14 + 44);
				goto l4000000000080000;
			}
			else
			{
l400000000007FF70:
				r14 = __ld_acquire<word32>(r37);
				word32 v36 = (word32) 0x00;
				word32 v37 = (word32) r14;
				p06 = v36 == v37;
				p07 = v36 != v37;
				if (p07)
					goto l40000000000808A0;
				goto l400000000007FF90;
			}
		}
l400000000007FF50:
		r37 = r1 + 7676;
		goto l400000000007FF70;
	}
l400000000007FF20:
	r38 = r1 + 6516;
	word32 v29 = *r38;
	r14.u2 = (word64) v29;
	word32 v30 = (word32) 0x00;
	word32 v31 = (word32) r14;
	p07 = v30 == v31;
	p06 = v30 != v31;
	if (p06)
		goto l40000000000805C0;
	goto l400000000007FF50;
}

// 4000000000081080: define wait_for_job
define wait_for_job
{
	word64 r32;
	word64 r1;
	<anonymous> * b4;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r37 = ar.pfs;
	word64 r12 = r12 + ~0xFF;
	<anonymous> * r36 = b4;
	word64 r38 = r1 + 0x00;
	union Eq_n * r33 = r1 + 7444;
	int32 v13 = (int32) r32;
	union Eq_n * r34 = (int64) v13;
	word32 * r39 = r12 + 0x90;
	r34 = (r34 << 0x03) + 0x00;
	<anonymous> * b0;
	b0();
	struct Eq_n * r40 = 0x00 + 0x0011;
	r1 = r38 + 0x00;
	r39 = r12 + 0x90;
	b0();
	r1 = r38 + 0x00;
	r39 = r12 + 0x10;
	b0();
	r1 = r38 + 0x00;
	r40 = r12 + 0x90;
	word64 r41 = r12 + 0x10;
	r39 = 0x00 + 0x00;
	b0();
	Eq_n r14;
	r14.u1 = r33->u1;
	r1 = r38 + 0x00;
	r14.u1 = r34 + r14;
	r14.u1 = r14.u1->t0000.u1;
	r14.u0 = (word32) r14 + 20;
	Eq_n v20;
	v20.u0 = r14.u1->t0000.u0;
	r14.u1 = (word64) v20;
	word32 v21 = (word32) 0x02;
	word32 v22 = (word32) r14;
	Eq_n p07 = v21 == v22;
	Eq_n p06 = v21 != v22;
	word32 * r8;
	if (p07)
	{
		r40 = r1 + -0x00001EEC;
		r41 = 0x00 + 5;
		r39 = 0x00 + 0x00;
		r40 = r40->ptr0000;
		b0();
		r1 = r38 + 0x00;
		r39 = r8;
		r40 = r32 + 0x01;
		b0();
		r1 = r38 + 0x00;
	}
	r39 = r32 + 0x00;
	b0();
	r8 += 2;
	r41 = 0x00 + 0x00;
	r40 = r12 + 0x10;
	r1 = r38 + 0x00;
	r39 = 0x00 + 2;
	word32 v26 = *r8;
	word32 * r35 = (word64) v26;
	b0();
	r39 = r35;
	r1 = r38 + 0x00;
	b0();
	r1 = r38 + 0x00;
	r35 = r8;
	r39 = r12 + 0x90;
	b0();
	r40 = 0x00 + 0x0011;
	r1 = r38 + 0x00;
	r39 = r12 + 0x90;
	b0();
	r1 = r38 + 0x00;
	r39 = r12 + 0x10;
	b0();
	r1 = r38 + 0x00;
	r39 = 0x00 + 0x00;
	r40 = r12 + 0x90;
	r41 = r12 + 0x10;
	b0();
	r1 = r38 + 0x00;
	word32 v28 = (word32) ~0x00;
	word32 v29 = (word32) r32;
	p06 = v28 == v29;
	p07 = v28 != v29;
	if (!p06)
	{
		r14.u1 = r33->u1;
		r34 += r14;
		r14.u1 = r34->u1;
		word32 * r15 = (word32 *) ((word32) r14 + 20);
		p06 = 0x00 == r14;
		p07 = 0x00 != r14;
		if (!p06)
		{
			word32 v31 = *r15;
			r15 = (word64) v31;
			word32 v32 = (word32) 0x04;
			word32 v33 = (word32) r15;
			p07 = v32 == v33;
			p06 = v32 != v33;
			if (p07)
				r14.u0 = (word32) r14 + 24;
			byte v34 = (byte) r11;
			word64 r96 = (word64) v34;
		}
	}
	r39 = 0x00 + 2;
	r40 = r12 + 0x10;
	r41 = 0x00 + 0x00;
	b0();
	r8 = r35;
	r1 = r38 + 0x00;
	ar.pfs = r37;
	b0 = r36;
	r12 += 0x0100;
}

// 4000000000081340: define wait_for_single_pid
define wait_for_single_pid
{
	word64 r8;
	<anonymous> * b2;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word64 r12 = r12 + ~0xFF;
	word64 r36 = r1 + 0x00;
	<anonymous> * r34 = b2;
	word64 r37 = r12 + 0x90;
	<anonymous> * b0;
	b0();
	struct Eq_n * r38 = 0x00 + 0x0011;
	r1 = r36 + 0x00;
	r37 = r12 + 0x90;
	b0();
	r1 = r36 + 0x00;
	r37 = r12 + 0x10;
	b0();
	r1 = r36 + 0x00;
	r38 = r12 + 0x90;
	word64 r39 = r12 + 0x10;
	r37 = 0x00 + 0x00;
	b0();
	r1 = r36 + 0x00;
	word64 r32;
	r37 = r32 + 0x00;
	r38 = 0x00 + 0x00;
	r39 = 0x00 + 0x00;
	b0();
	r39 = 0x00 + 0x00;
	r38 = r12 + 0x10;
	word64 r33 = r8 + 0x00;
	r1 = r36 + 0x00;
	r37 = 0x00 + 2;
	b0();
	Eq_n p07 = 0x00 == r33;
	Eq_n p06 = 0x00 != r33;
	r1 = r36 + 0x00;
	r37 = r32 + 0x00;
	Eq_n r14;
	Eq_n r15;
	if (p07)
	{
		r14 = r1 + 0x00003A34;
		r14.u1 = r14.u1->t0000.u1;
		r15.u0 = (word32) r14 + 8;
		p06 = 0x00 == r14;
		p07 = 0x00 != r14;
		if (p06)
		{
l40000000000816C0:
			r38 = r1 + -0x00001EE4;
			r39 = 0x00 + 5;
			r37 = 0x00 + 0x00;
			r33 = 0x00 + 0x007F;
			r38 = r38->ptr0000;
			b0();
			r1 = r36 + 0x00;
			r37 = r8 + 0x00;
			int32 v28 = (int32) r32;
			r38 = (int64) v28;
			b0();
			r8 = r33 + 0x00;
			r1 = r36 + 0x00;
			ar.pfs = r35;
			b0 = r34;
			r12 += 0x0100;
			return;
		}
		Eq_n v32;
		v32.u0 = r15.u1->t0000.u0;
		r15.u1 = (word64) v32;
		word32 v33 = (word32) r15;
		word32 v34 = (word32) r32;
		p06 = v33 == v34;
		p07 = v33 != v34;
		if (!p06)
		{
			do
			{
				r14.u1 = r14.u1->t0000.u1;
				r15.u0 = (word32) r14 + 8;
				p07 = 0x00 == r14;
				p06 = 0x00 != r14;
				if (p07)
					goto l40000000000816C0;
				Eq_n v40;
				v40.u0 = r15.u1->t0000.u0;
				r15.u1 = (word64) v40;
				word32 v41 = (word32) r15;
				word32 v42 = (word32) r32;
				p07 = v41 == v42;
				p06 = v41 != v42;
			} while (p06);
		}
		r14.u0 = (word32) r14 + 0x0C;
		Eq_n v37;
		v37.u0 = r14.u1->t0000.u0;
		r33 = (word64) v37;
		int32 v38 = (word32) r33;
		int32 v39 = (word32) 0x00;
		p07 = v38 < v39;
		p06 = v38 >= v39;
		if (!p06)
			goto l40000000000816C0;
	}
	else
	{
		b0();
		r1 = r36 + 0x00;
		r33 = r8 + 0x00;
		r37 = r12 + 0x90;
		b0();
		r38 = 0x00 + 0x0011;
		r1 = r36 + 0x00;
		r37 = r12 + 0x90;
		b0();
		r1 = r36 + 0x00;
		r37 = r12 + 0x10;
		b0();
		r1 = r36 + 0x00;
		r38 = r12 + 0x90;
		r39 = r12 + 0x10;
		r37 = 0x00 + 0x00;
		b0();
		r1 = r36 + 0x00;
		r37 = r32 + 0x00;
		r38 = 0x00 + 0x00;
		r39 = 0x00 + 0x00;
		b0();
		r1 = r36 + 0x00;
		r38 = r12 + 0x10;
		r39 = 0x00 + 0x00;
		r37 = 0x00 + 2;
		word32 v20 = (word32) ~0x00;
		word32 v21 = (word32) r8;
		p06 = v20 == v21;
		p07 = v20 != v21;
		int32 v22 = (int32) r8;
		r14.u1 = (int64) v22;
		r15 = r1 + 7444;
		if (!p06)
		{
			r15.u1 = r15.u1->t0000.u1;
			r14.u1 = r15.u1 + r14 *64 2;
			r14.u1 = r14.u1->t0000.u1;
			r15.u0 = (word32) r14 + 20;
			p06 = 0x00 == r14;
			p07 = 0x00 != r14;
			if (!p06)
			{
				Eq_n v29;
				v29.u0 = r15.u1->t0000.u0;
				r15.u1 = (word64) v29;
				word32 v30 = (word32) 0x04;
				word32 v31 = (word32) r15;
				p07 = v30 == v31;
				p06 = v30 != v31;
				if (p07)
					r14.u0 = (word32) r14 + 24;
				byte v35 = (byte) r11;
				word64 r96 = (word64) v35;
			}
		}
		b0();
		r1 = r36 + 0x00;
		r14 = r1 + 6456;
		Eq_n v25;
		v25.u0 = r14.u1->t0000.u0;
		r14.u1 = (word64) v25;
		word32 v26 = (word32) 0x00;
		word32 v27 = (word32) r14;
		p06 = v26 == v27;
		p07 = v26 != v27;
		if (p07)
		{
			b0();
			r1 = r36 + 0x00;
			r37 = r32 + 0x00;
			b0();
			r8 = r33 + 0x00;
			r1 = r36 + 0x00;
			ar.pfs = r35;
			b0 = r34;
			r12 += 0x0100;
			return;
		}
	}
	r8 = r33 + 0x00;
	ar.pfs = r35;
	b0 = r34;
	r12 += 0x0100;
}

// 4000000000081740: define wait_for_background_pids
define wait_for_background_pids
{
	<anonymous> * b1;
	word64 r1;
	Eq_n LC;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r42 = ar.pfs;
	word64 r12 = r12 + ~0x01FF;
	Eq_n r44 = LC;
	word32 * r35 = r1 + -20676;
	Eq_n r34 = r1 + 7676;
	Eq_n r37 = r1 + 7684;
	word64 r43 = r1 + 0x00;
	<anonymous> * r41 = b1;
	union Eq_n * r36 = r1 + 7444;
	word32 * r39 = 0x00 + 4;
	word32 * r38 = r35 + 11;
	r35 += 7;
	word64 r40 = r38;
l40000000000817A0:
	Eq_n r45 = r12 + 400;
	<anonymous> * b0;
	b0();
	word64 r46 = 0x00 + 0x0011;
	r1 = r43 + 0x00;
	r45 = r12 + 400;
	b0();
	r1 = r43 + 0x00;
	r45 = r12 + 0x0110;
	b0();
	r1 = r43 + 0x00;
	r45 = 0x00 + 0x00;
	r46 = r12 + 400;
	word64 r47 = r12 + 0x0110;
	b0();
	word32 v24 = *r35;
	Eq_n r14;
	r14.u2 = (word64) v24;
	r1 = r43 + 0x00;
	int32 v26 = (word32) 0x00;
	int32 v27 = (word32) r14;
	Eq_n p07 = v26 < v27;
	Eq_n p06 = v26 >= v27;
	word32 * r8;
	word64 r33;
	word32 * r32;
	word32 * r0;
	Eq_n r16;
	Eq_n r15;
	if (p06)
	{
		do
		{
			word32 v32 = (word32) 0x00;
			word32 v33 = (word32) r14;
			p07 = v32 == v33;
			p06 = v32 != v33;
			r45 = 0x00 + 0x00;
			if (p07)
				goto l4000000000081890;
			b0();
			r8 += 2;
			r1 = r43 + 0x00;
			r47 = 0x00 + 0x00;
			r46 = r12 + 0x0110;
			r45 = 0x00 + 2;
			word32 v39 = *r8;
			r33 = (word64) v39;
			b0();
			r14 = __ld_acquire<word32>(r34);
			r1 = r43 + 0x00;
			word32 v41 = (word32) 0x00;
			word32 v42 = (word32) r14;
			p06 = v41 == v42;
			p07 = v41 != v42;
			if (!p06)
				goto l4000000000081C90;
l4000000000081990:
			r14 = __ld_acquire<word32>(r37);
			word32 v46 = (word32) 0x00;
			word32 v47 = (word32) r14;
			p06 = v46 == v47;
			p07 = v46 != v47;
			if (!p07)
				goto l40000000000819B0;
l4000000000081C30:
			b0();
			r1 = r43 + 0x00;
			b0();
			r1 = r43 + 0x00;
			r32 = r8;
			r45 = r33 + 0x00;
			*r0 = (word32) r8;
			b0();
			r1 = r43 + 0x00;
			word32 v54 = (word32) ~0x00;
			word32 v55 = (word32) r8;
			p07 = v54 == v55;
			p06 = v54 != v55;
			if (p06)
				goto l40000000000817A0;
l40000000000819F0:
			word32 v56 = *r32;
			r14.u2 = (word64) v56;
			word32 v57 = (word32) 0x0A;
			word32 v58 = (word32) r14;
			p07 = v57 == v58;
			p06 = v57 != v58;
			if (p06)
				goto l40000000000817A0;
			word32 v59 = *r35;
			r14.u2 = (word64) v59;
			word32 v60 = (word32) 0x00;
			word32 v61 = (word32) r14;
			p06 = v60 == v61;
			p07 = v60 != v61;
			if (p06)
				goto l40000000000817A0;
			r45 = r12 + 0x90;
			b0();
			r46 = 0x00 + 0x0011;
			r1 = r43 + 0x00;
			r45 = r12 + 0x90;
			b0();
			r1 = r43 + 0x00;
			r45 = r12 + 0x10;
			b0();
			r1 = r43 + 0x00;
			r45 = 0x00 + 0x00;
			r46 = r12 + 0x90;
			r47 = r12 + 0x10;
			b0();
			word32 v62 = *r35;
			r14.u2 = (word64) v62;
			r1 = r43 + 0x00;
			int32 v63 = (word32) 0x00;
			int32 v64 = (word32) r14;
			p06 = v63 < v64;
			p07 = v63 >= v64;
			r14.u1 = (word32) r14 - 1;
			if (!p07)
			{
				r16.u2 = r36->u2;
				r15 = __addp4(0x00, r14);
				word32 v65 = *r38;
				word64 r17 = (word64) v65;
				r14.u1 = (word32) r16 + 8;
				LC = r15;
				r15.u2 = *r16.u2;
				r16.u2 = r14.u2;
				r14.u1 = (word32) r14 + 8;
				p06 = 0x00 == r15;
				p07 = 0x00 != r15;
				Eq_n r18;
				r18.u0 = (word32) r15 + 20;
				if (p07)
					*r39 = (word32) r18;
			}
			r47 = 0x00 + 0x00;
			r46 = r12 + 0x10;
			r45 = 0x00 + 2;
			b0();
			r1 = r43 + 0x00;
			r45 = r12 + 400;
			b0();
			r46 = 0x00 + 0x0011;
			r1 = r43 + 0x00;
			r45 = r12 + 400;
			b0();
			r1 = r43 + 0x00;
			r45 = r12 + 0x0110;
			b0();
			r1 = r43 + 0x00;
			r45 = 0x00 + 0x00;
			r46 = r12 + 400;
			r47 = r12 + 0x0110;
			b0();
			word32 v68 = *r35;
			r14.u2 = (word64) v68;
			r1 = r43 + 0x00;
			int32 v69 = (word32) 0x00;
			int32 v70 = (word32) r14;
			p07 = v69 < v70;
			p06 = v69 >= v70;
		} while (!p07);
	}
	r14.u1 = (word32) r14 - 1;
	r15.u2 = r36->u2;
	r45 = 0x00 + 0x00;
	r14 = __addp4(0x00, r14);
	LC = r14;
l4000000000081840:
	r14.u2 = *r15.u2;
	r15.u1 = (word32) r15 + 8;
	r16.u1 = (word32) r14 + 20;
	p06 = 0x00 == r14;
	p07 = 0x00 != r14;
	if (p06)
	{
l4000000000081880:
		r45.u2 = &r45.u3->ptr0001;
		if (LC == 0x00)
		{
l4000000000081890:
			r46 = r12 + 0x0110;
			r47 = 0x00 + 0x00;
			r45 = 0x00 + 2;
			b0();
			r45 = 0x00 + 1;
			r1 = r43 + 0x00;
			b0();
			r1 = r43 + 0x00;
			b0();
			r1 = r43 + 0x00;
			b0();
			r1 = r43 + 0x00;
			ar.pfs = r42;
			LC = r44;
			b0 = r41;
			r12 += 0x0200;
			return;
		}
		--LC;
		goto l4000000000081840;
	}
	Eq_n v34;
	v34.u1 = r16.u3->t0000.u1;
	r16.u2 = (word64) v34;
	word32 v35 = (word32) 0x01;
	word32 v36 = (word32) r16;
	p07 = v35 == v36;
	p06 = v35 != v36;
	if (!p07)
		goto l4000000000081880;
	r14.u1 = (word32) r14 + 24;
	Eq_n v37;
	v37.u1 = r14.u3->t0000.u1;
	r14.u2 = (word64) v37;
	if (p07)
		goto l4000000000081880;
	b0();
	r8 += 2;
	r1 = r43 + 0x00;
	r47 = 0x00 + 0x00;
	r46 = r12 + 0x0110;
	r45 = 0x00 + 2;
	word32 v43 = *r8;
	r33 = (word64) v43;
	b0();
	r14 = __ld_acquire<word32>(r34);
	r1 = r43 + 0x00;
	word32 v44 = (word32) 0x00;
	word32 v45 = (word32) r14;
	p06 = v44 == v45;
	p07 = v44 != v45;
	if (p07)
	{
l4000000000081C90:
		r45 = __ld_acquire<word32>(r34);
		b0();
		r14 = __ld_acquire<word32>(r37);
		r1 = r43 + 0x00;
		word32 v48 = (word32) 0x00;
		word32 v49 = (word32) r14;
		p06 = v48 == v49;
		p07 = v48 != v49;
		if (p06)
		{
l40000000000819B0:
			b0();
			r1 = r43 + 0x00;
			r32 = r8;
			r45 = r33 + 0x00;
			*r0 = (word32) r8;
			b0();
			r1 = r43 + 0x00;
			word32 v52 = (word32) ~0x00;
			word32 v53 = (word32) r8;
			p07 = v52 == v53;
			p06 = v52 != v53;
			if (!p06)
				goto l40000000000819F0;
			goto l40000000000817A0;
		}
		goto l4000000000081C30;
	}
	goto l4000000000081990;
}

// 4000000000081D00: define start_job
define start_job
{
	word64 r33;
	<anonymous> * b0;
	word64 r32;
	word64 r1;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r41 = ar.pfs;
	word64 r12 = r12 + ~0xFF;
	word64 r43 = pr;
	word64 r42 = r1 + 0x00;
	word64 r36 = r1 + 7444;
	int32 v13 = (int32) r32;
	int64 r35 = (int64) v13;
	<anonymous> * r40 = b0;
	word64 r44 = r12 + 0x90;
	r35 = (r35 << 0x03) + 0x00;
	word32 v19 = (word32) 0x00;
	word32 v20 = (word32) r33;
	Eq_n p16 = v19 == v20;
	Eq_n p17 = v19 != v20;
	b0();
	word64 r45 = 0x00 + 0x0011;
	r1 = r42 + 0x00;
	r44 = r12 + 0x90;
	if (p17)
	{
		word64 r37 = 0x00 + 0x00;
	}
	word64 p32;
	if (p32)
		__break();
	if (!p16)
	{
		if (p32)
			__break();
		word64 p33;
		if (p33)
		{
			word64 KR0 = r1;
		}
	}
}

// 4000000000082740: define make_child
define make_child
{
	word32 * r8;
	word64 r33;
	word64 LC;
	word64 b5;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r38 = ar.pfs;
	word64 r12 = r12 + ~0x010F;
	word64 r39 = r1 + 0x00;
	word64 r37 = b5;
	word64 r41 = r12 + 0x90;
	word64 r40 = LC;
	word64 r34 = 0x00 + 1;
	<anonymous> * b0;
	b0();
	r1 = r39 + 0x00;
	r41 = r12 + 0x90;
	word64 r42 = 0x00 + 0x0011;
	b0();
	r42 = 0x00 + 2;
	r1 = r39 + 0x00;
	r41 = r12 + 0x90;
	b0();
	r1 = r39 + 0x00;
	r41 = r12 + 0x10;
	b0();
	r41 = 0x00 + 0x00;
	r1 = r39 + 0x00;
	r42 = r12 + 0x90;
	word64 r43 = r12 + 0x10;
	b0();
	r1 = r39 + 0x00;
	b0();
	r1 = r39 + 0x00;
	word32 v19 = (word32) 0x00;
	word32 v20 = (word32) r33;
	Eq_n p08 = v19 == v20;
	Eq_n p09 = v19 != v20;
	word32 * r14 = r1 + 5636;
	word32 v24 = *r14;
	r41 = (word64) v24;
	word32 v25 = (word32) ~0x00;
	word32 v26 = (word32) r41;
	Eq_n p06 = v25 == v26;
	Eq_n p07 = v25 != v26;
	if (p06)
	{
		LC = 0x04;
		b0();
		r1 = r39 + 0x00;
		word64 r35 = r8;
		int32 v32 = (word32) r8;
		int32 v33 = (word32) 0x00;
		p07 = v32 < v33;
		p06 = v32 >= v33;
		if (!p06)
		{
			b0();
			word32 v34 = *r8;
			r14 = (word64) v34;
			r1 = r39 + 0x00;
			r41 = 0x00 + 0x00;
			word32 v35 = (word32) 11;
			word32 v36 = (word32) r14;
			p07 = v35 == v36;
			p06 = v35 != v36;
			word64 p16;
			if (!p06)
			{
				if (p16)
					__break();
			}
			else
			{
				r41 = r1 + -7804;
				__break();
				if (p16)
					__break();
			}
		}
		else
		{
			word32 v37 = (word32) 0x00;
			word32 v38 = (word32) r8;
			p06 = v37 == v38;
			p07 = v37 != v38;
			if (p07)
				r34 = r1 + 7428;
		}
	}
}

// 4000000000083400: define stop_pipeline
define stop_pipeline
{
	word64 r32;
	word64 r80;
	Eq_n LC;
	<anonymous> * b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r44 = ar.pfs;
	word64 r12 = r12 + ~0x01FF;
	word32 * r37 = r1 + -20676;
	word64 r45 = r1 + 0x00;
	<anonymous> * r43 = b3;
	Eq_n r47 = r12 + 400;
	Eq_n r46 = LC;
	<anonymous> * b0;
	b0();
	int64 r48 = 0x00 + 0x0011;
	r1 = r45 + 0x00;
	r47 = r12 + 400;
	word32 * r34 = r37 + 7;
	b0();
	r1 = r45 + 0x00;
	r47 = r12 + 0x0110;
	b0();
	r48 = r12 + 400;
	word64 r49 = r12 + 0x0110;
	r1 = r45 + 0x00;
	r47 = 0x00 + 0x00;
	b0();
	r1 = r45 + 0x00;
	r47 = r1 + 5880;
	b0();
	r1 = r45 + 0x00;
	b0();
	r1 = r45 + 0x00;
	word32 v19 = *r34;
	Eq_n r14;
	r14.u2 = (word64) v19;
	Eq_n r15 = r1 + 6516;
	word32 v22 = (word32) 0x00;
	word32 v23 = (word32) r14;
	Eq_n p07 = v22 == v23;
	Eq_n p06 = v22 != v23;
	Eq_n r35 = r1 + 7444;
	Eq_n r8;
	Eq_n r16;
	Eq_n p08;
	if (p07)
	{
		r14 = 0x00 + 8;
		r35 = r1 + 7444;
		r47 = 0x00 + 64;
		r14.u3->t0000.u1 = (word32) (word32) r34;
		b0();
		word32 v30 = *r34;
		r14.u2 = (word64) v30;
		r1 = r45 + 0x00;
		r15 = 0x00 + 0x00;
		*r8.u2 = (word64) r35;
		int32 v32 = (word32) 0x00;
		int32 v33 = (word32) r14;
		p06 = v32 < v33;
		p07 = v32 >= v33;
		r16.u1 = (word32) r14 - 1;
		if (p06)
			r16 = __addp4(0x00, r16);
		word64 pr = r80;
		word64 p62;
		if (p62)
		{
			word64 r33;
			0x00 == r33;
			p08 = 0x00 != r33;
		}
	}
	Eq_n v27;
	v27.u1 = r15.u3->t0000.u1;
	r15.u2 = (word64) v27;
	word32 v28 = (word32) 0x00;
	word32 v29 = (word32) r15;
	p07 = v28 == v29;
	p06 = v28 != v29;
	if (p07)
	{
		r15.u2 = r37 + 8;
		r35 = r1 + 7444;
		Eq_n v38;
		v38.u1 = r15.u3->t0000.u1;
		r34 = (word64) v38;
		word32 v39 = (word32) 0x00;
		word32 v40 = (word32) r34;
		p06 = v39 == v40;
		p07 = v39 != v40;
		if (p07)
			r34 = (word32 *) ((char *) r34 + 1);
		__break();
	}
	int32 v35 = (int32) r14;
	r15.u2 = (int64) v35;
	r16.u2 = *r35.u2;
	Eq_n r18;
	r18.u1 = (word32) r14 - 1;
	r34 = (word32 *) r14.u2;
	Eq_n r17;
	r17.u1 = (word32) r15 - 1;
	r15.u1 = (word32) r15 - 2;
	r18 = __addp4(0x00, r18);
	r17.u2 = r16.u2 + r17;
	r15.u2 = r16.u2 + r15;
	LC = r18;
	r16.u2 = *r17.u2;
	p07 = 0x00 == r16;
	p06 = 0x00 != r16;
	Eq_n p09;
	if (p06)
	{
		r34 = (word32 *) r14.u2;
		p09 = 0x00 == 0x00;
		p08 = 0x00 != 0x00;
	}
	else
	{
		do
		{
			r34 = (word32 *) ((char *) r34 - 1);
			if (LC == 0x00)
			{
				word32 v85 = (word32) 0x00;
				word32 v86 = (word32) r14;
				p09 = v85 == v86;
				p08 = v85 != v86;
				goto l40000000000835A0;
			}
			--LC;
			r16.u2 = *r15.u2;
			r15.u1 = (word32) r15 - 8;
			p07 = 0x00 == r16;
			p06 = 0x00 != r16;
		} while (p07);
		word32 v87 = (word32) r14;
		word32 v88 = (word32) r34;
		p09 = v87 == v88;
		p08 = v87 != v88;
	}
l40000000000835A0:
	r14 = r1 + 6512;
	Eq_n v49;
	v49.u1 = r14.u3->t0000.u1;
	r14.u2 = (word64) v49;
	word32 v50 = (word32) 0x00;
	word32 v51 = (word32) r14;
	p06 = v50 == v51;
	p07 = v50 != v51;
	if (!p06)
	{
		r14 = r1 + 0x00002344;
		Eq_n v53;
		v53.u1 = r14.u3->t0000.u1;
		r14.u2 = (word64) v53;
		word32 v54 = (word32) 0x00;
		word32 v55 = (word32) r14;
		p06 = v54 == v55;
		p07 = v54 != v55;
		if (p06)
		{
			if (p08)
				goto l4000000000083610;
			goto l40000000000841E0;
		}
	}
	if (!p09)
		goto l4000000000083610;
	r14 = 0x00 + 0x0FFF;
	int32 v58 = (word32) r14;
	int32 v59 = (word32) r34;
	p07 = v58 < v59;
	p06 = v58 >= v59;
	union Eq_n * r39;
	if (!p06)
	{
		r14 = r1 + 7464;
		Eq_n v68;
		v68.u1 = r14.u3->t0000.u1;
		r14.u2 = (word64) v68;
		word32 v69 = (word32) 0x00;
		word32 v70 = (word32) r14;
		p07 = v69 == v70;
		p06 = v69 != v70;
		if (!p06)
		{
			r34 = r37 + 7;
			b0();
			r14.u2 = r37 + 0x0A;
			r1 = r45 + 0x00;
			r47 = r12 + 0x90;
			Eq_n v73;
			v73.u1 = r14.u3->t0000.u1;
			r14.u2 = (word64) v73;
			bool v74 = SLICE(r14, bool, 31);
			r15.u2 = (word64) v74;
			r16.u1 = (word32) r14 + 7;
			word3 v75 = SLICE(r15, word3, 61);
			r15.u2 = (word64) v75;
			r14.u2 = r15 + r14;
			bool v76 = SLICE(r16, bool, 31);
			r17.u2 = (word64) v76;
			word3 v77 = SLICE(r17, word3, 61);
			r17.u2 = (word64) v77;
			r14 &= 0x07;
			r14 = r15 - r14;
			r16.u2 = r16 + r17;
			int29 v78 = SLICE(r16, int29, 3);
			r39 = (int64) v78;
			int32 v79 = (word32) 0x04;
			int32 v80 = (word32) r14;
			p06 = v79 < v80;
			p07 = v79 >= v80;
			r39 = (r39 << 0x03) + 0x00;
			if (p06)
				r39 = (union Eq_n *) ((char *) r39 + 8);
			__break();
			word64 p02;
			if (p02)
				__break();
			if (p08)
				__break();
		}
	}
l40000000000841E0:
	r14.u2 = r34 + 2;
	r35 = r1 + 7444;
	word64 * r36 = (word64 *) (r37 + 7);
	int32 v63 = (int32) r14;
	r48 = (int64) v63;
	r14.u3->t0000.u1 = (word32) (word32) r36;
	r47.u2 = *r35.u2;
	r48 = (r48 << 0x03) + 0x00;
	b0();
	word32 v64 = (word32) *r36;
	r16.u2 = (word64) v64;
	int32 v65 = (int32) r34;
	r15.u2 = (int64) v65;
	r1 = r45 + 0x00;
	*r8.u2 = (word64) r35;
	r17 = r34 - r16;
	r14 = (r15 << 0x03) + 0x00;
	int32 v66 = (word32) r34;
	int32 v67 = (word32) r16;
	p07 = v66 < v67;
	p06 = v66 >= v67;
	union Eq_n * r0;
	if (!p06)
	{
		r17 = __addp4(0x00, r17);
		r15.u2 = r17 + r15;
		r15 = (r15 << 0x03) + 0x00;
		while (true)
		{
			r8.u2 = r14 + r8;
			r14.u1 = (word32) r14 + 8;
			r0->u2 = (word64 *) r8;
			p06 = r15 == r14;
			p07 = r15 != r14;
			if (p06)
				break;
			r8.u2 = *r35.u2;
		}
	}
l4000000000083610:
	r39 = r1 + 7428;
	r47 = 0x00 + 56;
	r35 = 0x00 + 1;
	r14.u2 = r39->u2;
	r35.u2 = &r35.u3->ptr0001;
	p06 = 0x00 == r14;
	p07 = 0x00 != r14;
	if (!p06)
	{
		b0();
		r36 = r8.u2;
		r8.u2 = r39->u2;
		r1 = r45 + 0x00;
		r16.u2 = *r8.u2;
		p06 = r16 == r8;
		p07 = r16 != r8;
		if (p06)
		{
			r16.u2 = r8.u2;
			r35 = 0x00 + 1;
		}
		else
		{
			r14.u2 = *r16.u2;
			p07 = r14 == r8;
			p06 = r14 != r8;
			if (!p07)
			{
				do
				{
					r16.u2 = r14.u2;
					r35.u2 = &r35.u3->ptr0001;
					r14.u2 = *r16.u2;
					p07 = r14 == r8;
					p06 = r14 != r8;
				} while (p06);
			}
		}
		r14.u2 = *r8.u2;
		r0->u2 = (word64 *) r16;
		r47.u2 = r8.u2;
		p06 = 0x00 == r14;
		p07 = 0x00 != r14;
		if (p06)
			r14 = 0x00 + 0x00;
		__break();
		__break();
	}
	else
	{
		word32 v60 = (word32) 0x00;
		word32 v61 = (word32) r32;
		p06 = v60 == v61;
		p07 = v60 != v61;
		if (p07)
		{
			r37 += 0x0C;
			b0();
			r1 = r45 + 0x00;
			r47 = 0x00 + 2;
			r48 = r12 + 0x0110;
			r49 = 0x00 + 0x00;
			r14 = r1 + 0x00001CFC;
			r0->u1 = (word32) (word32) r14;
			b0();
			r1 = r45 + 0x00;
			word32 v72 = *r37;
			r34 = (word64) v72;
		}
		else
		{
			r14 = r1 + 0x00001CFC;
			r47 = 0x00 + 2;
			r48 = r12 + 0x0110;
			r49 = 0x00 + 0x00;
			r37 += 0x0C;
			r0->u1 = (word32) (word32) r14;
			b0();
			r1 = r45 + 0x00;
			word32 v83 = *r37;
			r34 = (word64) v83;
		}
		r8.u2 = r34;
		ar.pfs = r44;
		LC = r46;
		b0 = r43;
		r12 += 0x0200;
	}
}

// 4000000000084900: define delete_all_jobs
define delete_all_jobs
{
	word64 r32;
	<anonymous> * b6;
	word64 r1;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r39 = ar.pfs;
	word64 r12 = r12 + ~0xFF;
	word64 r41 = pr;
	word64 r37 = r1 + -20676;
	word64 r40 = r1 + 0x00;
	struct Eq_n ** r35 = r1 + 7444;
	<anonymous> * r38 = b6;
	struct Eq_n * r42 = r12 + 0x90;
	<anonymous> * b0;
	b0();
	word64 r43 = 0x00 + 0x0011;
	r1 = r40 + 0x00;
	r42 = r12 + 0x90;
	word32 * r36 = r37 + 0x1C;
	word64 r34 = 0x00 + 0x00;
	b0();
	r1 = r40 + 0x00;
	r42 = r12 + 0x10;
	word64 r33 = 0x00 + 0x00;
	word32 v22 = (word32) 0x00;
	word32 v23 = (word32) r32;
	Eq_n p16 = v22 == v23;
	Eq_n p17 = v22 != v23;
	b0();
	r1 = r40 + 0x00;
	r42 = 0x00 + 0x00;
	r43 = r12 + 0x90;
	word64 r44 = r12 + 0x10;
	b0();
	word32 v27 = *r36;
	struct Eq_n * r14 = (word64) v27;
	word32 * r15 = 0x00 + -1;
	word64 r17 = r37 + 0x34;
	word64 r16 = r37 + 0x30;
	r1 = r40 + 0x00;
	word32 v32 = (word32) 0x00;
	word32 v33 = (word32) r32;
	Eq_n p09 = v32 == v33;
	Eq_n p08 = v32 != v33;
	word32 v36 = (word32) 0x00;
	word32 v37 = (word32) r14;
	Eq_n p06 = v36 == v37;
	Eq_n p07 = v36 != v37;
	if (p06)
	{
		if (p08)
			goto l4000000000084A90;
		b0();
		r1 = r40 + 0x00;
	}
	else
	{
		*r15 = (word32) r17;
		*r15 = (word32) r16;
		int32 v40 = (word32) 0x00;
		int32 v41 = (word32) r14;
		p06 = v40 < v41;
		p07 = v40 >= v41;
		if (!p07)
		{
			do
			{
				r14 = (struct Eq_n *) *r35;
				r42 = r33 + 0x00;
				r43 = 0x00 + 1;
				++r33;
				r14 = (struct Eq_n *) ((char *) &r14->ptr0000 + r34);
				r34 += 0x08;
				r14 = r14->ptr0000;
				r15 = (word32 *) ((char *) &r14->ptr0000 + 20);
				p06 = null == r14;
				p07 = null != r14;
				if (!p06)
					;
				word32 v43 = *r36;
				r14 = (word64) v43;
				int32 v44 = (word32) r33;
				int32 v45 = (word32) r14;
				p06 = v44 < v45;
				p07 = v44 >= v45;
			} while (p06);
		}
		if (!p16)
		{
l4000000000084A90:
			r42 = 0x00 + 2;
			r43 = r12 + 0x10;
			r44 = 0x00 + 0x00;
			b0();
			r1 = r40 + 0x00;
			pr = r41;
			ar.pfs = r39;
			b0 = r38;
			r12 += 0x0100;
			return;
		}
		r14 = r1 + 7444;
		r42 = r14->ptr0000;
		b0();
		r16 = r37 + 0x1C;
		r15 = r37 + 0x28;
		r14 = r37 + 0x20;
		r37 += 0x24;
		r1 = r40 + 0x00;
		word32 * r0;
		*r0 = (word32) r16;
		*r0 = (word32) r15;
		*r0 = (word32) r14;
		*r0 = (word32) r37;
		b0();
		r1 = r40 + 0x00;
	}
	r42 = 0x00 + 2;
	r43 = r12 + 0x10;
	r44 = 0x00 + 0x00;
	b0();
	r1 = r40 + 0x00;
	pr = r41;
	ar.pfs = r39;
	b0 = r38;
	r12 += 0x0100;
}

// 4000000000084C40: define nohup_all_jobs
define nohup_all_jobs
{
	word64 r96;
	word64 r32;
	Eq_n LC;
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 r12 = r12 + ~0xFF;
	word64 r35 = r1 + 0x00;
	<anonymous> * r33 = b1;
	word64 r37 = r12 + 0x90;
	Eq_n r36 = LC;
	<anonymous> * b0;
	b0();
	word64 r38 = 0x00 + 0x0011;
	r1 = r35 + 0x00;
	r37 = r12 + 0x90;
	b0();
	r1 = r35 + 0x00;
	r37 = r12 + 0x10;
	b0();
	r1 = r35 + 0x00;
	r37 = 0x00 + 0x00;
	r38 = r12 + 0x90;
	word64 r39 = r12 + 0x10;
	b0();
	r1 = r35 + 0x00;
	word32 v18 = (word32) 0x00;
	word32 v19 = (word32) r32;
	Eq_n p06 = v18 == v19;
	Eq_n p07 = v18 != v19;
	struct Eq_n * r14 = r1 + -20676;
	r14 = (struct Eq_n *) ((char *) &r14->t0000 + 28);
	Eq_n v23;
	v23.u0 = r14->t0000.u0;
	r14 = (word64) v23;
	word32 v24 = (word32) 0x00;
	word32 v25 = (word32) r14;
	Eq_n p09 = v24 == v25;
	Eq_n p08 = v24 != v25;
	Eq_n r15;
	r15.u2 = (char *) r14 - 1;
	if (!p09)
	{
		int32 v29 = (word32) 0x00;
		int32 v30 = (word32) r14;
		p09 = v29 < v30;
		p08 = v29 >= v30;
		r14 = r1 + 7444;
		r15 = __addp4(0x00, r15);
		if (!p08)
		{
			Eq_n r16;
			r16.u1 = r14->t0000.u1;
			LC = r15;
			r15.u1 = (word32) r16 + 8;
			while (true)
			{
				r14 = r16.u1->ptr0000;
				r16.u1 = r15.u2;
				r15.u1 = (word32) r15 + 8;
				ptr64 r17 = (char *) &r14->t0000 + 24;
				ptr64 r18 = (char *) &r14->t0000 + 20;
				p08 = null == r14;
				p09 = null != r14;
				if (!p08)
					break;
				if (LC == 0x00)
					goto l4000000000084DA0;
				--LC;
			}
			word64 p04;
			if (p04)
			{
				null < r33;
				Eq_n p03 = null >= r33;
			}
			word64 p16;
			if (p16)
				__break();
			if (p16)
			{
				int32 v38 = (word32) 0x00;
				int32 v39 = (word32) r96;
				v38 < v39;
				Eq_n p01 = v38 >= v39;
			}
		}
	}
l4000000000084DA0:
	r37 = 0x00 + 2;
	r38 = r12 + 0x10;
	r39 = 0x00 + 0x00;
	b0();
	r1 = r35 + 0x00;
	ar.pfs = r34;
	LC = r36;
	b0 = r33;
	r12 += 0x0100;
}

// 4000000000084E40: define count_all_jobs
define count_all_jobs
{
	word64 LC;
	word64 b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 r12 = r12 + ~0xFF;
	word64 r35 = r1 + 0x00;
	word64 r33 = b1;
	word64 r37 = r12 + 0x90;
	word64 r32 = 0x00 + 0x00;
	word64 r36 = LC;
	<anonymous> * b0;
	b0();
	word64 r38 = 0x00 + 0x0011;
	r1 = r35 + 0x00;
	r37 = r12 + 0x90;
	b0();
	r1 = r35 + 0x00;
	r37 = r12 + 0x10;
	b0();
	r1 = r35 + 0x00;
	r37 = 0x00 + 0x00;
	r38 = r12 + 0x90;
	word64 r39 = r12 + 0x10;
	b0();
	r1 = r35 + 0x00;
	word32 * r14 = r1 + -20676;
	r14 += 7;
	word32 v19 = *r14;
	r14 = (word64) v19;
	int32 v20 = (word32) 0x00;
	int32 v21 = (word32) r14;
	Eq_n p07 = v20 < v21;
	Eq_n p06 = v20 >= v21;
	ptr64 r15 = (char *) r14 - 1;
	r14 = r1 + 7444;
	if (p06)
		r32 = 0x00 + 0x00;
}

// 4000000000085000: define freeze_jobs_list
define freeze_jobs_list
{
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r15 = 0x00 + 1;
	word64 r14 = r1 + 7464;
	*r15 = (word32) r14;
}

// 4000000000085040: define unfreeze_jobs_list
define unfreeze_jobs_list
{
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r14 = r1 + 7464;
	word32 * r0;
	*r0 = (word32) r14;
}

// 4000000000085080: define set_job_control
define set_job_control
{
	word32 * r32;
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r14 = r1 + 5868;
	word32 v7 = (word32) 0x00;
	word32 v8 = (word32) r32;
	Eq_n p06 = v7 == v8;
	Eq_n p07 = v7 != v8;
	word32 v11 = *r14;
	word64 r8 = (word64) v11;
	*r32 = (word32) r14;
	if (p07)
		r14 = r1 + 7436;
	word32 v13 = (word32) r32;
	word32 v14 = (word32) r8;
	Eq_n p08 = v13 == v14;
	Eq_n p09 = v13 != v14;
	if (p08)
		return;
	if (p07)
	{
		word32 * r0;
		*r0 = (word32) r14;
	}
	__break();
}

// 40000000000850C0: define without_job_control
define without_job_control
{
	<anonymous> * b0;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	word64 r14 = r1 + 0x00001CFC;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	word32 * r0;
	*r0 = (word32) r14;
	b0();
	r1 = r34 + 0x00;
	word64 r35 = r1 + 5880;
	b0();
	r1 = r34 + 0x00;
	r35 = 0x00 + 0x00;
	b0();
	r1 = r34 + 0x00;
	ar.pfs = r33;
	r14 = r1 + 5868;
	b0 = r32;
	*r0 = (word32) r14;
}

// 4000000000085180: define end_job_control
define end_job_control
{
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word32 * r14 = r1 + 6512;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word32 * r32 = r1 + 5888;
	word32 v12 = *r14;
	r14 = (word64) v12;
	word32 v13 = (word32) 0x00;
	word32 v14 = (word32) r14;
	Eq_n p06 = v13 == v14;
	Eq_n p07 = v13 != v14;
	<anonymous> * b0;
	word64 r36;
	word64 r37;
	if (p07)
	{
		b0();
		word32 v23 = *r32;
		r36 = (word64) v23;
		r1 = r35 + 0x00;
		r37 = 0x00 + 1;
		int32 v24 = (word32) r36;
		int32 v25 = (word32) 0x00;
		p07 = v24 < v25;
		p06 = v24 >= v25;
		if (p07)
		{
l4000000000085200:
			ar.pfs = r34;
			b0 = r33;
			return;
		}
		b0();
		r1 = r35 + 0x00;
	}
	word32 v17 = *r32;
	r37 = (word64) v17;
	r36 = 0x00 + 0x00;
	int32 v20 = (word32) r37;
	int32 v21 = (word32) 0x00;
	p06 = v20 < v21;
	p07 = v20 >= v21;
	if (!p06)
	{
		b0();
		r1 = r35 + 0x00;
	}
	goto l4000000000085200;
}

// 4000000000085280: define restart_job_control
define restart_job_control
{
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word32 * r14 = r1 + 5900;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word32 v11 = *r14;
	word64 r36 = (word64) v11;
	word64 r32 = 0x00 + 0x00;
	word32 v14 = (word32) ~0x00;
	word32 v15 = (word32) r36;
	Eq_n p06 = v14 == v15;
	Eq_n p07 = v14 != v15;
	<anonymous> * b0;
	if (!p06)
	{
		b0();
		r1 = r35 + 0x00;
	}
	b0 = r33;
	ar.pfs = r34;
	word64 r2 = ar.pfs;
	initialize_job_control();
}

// 4000000000085300: define set_sigchld_handler
define set_sigchld_handler
{
	word64 r1;
	<anonymous> * b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	<anonymous> * r32 = b0;
	struct Eq_n * r36 = r1 + -7644;
	word64 r34 = r1 + 0x00;
	word64 r35 = 0x00 + 0x0011;
	r36 = r36->ptr0000;
	b0();
	r1 = r34 + 0x00;
	ar.pfs = r33;
	b0 = r32;
}

// 4000000000085380: define close_pgrp_pipe
define close_pgrp_pipe
{
	word64 r1;
	<anonymous> * b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	word64 r35 = r1 + 5880;
	b0();
	r1 = r34 + 0x00;
	ar.pfs = r33;
	b0 = r32;
}

// 4000000000085400: define save_pgrp_pipe
define save_pgrp_pipe
{
	word64 r33;
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r15 = r1 + 5880;
	word32 * r16 = 0x00 + -1;
	word32 v8 = (word32) 0x00;
	word32 v9 = (word32) r33;
	Eq_n p06 = v8 == v9;
	Eq_n p07 = v8 != v9;
	word32 * r14 = r15 + 0x00;
	word32 v13 = *r14;
	++r14;
	word32 * r32;
	word64 r4;
	*r32 = (word32) r4;
	++r32;
	word32 v17 = *r14;
	word32 * r17 = (word64) v17;
	*r17 = (word32) r32;
	if (p07)
		*r16 = (word32) r14;
}

// 4000000000085480: define restore_pgrp_pipe
define restore_pgrp_pipe
{
	word64 r1;
	word32 * r32;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 v5 = *r32;
	++r32;
	word32 * r14 = r1 + 5880;
	word64 r4;
	*r14 = (word32) r4;
	++r14;
	word32 v10 = *r32;
	word32 * r15 = (word64) v10;
	*r15 = (word32) r14;
}

// 40000000000879C0: define sub_append_string
define sub_append_string
{
	word64 r1;
	byte * r32;
	word64 b6;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r39 = ar.pfs;
	word64 r38 = b6;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	word64 r40 = r1 + 0x00;
	int64 r33;
	if (!p06)
	{
		byte v13 = *r32;
		int64 r14 = (word64) v13;
		int8 v15 = (int8) r14;
		r14 = (int64) v15;
		word32 v16 = (word32) 0x00;
		word32 v17 = (word32) r14;
		p06 = v16 == v17;
		p07 = v16 != v17;
		if (p06)
		{
			word64 r37 = 0x00 + 0x00;
		}
		word64 p05;
		if (p05)
		{
			0x00 < r33;
			Eq_n p11 = 0x00 >= r33;
		}
	}
	else
	{
		word64 r8 = r33 + 0x00;
		ar.pfs = r39;
		word64 b0 = r38;
	}
}

// 4000000000087C40: define extract_array_assignment_list
define extract_array_assignment_list
{
	word32 * r33;
	word64 r8;
	byte * r32;
	word64 r1;
	<anonymous> * b3;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	<anonymous> * r35 = b3;
	word64 r37 = r1 + 0x00;
	word64 r38 = r32;
	<anonymous> * b0;
	b0();
	int32 v14 = (int32) r8;
	int64 r14 = (int64) v14;
	r38 = r32;
	word32 * r34 = r8 + ~0x00;
	r8 = 0x00 + 0x00;
	r32 += r14;
	r1 = r37 + 0x00;
	word64 r40 = r34;
	r32 += -1;
	byte v18 = *r32;
	r14 = (word64) v18;
	int8 v19 = (int8) r14;
	r14 = (int64) v19;
	word32 v20 = (word32) 0x29;
	word32 v21 = (word32) r14;
	Eq_n p07 = v20 == v21;
	Eq_n p06 = v20 != v21;
	if (!p06)
	{
		word32 v25 = *r33;
		word64 r39 = (word64) v25;
		b0();
		r1 = r37 + 0x00;
		*r34 = (word32) r33;
	}
	ar.pfs = r36;
	b0 = r35;
}

// 4000000000087D40: define de_backslash
define de_backslash
{
	union Eq_n * r8;
	word64 LC;
	union Eq_n * r32;
	word64 r1;
	<anonymous> * b6;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r39 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	<anonymous> * r38 = b6;
	struct Eq_n * r36 = r1 + -9996;
	word64 r40 = r1 + 0x00;
	word64 r42 = &r32->u0;
	Eq_n r37 = r12 + 0x18;
	word64 r33 = 0x00 + 0x00;
	r36 = r36->ptr0000;
	word64 r41 = LC;
	int64 r34 = 0x00 + 0x00;
	union Eq_n * r0;
	r0->u2 = (struct Eq_n *) r37;
	<anonymous> * b0;
	b0();
	int32 v21 = (int32) r33;
	struct Eq_n * r14 = (int64) v21;
	struct Eq_n * r35 = (struct Eq_n *) &r8->u0;
	r1 = r40 + 0x00;
	Eq_n p06 = r14 < r35;
	Eq_n p07 = r14 >= r35;
	if (p07)
	{
		int32 v32 = (int32) r34;
		r34 = (int64) v32;
		r8 = r32 + null;
		r32 = &r32->u0 + r34;
		r0->u0 = (byte) (byte) r32;
		ar.pfs = r39;
		LC = r41;
		b0 = r38;
		r12 += 0x10;
		return;
	}
	r14 += r32;
	Eq_n v27;
	v27.u0 = r14->t0000.u0;
	Eq_n r15;
	r15.u2 = (word64) v27;
	int8 v29 = (int8) r15;
	r15.u2 = (int64) v29;
	word32 v30 = (word32) 0x5C;
	word32 v31 = (word32) r15;
	p07 = v30 == v31;
	p06 = v30 != v31;
	if (p07)
	{
		r14 += (union Eq_n *) 0x01;
		Eq_n v33;
		v33.u0 = r14->t0000.u0;
		r14 = (word64) v33;
		int8 v34 = (int8) r14;
		r14 = (int64) v34;
		word32 v35 = (word32) 0x60;
		word32 v36 = (word32) r14;
		p06 = v35 == v36;
		p07 = v35 != v36;
		if (p06)
		{
l4000000000088010:
			++r33;
			b0();
			r1 = r40 + 0x00;
			p07 = (union Eq_n *) 0x01 < r8;
			p06 = (union Eq_n *) 0x01 >= r8;
			struct Eq_n * r18;
			if (p07)
			{
l4000000000087E10:
				int32 v37 = (int32) r33;
				int64 r44 = (int64) v37;
				byte * r43 = (byte *) (&r32->u0 + r44);
				byte v40 = *r43;
				r14 = (word64) v40;
				int8 v41 = (int8) r14;
				r14 = (int64) v41;
				word3 v42 = SLICE(r14, word3, 5);
				ui64 r16 = (word64) v42;
				r15 = r14 & 0x1F;
				r14 = (struct Eq_n *) ((char *) &r36->ptr0000 + (r16 << 0x02));
				Eq_n v44;
				v44.u1 = r14->t0000.u1;
				r14 = (word64) v44;
				r14 >>= r15;
				if (!p07)
				{
					if (p06)
						r18 = 0x00 + 1;
					__break();
					__break();
l4000000000087E92:
					int32 v47 = (word32) r34;
					int32 v48 = (word32) r33;
					p07 = v47 < v48;
					p06 = v47 >= v48;
					if (p06)
						r34 = &r18->t0000.u0;
				}
				r14 = r37.u2->ptr0000;
				r15 = r12 + 0x10;
				r42 = 0x00 + 0x00;
				r44 -= r35;
				word64 * r45 = &r37.u2->ptr0000;
				r14->t0000.u2 = (struct Eq_n *) r15;
				b0();
				r14 = r8 + (union Eq_n *) 0x02;
				r15 = r12 + 0x10;
				r1 = r40 + 0x00;
				r18 = r33 + 0x01;
				p06 = (struct Eq_n *) 0x01 < r14;
				p07 = (struct Eq_n *) 0x01 >= r14;
				if (p06)
				{
					p06 = null == r8;
					p07 = null != r8;
					if (p07)
						r18 = r8 + null;
					__break();
				}
				r14 = r15.u2->ptr0000;
				r14->t0000.u2 = (struct Eq_n *) r37;
l4000000000087E90:
				goto l4000000000087E92;
			}
l4000000000088040:
			r18 = r33 + 0x01;
			goto l4000000000087E90;
		}
		word32 v51 = (word32) 0x24;
		word32 v52 = (word32) r14;
		p07 = v51 == v52;
		p06 = v51 != v52;
		if (!p06)
			goto l4000000000088010;
	}
	b0();
	r1 = r40 + 0x00;
	p07 = (union Eq_n *) 0x01 < r8;
	p06 = (union Eq_n *) 0x01 >= r8;
	if (!p06)
		goto l4000000000087E10;
	goto l4000000000088040;
}

// 4000000000088140: define skipsubscript
define skipsubscript
{
	<anonymous> * b4;
	word64 r32;
	word64 r1;
	int64 r33;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r45 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	word64 r47 = pr;
	word64 r35 = r33 + 0x01;
	word64 r41 = r1 + 7548;
	int32 v13 = (int32) r33;
	r33 = (int64) v13;
	Eq_n r39 = r12 + 0x38;
	word64 r46 = r1 + 0x00;
	int64 r48 = r33 + r32;
	<anonymous> * r44 = b4;
	word64 r43 = 0x00 + 1;
	union Eq_n * r0;
	r0->u1 = (struct Eq_n *) r39;
	word64 r40 = 0x00 + 0x00;
	word64 r38 = 0x00 + 0x00;
	int32 v24 = (int32) r35;
	int64 r37 = (int64) v24;
	<anonymous> * b0;
	b0();
	r1 = r46 + 0x00;
	struct Eq_n * r14 = 0x00 + 1;
	up64 r8;
	r33 += r8;
	struct Eq_n * r42 = r1 + -9996;
	r14->t0000.u0 = (word32) (word32) r41;
	r42 = r42->ptr0000;
	while (true)
	{
		byte * r36 = r37 + r32;
		byte v31 = *r36;
		Eq_n r15;
		r15.u1 = (word64) v31;
		int8 v33 = (int8) r15;
		r15.u1 = (int64) v33;
		word32 v34 = (word32) 0x00;
		word32 v35 = (word32) r15;
		Eq_n p07 = v34 == v35;
		Eq_n p06 = v34 != v35;
		r14 = (struct Eq_n *) &r15.u1->ptr0000;
		if (p07)
			break;
		word32 v38 = (word32) 0x00;
		word32 v39 = (word32) r38;
		p06 = v38 == v39;
		p07 = v38 != v39;
		if (p06)
		{
			word32 v40 = (word32) 0x5C;
			word32 v41 = (word32) r14;
			p07 = v40 == v41;
			p06 = v40 != v41;
			if (p07)
				++r35;
		}
		b0();
		r1 = r46 + 0x00;
		p07 = 0x01 < r8;
		p06 = 0x01 >= r8;
		if (p06)
		{
			++r35;
			goto l40000000000884C2;
		}
		byte v42 = *r36;
		r14 = (word64) v42;
		int8 v43 = (int8) r14;
		r14 = (int64) v43;
		word3 v44 = SLICE(r14, word3, 5);
		struct Eq_n ** r16 = (word64) v44;
		r15 = r14 & 0x1F;
		r14 = (struct Eq_n *) ((char *) &r42->ptr0000 + (r16 << 0x02));
		Eq_n v46;
		v46.u0 = r14->t0000.u0;
		r14 = (word64) v46;
		r14 >>= r15;
		if (!p07)
		{
			if (p06)
				r14 = 0x00 + 1;
			__break();
			__break();
		}
		r14 = r39.u1->ptr0000;
		r15 = r12 + 0x30;
		int64 r50 = r37 - r33;
		r48 = 0x00 + 0x00;
		byte * r49 = r36;
		word64 * r51 = &r39.u1->ptr0000;
		r14->t0000.u1 = (struct Eq_n *) r15;
		r38 = 0x00 + 0x00;
		b0();
		r14 = r8 + 0x02;
		r16 = r12 + 0x30;
		r1 = r46 + 0x00;
		p06 = (struct Eq_n *) 0x01 < r14;
		p07 = (struct Eq_n *) 0x01 >= r14;
		if (p06)
		{
			p06 = 0x00 == r8;
			p07 = 0x00 != r8;
			if (p07)
				r14 = r8 + 0x00;
			__break();
			__break();
l40000000000884C2:
			r38 = 0x00 + 0x00;
			int32 v47 = (int32) r35;
			r37 = (int64) v47;
			continue;
		}
		r14 = (struct Eq_n *) *r16;
		++r35;
		r14->t0000.u1 = (struct Eq_n *) r39;
		int32 v51 = (int32) r35;
		r37 = (int64) v51;
	}
	r8 = r35 + 0x00;
	r0->u0 = (word32) (word32) r41;
	pr = r47;
	ar.pfs = r45;
	b0 = r44;
	r12 += 0x40;
}

// 400000000008A3C0: define fn400000000008A3C0
// Called from:
//      extract_process_subst
//      extract_arithmetic_subst
//      extract_command_subst
define fn400000000008A3C0
{
	ui64 r37;
	up64 r8;
	byte * r34;
	word32 * r32;
	word64 b5;
	word64 r1;
	word32 * pr;
	word32 * r33;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r62 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	word32 v8 = *r33;
	word32 * r38 = (word64) v8;
	word32 * r64 = pr;
	word64 r63 = r1 + 0x00;
	word64 r61 = b5;
	int32 v16 = (int32) r38;
	int64 r41 = (int64) v16;
	Eq_n r45 = r12 + 0x40;
	union Eq_n * r0;
	r0->u2 = (struct Eq_n *) r45;
	byte * r65 = (char *) r32 + r41;
	<anonymous> * b0;
	b0();
	r1 = r63 + 0x00;
	Eq_n p06 = null == r34;
	Eq_n p07 = null != r34;
	int64 r47 = r41 + r8;
	struct Eq_n * r14;
	word64 r49;
	word64 p02;
	Eq_n p11;
	if (!p06)
	{
		byte v146 = *r34;
		r14 = (word64) v146;
		int8 v147 = (int8) r14;
		r14 = (int64) v147;
		word32 v148 = (word32) 0x00;
		word32 v149 = (word32) r14;
		p06 = v148 == v149;
		p07 = v148 != v149;
		if (!p06)
		{
			r14 = (struct Eq_n *) (r34 + 1);
			Eq_n v150;
			v150.u0 = r14->t0000.u0;
			r14 = (word64) v150;
			int8 v151 = (int8) r14;
			r14 = (int64) v151;
			word32 v152 = (word32) 0x00;
			word32 v153 = (word32) r14;
			p06 = v152 == v153;
			p07 = v152 != v153;
			if (p06)
				r49 = 0x00 + 1;
			if (p02)
			{
				null < r33;
				p11 = null >= r33;
			}
		}
	}
	r49 = 0x00 + 0x00;
	byte * r35;
	p06 = null == r35;
	p07 = null != r35;
	word64 r53;
	if (p07)
	{
		byte v30 = *r35;
		r14 = (word64) v30;
		int8 v32 = (int8) r14;
		r14 = (int64) v32;
		word32 v33 = (word32) 0x00;
		word32 v34 = (word32) r14;
		p06 = v33 == v34;
		p07 = v33 != v34;
		if (!p06)
		{
			r14 = (struct Eq_n *) (r35 + 1);
			Eq_n v141;
			v141.u0 = r14->t0000.u0;
			r14 = (word64) v141;
			int8 v142 = (int8) r14;
			r14 = (int64) v142;
			word32 v143 = (word32) 0x00;
			word32 v144 = (word32) r14;
			p06 = v143 == v144;
			p07 = v143 != v144;
			if (p06)
				r53 = 0x00 + 1;
			if (p02)
			{
				null < r33;
				p11 = null >= r33;
			}
		}
	}
	r53 = 0x00 + 0x00;
	byte * r36;
	p06 = null == r36;
	p07 = null != r36;
	word64 r52;
	word64 p03;
	if (p07)
	{
		byte v37 = *r36;
		r14 = (word64) v37;
		int8 v38 = (int8) r14;
		r14 = (int64) v38;
		word32 v39 = (word32) 0x00;
		word32 v40 = (word32) r14;
		p06 = v39 == v40;
		p07 = v39 != v40;
		if (!p06)
		{
			r14 = (struct Eq_n *) (r36 + 1);
			Eq_n v136;
			v136.u0 = r14->t0000.u0;
			r14 = (word64) v136;
			int8 v137 = (int8) r14;
			r14 = (int64) v137;
			word32 v138 = (word32) 0x00;
			word32 v139 = (word32) r14;
			p06 = v138 == v139;
			p07 = v138 != v139;
			if (p06)
				r52 = 0x00 + 1;
			if (p03)
			{
				null < r33;
				p11 = null >= r33;
			}
		}
	}
	r52 = 0x00 + 0x00;
	struct Eq_n * r44 = r1 + -9996;
	word64 r56 = r1 + -18556;
	word64 r42 = 0x00 + 0x00;
	word64 r43 = 0x00 + 0x00;
	word32 v46 = (word32) 0x00;
	word32 v47 = (word32) r49;
	Eq_n p18 = v46 == v47;
	Eq_n p19 = v46 != v47;
	word32 * r46 = r12 + 0x48;
	ui64 r51 = r37 | 0x01;
	word32 v53 = (word32) 0x00;
	word32 v54 = (word32) r53;
	Eq_n p20 = v53 == v54;
	Eq_n p21 = v53 != v54;
	word32 v57 = (word32) 0x00;
	word32 v58 = (word32) r52;
	Eq_n p23 = v57 == v58;
	Eq_n p22 = v57 != v58;
	word64 r50 = r12 + 0x18;
	r44 = r44->ptr0000;
	word64 r57 = 0x00 + 0x00002000;
	int32 v63 = (int32) r52;
	int64 r58 = (int64) v63;
	Eq_n r54 = r12 + 0x30;
	word64 r48 = r12 + 0x38;
	int32 v67 = (int32) r53;
	int64 r59 = (int64) v67;
	int32 v69 = (int32) r49;
	int64 r55 = (int64) v69;
	int64 r39;
	word32 * r15;
	union Eq_n * r66;
	byte * r67;
	while (true)
	{
		byte * r40 = (char *) r32 + r41;
		byte v72 = *r40;
		r14 = (word64) v72;
		int8 v73 = (int8) r14;
		r14 = (int64) v73;
		int64 r60 = &r14->t0000.u0;
		r39 = &r14->t0000.u0;
		word32 v76 = (word32) 0x00;
		word32 v77 = (word32) r14;
		p06 = v76 == v77;
		p07 = v76 != v77;
		if (p06)
			break;
		word32 v84 = (word32) 0x00;
		word32 v85 = (word32) r42;
		p06 = v84 == v85;
		p07 = v84 != v85;
		if (!p06)
		{
			word32 v133 = (word32) 0x0A;
			word32 v134 = (word32) r39;
			p07 = v133 == v134;
			p06 = v133 != v134;
			if (p06)
				r39 = 0x00 + 1;
			byte v135 = (byte) r64;
		}
		word32 v86 = (word32) 0x00;
		word32 v87 = (word32) r43;
		p06 = v86 == v87;
		p07 = v86 != v87;
		union Eq_n * r68;
		word64 p32;
		if (!p07)
		{
			word64 p48;
			if (p48)
				__break();
			__break();
			word64 p16;
			if (p16)
				__break();
			__break();
			__break();
			__break();
			if (!p20)
			{
				byte v123 = *r35;
				r15 = (word64) v123;
				int8 v124 = (int8) r15;
				r15 = (int64) v124;
				word32 v125 = (word32) r15;
				word32 v126 = (word32) r39;
				p07 = v125 == v126;
				p06 = v125 != v126;
				if (p07)
				{
					r65 = r40;
					r66 = (union Eq_n *) r35;
					r67 = r59 + 0x00;
					b0();
					r1 = r63 + 0x00;
					word32 v127 = (word32) 0x00;
					word32 v128 = (word32) r8;
					p07 = v127 == v128;
					p06 = v127 != v128;
					if (!p06)
					{
						r38 = (word32 *) ((char *) r38 + r53);
						r65 = (byte *) r32;
						r66 = (union Eq_n *) r46;
						r67 = r35;
						r68 = (union Eq_n *) r35;
						byte * r69 = r36;
						*r38 = (word32) r46;
						ui64 r70 = r51 + 0x00;
						b0();
						word32 v131 = *r46;
						r38 = (word64) v131;
						r1 = r63 + 0x00;
						r38 += (word32 *) 0x01;
						int32 v132 = (int32) r38;
						r41 = (int64) v132;
						continue;
					}
				}
			}
			if (!p23)
			{
				byte v105 = *r36;
				r15 = (word64) v105;
				int8 v106 = (int8) r15;
				r15 = (int64) v106;
				word32 v107 = (word32) r15;
				word32 v108 = (word32) r39;
				p07 = v107 == v108;
				p06 = v107 != v108;
				if (!p07)
				{
l400000000008AA10:
					word32 v111 = (word32) 0x60;
					word32 v112 = (word32) r60;
					p07 = v111 == v112;
					p06 = v111 != v112;
					word32 v113 = (word32) 0x27;
					word32 v114 = (word32) r60;
					Eq_n p08 = v113 == v114;
					Eq_n p09 = v113 != v114;
					r65 = (byte *) r32;
					r66 = r47 + 0x00;
					if (!p07)
					{
						if (p08)
							r15 = 0x00 + 1;
						if (p03)
						{
							word64 r3;
							r34 = r3 + 96700;
						}
						null < r66;
						Eq_n p17 = null >= r66;
						pr = r32;
						word64 p55;
						if (p55)
						{
							r64 < r33;
							p09 = r64 >= r33;
						}
						if (p32)
							__break();
						if (p16)
						{
							word64 r96;
							0x00 == r96;
							0x00 != r96;
						}
					}
					else
					{
						r67 = r1 + -0x00001AA4;
						r38 += (word32 *) 0x01;
						r65 = (byte *) r32;
						r66 = (union Eq_n *) r46;
						r68 = r51 + 0x00;
						*r38 = (word32) r46;
						r67 = (byte *) *r67;
						b0();
						word32 v117 = *r46;
						r38 = (word64) v117;
						r1 = r63 + 0x00;
						r38 += (word32 *) 0x01;
						int32 v118 = (int32) r38;
						r41 = (int64) v118;
						continue;
					}
				}
				r65 = r40;
				r66 = (union Eq_n *) r36;
				r67 = r58 + 0x00;
				b0();
				r1 = r63 + 0x00;
				word32 v109 = (word32) 0x00;
				word32 v110 = (word32) r8;
				p06 = v109 == v110;
				p07 = v109 != v110;
				if (p07)
					goto l400000000008AA10;
			}
			r15 = r52 + ~0x00;
			word32 v104 = *r33;
			r14 = (word64) v104;
			r40 = r12 + 0x48;
			r38 = r15 + r38;
			if (p06)
				r39 = 0x00 + 0x00;
		}
		b0();
		r1 = r63 + 0x00;
		p07 = 0x01 < r8;
		p06 = 0x01 >= r8;
		if (!p06)
		{
			byte v89 = *r40;
			r14 = (word64) v89;
			int8 v90 = (int8) r14;
			r14 = (int64) v90;
			word3 v91 = SLICE(r14, word3, 5);
			ui64 r16 = (word64) v91;
			r15 = r14 & 0x1F;
			r14 = (struct Eq_n *) ((char *) &r44->ptr0000 + (r16 << 0x02));
			Eq_n v93;
			v93.u1 = r14->t0000.u1;
			r14 = (word64) v93;
			r14 >>= r15;
			if (!p07)
			{
				if (p06)
					r14 = 0x00 + 1;
				__break();
			}
			r14 = r45.u2->ptr0000;
			r67 = r41 - r47;
			r65 = 0x00 + 0x00;
			r66 = (union Eq_n *) r40;
			r68 = (union Eq_n *) &r45.u2->ptr0000;
			r43 = 0x00 + 0x00;
			r14->t0000.u2 = (struct Eq_n *) r54;
			b0();
			r14 = r8 + 0x02;
			r1 = r63 + 0x00;
			p06 = (struct Eq_n *) 0x01 < r14;
			p07 = (struct Eq_n *) 0x01 >= r14;
			if (!p06)
			{
				r14 = r54.u2->ptr0000;
				r38 = (word32 *) ((char *) r38 + 1);
				r14->t0000.u2 = (struct Eq_n *) r45;
				int32 v99 = (int32) r38;
				r41 = (int64) v99;
				continue;
			}
			else
			{
				p06 = 0x00 == r8;
				p07 = 0x00 != r8;
				if (p07)
					r14 = r8 + 0x00;
				if (p32)
					__break();
				if (p32)
					__break();
			}
		}
		r38 = (word32 *) ((char *) r38 + 1);
		r43 = 0x00 + 0x00;
		int32 v88 = (int32) r38;
		r41 = (int64) v88;
	}
	r14 = r1 + 7548;
	Eq_n v78;
	v78.u1 = r14->t0000.u1;
	r14 = (word64) v78;
	word32 v79 = (word32) 0x00;
	word32 v80 = (word32) r14;
	p06 = v79 == v80;
	p07 = v79 != v80;
	if (!p06)
	{
		if (p07)
			r39 = 0x00 + 0x00;
	}
	else
	{
		r66 = r1 + -6804;
		r65 = 0x00 + 0x00;
		r67 = 0x00 + 5;
		r66 = *r66;
		b0();
		r1 = r63 + 0x00;
		r65 = r8 + 0x00;
		r66 = (union Eq_n *) r36;
		r67 = (byte *) r32;
		b0();
		r1 = r63 + 0x00;
		r15 = 0x00 + 1;
		r65 = 0x00 + 2;
		r14 = r1 + 9044;
		*r15 = (word32) r14;
		b0();
		__break();
		extract_process_subst();
	}
}

// 400000000008B500: define extract_process_subst
// Called from:
//      extract_command_subst
define extract_process_subst
{
	word64 r1;
	word64 r33;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	word64 r14 = r33 + 0x00;
	struct Eq_n * r35 = r1 + -6836;
	struct Eq_n * r36 = r1 + -6828;
	word64 r34;
	r33 = r34 + 0x00;
	r35 = r35->ptr0000;
	r34 = r14 + 0x00;
	word64 r37 = 0x00 + 0x00;
	r36 = r36->ptr0000;
	word64 r2 = ar.pfs;
	fn400000000008A3C0();
}

// 400000000008B580: define extract_arithmetic_subst
define extract_arithmetic_subst
{
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	struct Eq_n * r34 = r1 + -6788;
	struct Eq_n * r35 = r1 + -6780;
	struct Eq_n * r36 = r1 + -6772;
	r34 = r34->ptr0000;
	word64 r37 = 0x00 + 0x00;
	r35 = r35->ptr0000;
	r36 = r36->ptr0000;
	word64 r2 = ar.pfs;
	fn400000000008A3C0();
}

// 400000000008B600: define extract_command_subst
define extract_command_subst
{
	word64 r32;
	word64 r1;
	struct Eq_n * r34;
	word64 b6;
	word32 * r33;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r39 = ar.pfs;
	word32 v7 = *r33;
	byte * r42 = (word64) v7;
	word64 r38 = b6;
	ui64 r37 = &r34->ptr0000;
	word64 r40 = r1 + 0x00;
	word32 * r43 = r33;
	int32 v16 = (int32) r42;
	r42 = (int64) v16;
	word64 r41 = r32 + 0x00;
	r42 += r32;
	byte v19 = *r42;
	word32 * r14 = (word64) v19;
	int8 v21 = (int8) r14;
	r14 = (int64) v21;
	word32 v22 = (word32) 0x28;
	word32 v23 = (word32) r14;
	Eq_n p07 = v22 == v23;
	Eq_n p06 = v22 != v23;
	r14 = r1 + 7548;
	if (!p07)
	{
		word32 v26 = *r14;
		r14 = (word64) v26;
		word32 v27 = (word32) 0x00;
		word32 v28 = (word32) r14;
		p06 = v27 == v28;
		p07 = v27 != v28;
		if (p06)
		{
			word64 r44 = 0x00 + 0x00;
		}
	}
	else
	{
		r34 = r1 + -6844;
		struct Eq_n * r35 = r1 + -6836;
		struct Eq_n * r36 = r1 + -6828;
		r37 |= 0x08;
		word64 b0 = r38;
		r34 = r34->ptr0000;
		ar.pfs = r39;
		r35 = r35->ptr0000;
		r36 = r36->ptr0000;
		word64 r2 = ar.pfs;
		fn400000000008A3C0();
	}
}

// 400000000008C140: define skip_to_delim
define skip_to_delim
{
	word64 r8;
	word64 b2;
	word64 pr;
	word64 r32;
	ui64 r35;
	word64 r1;
	word64 r33;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r51 = ar.pfs;
	word64 r12 = r12 + ~0x3F;
	int32 v8 = (int32) r33;
	int64 r36 = (int64) v8;
	word64 r43 = r1 + 7548;
	word64 r52 = r1 + 0x00;
	ui64 r46 = r35 & 0x02;
	word64 r40 = r12 + 0x38;
	int64 r54 = r36 + r32;
	word64 r53 = pr;
	word64 r41 = 0x00 + 0x00;
	word64 r44 = 0x00 + 0x00;
	int32 v22 = (int32) r33;
	int64 r37 = (int64) v22;
	word64 r50 = b2;
	word64 * r0;
	*r0 = r40;
	<anonymous> * b0;
	b0();
	r1 = r52 + 0x00;
	int64 r45 = r36 + r8;
	word64 p07;
	if (p07)
	{
		word64 r14 = 0x00 + 1;
	}
}

