// elf-Linux-ia64-bash_text_nC.c
// Generated by decompiling elf-Linux-ia64-bash
// using Reko decompiler version 0.12.3.0.

#include "elf-Linux-ia64-bash.h"

// 40000000000DCA40: define executable_file
define executable_file
{
	word16 * r0;
	word64 r8;
	word64 r32;
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	<anonymous> * r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r37 = r32 + 0x00;
	<anonymous> * b0;
	b0();
	ui64 r33 = r8 + 0x00;
	r1 = r36 + 0x00;
	Eq_n p06;
	if (!p06)
	{
		b0();
		word32 * r14 = 0x00 + 21;
		r1 = r36 + 0x00;
		*r14 = (word32) r8;
	}
	r33 &= 0x12;
	ar.pfs = r35;
	word32 v17 = (word32) 0x02;
	word32 v18 = (word32) r33;
	p06 = v17 == v18;
	Eq_n p07 = v17 != v18;
	b0 = r34;
	if (p06)
		r8 = 0x00 + 1;
	if (p07)
		r8 = 0x00 + 0x00;
	__break();
	__break();
	word16 v21 = *r0;
}

// 40000000000DCB00: define is_directory
define is_directory
{
	word64 r32;
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = r32 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r35 + 0x00;
	ui64 r8 = r8 & 0x10;
	ar.pfs = r34;
	b0 = r33;
}

// 40000000000DD000: define fn40000000000DD000
// Called from:
//      find_user_command
//      find_path_file
define fn40000000000DD000
{
	ui64 r63;
	Eq_n b1;
	word64 r8;
	Eq_n r33;
	word64 r32;
	Eq_n b4;
	word64 r1;
	word32 * ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 * r37 = ar.pfs;
	Eq_n r39 = r1 + -0x00001114;
	Eq_n r36 = b4;
	Eq_n r38 = r1 + 0x00;
	word64 r35 = r32 + 0x00;
	word64 r34 = r33.u1;
	r39.u2 = *r39.u2;
	Eq_n r40 = 0x00 + 1;
	Eq_n b0;
	b0();
	Eq_n r14 = r8 + 0x08;
	r1 = r38.u2;
	r39 = r32 + 0x00;
	Eq_n p06 = 0x00 == r8;
	Eq_n p07 = 0x00 != r8;
	if (p06)
	{
l40000000000DD090:
		b0();
		r1 = r38.u2;
		r39 = r8 + 0x01;
		b0();
		r1 = r38.u2;
		r39 = r8 + 0x00;
		r40 = r35 + 0x00;
		b0();
		r1 = r38.u2;
		ar.pfs = r37;
		b0 = r36;
		return;
	}
	r33.u1 = *r14.u2;
	p06 = 0x00 == r33;
	p07 = 0x00 != r33;
	if (p06)
		goto l40000000000DD090;
	byte v21 = *r33.u1;
	int64 r15 = (word64) v21;
	int8 v23 = (int8) r15;
	r15 = (int64) v23;
	word32 v24 = (word32) 0x00;
	word32 v25 = (word32) r15;
	p07 = v24 == v25;
	p06 = v24 != v25;
	if (!p06)
		goto l40000000000DD090;
	b0 = r36;
	ar.pfs = r37;
	word32 * r2 = ar.pfs;
	word32 * r42 = ar.pfs;
	word64 r12 = r12 + ~0x9F;
	Eq_n r41 = b1;
	r14 = r1 + 8268;
	word64 r43 = r1 + 0x00;
	Eq_n r44 = r32 + 0x00;
	union Eq_n * r0;
	r0->u0 = (word32) (word32) r14;
	b0();
	word32 v34 = (word32) 0x00;
	word32 v35 = (word32) r8;
	p06 = v34 == v35;
	p07 = v34 != v35;
	r1 = r43 + 0x00;
	r44 = r32 + 0x00;
	word32 * r45;
	if (p07)
	{
		r45 = r34 + 0x00;
		b0();
		r36 = r8 + 0x00;
		r1 = r43 + 0x00;
		r8 = r36.u2;
		ar.pfs = r42;
		b0 = r41;
		r12 += 0xA0;
		return;
	}
	p06 = 0x00 == r33;
	p07 = 0x00 != r33;
	if (!p06)
	{
		byte v37 = *r33.u1;
		r14.u2 = (word64) v37;
		int8 v38 = (int8) r14;
		r14.u2 = (int64) v38;
		word32 v39 = (word32) 0x00;
		word32 v40 = (word32) r14;
		p07 = v39 == v40;
		p06 = v39 != v40;
		if (p06)
		{
			r40 = r1 + 8276;
			r45 = r1 + -0x0000111C;
			r38 = r1 + 7676;
			r39 = r1 + 7684;
			r37 = r12 + 0xA0;
			r44 = 0x00 + 1;
			word64 r46 = r12 + 0x10;
			r0->u1 = (union Eq_n *) r40;
			r45 = (word32 *) *r45;
			b0();
			r1 = r43 + 0x00;
			r0->u0 = (word32) (word32) r37;
			r14 = 0x00 + 0x00;
			while (true)
			{
				int32 v42 = (int32) r14;
				r14.u2 = (int64) v42;
				r14.u2 = r14 + r33;
				Eq_n v43;
				v43.u0 = r14.u3->t0000.u0;
				r14.u2 = (word64) v43;
				int8 v44 = (int8) r14;
				r14.u2 = (int64) v44;
				word32 v45 = (word32) 0x00;
				word32 v46 = (word32) r14;
				p07 = v45 == v46;
				p06 = v45 != v46;
				if (p07)
					break;
				r14 = __ld_acquire<word32>(r38);
				word32 v50 = (word32) 0x00;
				word32 v51 = (word32) r14;
				p06 = v50 == v51;
				p07 = v50 != v51;
				if (p07)
				{
					r44 = __ld_acquire<word32>(r38);
					b0();
					r14 = __ld_acquire<word32>(r39);
					r1 = r43 + 0x00;
					word32 v52 = (word32) 0x00;
					word32 v53 = (word32) r14;
					p06 = v52 == v53;
					p07 = v52 != v53;
					if (p06)
						goto l40000000000DCD50;
					goto l40000000000DCE60;
				}
				r14 = __ld_acquire<word32>(r39);
				word32 v58 = (word32) 0x00;
				word32 v59 = (word32) r14;
				p06 = v58 == v59;
				p07 = v58 != v59;
				word64 r47;
				if (p07)
				{
l40000000000DCE60:
					b0();
					r1 = r43 + 0x00;
					r44.u2 = r33.u1;
					r45 = r37;
					b0();
					r1 = r43 + 0x00;
					r35 = r8 + 0x00;
					r45 = r8 + 0x00;
					r46 = r34 + 0x00;
					r47 = r12 + 0x10;
					r44 = r32 + 0x00;
					p07 = 0x00 == r8;
					p06 = 0x00 != r8;
					if (!p06)
						break;
				}
				else
				{
l40000000000DCD50:
					r44.u2 = r33.u1;
					r45 = r37;
					b0();
					r46 = r34 + 0x00;
					r35 = r8 + 0x00;
					r45 = r8 + 0x00;
					r47 = r12 + 0x10;
					r44 = r32 + 0x00;
					r1 = r43 + 0x00;
					p07 = 0x00 == r8;
					p06 = 0x00 != r8;
					if (p07)
						break;
				}
				b0();
				r1 = r43 + 0x00;
				r36 = r8 + 0x00;
				r44 = r35 + 0x00;
				b0();
				p06 = 0x00 == r36;
				p07 = 0x00 != r36;
				r1 = r43 + 0x00;
				r44.u2 = r36.u2;
				if (!p06)
				{
					b0();
					r1 = r43 + 0x00;
					word32 v56 = (word32) 0x00;
					word32 v57 = (word32) r8;
					p06 = v56 == v57;
					p07 = v56 != v57;
					if (!p07)
					{
						r44.u2 = r40.u1->u2;
						p06 = 0x00 == r44;
						p07 = 0x00 != r44;
						if (p06)
							goto l40000000000DCC50;
						b0();
						r8 = r36.u2;
						r1 = r43 + 0x00;
						ar.pfs = r42;
						b0 = r41;
						r12 += 0xA0;
						return;
					}
					r44.u2 = r36.u2;
					b0();
					r1 = r43 + 0x00;
				}
				word32 v55 = *r37;
				r14.u2 = (word64) v55;
			}
			r36.u2 = r40.u1->u2;
			p07 = 0x00 == r36;
			p06 = 0x00 != r36;
			if (!p07)
			{
				word64 p44;
				if (p44)
				{
					ui64 r127 = r37 + r63;
				}
				__break();
			}
l40000000000DCC50:
			r8 = r36.u2;
			ar.pfs = r42;
			b0 = r41;
			r12 += 0xA0;
			return;
		}
	}
	b0();
	r1 = r43 + 0x00;
	r44 = r8 + 0x01;
	b0();
	r1 = r43 + 0x00;
	r44 = r8 + 0x00;
	r45 = r32 + 0x00;
	b0();
	r1 = r43 + 0x00;
	r36 = r8 + 0x00;
	goto l40000000000DCC50;
}

// 40000000000DD140: define executable_or_directory
define executable_or_directory
{
	word64 r32;
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = r32 + 0x00;
	<anonymous> * b0;
	b0();
	ui64 r8 = r8 & 0x12;
	r1 = r35 + 0x00;
	ar.pfs = r34;
	word32 v14 = (word32) 0x00;
	word32 v15 = (word32) r8;
	Eq_n p07 = v14 == v15;
	Eq_n p06 = v14 != v15;
	b0 = r33;
	if (p06)
		r8 = 0x00 + 1;
	if (p07)
		r8 = 0x00 + 0x00;
	__break();
	__break();
	__break();
	__break();
}

// 40000000000DD1C0: define find_user_command
define find_user_command
{
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	word64 r33 = 0x00 + 36;
	word64 r2 = ar.pfs;
	fn40000000000DD000();
}

// 40000000000DD200: define find_path_file
define find_path_file
{
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r16 = ar.pfs;
	word64 r33 = 0x00 + 64;
	word64 r2 = ar.pfs;
	fn40000000000DD000();
}

// 40000000000DD240: define search_for_command
define search_for_command
{
	Eq_n r8;
	<anonymous> * b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	struct Eq_n * r38 = r1 + -0x00001114;
	word64 r37 = r1 + 0x00;
	<anonymous> * r35 = b3;
	r38 = r38->ptr0000;
	word64 r39 = 0x00 + 1;
	<anonymous> * b0;
	b0();
	struct Eq_n * r14 = (struct Eq_n *) ((word32) r8 + 40);
	r1 = r37 + 0x00;
	word64 * r33 = &r8.u1->ptr0000;
	Eq_n p06 = 0x00 == r8;
	Eq_n p07 = 0x00 != r8;
	word64 r34;
	word64 r32;
	if (!p06)
	{
		Eq_n v19;
		v19.u0 = r14->t0000.u0;
		r14 = (word64) v19;
		if (!p07)
		{
			r34 = 0x00 + 1;
			r38 = r32 + 0x00;
			b0();
			word32 v24 = (word32) 0x00;
			word32 v25 = (word32) r8;
			p07 = v24 == v25;
			p06 = v24 != v25;
			r1 = r37 + 0x00;
			if (!p06)
			{
				word32 v27 = (word32) 0x00;
				word32 v28 = (word32) r34;
				p06 = v27 == v28;
				p07 = v27 != v28;
				word64 r40;
				if (p06)
				{
					r38 = r32 + 0x00;
					b0();
					r1 = r37 + 0x00;
				}
				else
				{
					++r33;
					r38 = r32 + 0x00;
					r40 = 0x00 + 36;
					r39 = *r33;
					b0();
					r1 = r37 + 0x00;
				}
				r14 = r1 + 5864;
				p06 = 0x00 == r8;
				p07 = 0x00 != r8;
				if (!p06)
				{
					Eq_n v31;
					v31.u0 = r14->t0000.u0;
					r14 = (word64) v31;
					word32 v32 = (word32) 0x00;
					word32 v33 = (word32) r14;
					p06 = v32 == v33;
					p07 = v32 != v33;
					if (!p06)
					{
						word32 v34 = (word32) 0x00;
						word32 v35 = (word32) r34;
						p07 = v34 == v35;
						p06 = v34 != v35;
						if (p07)
						{
							r14 = r1 + 8268;
							r39 = (word64) &r8.u1->ptr0000;
							r38 = r32 + 0x00;
							word64 r41 = 0x00 + 1;
							Eq_n v37;
							v37.u0 = r14->t0000.u0;
							r40 = (word64) v37;
							r14 = r12 + 0x10;
							r8.u1->ptr0000 = r14;
							b0();
							r14 = r12 + 0x10;
							r1 = r37 + 0x00;
							r8.u1 = r14->t0000.u1;
							ar.pfs = r36;
							b0 = r35;
							r12 += 0x10;
							return;
						}
					}
				}
				ar.pfs = r36;
				b0 = r35;
				r12 += 0x10;
				return;
			}
			else
			{
				r38 = r32 + 0x00;
				b0();
				r1 = r37 + 0x00;
				r38 = (struct Eq_n *) ((word32) r8 + 1);
				b0();
				r1 = r37 + 0x00;
				r38 = (struct Eq_n *) &r8.u1->ptr0000;
				r39 = r32 + 0x00;
				b0();
				r1 = r37 + 0x00;
				ar.pfs = r36;
				b0 = r35;
				r12 += 0x10;
				return;
			}
		}
	}
	r38 = r32 + 0x00;
	b0();
	word32 v21 = (word32) 0x00;
	word32 v22 = (word32) r8;
	p07 = v21 == v22;
	p06 = v21 != v22;
	r1 = r37 + 0x00;
	if (p06)
		r34 = 0x00 + 0x00;
	__break();
}

// 40000000000DD600: define user_command_matches
define user_command_matches
{
	word64 r33;
	word64 r34;
	word64 b5;
	word64 LC;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r46 = ar.pfs;
	word64 r12 = r12 + ~0x9F;
	word32 * r37 = r1 + 8296;
	word64 r48 = LC;
	word64 r47 = r1 + 0x00;
	word64 r45 = b5;
	Eq_n r41 = r1 + 8284;
	word32 v16 = (word32) 0x00;
	word32 v17 = (word32) r34;
	Eq_n p06 = v16 == v17;
	Eq_n p07 = v16 != v17;
	Eq_n r14;
	Eq_n r16;
	Eq_n r15;
	Eq_n r8;
	if (!p06)
	{
		word32 v20 = *r37;
		r14.u2 = (word64) v20;
		r16.u2 = *r41.u2;
		int32 v23 = (int32) r14;
		r15.u2 = (int64) v23;
		r14.u1 = (word32) r14 + 1;
		r15 = (r15 << 0x03) + 0x00;
		r15.u2 = r15 + r16;
		r8.u2 = *r15.u2;
		p06 = 0x00 == r8;
		p07 = 0x00 != r8;
		if (p07)
			r14.u3->t0000.u1 = (word32) (word32) r37;
		__break();
		__break();
		__break();
	}
	else
	{
		word32 * r42 = r1 + 8292;
		r14.u2 = *r41.u2;
		p07 = 0x00 == r14;
		p06 = 0x00 != r14;
		Eq_n r49;
		<anonymous> * b0;
		if (!p07)
		{
			word32 v27 = *r42;
			r14.u2 = (word64) v27;
			int32 v28 = (word32) 0x00;
			int32 v29 = (word32) r14;
			p06 = v28 < v29;
			p07 = v28 >= v29;
			r16.u1 = (word32) r14 - 1;
			if (!p07)
			{
				if (p06)
					r15.u2 = *r41.u2;
			}
			else
			{
				r37 = r1 + 8296;
				word64 r32;
				r49 = r32 + 0x00;
				union Eq_n * r0;
				r0->u1 = (word32) (word32) r37;
				b0();
				r49 = r32 + 0x00;
				union Eq_n * r50 = r33 + 0x00;
				r1 = r47 + 0x00;
				word32 v39 = (word32) 0x00;
				word32 v40 = (word32) r8;
				p07 = v39 == v40;
				p06 = v39 != v40;
				Eq_n r35;
				if (p07)
				{
					r14 = r1 + 8268;
					Eq_n r40 = r1 + 8276;
					r50 = r1 + -0x0000111C;
					word64 r51 = r12 + 0x10;
					r49 = 0x00 + 1;
					word32 * r38 = r12 + 0xA0;
					r50 = r50->u0;
					r0->u1 = (word32) (word32) r14;
					r0->u2 = (word64 *) r40;
					word32 * r43 = r37;
					b0();
					r1 = r47 + 0x00;
					r49 = r1 + -0x00001114;
					r49.u2 = *r49.u2;
					b0();
					r1 = r47 + 0x00;
					word64 * r39 = r8.u2;
					r0->u1 = (word32) (word32) r38;
					p07 = 0x00 == r8;
					p06 = 0x00 != r8;
					if (!p07)
					{
						word64 r44 = r1 + 8292;
						do
						{
							word32 v49 = *r38;
							r15.u2 = (word64) v49;
							r49.u2 = r39;
							r50 = (union Eq_n *) r38;
							int32 v50 = (int32) r15;
							r14.u2 = (int64) v50;
							r14.u2 = r14 + r39;
							Eq_n v51;
							v51.u0 = r14.u3->t0000.u0;
							r14.u2 = (word64) v51;
							int8 v52 = (int8) r14;
							r14.u2 = (int64) v52;
							word32 v53 = (word32) 0x00;
							word32 v54 = (word32) r14;
							p07 = v53 == v54;
							p06 = v53 != v54;
							if (p07)
								goto l40000000000DD790;
							b0();
							p06 = 0x00 == r8;
							p07 = 0x00 != r8;
							r1 = r47 + 0x00;
							r50 = (union Eq_n *) r8.u2;
							r35.u2 = r8.u2;
							r51 = r33 + 0x00;
							if (p06)
								goto l40000000000DD790;
							word64 r52 = r12 + 0x10;
							r49 = r32 + 0x00;
							b0();
							r1 = r47 + 0x00;
							word64 * r36 = r8.u2;
							r49.u2 = r35.u2;
							b0();
							r1 = r47 + 0x00;
							p06 = null == r36;
							p07 = null != r36;
						} while (p06);
						word32 v59 = *r37;
						r50 = (word64) v59;
						word32 v60 = *r42;
						r16.u2 = (word64) v60;
						r14.u2 = (char *) r50 + 1;
						word32 v61 = (word32) r16;
						word32 v62 = (word32) r14;
						p06 = v61 == v62;
						p07 = v61 != v62;
						if (!p06)
						{
							if (p07)
								r8.u2 = *r41.u2;
							__break();
							__break();
						}
						else
						{
							r14.u2 = (char *) r50 + 11;
							r49.u2 = *r41.u2;
							r50 = (union Eq_n *) ((char *) r50 + 0x0C);
							r14.u3->t0000.u1 = (word32) (word32) r44;
							b0();
							word32 v63 = *r43;
							r50 = (word64) v63;
							r1 = r47 + 0x00;
							*r8.u2 = (word64) r41;
							r14.u2 = (char *) r50 + 1;
							if (!p07)
								;
						}
					}
				}
				else
				{
					r35.u2 = *r41.u2;
					b0();
					r14.u2 = *r41.u2;
					r1 = r47 + 0x00;
					r14.u1 = (word32) r14 + 8;
					*r8.u2 = (word64) r35;
					r0->u2 = (word64 *) r14;
				}
l40000000000DD790:
				r16.u2 = *r41.u2;
				r15 = 0x00 + 0x00;
				r14 = 0x00 + 0x00;
				r0->u1 = (word32) (word32) r37;
				r15.u2 = r15 + r16;
				r14.u1 = (word32) r14 + 1;
				r8.u2 = *r15.u2;
				p06 = 0x00 == r8;
				p07 = 0x00 != r8;
				if (p07)
					r14.u3->t0000.u1 = (word32) (word32) r37;
				__break();
				__break();
				__break();
			}
		}
		else
		{
			r14 = 0x00 + 5;
			r49 = 0x00 + 5;
			r14.u3->t0000.u1 = (word32) (word32) r42;
			b0();
			word32 v32 = *r42;
			r14.u2 = (word64) v32;
			*r8.u2 = (word64) r41;
			r1 = r47 + 0x00;
			int32 v33 = (word32) 0x00;
			int32 v34 = (word32) r14;
			p06 = v33 < v34;
			p07 = v33 >= v34;
			r16.u1 = (word32) r14 - 1;
			if (p06)
				r15.u2 = *r41.u2;
		}
	}
}

// 40000000000DE3C0: define redirection_expand
define redirection_expand
{
	word64 r8;
	word64 r32;
	word64 b5;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r38 = ar.pfs;
	word64 r34 = r1 + 9208;
	word64 r37 = b5;
	word64 r39 = r1 + 0x00;
	word64 r40 = r32 + 0x00;
	word64 r36 = 0x00 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r39 + 0x00;
	word32 * r14 = r8 + 0x08;
	word64 r41 = 0x00 + 0x00;
	r40 = r8 + 0x00;
	word32 * r15 = r1 + 6456;
	word32 v19 = *r15;
	r15 = (word64) v19;
	word32 v20 = (word32) 0x00;
	word32 v21 = (word32) r15;
	Eq_n p06 = v20 == v21;
	Eq_n p07 = v20 != v21;
	if (p07)
	{
		word32 v24 = *r14;
		r15 = (word64) v24;
	}
	byte v25 = (byte) r11;
	word64 r100 = (word64) v25;
}

// 40000000000E0E00: define redirection_error
define redirection_error
{
	word64 r1;
	<anonymous> * b5;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r38 = ar.pfs;
	Eq_n r14;
	union Eq_n * r32;
	r14.u2 = (char *) r32 + 16;
	<anonymous> * r37 = b5;
	word64 r39 = r1 + 0x00;
	Eq_n v12;
	v12.u1 = r14.u3->t0000.u1;
	r14.u2 = (char *) r32 + 8;
	Eq_n p07;
	word64 r34;
	Eq_n r40;
	<anonymous> * b0;
	word64 r8;
	Eq_n r41;
	word64 r33;
	Eq_n r35;
	Eq_n p06;
	if (p07)
	{
		r32 = (union Eq_n *) ((char *) r32 + 8);
		r34 = 0x00 + 0x00;
		r14.u2 = r32->u2;
		r40.u2 = *r14.u2;
		b0();
		r1 = r39 + 0x00;
		r40 = r8 + 0x01;
		b0();
		r14.u2 = r32->u2;
		r1 = r39 + 0x00;
		r40 = r8 + 0x00;
		r41.u2 = *r14.u2;
		b0();
		r14 = r33 + 0x05;
		r1 = r39 + 0x00;
		r35 = r8 + 0x00;
		up32 v25 = (word32) 0x04;
		up32 v26 = (word32) r14;
		p06 = v25 < v26;
		p07 = v25 >= v26;
		if (p06)
			goto l40000000000E0EE0;
		goto l40000000000E1060;
	}
	Eq_n v14;
	v14.u1 = r14.u3->t0000.u1;
	r40.u2 = (word64) v14;
	r14.u2 = (char *) r32 + 24;
	int32 v16 = (word32) r40;
	int32 v17 = (word32) 0x00;
	p07 = v16 < v17;
	p06 = v16 >= v17;
	word64 r42;
	if (p07)
	{
		r41 = r1 + -9092;
		r40 = 0x00 + 0x00;
		r42 = 0x00 + 5;
		r34 = 0x00 + 0x00;
		r41.u2 = *r41.u2;
		b0();
		r14 = r33 + 0x05;
		r1 = r39 + 0x00;
		r35 = r8 + 0x00;
		up32 v31 = (word32) 0x04;
		up32 v32 = (word32) r14;
		p06 = v31 < v32;
		p07 = v31 >= v32;
		if (p06)
			goto l40000000000E0EE0;
		goto l40000000000E1060;
	}
	Eq_n v27;
	v27.u1 = r14.u3->t0000.u1;
	r14.u2 = (word64) v27;
	word32 v28 = (word32) 0x09;
	word32 v29 = (word32) r33;
	p07 = v28 == v29;
	p06 = v28 != v29;
	Eq_n r15;
	if (p07)
	{
		up32 v35 = (word32) 0x10;
		up32 v36 = (word32) r14;
		p06 = v35 < v36;
		p07 = v35 >= v36;
		if (!p06)
		{
			r15 = 0x00 + 1;
			int32 v41 = (int32) r14;
			r14.u2 = (int64) v41;
			r14 = r15 << r14;
			r15 = 0x00 + 98496;
			r15 = r14 & r15;
			p07 = 0x00 == r15;
			p06 = 0x00 != r15;
			if (p06)
			{
				r32 = (union Eq_n *) ((char *) r32 + 32);
				Eq_n v49;
				v49.u1 = r32->u1;
				r40.u2 = (word64) v49;
				goto l40000000000E1500;
			}
			if (p06)
			{
				word32 v59 = (word32) 0x01;
				word32 v60 = (word32) r40;
				p06 = v59 == v60;
				p07 = v59 != v60;
				int32 v61 = (int32) r40;
				r40.u2 = (int64) v61;
				if (!p06)
				{
					b0();
					r1 = r39 + 0x00;
					r34 = r8 + 0x00;
					r35 = r8 + 0x00;
l40000000000E1520:
					r40 = r33 + 0x00;
					b0();
					r1 = r39 + 0x00;
					r41.u2 = r35.u2;
					r42 = r8 + 0x00;
					r40 = r1 + -9044;
					r40.u2 = *r40.u2;
					b0();
					r1 = r39 + 0x00;
l40000000000E0F40:
					p06 = 0x00 == r34;
					p07 = 0x00 != r34;
					r40 = r34 + 0x00;
					if (!p06)
					{
						b0();
						r1 = r39 + 0x00;
					}
					ar.pfs = r38;
					b0 = r37;
					return;
				}
			}
			else
			{
				if (p07)
					goto l40000000000E1500;
				word32 v63 = (word32) 0x00;
				word32 v64 = (word32) r40;
				p07 = v63 == v64;
				p06 = v63 != v64;
				if (p06)
					goto l40000000000E1500;
			}
			r32 = (union Eq_n *) ((char *) r32 + 32);
			r40 = r33 + 0x00;
			r34 = 0x00 + 0x00;
			r14.u2 = r32->u2;
			r35.u2 = *r14.u2;
			b0();
			r1 = r39 + 0x00;
			r41.u2 = r35.u2;
			r42 = r8 + 0x00;
			r40 = r1 + -9044;
			r40.u2 = *r40.u2;
			b0();
			r1 = r39 + 0x00;
			goto l40000000000E0F40;
		}
		else
		{
l40000000000E1500:
			int32 v39 = (int32) r40;
			r40.u2 = (int64) v39;
			b0();
			r1 = r39 + 0x00;
			r34 = r8 + 0x00;
			r35 = r8 + 0x00;
			goto l40000000000E1520;
		}
	}
	up32 v33 = (word32) 0x13;
	up32 v34 = (word32) r14;
	p06 = v33 < v34;
	p07 = v33 >= v34;
	if (p07)
	{
		r15 = 0x00 + 1;
		int32 v38 = (int32) r14;
		r14.u2 = (int64) v38;
		r14 = r15 << r14;
		r15 = 0x00 + 949263;
		r14 &= r15;
		p07 = 0x00 == r14;
		p06 = 0x00 != r14;
		if (!p07)
		{
			r35 = r1 + 6456;
			Eq_n v42;
			v42.u1 = r35.u3->t0000.u1;
			r14.u2 = (word64) v42;
			word32 v43 = (word32) 0x00;
			word32 v44 = (word32) r14;
			p07 = v43 == v44;
			p06 = v43 != v44;
			if (!p06)
			{
				if (p07)
					r32 = (union Eq_n *) ((char *) r32 + 32);
				__break();
				__break();
				word64 p32;
				if (p32)
					__break();
				word64 p12;
				if (p12)
					__break();
				p07 = 0x00 == r34;
				p06 = 0x00 != r34;
				if (p07)
					r14.u2 = r32->u2;
			}
			else
			{
				r14 = r1 + 6512;
				r32 = (union Eq_n *) ((char *) r32 + 32);
				r40.u2 = r32->u2;
				Eq_n v50;
				v50.u1 = r14.u3->t0000.u1;
				r14.u2 = (word64) v50;
				word32 v51 = (word32) 0x00;
				word32 v52 = (word32) r14;
				p07 = v51 == v52;
				p06 = v51 != v52;
				if (p07)
					r14.u2 = r32->u2;
			}
		}
	}
	r32 = (union Eq_n *) ((char *) r32 + 32);
	Eq_n v45;
	v45.u1 = r32->u1;
	r40.u2 = (word64) v45;
	int32 v46 = (word32) r40;
	int32 v47 = (word32) 0x00;
	p06 = v46 < v47;
	p07 = v46 >= v47;
	int32 v48 = (int32) r40;
	r40.u2 = (int64) v48;
	if (p06)
	{
		r35 = r1 + -9092;
		r14 = r33 + 0x05;
		r34 = 0x00 + 0x00;
		r35.u2 = *r35.u2;
		up32 v53 = (word32) 0x04;
		up32 v54 = (word32) r14;
		p06 = v53 < v54;
		p07 = v53 >= v54;
		if (p06)
		{
l40000000000E0EE0:
			r40 = r33 + 0x00;
			b0();
			r1 = r39 + 0x00;
			r41.u2 = r35.u2;
			r42 = r8 + 0x00;
			r40 = r1 + -9044;
			r40.u2 = *r40.u2;
			b0();
			r1 = r39 + 0x00;
			goto l40000000000E0F40;
		}
	}
	else
	{
		b0();
		r1 = r39 + 0x00;
		r34 = r8 + 0x00;
		r35 = r8 + 0x00;
		r14 = r33 + 0x05;
		up32 v55 = (word32) 0x04;
		up32 v56 = (word32) r14;
		p06 = v55 < v56;
		p07 = v55 >= v56;
		if (!p07)
			goto l40000000000E0EE0;
	}
l40000000000E1060:
	r15 = r1 + -0x00002344;
	r14 = __addp4(0x00, r14);
	r42 = 0x00 + 5;
	r40 = 0x00 + 0x00;
	r15.u2 = *r15.u2;
	r14.u2 = r15.u2 + r14;
	r15.u2 = *r14.u2;
	r14.u2 = r15 + r14;
	Eq_n b6 = r14;
	b6();
}

// 40000000000E1640: define do_redirections
define do_redirections
{
	word64 r33;
	word64 r32;
	word64 r1;
	<anonymous> * b4;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r37 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	<anonymous> * r36 = b4;
	struct Eq_n ** r35 = r1 + 7068;
	word64 r38 = r1 + 0x00;
	struct Eq_n * r34 = r32 + 0x00;
	Eq_n p07;
	struct Eq_n * r14;
	Eq_n p06;
	word64 * r39;
	<anonymous> * b0;
	if (!p07)
	{
		r14 = (struct Eq_n *) *r35;
		p06 = null == r14;
		p07 = null != r14;
		r39 = &r14->ptr0000;
		if (!p06)
		{
			b0();
			r1 = r38 + 0x00;
			struct Eq_n *** r0;
			*r0 = (struct Eq_n ***) r35;
		}
		r14 = r1 + 7060;
		r14 = r14->ptr0000;
		p06 = null == r14;
		p07 = null != r14;
		if (!p06)
		{
			b0();
			r1 = r38 + 0x00;
		}
	}
	p07 = 0x00 == r32;
	p06 = 0x00 != r32;
	struct Eq_n * r8;
	if (!p07)
	{
		do
		{
			r39 = &r34->ptr0000;
			word64 r40 = r33 + 0x00;
			b0();
			r1 = r38 + 0x00;
			word32 v23 = (word32) 0x00;
			word32 v24 = (word32) r8;
			p06 = v23 == v24;
			p07 = v23 != v24;
			if (p07)
			{
				r14 = r12 + 0x10;
				r40 = &r8->ptr0000;
				r39 = &r34->ptr0000;
				r8->ptr0000 = r14;
				b0();
				r14 = r12 + 0x10;
				r1 = r38 + 0x00;
				r8 = r14->ptr0000;
				ar.pfs = r37;
				b0 = r36;
				r12 += 0x10;
				return;
			}
			r34 = r34->ptr0000;
			p07 = null == r34;
			p06 = null != r34;
		} while (p06);
	}
	r8 = 0x00 + 0x00;
	ar.pfs = r37;
	b0 = r36;
	r12 += 0x10;
}

// 40000000000E1800: define stdin_redirects
define stdin_redirects
{
	word64 r64;
	word64 r32;
	ptr64 fp;
	ptr64 r11 = fp;
	Eq_n r8 = 0x00 + 0x00;
	ui64 r19 = 0x00 + 1;
	ui64 r20 = 0x00 + 0x0936;
	ui64 r21 = 0x00 + 8768;
	struct Eq_n * r14 = r32 + 0x00;
	Eq_n p06 = 0x00 == r32;
	Eq_n p07 = 0x00 != r32;
	if (!p06)
	{
		do
		{
			word32 * r15 = (word32 *) ((char *) &r14->ptr0000 + 16);
			word32 * r17 = (word32 *) ((char *) &r14->ptr0000 + 24);
			word32 * r16 = (word32 *) ((char *) &r14->ptr0000 + 8);
			word32 v15 = *r15;
			r15 = (word64) v15;
			if (!p06)
			{
				word32 v17 = *r17;
				r15 = (word64) v17;
				word32 v18 = *r16;
				r17 = (word64) v18;
				int32 v19 = (int32) r15;
				r16 = (int64) v19;
				up32 v20 = (word32) 0x0D;
				up32 v21 = (word32) r15;
				p06 = v20 < v21;
				p07 = v20 >= v21;
				if (!p06)
				{
					r16 = r19 << r16;
					r15 = 0x00 + 1;
					ui64 r18 = r16 & r20;
					r16 &= r21;
					p07 = 0x00 == r18;
					p06 = 0x00 != r18;
					if (p06)
					{
						r8 = r15 + r8;
						goto l40000000000E1910;
					}
					word32 v23 = (word32) 0x00;
					word32 v24 = (word32) r17;
					p06 = v23 == v24;
					p07 = v23 != v24;
					Eq_n p09 = null == r16;
					Eq_n p08 = null != r16;
					if (!p09)
					{
						if (p06)
							r17 = 0x00 + 1;
						byte v28 = (byte) r64;
					}
				}
				r15 = 0x00 + 0x00;
				r8 = r15 + r8;
				goto l40000000000E1910;
			}
l40000000000E1910:
			r14 = r14->ptr0000;
			p07 = null == r14;
			p06 = null != r14;
		} while (p06);
	}
	else
		r8 = 0x00 + 0x00;
}

// 40000000000E3CC0: define set_itemlist_dirty
define set_itemlist_dirty
{
	word32 * r32;
	ptr64 fp;
	ptr64 r11 = fp;
	word32 v5 = *r32;
	word32 * r14 = (word64) v5;
	r14 |= 0x02;
	*r14 = (word32) r32;
}

// 40000000000E3D00: define initialize_itemlist
define initialize_itemlist
{
	struct Eq_n * r1;
	<anonymous> * b1;
	word32 * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	struct Eq_n * r14 = (struct Eq_n *) (r32 + 2);
	<anonymous> * r33 = b1;
	word64 r35 = &r1->t0000.u0;
	word64 r36 = r32;
	Eq_n r8;
	r8.u1 = r14->t0000.u1;
	r14 = r8.u1->ptr0000;
	r8.u0 = (word32) r8 + 8;
	struct Eq_n * b6 = r14;
	r1 = r8.u1->ptr0000;
	<anonymous> * b0;
	b0();
	word32 v16 = *r32;
	r14 = (word64) v16;
	r1 = r35 + 0x00;
	ar.pfs = r34;
	r14 &= 0xFD;
	b0 = r33;
	r14 |= 0x04;
	r14->t0000.u0 = (word32) (word32) r32;
}

// 40000000000E3D80: define clean_itemlist
define clean_itemlist
{
	word64 r1;
	<anonymous> * b3;
	word32 * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 *** r34 = (word64 ***) (r32 + 4);
	<anonymous> * r35 = b3;
	word64 r37 = r1 + 0x00;
	word64 ** r33 = *r34;
	Eq_n p06 = null == r33;
	Eq_n p07 = null != r33;
	word32 * r14;
	<anonymous> * b0;
	if (p06)
	{
l40000000000E3E00:
		word32 v20 = *r32;
		r14 = (word64) v20;
		word64 **** r0;
		*r0 = r34;
		ar.pfs = r36;
		r14 &= 0xC9;
		b0 = r35;
		*r14 = (word32) r32;
		return;
	}
	word32 v15 = *r32;
	r14 = (word64) v15;
	ui64 r15 = r14 & 0x30;
	word32 v18 = (word32) 0x00;
	word32 v19 = (word32) r15;
	p07 = v18 == v19;
	p06 = v18 != v19;
	word64 * r38;
	if (p07)
	{
		r38 = *r33;
		b0();
		word32 v24 = *r32;
		r14 = (word64) v24;
		r1 = r37 + 0x00;
		if (p06)
		{
l40000000000E3DE0:
			r38 = r33;
			b0();
			r1 = r37 + 0x00;
			goto l40000000000E3E00;
		}
	}
	else if (!p07)
		goto l40000000000E3DE0;
	r38 = *r33;
	b0();
	r1 = r37 + 0x00;
	r38 = r33;
	b0();
	r1 = r37 + 0x00;
	goto l40000000000E3E00;
}

// 40000000000E4400: define filter_stringlist
define filter_stringlist
{
	word64 r1;
	word64 r33;
	word64 b5;
	word64 * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r46 = ar.pfs;
	word64 r37 = (char *) r32 + 0x0C;
	word64 r45 = b5;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	word64 r14 = r33 + 0x00;
	if (!p06)
	{
		word64 r15 = *r32;
		p07 = 0x00 == r33;
		p06 = 0x00 != r33;
		word64 r47 = r1 + 0x00;
		Eq_n p08 = 0x00 == r15;
		Eq_n p09 = 0x00 != r15;
		if (p07)
		{
			word64 r44 = 0x00 + 0x00;
		}
	}
	else
	{
		word64 * r8 = r32;
		ar.pfs = r46;
		word64 b0 = r45;
	}
}

// 40000000000E4880: define completions_to_stringlist
define completions_to_stringlist
{
	word64 r99;
	int64 r1;
	<anonymous> * b7;
	word64 * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r40 = ar.pfs;
	Eq_n p06 = null == r32;
	Eq_n p07 = null != r32;
	<anonymous> * r39 = b7;
	word64 r41 = r1 + 0x00;
	word64 r42 = r32;
	<anonymous> * b0;
	word64 r8;
	word64 r35;
	if (!p06)
	{
		word64 r36 = r32 - 0xF8;
		b0();
		word64 r38 = r8 + 0x00;
		r1 = r41 + 0x00;
		r42 = r8 + 0x01;
		b0();
		Eq_n r37 = r38 + ~0x01;
		struct Eq_n * r14 = (struct Eq_n *) (r32 + 1);
		word64 r15 = r32 + 2;
		r42 = *r32;
		r1 = r41 + 0x00;
		r35 = r8 + 0x00;
		r37 = __addp4(0x00, r37);
		int32 v22 = (word32) 0x01;
		int32 v23 = (word32) r38;
		Eq_n p08 = v22 < v23;
		Eq_n p09 = v22 >= v23;
		p06 = 0x00 == r42;
		p07 = 0x00 != r42;
		word64 r33 = &r14->ptr0000;
		if (!p06)
		{
			r37 = (r37 << 0x03) + r15;
			r14 = r14->ptr0000;
			if (p09)
			{
				word64 r16 = 0x00 + 0x00;
			}
			if (p09)
				r38 = 0x00 + 0x00;
			r1 < 0x00;
			Eq_n p19 = r1 >= 0x00;
			word64 pr = r99;
		}
		else
		{
			r8 = r35 + 0x00;
			ar.pfs = r40;
			b0 = r39;
		}
	}
	else
	{
		r42 = 0x00 + 1;
		b0();
		r35 = r8 + 0x00;
		r1 = r41 + 0x00;
		ar.pfs = r40;
		r8 = r35 + 0x00;
		b0 = r39;
	}
}

// 40000000000E5AC0: define gen_compspec_completions
define gen_compspec_completions
{
	Eq_n r8;
	word64 b5;
	word64 r32;
	word64 r34;
	word64 r1;
	word64 pr;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r54 = ar.pfs;
	word64 r12 = r12 + ~0x6F;
	word64 r56 = pr;
	word64 r55 = r1 + 0x00;
	Eq_n r58 = r34 + 0x00;
	union Eq_n * r39 = r32 + 0x18;
	word64 r53 = b5;
	Eq_n r57 = r32 + 0x00;
	<anonymous> * b0;
	b0();
	Eq_n r14;
	r14.u1 = r39->u1;
	word64 * r44 = (word64 *) r8.u1;
	r1 = r55 + 0x00;
	r57 = 0x00 + 0x00;
	Eq_n p06 = 0x00 == r14;
	Eq_n p07 = 0x00 != r14;
	Eq_n r38;
	union Eq_n * r0;
	if (!p06)
	{
		b0();
		r1 = r55 + 0x00;
		r38.u1 = r8.u1;
		r57.u1 = r39->u1;
		r58 = 0x00 + 0x00;
		b0();
		r1 = r55 + 0x00;
		*r8.u2 = r38;
		r57.u1 = r8.u1;
		r14 = r1 + 0x00002444;
		p07 = r14 == r8;
		p06 = r14 != r8;
		if (p07)
			r0->u1 = (byte *) r38;
		__break();
		__break();
	}
	else
	{
		r14 = r32 + 0x20;
		r38 = *r14.u2;
		p06 = 0x00 == r38;
		p07 = 0x00 != r38;
		r57.u1 = r38.u1;
		Eq_n r59;
		word64 r60;
		word64 r61;
		word64 r62;
		word64 * r63;
		word64 * r46;
		Eq_n r40;
		word64 * r47;
		if (!p06)
		{
			byte v27 = *r38.u1;
			r14.u1 = (word64) v27;
			int8 v28 = (int8) r14;
			r14.u1 = (int64) v28;
			word32 v29 = (word32) 0x00;
			word32 v30 = (word32) r14;
			p06 = v29 == v30;
			p07 = v29 != v30;
			if (!p06)
			{
				b0();
				r59 = 0x00 + 0x00;
				r58.u1 = r8.u1;
				r60 = 0x00 + -1;
				r61 = 0x00 + 0x00;
				r62 = 0x00 + 0x00;
				r63 = 0x00 + 0x00;
				r57.u1 = r38.u1;
				r1 = r55 + 0x00;
				b0();
				p06 = 0x00 == r8;
				p07 = 0x00 != r8;
				r1 = r55 + 0x00;
				r38.u1 = r8.u1;
				r57.u1 = r8.u1;
				if (!p06)
				{
					b0();
					r1 = r55 + 0x00;
					r46 = (word64 *) r8.u1;
					r57.u1 = r38.u1;
					b0();
					r1 = r55 + 0x00;
					r57.u1 = r46;
					b0();
					r1 = r55 + 0x00;
					r57.u1 = (word32) r8 + 1;
					b0();
					r1 = r55 + 0x00;
					word64 * r45 = (word64 *) r8.u1;
					r57 = r34 + 0x00;
					b0();
					r1 = r55 + 0x00;
					word64 * r43 = (word64 *) r8.u1;
					Eq_n p18 = 0x00 == r8;
					Eq_n p19 = 0x00 != r8;
					if (!p18)
					{
						Eq_n v47;
						v47.u0 = *r8.u1;
						r14.u1 = (word64) v47;
						int8 v48 = (int8) r14;
						r14.u1 = (int64) v48;
						word32 v49 = (word32) 0x00;
						word32 v50 = (word32) r14;
						p06 = v49 == v50;
						p07 = v49 != v50;
						if (!p06)
						{
							r14.u1 = (word32) r8 + 1;
							Eq_n v52;
							v52.u0 = *r14.u1;
							r14.u1 = (word64) v52;
							int8 v53 = (int8) r14;
							r14.u1 = (int64) v53;
							word32 v54 = (word32) 0x00;
							word32 v55 = (word32) r14;
							p06 = v54 == v55;
							p07 = v54 != v55;
							if (p06)
								r8 = 0x00 + 1;
							word64 p03;
							if (p03)
							{
								int64 r33;
								0x00 < r33;
								Eq_n p11 = 0x00 >= r33;
							}
						}
					}
					r8 = 0x00 + 0x00;
					r38.u1 = r46;
					r40 = 0x00 + 0x00;
					word32 v57 = (word32) 0x00;
					word32 v58 = (word32) r8;
					Eq_n p17 = v57 == v58;
					Eq_n p16 = v57 != v58;
					int32 v61 = (int32) r8;
					r47 = (int64) v61;
					p06 = null == r46;
					p07 = null != r46;
					int64 r16;
					Eq_n r15;
					if (p06)
					{
						r16 = 0x00 + 0x00;
						r40 = 0x00 + 0x00;
					}
					else
					{
						do
						{
							int32 v66 = (int32) r40;
							r14.u1 = (int64) v66;
							r39 = (union Eq_n *) ((word32) r38 + 8);
							Eq_n r42;
							byte * r41;
							if (!p16)
							{
								r15.u1 = r39->u1;
								r42.u1 = *r45;
								r42.u1 += r14 << 0x03;
								r41 = (byte *) *r15.u2;
								p07 = null == r41;
								p06 = null != r41;
								r57.u1 = r41;
								if (p07)
									r8 = 0x00 + 0x00;
								__break();
								__break();
							}
							r15.u1 = r39->u1;
							byte v70 = (byte) *r43;
							r14.u1 = (word64) v70;
							int8 v71 = (int8) r14;
							r16 = (int64) v71;
							r41 = (byte *) *r15.u2;
							byte v72 = *r41;
							r14.u1 = (word64) v72;
							int8 v73 = (int8) r14;
							r14.u1 = (int64) v73;
							word32 v74 = (word32) r14;
							word32 v75 = (word32) r16;
							p07 = v74 == v75;
							p06 = v74 != v75;
							if (!p06)
							{
								r57.u1 = r41;
								r58.u1 = r43;
								r59.u1 = r47;
								b0();
								int32 v78 = (int32) r40;
								r14.u1 = (int64) v78;
								r1 = r55 + 0x00;
								word32 v79 = (word32) 0x00;
								word32 v80 = (word32) r8;
								p06 = v79 == v80;
								p07 = v79 != v80;
								if (!p07)
								{
									r42.u1 = *r45;
									r57.u1 = r41;
									r42.u1 += r14 << 0x03;
									b0();
									r1 = r55 + 0x00;
									r57.u1 = (word32) r8 + 1;
									b0();
									r14.u1 = r39->u1;
									r1 = r55 + 0x00;
									r57.u1 = r8.u1;
									r58 = *r14.u2;
									b0();
									r1 = r55 + 0x00;
									*r8.u2 = r42;
									r40.u0 = (word32) r40 + 1;
								}
							}
							r38 = *r38.u2;
							p07 = 0x00 == r38;
							p06 = 0x00 != r38;
						} while (p06);
						int32 v82 = (int32) r40;
						r16 = (int64) v82;
						r16 = (r16 << 0x03) + 0x00;
					}
					r14.u1 = r45;
					r57.u1 = r46;
					r15 = *r14.u2;
					r14.u1 = (word32) r14 + 0x0C;
					r15.u1 += r16;
					r40.u1->t0000.u0 = (word32) (word32) r14;
					r0->u1 = (byte *) r15;
					b0();
					r1 = r55 + 0x00;
					r57.u1 = r43;
					if (p18)
						r57.u1 = r44;
					else
					{
						word64 p48;
						if (p48)
							__break();
						if (p16)
							__break();
					}
					r58.u1 = r45;
					b0();
					r1 = r55 + 0x00;
					r44 = (word64 *) r8.u1;
					r57.u1 = r45;
					b0();
					r1 = r55 + 0x00;
				}
			}
		}
		r46 = r32 + 0x40;
		union Eq_n * r50 = r32 + 0x38;
		r14.u1 = *r46;
		p07 = 0x00 == r14;
		p06 = 0x00 != r14;
		if (p07)
		{
			r14.u1 = r50->u1;
			p06 = 0x00 == r14;
			p07 = 0x00 != r14;
			if (!p07)
			{
				word64 r37;
				p06 = 0x00 == r37;
				p07 = 0x00 != r37;
				word64 r51 = 0x00 + 0x00;
				word32 * r52 = 0x00 + 1;
				if (p07)
					*r52 = (word32) r37;
			}
		}
		r14 = r1 + -0x0000292C;
		r40 = r1 + -10252;
		word64 r35;
		r58 = r35 + 0x00;
		word64 r36;
		r59 = r36 + 0x00;
		r39 = r12 + 0x70;
		r14 = *r14.u2;
		r40.u1 = r40.u1->t0000.u1;
		r57 = *r14.u2;
		b0();
		r1 = r55 + 0x00;
		Eq_n v85;
		v85.u0 = r40.u1->t0000.u0;
		r60 = (word64) v85;
		r62 = r12 + 116;
		r63 = (word64 *) &r39->u0;
		word64 * r48 = (word64 *) r8.u1;
		r61 = 0x00 + 4;
		r14 = r1 + -10460;
		r60 = r35 - r60;
		r57.u1 = r8.u1;
		r58 = r35 - r36;
		r14 = *r14.u2;
		r59 = *r14.u2;
		b0();
		r38.u1 = r50->u1;
		r47 = (word64 *) r8.u1;
		r1 = r55 + 0x00;
		p07 = 0x00 == r38;
		p06 = 0x00 != r38;
		r57.u1 = r38.u1;
		if (p07)
			r14.u1 = *r46;
	}
}

// 40000000000E7780: define pcomp_set_readline_variables
define pcomp_set_readline_variables
{
	word64 r7;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 p07;
	struct Eq_n * r14;
	if (p07)
	{
		word64 r1;
		r14 = r1 + -10172;
	}
	if (p07)
		r14 = r14->ptr0000;
	word64 p03;
	if (p03)
	{
		up32 v9 = (word32) 0x20;
		up32 v10 = (word32) r7;
		Eq_n p08 = v9 < v10;
		Eq_n p40 = v9 >= v10;
	}
}

// 40000000000E77C0: define pcomp_set_compspec_options
define pcomp_set_compspec_options
{
	word64 * r32;
	ptr64 fp;
	ptr64 r11 = fp;
	Eq_n p07 = null == r32;
	Eq_n p06 = null != r32;
	word64 ** r14 = r32 + 2;
	word64 r34;
	int64 r15;
	word64 p08;
	word64 p17;
	word64 p16;
	if (!p07)
	{
		word32 v9 = (word32) 0x00;
		word32 v10 = (word32) r34;
		p06 = v9 == v10;
		p07 = v9 != v10;
		int32 v12 = (int32) r15;
		r15 = (int64) v12;
		if (p07)
			r32 = r14;
		if (!p08)
		{
			if (p17)
				__break();
			if (p16)
				__break();
			word64 p34;
			if (p34)
				__break();
		}
	}
	else
	{
		word64 r1;
		r14 = r1 + 9220;
		int32 v14 = (int32) r15;
		r15 = (int64) v14;
		r32 = *r14;
		p06 = null == r32;
		p07 = null != r32;
		r14 = r32 + 2;
		if (p06)
			return;
		word32 v18 = (word32) 0x00;
		word32 v19 = (word32) r34;
		p06 = v18 == v19;
		p07 = v18 != v19;
		if (p07)
			r32 = r14;
		if (!p08)
		{
			if (p17)
				__break();
			if (p16)
				__break();
			word64 p04;
			if (p04)
				__break();
			__break();
			__break();
			programmable_completions();
		}
	}
}

// 40000000000E78C0: define programmable_completions
// Called from:
//      pcomp_set_compspec_options
define programmable_completions
{
	word64 r64;
	word64 r35;
	word64 r34;
	word64 r33;
	word64 LC;
	int64 r1;
	word64 b7;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r40 = ar.pfs;
	Eq_n r12;
	r12.u0 = (word64) r12.u0 - 32;
	word64 r39 = b7;
	word64 r41 = r1 + 0x00;
	union Eq_n * r38 = (word64) r12.u0 + 16;
	word32 * r37 = (word64) r12.u0 + 24;
	word64 r42 = LC;
	r38->u0 = (word64) r12;
	r38 = (union Eq_n *) ((char *) r38 + 0x0C);
	LC = 0x20;
	word32 * r0;
	*r0 = (word32) r38;
	Eq_n r43;
	int64 r32;
	Eq_n p07;
	Eq_n p06;
	struct Eq_n * r8;
	do
	{
		r43 = r32 + 0x00;
		word64 r44 = r32 + 0x00;
		word64 r45 = r33 + 0x00;
		word64 r46 = r34 + 0x00;
		word64 r47 = r35 + 0x00;
		word64 * r48 = &r38->u0;
		word32 * r49 = r37;
		word64 r50 = (word64) r12.u0 + 16;
		*r0 = (word32) r37;
		<anonymous> * b0;
		b0();
		Eq_n v29;
		v29.u1 = r38->u1;
		struct Eq_n * r14 = (word64) v29;
		r43 = r32 + 0x00;
		r44 = 0x00 + 47;
		r1 = r41 + 0x00;
		word32 v31 = (word32) 0x00;
		word32 v32 = (word32) r14;
		p07 = v31 == v32;
		p06 = v31 != v32;
		if (!p06)
		{
			b0();
			r43.u1 = (char *) &r8->ptr0000 + 1;
			r1 = r41 + 0x00;
			p07 = null == r8;
			p06 = null != r8;
			if (!p07)
			{
				Eq_n v36;
				v36.u0 = r43.u2->t0000.u0;
				r14 = (word64) v36;
				int8 v37 = (int8) r14;
				r14 = (int64) v37;
				word32 v38 = (word32) 0x00;
				word32 v39 = (word32) r14;
				p06 = v38 == v39;
				p07 = v38 != v39;
				if (p07)
				{
					r44 = r32 + 0x00;
					r45 = r33 + 0x00;
					r46 = r34 + 0x00;
					r47 = r35 + 0x00;
					r48 = &r38->u0;
					r49 = r37;
					r50 = (word64) r12.u0 + 16;
					b0();
					Eq_n v43;
					v43.u1 = r38->u1;
					r14 = (word64) v43;
					r1 = r41 + 0x00;
					word32 v44 = (word32) 0x00;
					word32 v45 = (word32) r14;
					p06 = v44 == v45;
					p07 = v44 != v45;
					if (!p06)
						;
				}
			}
			r43 = r1 + -532;
			r44 = r32 + 0x00;
			r45 = r33 + 0x00;
			r46 = r34 + 0x00;
			r47 = r35 + 0x00;
			r48 = &r38->u0;
			r43.u1 = *r43.u1;
			r49 = r37;
			r50 = (word64) r12.u0 + 16;
			b0();
			r1 = r41 + 0x00;
		}
		if (LC == 0x00)
		{
			r43 = r1 + -524;
			r14 = (word64) r12.u0 + 32;
			r44 = r32 + 0x00;
			r8->ptr0000 = r14;
			r43.u1 = *r43.u1;
			b0();
			r14 = (word64) r12.u0 + 32;
			r1 = r41 + 0x00;
			r8 = r14->ptr0000;
			break;
		}
		--LC;
		word32 v40 = *r37;
		r14 = (word64) v40;
		word32 v41 = (word32) 0x00;
		word32 v42 = (word32) r14;
		p07 = v41 == v42;
		p06 = v41 != v42;
	} while (p06);
	p06 = null == r8;
	p07 = null != r8;
	r43.u1 = &r8->ptr0000;
	if (p06)
		r37 = 0x00 + 0x00;
	byte v49 = (byte) r64;
	r32 = (word64) v49;
	__break();
	r1 < 0x00;
	Eq_n p09 = r1 >= 0x00;
	byte v51 = (byte) r64;
	word64 r4 = (word64) v51;
	r32 < 0x00;
	r32 >= 0x00;
	word64 p04;
	if (p04)
		__break();
	word64 p24;
	if (p24)
		__break();
	__break();
	__break();
	word64 p32;
	if (p32)
	{
		bool v57 = (bool) r1;
		word64 r66 = (word64) v57;
	}
	word64 p08;
	if (p08)
		__break();
}

// 40000000000E7C00: define compspec_create
define compspec_create
{
	word64 r8;
	word64 r1;
	<anonymous> * b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	word64 r35 = 0x00 + 88;
	b0();
	word32 * r15 = r8 + 0x00;
	word32 * r23 = r8 + 0x10;
	word32 * r22 = r8 + 0x18;
	word32 * r21 = r8 + 0x20;
	word32 * r20 = r8 + 0x28;
	word32 * r19 = r8 + 0x30;
	*r15 = (word32) r8;
	r15 += 2;
	word32 * r18 = r8 + 0x38;
	word32 * r17 = r8 + 0x40;
	word32 * r16 = r8 + 0x48;
	word32 * r14 = r8 + 0x50;
	r1 = r34 + 0x00;
	word32 ** r0;
	*r0 = (word32 **) r23;
	*r0 = (word32 **) r15;
	ar.pfs = r33;
	*r0 = (word32 **) r22;
	*r0 = (word32 **) r21;
	b0 = r32;
	*r0 = (word32 **) r20;
	*r0 = (word32 **) r19;
	*r0 = (word32 **) r18;
	*r0 = (word32 **) r17;
	*r0 = (word32 **) r16;
	*r0 = (word32 **) r14;
}

// 40000000000E7CC0: define compspec_dispose
define compspec_dispose
{
	word64 r1;
	<anonymous> * b1;
	word32 * r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word32 v7 = *r32;
	union Eq_n * r14 = (word64) v7;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	r14 = (union Eq_n *) ((char *) r14 - 1);
	r14->u0 = (word32) (word32) r32;
	word32 v13 = (word32) 0x00;
	word32 v14 = (word32) r14;
	Eq_n p07 = v13 == v14;
	Eq_n p06 = v13 != v14;
	r14 = (union Eq_n *) (r32 + 6);
	<anonymous> * b0;
	if (!p06)
	{
		Eq_n r36;
		r36.u1 = r14->u1;
		p06 = 0x00 == r36;
		p07 = 0x00 != r36;
		if (!p06)
		{
			b0();
			r1 = r35 + 0x00;
		}
		r14 = (union Eq_n *) (r32 + 8);
		r36.u1 = r14->u1;
		p06 = 0x00 == r36;
		p07 = 0x00 != r36;
		if (!p06)
		{
			b0();
			r1 = r35 + 0x00;
		}
		r14 = (union Eq_n *) (r32 + 0x0A);
		r36.u1 = r14->u1;
		p06 = 0x00 == r36;
		p07 = 0x00 != r36;
		if (!p06)
		{
			b0();
			r1 = r35 + 0x00;
		}
		r14 = (union Eq_n *) (r32 + 0x0C);
		r36.u1 = r14->u1;
		p06 = 0x00 == r36;
		p07 = 0x00 != r36;
		if (!p06)
		{
			b0();
			r1 = r35 + 0x00;
		}
		r14 = (union Eq_n *) (r32 + 0x0E);
		r36.u1 = r14->u1;
		p06 = 0x00 == r36;
		p07 = 0x00 != r36;
		if (!p06)
		{
			b0();
			r1 = r35 + 0x00;
		}
		r14 = (union Eq_n *) (r32 + 16);
		r36.u1 = r14->u1;
		p06 = 0x00 == r36;
		p07 = 0x00 != r36;
		if (!p06)
		{
			b0();
			r1 = r35 + 0x00;
		}
		r14 = (union Eq_n *) (r32 + 18);
		r36.u1 = r14->u1;
		p06 = 0x00 == r36;
		p07 = 0x00 != r36;
		if (!p06)
		{
			b0();
			r1 = r35 + 0x00;
		}
		r14 = (union Eq_n *) (r32 + 20);
		r36.u1 = r14->u1;
		p06 = 0x00 == r36;
		p07 = 0x00 != r36;
		if (!p06)
		{
			b0();
			r1 = r35 + 0x00;
		}
		r36.u1 = r32;
		b0();
		r1 = r35 + 0x00;
	}
	ar.pfs = r34;
	b0 = r33;
}

// 40000000000E7F80: define compspec_copy
define compspec_copy
{
	word64 r32;
	word64 b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 r37 = r1 + 0x00;
	word64 r35 = b3;
	word64 * r34 = r32 + 0x18;
	word64 r38 = 0x00 + 88;
	<anonymous> * b0;
	b0();
	r38 = *r34;
	Eq_n r15 = r32 + 0x00;
	Eq_n r14;
	union Eq_n * r8;
	r14.u1 = &r8->u0;
	struct Eq_n * r16 = r32 + 0x10;
	struct Eq_n * r17 = (struct Eq_n *) ((char *) r8 + 16);
	word64 r33 = &r8->u0;
	Eq_n p06 = 0x00 == r38;
	Eq_n p07 = 0x00 != r38;
	Eq_n v22;
	v22.u0 = r15.u1->t0000.u0;
	word64 r18 = (word64) v22;
	r15.u0 = (word32) r15 + 8;
	r1 = r37 + 0x00;
	r16 = r16->ptr0000;
	r14.u1->t0000.u0 = (word32) (word32) r8;
	r14.u0 = (word32) r14 + 8;
	r15.u1 = r15.u1->t0000.u1;
	if (p06)
		r8 = 0x00 + 0x00;
	r16->ptr0000 = r17;
	r15.u1->t0000.u1 = (struct Eq_n *) r14;
	word64 p01;
	if (!p06)
	{
		if (p01)
			__break();
	}
	else
	{
		r34 = r32 + 0x20;
		r14 = r33 + 0x18;
		r38 = *r34;
		r8->u1 = (struct Eq_n *) r14;
		p06 = 0x00 == r38;
		p07 = 0x00 != r38;
		if (p06)
			r8 = 0x00 + 0x00;
		__break();
		__break();
		if (p01)
			__break();
	}
}

// 40000000000E8480: define progcomp_create
define progcomp_create
{
	word64 r1;
	<anonymous> * b1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	<anonymous> * r33 = b1;
	word64 * r32 = r1 + 8324;
	word64 r35 = r1 + 0x00;
	word64 r14 = *r32;
	ar.pfs = r34;
	Eq_n p07 = 0x00 == r14;
	Eq_n p06 = 0x00 != r14;
	<anonymous> * b0 = r33;
	if (p07)
	{
		word64 r36 = 0x00 + 32;
		b0();
		r1 = r35 + 0x00;
		word64 ** r8;
		*r8 = r32;
		ar.pfs = r34;
		b0 = r33;
	}
}

// 40000000000E8500: define progcomp_size
define progcomp_size
{
	word64 r1;
	ptr64 fp;
	ptr64 r11 = fp;
	struct Eq_n * r14 = r1 + 8324;
	r14 = r14->ptr0000;
	Eq_n p06 = null == r14;
	Eq_n p07 = null != r14;
	word32 * r15 = (word32 *) ((char *) &r14->ptr0000 + 0x0C);
	if (p07)
	{
		word32 v9 = *r15;
		word64 r8 = (word64) v9;
	}
}

// 40000000000E8540: define progcomp_flush
define progcomp_flush
{
	<anonymous> * b0;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r33 = ar.pfs;
	word64 * r14 = r1 + 8324;
	struct Eq_n * r36 = r1 + -3404;
	<anonymous> * r32 = b0;
	word64 r34 = r1 + 0x00;
	word64 r35 = *r14;
	r36 = r36->ptr0000;
	Eq_n p06 = 0x00 == r35;
	Eq_n p07 = 0x00 != r35;
	if (!p06)
	{
		b0();
		r1 = r34 + 0x00;
	}
	ar.pfs = r33;
	b0 = r32;
}

// 40000000000E85C0: define progcomp_dispose
define progcomp_dispose
{
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 * r32 = r1 + 8324;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = *r32;
	Eq_n p06 = 0x00 == r36;
	Eq_n p07 = 0x00 != r36;
	<anonymous> * b0;
	if (!p06)
	{
		b0();
		r1 = r35 + 0x00;
	}
	word64 ** r0;
	*r0 = r32;
	ar.pfs = r34;
	b0 = r33;
}

// 40000000000E8640: define progcomp_remove
define progcomp_remove
{
	word64 r32;
	word64 b2;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	struct Eq_n * r14 = r1 + 8324;
	word64 r34 = b2;
	word64 r36 = r1 + 0x00;
	word64 r37 = r32 + 0x00;
	r14 = r14->ptr0000;
	word64 r39 = 0x00 + 0x00;
	Eq_n p06 = null == r14;
	Eq_n p07 = null != r14;
	word64 * r38 = &r14->ptr0000;
	if (p06)
	{
		word64 r8 = 0x00 + 1;
	}
	__break();
	__break();
	__break();
	word64 pr = 0x00;
}

// 40000000000E8780: define progcomp_insert
define progcomp_insert
{
	union Eq_n * r33;
	<anonymous> * b4;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r37 = ar.pfs;
	Eq_n r34 = r1 + 8324;
	<anonymous> * r36 = b4;
	word64 r38 = r1 + 0x00;
	Eq_n p07 = null == r33;
	Eq_n p06 = null != r33;
	struct Eq_n * r40;
	word64 r41;
	struct Eq_n * r39;
	<anonymous> * b0;
	word64 r32;
	word64 * r8;
	if (p07)
	{
		r40 = r1 + -0x0D44;
		r41 = 0x00 + 5;
		r39 = 0x00 + 0x00;
		r40 = r40->ptr0000;
		b0();
		r1 = r38 + 0x00;
		r40 = r32 + 0x00;
		r39 = (struct Eq_n *) r8;
		b0();
		r40 = (struct Eq_n *) *r34.u1;
		r1 = r38 + 0x00;
		p07 = null == r40;
		p06 = null != r40;
		if (p06)
			goto l40000000000E87C0;
	}
	else
	{
		r40 = (struct Eq_n *) *r34.u1;
		p07 = null == r40;
		p06 = null != r40;
		if (!p07)
			goto l40000000000E87C0;
	}
	b0();
	r1 = r38 + 0x00;
	r40 = (struct Eq_n *) *r34.u1;
l40000000000E87C0:
	Eq_n v20;
	v20.u0 = r33->u0;
	word32 * r14 = (word64) v20;
	r41 = 0x00 + 0x00;
	r39 = r32 + 0x00;
	r14 = (word32 *) ((char *) r14 + 1);
	*r14 = (word32) r33;
	b0();
	r34.u1 = r8 + 2;
	r1 = r38 + 0x00;
	word64 r35 = r8;
	r39 = (struct Eq_n *) *r34.u1;
	p06 = null == r39;
	p07 = null != r39;
	if (!p06)
	{
		b0();
		r8 = 0x00 + 1;
		r1 = r38 + 0x00;
		r33->u1 = (struct Eq_n **) r34;
		ar.pfs = r37;
		b0 = r36;
	}
	else
	{
		r39 = r32 + 0x00;
		r35 += 0x08;
		b0();
		r1 = r38 + 0x00;
		r39 = (struct Eq_n *) ((char *) r8 + 1);
		b0();
		r1 = r38 + 0x00;
		r39 = (struct Eq_n *) r8;
		r40 = r32 + 0x00;
		b0();
		r1 = r38 + 0x00;
		*r8 = r35;
		r33->u1 = (struct Eq_n **) r34;
		r8 = 0x00 + 1;
		ar.pfs = r37;
		b0 = r36;
	}
}

// 40000000000E8980: define progcomp_search
define progcomp_search
{
	word64 r32;
	<anonymous> * b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	struct Eq_n * r14 = r1 + 8324;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = r32 + 0x00;
	r14 = r14->ptr0000;
	word64 r38 = 0x00 + 0x00;
	Eq_n p07 = null == r14;
	Eq_n p06 = null != r14;
	word64 * r37 = &r14->ptr0000;
	<anonymous> * b0;
	struct Eq_n * r8;
	if (!p07)
	{
		b0();
		r14 = (struct Eq_n *) ((char *) &r8->ptr0000 + 16);
		p06 = null == r8;
		p07 = null != r8;
		r1 = r35 + 0x00;
		ar.pfs = r34;
		if (!p06)
		{
			b0 = r33;
			r8 = r14->ptr0000;
			return;
		}
	}
	r8 = 0x00 + 0x00;
	ar.pfs = r34;
	b0 = r33;
}

// 40000000000E8A40: define progcomp_walk
define progcomp_walk
{
	word64 r32;
	word64 b1;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	word64 * r14 = r1 + 8324;
	word64 r33 = b1;
	Eq_n p08 = 0x00 == r32;
	Eq_n p09 = 0x00 != r32;
	word64 r35 = r1 + 0x00;
	word64 r36 = *r14;
	r14 = r36 + 0x0C;
	Eq_n p06 = 0x00 == r36;
	Eq_n p07 = 0x00 != r36;
	if (p06)
	{
		ar.pfs = r34;
		word64 b0 = r33;
	}
}

// 40000000000E8CC0: define xmalloc
define xmalloc
{
	word64 r32;
	word64 r1;
	<anonymous> * b2;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	<anonymous> * r34 = b2;
	word32 * r33 = r1 + 8332;
	word64 r36 = r1 + 0x00;
	struct Eq_n * r37 = r32 + 0x00;
	word32 v14 = *r33;
	struct Eq_n * r14 = (word64) v14;
	word32 v16 = (word32) 0x00;
	word32 v17 = (word32) r14;
	Eq_n p07 = v16 == v17;
	Eq_n p06 = v16 != v17;
	<anonymous> * b0;
	Eq_n r8;
	if (p07)
	{
		r37 = 0x00 + 0x00;
		b0();
		r1 = r36 + 0x00;
		r37 = r32 + 0x00;
		r14 = r1 + 8340;
		r8.u1->ptr0000 = r14;
		r14 = 0x00 + 1;
		r14->t0000.u0 = (word32) (word32) r33;
		b0();
		r1 = r36 + 0x00;
		p07 = 0x00 == r8;
		p06 = 0x00 != r8;
		if (p06)
		{
l40000000000E8D20:
			ar.pfs = r35;
			b0 = r34;
			r12 += 0x10;
			return;
		}
	}
	else
	{
		b0();
		r1 = r36 + 0x00;
		p07 = 0x00 == r8;
		p06 = 0x00 != r8;
		if (!p07)
			goto l40000000000E8D20;
	}
	r14 = r12 + 0x10;
	r37 = r1 + 0x052C;
	word64 r38 = r32 + 0x00;
	r8.u1->ptr0000 = r14;
	r37 = r37->ptr0000;
	b0();
	r14 = r12 + 0x10;
	r1 = r36 + 0x00;
	r8.u1 = r14->t0000.u1;
	ar.pfs = r35;
	b0 = r34;
	r12 += 0x10;
}

// 40000000000E8E00: define xrealloc
define xrealloc
{
	<anonymous> * b3;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word32 * r34 = r1 + 8332;
	<anonymous> * r35 = b3;
	word64 r37 = r1 + 0x00;
	word32 v12 = *r34;
	struct Eq_n * r14 = (word64) v12;
	word32 v14 = (word32) 0x00;
	word32 v15 = (word32) r14;
	Eq_n p07 = v14 == v15;
	Eq_n p06 = v14 != v15;
	struct Eq_n * r38;
	<anonymous> * b0;
	word64 r32;
	Eq_n r8;
	word64 r39;
	word64 r33;
	if (p07)
	{
		r38 = 0x00 + 0x00;
		b0();
		r1 = r37 + 0x00;
		p06 = 0x00 == r32;
		p07 = 0x00 != r32;
		r14 = r1 + 8340;
		r8.u1->ptr0000 = r14;
		r14 = 0x00 + 1;
		r14->t0000.u0 = (word32) (word32) r34;
		if (p07)
		{
l40000000000E8E50:
			r38 = r32 + 0x00;
			r39 = r33 + 0x00;
			b0();
			r1 = r37 + 0x00;
			p07 = 0x00 == r8;
			p06 = 0x00 != r8;
			if (p07)
				goto l40000000000E8F00;
			goto l40000000000E8E70;
		}
	}
	else
	{
		p06 = 0x00 == r32;
		p07 = 0x00 != r32;
		if (!p06)
			goto l40000000000E8E50;
	}
	r38 = r33 + 0x00;
	b0();
	r1 = r37 + 0x00;
	p07 = 0x00 == r8;
	p06 = 0x00 != r8;
	if (!p06)
	{
l40000000000E8F00:
		r14 = r12 + 0x10;
		r38 = r1 + 1332;
		r39 = r33 + 0x00;
		r8.u1->ptr0000 = r14;
		r38 = r38->ptr0000;
		b0();
		r14 = r12 + 0x10;
		r1 = r37 + 0x00;
		r8.u1 = r14->t0000.u1;
		ar.pfs = r36;
		b0 = r35;
		r12 += 0x10;
		return;
	}
l40000000000E8E70:
	ar.pfs = r36;
	b0 = r35;
	r12 += 0x10;
}

// 40000000000E8F80: define xfree
define xfree
{
	word64 r1;
	<anonymous> * b1;
	word64 r32;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r34 = ar.pfs;
	Eq_n p06 = 0x00 == r32;
	Eq_n p07 = 0x00 != r32;
	<anonymous> * r33 = b1;
	word64 r35 = r1 + 0x00;
	word64 r36 = r32 + 0x00;
	<anonymous> * b0;
	if (!p06)
	{
		b0();
		r1 = r35 + 0x00;
	}
	ar.pfs = r34;
	b0 = r33;
}

// 40000000000E9180: define alias_builtin
define alias_builtin
{
	word64 b6;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r39 = ar.pfs;
	word32 * r14 = r1 + 6456;
	word64 r40 = r1 + 0x00;
	word64 r38 = b6;
	word64 r33 = 0x00 + 0x00;
	word32 v12 = *r14;
	word64 r36 = (word64) v12;
	word32 v14 = (word32) 0x00;
	word32 v15 = (word32) r36;
	Eq_n p06 = v14 == v15;
	Eq_n p07 = v14 != v15;
	if (p06)
		r36 = 0x00 + 1;
}

// 40000000000E96C0: define unalias_builtin
define unalias_builtin
{
	word64 r32;
	<anonymous> * b4;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r37 = ar.pfs;
	word64 r38 = r1 + 0x00;
	<anonymous> * r36 = b4;
	word64 r34 = 0x00 + 0x00;
	<anonymous> * b0;
	b0();
	r1 = r38 + 0x00;
	struct Eq_n ** r8;
	Eq_n p06;
	do
	{
		struct Eq_n * r40 = r1 + -9452;
		struct Eq_n * r39 = r32 + 0x00;
		r40 = r40->ptr0000;
		b0();
		word32 v16 = (word32) ~0x00;
		word32 v17 = (word32) r8;
		Eq_n p07 = v16 == v17;
		p06 = v16 != v17;
		r1 = r38 + 0x00;
		if (p07)
		{
			struct Eq_n ** r14 = r1 + 0x00002434;
			word32 v23 = (word32) 0x00;
			word32 v24 = (word32) r34;
			p06 = v23 == v24;
			p07 = v23 != v24;
			if (!p07)
			{
				struct Eq_n * r33 = (struct Eq_n *) *r14;
				p07 = null == r33;
				p06 = null != r33;
				if (p07)
					break;
				do
				{
					struct Eq_n *** r35 = (struct Eq_n ***) ((char *) &r33->ptr0000 + 8);
					r14 = (struct Eq_n **) *r35;
					r39 = (struct Eq_n *) *r14;
					b0();
					p06 = null == r8;
					p07 = null != r8;
					r1 = r38 + 0x00;
					if (p06)
					{
						r14 = (struct Eq_n **) *r35;
						++r34;
						r39 = (struct Eq_n *) *r14;
						b0();
						r33 = r33->ptr0000;
						r1 = r38 + 0x00;
						p07 = null == r33;
						p06 = null != r33;
						if (p06)
							continue;
						break;
					}
					r39 = (struct Eq_n *) *r8;
					b0();
					r33 = r33->ptr0000;
					r1 = r38 + 0x00;
					p07 = null == r33;
					p06 = null != r33;
				} while (p06);
				word32 v27 = (word32) 0x00;
				word32 v28 = (word32) r34;
				p07 = v27 == v28;
				p06 = v27 != v28;
				ar.pfs = r37;
				if (p06)
					r34 = 0x00 + 1;
			}
			else
			{
				b0();
				r8 = 0x00 + 0x00;
				r1 = r38 + 0x00;
				ar.pfs = r37;
				b0 = r36;
				return;
			}
		}
		r34 = 0x00 + 1;
		word32 v20 = (word32) 0x61;
		word32 v21 = (word32) r8;
		p06 = v20 == v21;
		p07 = v20 != v21;
	} while (p06);
	b0();
	r8 = 0x00 + 258;
	r1 = r38 + 0x00;
	ar.pfs = r37;
	b0 = r36;
}

// 40000000000E98C0: define bind_builtin
define bind_builtin
{
	<anonymous> * b1;
	word64 LC;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r50 = ar.pfs;
	Eq_n r14 = r1 + 6468;
	word64 r52 = LC;
	word64 r51 = r1 + 0x00;
	<anonymous> * r49 = b1;
	Eq_n v13 = r14.u2->u1;
	r14.u1 = (word64) v13;
	word32 v14 = (word32) 0x00;
	word32 v15 = (word32) r14;
	Eq_n p06 = v14 == v15;
	Eq_n p07 = v14 != v15;
	r14 = r1 + 7796;
	Eq_n r54;
	Eq_n r55;
	Eq_n r53;
	<anonymous> * b0;
	Eq_n r8;
	word64 r40;
	word64 r41;
	Eq_n r37;
	word64 r39;
	Eq_n r38;
	Eq_n r33;
	word64 r47;
	word64 r46;
	word64 r45;
	word64 r44;
	word64 r43;
	word64 r42;
	Eq_n r36;
	Eq_n r34;
	Eq_n r35;
	if (p07)
	{
		r54 = r1 + -7740;
		r55 = 0x00 + 5;
		r53 = 0x00 + 0x00;
		r54.u1 = *r54.u1;
		b0();
		r1 = r51 + 0x00;
		r53.u1 = r8.u2;
		b0();
		r1 = r51 + 0x00;
		r14 = r1 + 7796;
		Eq_n v26 = r14.u2->u1;
		r14.u1 = (word64) v26;
		word32 v27 = (word32) 0x00;
		word32 v28 = (word32) r14;
		p07 = v27 == v28;
		p06 = v27 != v28;
		if (p06)
		{
l40000000000E9920:
			r53 = r1 + -7732;
			r40 = 0x00 + 0x00;
			r41 = 0x00 + 0x00;
			r37 = 0x00 + 0x00;
			r39 = 0x00 + 0x00;
			r38 = 0x00 + 0x00;
			r53.u1 = *r53.u1;
			r33 = 0x00 + 0x00;
			r47 = 0x00 + 0x00001000;
			r46 = 0x00 + 0x0400;
			r45 = 0x00 + 0x0200;
			b0();
			r1 = r51 + 0x00;
			r54 = 0x00 + 8;
			r44 = 0x00 + 0x0080;
			r43 = 0x00 + 0x0100;
			r42 = 0x00 + 0x0800;
			r36 = r1 + -10700;
			r36.u1 = *r36.u1;
			r53.u1 = r36.u1;
			b0();
			r1 = r51 + 0x00;
			r14 = r1 + -10260;
			r34 = r1 + -7652;
			r35 = r1 + 0x00002424;
			r14.u1 = *r14.u1;
			r34.u1 = *r34.u1;
			r14.u1 = *r14.u1;
			*r14.u1 = (word64) r36;
			b0();
			r1 = r51 + 0x00;
			goto l40000000000E9A00;
		}
	}
	else
	{
		Eq_n v18 = r14.u2->u1;
		r14.u1 = (word64) v18;
		word32 v19 = (word32) 0x00;
		word32 v20 = (word32) r14;
		p07 = v19 == v20;
		p06 = v19 != v20;
		if (!p07)
			goto l40000000000E9920;
	}
	r40 = 0x00 + 0x00;
	r41 = 0x00 + 0x00;
	r37 = 0x00 + 0x00;
	r39 = 0x00 + 0x00;
	r38 = 0x00 + 0x00;
	b0();
	r1 = r51 + 0x00;
	r33 = 0x00 + 0x00;
	r47 = 0x00 + 0x00001000;
	r46 = 0x00 + 0x0400;
	r45 = 0x00 + 0x0200;
	r44 = 0x00 + 0x0080;
	r53 = r1 + -7732;
	r43 = 0x00 + 0x0100;
	r42 = 0x00 + 0x0800;
	r53.u1 = *r53.u1;
	b0();
	r1 = r51 + 0x00;
	r54 = 0x00 + 8;
	r36 = r1 + -10700;
	r36.u1 = *r36.u1;
	r53.u1 = r36.u1;
	b0();
	r1 = r51 + 0x00;
	r14 = r1 + -10260;
	r34 = r1 + -7652;
	r35 = r1 + 0x00002424;
	r14.u1 = *r14.u1;
	r34.u1 = *r34.u1;
	r14.u1 = *r14.u1;
	*r14.u1 = (word64) r36;
	b0();
	r1 = r51 + 0x00;
l40000000000E9A00:
	r54 = r1 + -7724;
	word64 r32;
	r53 = r32 + 0x00;
	r54.u1 = *r54.u1;
	b0();
	r1 = r51 + 0x00;
	word32 v45 = (word32) ~0x00;
	word32 v46 = (word32) r8;
	p07 = v45 == v46;
	p06 = v45 != v46;
	if (!p07)
	{
		r8.u1 = (word32) r8 - 80;
		up32 v47 = (word32) 0x28;
		up32 v48 = (word32) r8;
		p06 = v47 < v48;
		p07 = v47 >= v48;
		if (p07)
		{
			r8 = __addp4(0x00, r8);
			r8.u2 = r34.u1 + r8;
			r14.u1 = *r8.u2;
			r8.u2 = r14 + r8;
			Eq_n b6 = r8;
			b6();
			return;
		}
		r35 = 0x00 + 258;
		b0();
		r1 = r51 + 0x00;
l40000000000E9A70:
		r53 = r1 + -7732;
		r53.u1 = *r53.u1;
		b0();
		r1 = r51 + 0x00;
		r53.u1 = r35.u1;
		b0();
		r1 = r51 + 0x00;
		ar.pfs = r50;
		LC = r52;
		b0 = r49;
		return;
	}
	r14 = r1 + 0x00002434;
	r34.u1 = *r14.u1;
	if (!p06)
	{
		p06 = 0x00 == r39;
		p07 = 0x00 != r39;
		r53 = r39 + 0x00;
		if (!p06)
		{
			b0();
			p07 = 0x00 == r8;
			p06 = 0x00 != r8;
			r1 = r51 + 0x00;
			r35.u1 = r8.u2;
			if (p07)
			{
				r54 = r1 + -7716;
				r55 = 0x00 + 5;
				r53 = 0x00 + 0x00;
				r35 = 0x00 + 1;
				r54.u1 = *r54.u1;
				b0();
				r54 = r39 + 0x00;
				r53.u1 = r8.u2;
				r1 = r51 + 0x00;
				b0();
				r1 = r51 + 0x00;
				r53 = r1 + -7732;
				r53.u1 = *r53.u1;
				b0();
				r1 = r51 + 0x00;
				r53.u1 = r35.u1;
				b0();
				r1 = r51 + 0x00;
				ar.pfs = r50;
				LC = r52;
				b0 = r49;
				return;
			}
			b0();
			r1 = r51 + 0x00;
			r36.u1 = r8.u2;
			r53.u1 = r35.u1;
			b0();
			r1 = r51 + 0x00;
			if (!p07)
			{
l40000000000E9BF0:
				if (p07)
					goto l40000000000EA310;
				goto l40000000000E9C00;
			}
l40000000000EA340:
			b0();
			r1 = r51 + 0x00;
			if (!p06)
			{
l40000000000EA310:
				r53 = 0x00 + 1;
				b0();
				r1 = r51 + 0x00;
				if (p06)
				{
l40000000000E9C10:
					if (p07)
						goto l40000000000EA2B0;
					goto l40000000000E9C20;
				}
l40000000000EA2E0:
				r53 = 0x00 + 0x00;
				b0();
				r1 = r51 + 0x00;
				if (!p06)
				{
l40000000000EA2B0:
					r53 = 0x00 + 1;
					b0();
					r1 = r51 + 0x00;
					if (p06)
					{
l40000000000E9C30:
						if (p07)
							goto l40000000000EA280;
						goto l40000000000E9C40;
					}
l40000000000EA3A0:
					r53 = 0x00 + 0x00;
					b0();
					r1 = r51 + 0x00;
					if (!p06)
					{
l40000000000EA280:
						r53 = 0x00 + 1;
						b0();
						r1 = r51 + 0x00;
						if (p06)
						{
l40000000000E9C50:
							if (p06)
								goto l40000000000E9C90;
							goto l40000000000E9C60;
						}
l40000000000EA370:
						r53 = 0x00 + 0x00;
						b0();
						r1 = r51 + 0x00;
						if (p06)
							goto l40000000000E9C90;
l40000000000E9C60:
						p06 = 0x00 == r38;
						p07 = 0x00 != r38;
						r53.u1 = r38.u1;
						if (!p06)
						{
							b0();
							r1 = r51 + 0x00;
							word32 v50 = (word32) 0x00;
							word32 v51 = (word32) r8;
							p06 = v50 == v51;
							p07 = v50 != v51;
							if (p07)
							{
								r54 = r1 + -7708;
								r55 = 0x00 + 5;
								r53 = 0x00 + 0x00;
								r35 = 0x00 + 1;
								r54.u1 = *r54.u1;
								b0();
								r1 = r51 + 0x00;
								r33.u1 = r8.u2;
								b0();
								r1 = r51 + 0x00;
								word32 v52 = r8.u3->t0000.u1;
								r53.u1 = (word64) v52;
								b0();
								r1 = r51 + 0x00;
								r53.u1 = r33.u1;
								r54.u1 = r38.u1;
								r55.u1 = r8.u2;
								b0();
								r1 = r51 + 0x00;
								goto l40000000000E9F60;
							}
						}
l40000000000E9C90:
						if (p06)
						{
l40000000000EA260:
							r35 = 0x00 + 0x00;
							if (p06)
								goto l40000000000E9EB0;
							goto l40000000000E9E30;
						}
						p06 = 0x00 == r37;
						p07 = 0x00 != r37;
						r53.u1 = r37.u1;
						if (p06)
							goto l40000000000EA260;
						b0();
						p07 = 0x00 == r8;
						p06 = 0x00 != r8;
						r1 = r51 + 0x00;
						r53.u1 = r8.u2;
						if (p07)
						{
							r54 = r1 + -7700;
							r55 = 0x00 + 5;
							r53 = 0x00 + 0x00;
							r35 = 0x00 + 1;
							r54.u1 = *r54.u1;
							b0();
							r1 = r51 + 0x00;
							r53.u1 = r8.u2;
							r54.u1 = r37.u1;
							b0();
							r1 = r51 + 0x00;
							if (p06)
								goto l40000000000E9EB0;
							goto l40000000000E9E30;
						}
						b0();
						r1 = r51 + 0x00;
						p07 = 0x00 == r8;
						p06 = 0x00 != r8;
						r53 = 0x00 + 0x00;
						r38.u1 = r8.u2;
						r55 = 0x00 + 5;
						if (p07)
						{
							r54 = r1 + -7692;
							r55 = 0x00 + 5;
							r35 = 0x00 + 1;
							r54.u1 = *r54.u1;
							b0();
							r1 = r51 + 0x00;
							r53 = 0x00 + 1;
							r54.u1 = r8.u2;
							r55.u1 = r37.u1;
							b0();
							r1 = r51 + 0x00;
							if (p06)
								goto l40000000000E9EB0;
						}
						else
						{
							r54 = r1 + -7684;
							r35.u1 = r8.u2;
							r54.u1 = *r54.u1;
							b0();
							r1 = r51 + 0x00;
							r55.u1 = r37.u1;
							r53 = 0x00 + 1;
							r54.u1 = r8.u2;
							r37.u0 = (word32) r38 + 40;
							b0();
							r1 = r51 + 0x00;
							LC = 0x04;
							r55.u1 = *r35.u1;
							r35.u0 = (word32) r35 + 8;
							r54 = r1 + -7676;
							r53 = 0x00 + 1;
							p07 = 0x00 == r55;
							p06 = 0x00 != r55;
							if (!p07)
							{
								word64 r56 = *r35.u1;
								r54.u1 = *r54.u1;
								p06 = 0x00 == r56;
								p07 = 0x00 != r56;
								if (p07)
									r56 = r1 + -7756;
							}
							r53.u1 = r38.u1;
							r35 = 0x00 + 0x00;
							b0();
							r1 = r51 + 0x00;
							if (p06)
							{
l40000000000E9EB0:
								if (p06)
									goto l40000000000E9F00;
								goto l40000000000E9EC0;
							}
						}
l40000000000E9E30:
						p06 = 0x00 == r41;
						p07 = 0x00 != r41;
						r53 = r41 + 0x00;
						if (!p06)
						{
							r35 = 0x00 + 0x00;
							b0();
							p07 = 0x00 == r8;
							p06 = 0x00 != r8;
							r1 = r51 + 0x00;
							r37.u1 = r8.u2;
							if (p07)
							{
								r54 = r1 + -7700;
								r55 = 0x00 + 5;
								r53 = 0x00 + 0x00;
								r35 = 0x00 + 1;
								r54.u1 = *r54.u1;
								b0();
								r1 = r51 + 0x00;
								r53.u1 = r8.u2;
								r54 = r41 + 0x00;
								b0();
								r1 = r51 + 0x00;
								if (p06)
								{
l40000000000E9F00:
									if (p07)
									{
										word64 r48;
										r53 = r48 + 0x00;
										b0();
										r1 = r51 + 0x00;
										r35.u1 = r8.u2;
										p06 = 0x00 == r34;
										p07 = 0x00 != r34;
										if (!p07)
											goto l40000000000E9F60;
									}
									else
									{
										p06 = 0x00 == r34;
										p07 = 0x00 != r34;
										if (p06)
											goto l40000000000E9F60;
									}
									do
									{
										r14.u0 = (word32) r34 + 8;
										r14.u1 = *r14.u1;
										r53.u1 = *r14.u1;
										b0();
										r34.u1 = *r34.u1;
										r1 = r51 + 0x00;
										p07 = 0x00 == r34;
										p06 = 0x00 != r34;
									} while (p06);
l40000000000E9F60:
									p06 = 0x00 == r36;
									p07 = 0x00 != r36;
									r53.u1 = r36.u1;
									if (!p06)
									{
										b0();
										r1 = r51 + 0x00;
										r53 = r1 + -7732;
										r53.u1 = *r53.u1;
										b0();
										r1 = r51 + 0x00;
										r53.u1 = r35.u1;
										b0();
										r1 = r51 + 0x00;
										ar.pfs = r50;
										LC = r52;
										b0 = r49;
										return;
									}
									goto l40000000000E9A70;
								}
l40000000000E9EC0:
								p06 = 0x00 == r40;
								p07 = 0x00 != r40;
								r53 = r40 + 0x00;
								r54 = 0x00 + 0x00;
								if (!p06)
								{
									b0();
									r1 = r51 + 0x00;
									word32 v54 = (word32) 0x00;
									word32 v55 = (word32) r8;
									p06 = v54 == v55;
									p07 = v54 != v55;
									if (p07)
									{
										r54 = r1 + -7660;
										r55 = 0x00 + 5;
										r53 = 0x00 + 0x00;
										r35 = 0x00 + 1;
										r54.u1 = *r54.u1;
										b0();
										r1 = r51 + 0x00;
										r53.u1 = r8.u2;
										r54 = r40 + 0x00;
										b0();
										r1 = r51 + 0x00;
										goto l40000000000E9F60;
									}
								}
								goto l40000000000E9F00;
							}
							b0();
							r1 = r51 + 0x00;
							r53.u1 = r37.u1;
							r54.u1 = r8.u2;
							b0();
							r1 = r51 + 0x00;
						}
						goto l40000000000E9EB0;
					}
l40000000000E9C40:
					if (!p07)
						goto l40000000000E9C50;
					goto l40000000000EA370;
				}
l40000000000E9C20:
				if (!p07)
					goto l40000000000E9C30;
				goto l40000000000EA3A0;
			}
l40000000000E9C00:
			if (!p07)
				goto l40000000000E9C10;
			goto l40000000000EA2E0;
		}
	}
	r36 = 0x00 + 0x00;
	if (p06)
		goto l40000000000E9BF0;
	goto l40000000000EA340;
}

// 40000000000EA800: define break_builtin
define break_builtin
{
	word32 *** r32;
	word64 * r8;
	<anonymous> * b2;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r36 = r1 + 0x00;
	<anonymous> * r34 = b2;
	<anonymous> * b0;
	b0();
	word32 ** r14 = 0x00 + 0x00;
	word32 v14 = (word32) 0x00;
	word32 v15 = (word32) r8;
	Eq_n p06 = v14 == v15;
	Eq_n p07 = v14 != v15;
	r1 = r36 + 0x00;
	if (!p07)
	{
		r8 = r14;
		ar.pfs = r35;
		b0 = r34;
		r12 += 0x10;
	}
	else
	{
		word64 r37 = r32;
		word64 r39 = r12 + 0x10;
		struct Eq_n * r38 = 0x00 + 1;
		b0();
		r1 = r36 + 0x00;
		r14 = r12 + 0x10;
		word32 * r15 = (word32 *) *r14;
		word32 * r16 = r1 + 8364;
		r14 = 0x00 + 0x00;
		word64 r17 = r1 + 8360;
		p06 = null < r15;
		p07 = null >= r15;
		r8 = r14;
		if (!p07)
		{
			word32 v25 = *r16;
			r16 = (word64) v25;
			int32 v26 = (int32) r16;
			r16 = (int64) v26;
			p07 = r15 < r16;
			p06 = r15 >= r16;
			if (p06)
				r15 = r16;
		}
		else
		{
			r32 = (word32 ***) ((char *) r32 + 8);
			r38 = r1 + -0x000024D4;
			r39 = 0x00 + 5;
			r37 = 0x00 + 0x00;
			r14 = (word32 **) *r32;
			r38 = r38->ptr0000;
			word32 * r33 = (word32 *) *r14;
			b0();
			r1 = r36 + 0x00;
			r38 = (struct Eq_n *) r8;
			r37 = r33;
			b0();
			r1 = r36 + 0x00;
			r14 = 0x00 + 1;
			r15 = r1 + 8364;
			r8 = r14;
			word32 v28 = *r15;
			r16 = (word64) v28;
			r15 = r1 + 8360;
			*r16 = (word32) r15;
			ar.pfs = r35;
			b0 = r34;
			r12 += 0x10;
		}
	}
}

// 40000000000EA9C0: define continue_builtin
define continue_builtin
{
	word32 *** r32;
	word64 * r8;
	<anonymous> * b2;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r35 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	word64 r36 = r1 + 0x00;
	<anonymous> * r34 = b2;
	<anonymous> * b0;
	b0();
	word32 ** r14 = 0x00 + 0x00;
	word32 v14 = (word32) 0x00;
	word32 v15 = (word32) r8;
	Eq_n p06 = v14 == v15;
	Eq_n p07 = v14 != v15;
	r1 = r36 + 0x00;
	if (!p07)
	{
		r8 = r14;
		ar.pfs = r35;
		b0 = r34;
		r12 += 0x10;
	}
	else
	{
		word64 r37 = r32;
		word64 r39 = r12 + 0x10;
		struct Eq_n * r38 = 0x00 + 1;
		b0();
		r1 = r36 + 0x00;
		r14 = r12 + 0x10;
		word32 * r15 = (word32 *) *r14;
		word32 * r16 = r1 + 8364;
		r14 = 0x00 + 0x00;
		word64 r17 = r1 + 8356;
		p06 = null < r15;
		p07 = null >= r15;
		r8 = r14;
		if (!p07)
		{
			word32 v25 = *r16;
			r16 = (word64) v25;
			int32 v26 = (int32) r16;
			r16 = (int64) v26;
			p07 = r15 < r16;
			p06 = r15 >= r16;
			if (p06)
				r15 = r16;
		}
		else
		{
			r32 = (word32 ***) ((char *) r32 + 8);
			r38 = r1 + -0x000024D4;
			r39 = 0x00 + 5;
			r37 = 0x00 + 0x00;
			r14 = (word32 **) *r32;
			r38 = r38->ptr0000;
			word32 * r33 = (word32 *) *r14;
			b0();
			r1 = r36 + 0x00;
			r38 = (struct Eq_n *) r8;
			r37 = r33;
			b0();
			r1 = r36 + 0x00;
			r14 = 0x00 + 1;
			r15 = r1 + 8364;
			r8 = r14;
			word32 v28 = *r15;
			r16 = (word64) v28;
			r15 = r1 + 8360;
			*r16 = (word32) r15;
			ar.pfs = r35;
			b0 = r34;
			r12 += 0x10;
		}
	}
}

// 40000000000EAB80: define builtin_builtin
define builtin_builtin
{
	word64 r64;
	word64 r8;
	word64 r32;
	word64 b3;
	int64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r36 = ar.pfs;
	word64 r37 = r1 + 0x00;
	word64 r35 = b3;
	word64 r38 = r32 + 0x00;
	<anonymous> * b0;
	b0();
	word32 v14 = (word32) 0x00;
	word32 v15 = (word32) r8;
	Eq_n p07 = v14 == v15;
	Eq_n p06 = v14 != v15;
	r1 = r37 + 0x00;
	if (!p07)
	{
		if (p06)
			r8 = 0x00 + 258;
		__break();
		word64 pr = 0x4000;
		__break();
		__break();
		__break();
	}
	else
	{
		word64 * r14 = r1 + 0x00002434;
		word64 r33 = *r14;
		p06 = 0x00 == r33;
		p07 = 0x00 != r33;
		r14 = r33 + 0x08;
		if (p06)
			r8 = 0x00 + 0x00;
		r1 < 0x00;
		Eq_n p17 = r1 >= 0x00;
		byte v24 = (byte) r64;
		r64 = (word64) v24;
		__break();
	}
}

// 40000000000EAD00: define caller_builtin
define caller_builtin
{
	word64 * r8;
	<anonymous> * b5;
	word64 r1;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r38 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	struct Eq_n * r40 = r1 + -0x04C4;
	word64 r39 = r1 + 0x00;
	<anonymous> * r37 = b5;
	r40 = r40->ptr0000;
	<anonymous> * b0;
	b0();
	word32 * r14 = (word32 *) (r8 + 5);
	Eq_n p06 = null == r8;
	Eq_n p07 = null != r8;
	r1 = r39 + 0x00;
	if (!p06)
	{
		word32 v17 = *r14;
		r14 = (word64) v17;
		if (!p06)
		{
			if (p07)
				++r8;
		}
	}
	word64 r35 = 0x00 + 0x00;
	r40 = r1 + -1212;
	r40 = r40->ptr0000;
	b0();
	r14 = (word32 *) (r8 + 5);
	p06 = null == r8;
	p07 = null != r8;
	r1 = r39 + 0x00;
	if (!p06)
	{
		word32 v19 = *r14;
		r14 = (word64) v19;
		if (!p06)
		{
			if (p07)
				++r8;
		}
	}
	word64 r33 = 0x00 + 0x00;
	r40 = r1 + -0x04B4;
	r40 = r40->ptr0000;
	b0();
	r14 = (word32 *) (r8 + 5);
	r1 = r39 + 0x00;
	p07 = null == r8;
	p06 = null != r8;
	if (!p07)
	{
		word32 v21 = *r14;
		r14 = (word64) v21;
		if (!p06)
		{
			++r8;
			word64 r34 = *r8;
			r14 = r34 + 0x10;
			p06 = 0x00 == r34;
			p07 = 0x00 != r34;
			if (!p06)
			{
				word32 v23 = *r14;
				r14 = (word64) v23;
				word32 v24 = (word32) 0x00;
				word32 v25 = (word32) r14;
				p06 = v24 == v25;
				p07 = v24 != v25;
				r14 = r33 + 0x10;
				if (!p06)
				{
					p06 = 0x00 == r33;
					p07 = 0x00 != r33;
					if (!p06)
					{
						word32 v26 = *r14;
						r14 = (word64) v26;
						word32 v27 = (word32) 0x00;
						word32 v28 = (word32) r14;
						p06 = v27 == v28;
						p07 = v27 != v28;
						if (p07)
						{
							word64 r32;
							r40 = r32 + 0x00;
							b0();
							word32 v30 = (word32) 0x00;
							word32 v31 = (word32) r8;
							p07 = v30 == v31;
							p06 = v30 != v31;
							r1 = r39 + 0x00;
							if (p06)
								r8 = 0x00 + 258;
							word64 p22;
							if (p22)
								__break();
							word64 p32;
							if (p32)
								__break();
							int64 r56;
							r56 < 0x00;
							Eq_n p56 = r56 >= 0x00;
							__break();
						}
					}
				}
			}
		}
	}
	r8 = 0x00 + 1;
	ar.pfs = r38;
	b0 = r37;
	r12 += 0x10;
}

// 40000000000EBD80: define cd_builtin
define cd_builtin
{
	int64 r64;
	word64 r1;
	<anonymous> * b0;
	word64 ar.pfs;
	ptr64 fp;
	ptr64 r11 = fp;
	word64 r41 = ar.pfs;
	word64 r12 = r12 + ~0x0F;
	<anonymous> * r40 = b0;
	Eq_n r14 = r1 + 7352;
	word64 r42 = r1 + 0x00;
	Eq_n r33 = r1 + 8372;
	Eq_n r35 = 0x00 + 1;
	Eq_n v14;
	v14.u1 = *r14.u2;
	r14.u2 = (word64) v14;
	word32 v15 = (word32) 0x00;
	word32 v16 = (word32) r14;
	Eq_n p06 = v15 == v16;
	Eq_n p07 = v15 != v16;
	r14 = r1 + 0x00001CC0;
	Eq_n r43;
	word32 * r8;
	if (p07)
	{
		r43 = 0x00 + 0x00;
		b0();
		r8 = 0x00 + 1;
		r1 = r42 + 0x00;
		ar.pfs = r41;
		b0 = r40;
		r12 += 0x10;
		return;
	}
	word32 * r0;
	*r0 = (word32) r33;
	Eq_n v20;
	v20.u1 = *r14.u2;
	word64 r34 = (word64) v20;
	b0();
	r1 = r42 + 0x00;
	word32 * r44;
	while (true)
	{
		r44 = r1 + 0x04E4;
		word64 r32;
		r43 = r32 + 0x00;
		r44 = (word32 *) *r44;
		b0();
		word32 v26 = (word32) ~0x00;
		word32 v27 = (word32) r8;
		p07 = v26 == v27;
		p06 = v26 != v27;
		r1 = r42 + 0x00;
		if (p07)
			break;
		word32 v28 = (word32) 0x50;
		word32 v29 = (word32) r8;
		p06 = v28 == v29;
		p07 = v28 != v29;
		if (!p06)
		{
			word32 v36 = (word32) 101;
			word32 v37 = (word32) r8;
			p06 = v36 == v37;
			p07 = v36 != v37;
			if (p06)
			{
				*r35.u2 = (word32) (word32) r33;
				continue;
			}
			word32 v43 = (word32) 0x4C;
			word32 v44 = (word32) r8;
			p06 = v43 == v44;
			p07 = v43 != v44;
			if (!p06)
			{
				b0();
				r8 = 0x00 + 1;
				r1 = r42 + 0x00;
				ar.pfs = r41;
				b0 = r40;
				r12 += 0x10;
				return;
			}
			else
			{
				r34 = 0x00 + 0x00;
				continue;
			}
		}
		r34 = 0x00 + 1;
	}
	r14 = r1 + 0x00002414;
	Eq_n v30;
	v30.u1 = *r14.u2;
	ui64 r37 = (word64) v30;
	r14 = r1 + 6516;
	word32 v32 = (word32) 0x00;
	word32 v33 = (word32) r37;
	Eq_n p09 = v32 == v33;
	Eq_n p08 = v32 != v33;
	if (p08)
		r37 = 0x00 + 1;
	Eq_n v38;
	v38.u1 = *r14.u2;
	word32 * r15 = (word64) v38;
	r14 = r1 + 0x00002434;
	if (p09)
		r37 = 0x00 + 0x00;
	word32 v40 = (word32) 0x00;
	word32 v41 = (word32) r15;
	p06 = v40 == v41;
	p07 = v40 != v41;
	int64 r16;
	if (p06)
		r16 = 0x00 + 0x00;
	r14.u2 = r14.u3->t0000.u2;
	if (p06)
	{
		Eq_n v45;
		v45.u1 = *r33.u1;
		r15 = (word64) v45;
		r37 |= r16;
		word32 v46 = (word32) 0x00;
		word32 v47 = (word32) r15;
		p06 = v46 == v47;
		p07 = v46 != v47;
		if (p07)
		{
			word32 v51 = (word32) 0x00;
			word32 v52 = (word32) r34;
			p07 = v51 == v52;
			p06 = v51 != v52;
			if (p07)
				r15 = r1 + 8372;
		}
	}
	else
	{
		r15 = r1 + 8368;
		word32 v48 = *r15;
		r16 = (word64) v48;
		word32 v49 = (word32) 0x00;
		word32 v50 = (word32) r16;
		p06 = v49 == v50;
		p07 = v49 != v50;
		if (p06)
			r16 = 0x00 + 0x00;
		word64 p16;
		if (p16)
			__break();
		word64 p01;
		if (p01)
			__break();
	}
	r33.u0 = (word32) r14 + 8;
	p07 = 0x00 == r14;
	p06 = 0x00 != r14;
	if (p07)
	{
		r43 = r1 + 0x04EC;
		r37 = 0x00 + 0x00;
		r43.u2 = r43.u3->t0000.u2;
		b0();
		r1 = r42 + 0x00;
		p07 = null == r8;
		p06 = null != r8;
		r35.u2 = r8;
		if (p07)
			r44 = r1 + 0x04F4;
	}
	r14.u2 = r33.u2->u2;
	r43.u2 = r14.u3->t0000.u2;
	Eq_n v54;
	v54.u0 = r43.u3->t0000.u0;
	r14.u2 = (word64) v54;
	int8 v55 = (int8) r14;
	r14.u2 = (int64) v55;
	word32 v56 = (word32) 0x2D;
	word32 v57 = (word32) r14;
	p07 = v56 == v57;
	p06 = v56 != v57;
	if (p07)
	{
		r14.u1 = (word32) r43 + 1;
		Eq_n v60;
		v60.u0 = r14.u3->t0000.u0;
		r14.u2 = (word64) v60;
		int8 v61 = (int8) r14;
		r14.u2 = (int64) v61;
		word32 v62 = (word32) 0x00;
		word32 v63 = (word32) r14;
		p07 = v62 == v63;
		p06 = v62 != v63;
		if (!p06)
		{
			r43 = r1 + 0x04D4;
			r43.u2 = r43.u3->t0000.u2;
			b0();
			p07 = null == r8;
			p06 = null != r8;
			r1 = r42 + 0x00;
			r35.u2 = r8;
			if (p06)
				r37 = 0x00 + 4;
		}
	}
	b0();
	r1 = r42 + 0x00;
	word32 v58 = (word32) 0x00;
	word32 v59 = (word32) r8;
	p06 = v58 == v59;
	p07 = v58 != v59;
	if (!p07)
	{
		r14 = r1 + 7344;
		Eq_n v75;
		v75.u1 = *r14.u2;
		r14.u2 = (word64) v75;
		word32 v76 = (word32) 0x00;
		word32 v77 = (word32) r14;
		p07 = v76 == v77;
		p06 = v76 != v77;
		if (!p06)
		{
			r43 = r1 + 0x0504;
			r43.u2 = r43.u3->t0000.u2;
			b0();
			r1 = r42 + 0x00;
			p06 = null == r8;
			p07 = null != r8;
			word32 * r38 = r8;
			if (!p06)
			{
				r14.u2 = r33.u2->u2;
				r35.u2 = r14.u3->t0000.u2;
				r14 = r12 + 0x10;
				*r0 = (word32) r14;
				word32 * r45;
				while (true)
				{
					r43.u2 = r38;
					r44 = r12 + 0x10;
					b0();
					r33.u1 = r8;
					p07 = null == r8;
					p06 = null != r8;
					r1 = r42 + 0x00;
					r45 = 0x00 + 1;
					r44 = r35.u2;
					if (p07)
						break;
					Eq_n v82;
					v82.u0 = r33.u2->u0;
					r14.u2 = (word64) v82;
					r43.u2 = r33.u1;
					int8 v83 = (int8) r14;
					r14.u2 = (int64) v83;
					Eq_n r39;
					r39.u2 = r14.u2;
					b0();
					r1 = r42 + 0x00;
					word32 * r36 = r8;
					r43.u2 = r33.u1;
					b0();
					r1 = r42 + 0x00;
					r43.u2 = r36;
					r44 = r34 + 0x00;
					b0();
					word32 v86 = (word32) 0x00;
					word32 v87 = (word32) r8;
					p06 = v86 == v87;
					p07 = v86 != v87;
					r1 = r42 + 0x00;
					r43.u2 = r36;
					if (p07)
					{
						word32 v88 = (word32) 0x00;
						word32 v89 = (word32) r39;
						p06 = v88 == v89;
						p07 = v88 != v89;
						r43.u2 = r36;
						if (!p06)
						{
							word32 v90 = (word32) 0x00;
							word32 v91 = (word32) r34;
							p07 = v90 == v91;
							p06 = v90 != v91;
							if (p07)
								r14 = r1 + 8380;
						}
						else
						{
							r43.u2 = r36;
							b0();
							r1 = r42 + 0x00;
							r43 = r34 + 0x00;
							b0();
							r1 = r42 + 0x00;
							ar.pfs = r41;
							b0 = r40;
							r12 += 0x10;
							return;
						}
					}
					b0();
					r1 = r42 + 0x00;
				}
l40000000000EC1B0:
				r43.u2 = r35.u2;
				r44 = r34 + 0x00;
				b0();
				r1 = r42 + 0x00;
				word32 v65 = (word32) 0x00;
				word32 v66 = (word32) r8;
				p06 = v65 == v66;
				p07 = v65 != v66;
				if (p06)
				{
					if (p07)
					{
						r43.u2 = r35.u2;
						b0();
						p06 = null == r8;
						p07 = null != r8;
						r1 = r42 + 0x00;
						r33.u1 = r8;
						r43.u2 = r8;
						r44 = r34 + 0x00;
						if (!p06)
						{
							b0();
							word32 v69 = (word32) 0x00;
							word32 v70 = (word32) r8;
							p06 = v69 == v70;
							p07 = v69 != v70;
							r1 = r42 + 0x00;
							if (!p06)
							{
								if (p07)
									r43.u2 = r33.u1;
								__break();
								__break();
								__break();
								word64 p32;
								if (p32)
								{
									Eq_n p10 = r64 < r16;
									r64 >= r16;
								}
							}
						}
					}
					if (p06)
					{
l40000000000EC2F0:
						b0();
						r1 = r42 + 0x00;
						word32 v71 = *r8;
						r43.u2 = (word64) v71;
						b0();
						r1 = r42 + 0x00;
						r45 = r8;
						r44 = r35.u2;
						r43 = r1 + 1292;
						r43.u2 = r43.u3->t0000.u2;
						b0();
						r8 = 0x00 + 1;
						r1 = r42 + 0x00;
						ar.pfs = r41;
						b0 = r40;
						r12 += 0x10;
						return;
					}
					r43.u2 = r35.u2;
					b0();
					p06 = null == r8;
					p07 = null != r8;
					r1 = r42 + 0x00;
					r33.u1 = r8;
					r43.u2 = r8;
					r44 = r34 + 0x00;
					if (p06)
						goto l40000000000EC2F0;
					b0();
					word32 v73 = (word32) 0x00;
					word32 v74 = (word32) r8;
					p06 = v73 == v74;
					p07 = v73 != v74;
					r1 = r42 + 0x00;
					r43.u2 = r33.u1;
					if (!p07)
					{
						b0();
						r1 = r42 + 0x00;
						goto l40000000000EC2F0;
					}
				}
				else
				{
					r43 = r34 + 0x00;
					if (!p07)
					{
						b0();
						r1 = r42 + 0x00;
						goto l40000000000EC210;
					}
					r43.u2 = r35.u2;
				}
				b0();
				r1 = r42 + 0x00;
				r43 = r34 + 0x00;
				b0();
				r1 = r42 + 0x00;
l40000000000EC210:
				ar.pfs = r41;
				b0 = r40;
				r12 += 0x10;
				return;
			}
		}
	}
	r14.u2 = r33.u2->u2;
	r35.u2 = r14.u3->t0000.u2;
	goto l40000000000EC1B0;
}

