#region License
/* 
 * Copyright (C) 1999-2026 John Källén.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#endregion

namespace Reko.Arch.IA64;

public enum Mnemonic
{
    Invalid,
    _long_immediate,

    add,
    addl,
    addp4,
    adds,
    alloc,
    and,
    andcm,
    br_cloop,
    br_cond,
    br_wexit,
    br_wtop,
    break_i,
    break_m,
    cmp4_eq,
    cmp4_eq_and,
    cmp4_eq_or,
    cmp4_eq_or_andcm,
    cmp4_eq_unc,
    cmp4_ge_and,
    cmp4_ge_or,
    cmp4_ge_or_andcm,
    cmp4_gt,
    cmp4_gt_and,
    cmp4_gt_or_andcm,
    cmp4_le_and,
    cmp4_le_or,
    cmp4_le_or_andcm,
    cmp4_lt,
    cmp4_lt_and,
    cmp4_lt_or,
    cmp4_lt_or_andcm,
    cmp4_lt_unc,
    cmp4_ltu,
    cmp4_ltu_unc,
    cmp4_ne_and,
    cmp4_ne_or,
    cmp4_ne_or_andcm,
    cmp_eq,
    cmp_eq_and,
    cmp_eq_or,
    cmp_eq_or_andcm,
    cmp_eq_unc,
    cmp_ge_and,
    cmp_ge_or,
    cmp_ge_or_andcm,
    cmp_gt,
    cmp_gt_or,
    cmp_gt_or_andcm,
    cmp_le_and,
    cmp_le_or,
    cmp_le_or_andcm,
    cmp_lt,
    cmp_lt_and,
    cmp_lt_or,
    cmp_lt_or_andcm,
    cmp_lt_unc,
    cmp_ltu,
    cmp_ltu_unc,
    cmp_ne_and,
    cmp_ne_or,
    cmp_ne_or_andcm,
    czx1_l,
    czx1_r,
    czx2_l,
    czx2_r,
    ld1,
    ld1_a,
    ld1_acq,
    ld1_bias,
    ld1_c_clr,
    ld1_c_clr_acq,
    ld1_c_nc,
    ld1_s,
    ld1_sa,
    ld2,
    ld2_a,
    ld2_acq,
    ld2_bias,
    ld2_c_clr,
    ld2_c_clr_acq,
    ld2_c_nc,
    ld2_s,
    ld2_sa,
    ld4,
    ld4_a,
    ld4_acq,
    ld4_bias,
    ld4_c_clr,
    ld4_c_clr_acq,
    ld4_c_nc,
    ld4_s,
    ld4_sa,
    ld8,
    ld8_a,
    ld8_acq,
    ld8_bias,
    ld8_c_clr,
    ld8_c_clr_acq,
    ld8_c_nc,
    ld8_fill,
    ld8_s,
    ld8_sa,
    movl,
    nop,
    nop_i,
    nop_m,
    st1,
    st1_rel,
    st2,
    st2_rel,
    st4,
    st4_rel,
    st8,
    st8_rel,
    st8_spill,
    sxt1,
    sxt2,
    sxt4,
    zxt1,
    zxt2,
    zxt4,
    mov_i,
    mov,
    or,
    shladd,
    shladdp4,
    sub,
    xor,
    fpmerge_s,
    nop_f,
    break_f,
    br_call,
    break_b,
    br_ret,
    nop_b,
}
